import { PrismaClient, BookingMode, BookingStatus, ChargeType, CommercialRuleKind, CommercialRuleVersionStatus, CommercialScopeType, CommercialStackingMode, CommercialVersionStatus, OrganizationRole, PricingUnit, PayoutStatus, ProductRevisionStatus, ProductStatus, ProductType, RatePlanStatus, SupplierCommercialModel, TenantKind, TravellerType, UserRole, VendorVerificationStatus, VariantStatus } from '@prisma/client';
import { hash } from 'bcryptjs';
import { mkdir, writeFile } from 'fs/promises';
import { join } from 'path';
import { zonedTimeToUtc } from '../src/schedules/schedule-utils';

const prisma = new PrismaClient();
const days = (offset: number) => { const d = new Date(); d.setUTCHours(0, 0, 0, 0); d.setUTCDate(d.getUTCDate() + offset); return d; };
const slug = (s: string) => s.toUpperCase().replace(/[^A-Z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 40);
const samples = [
  ['Sunrise Trek to Top Station', ProductType.ACTIVITY, 'TICKET_ONLY', ProductStatus.LIVE, 1, 4.8, 'Guided early-morning trek through the Munnar highlands with sunrise viewpoints and local guide support.'],
  ['Athirappilly Excursion from Kochi to Munnar', ProductType.ACTIVITY, 'SIGHTSEEING', ProductStatus.LIVE, 2, 4.9, 'En-route excursion to Athirappilly Waterfalls while travelling from Kochi to Munnar.'],
  ['Photoshoot at Tata Tea Museum', ProductType.ACTIVITY, 'TICKET_ONLY', ProductStatus.DRAFT, 3, 4.8, 'Tea-estate photoshoot experience with edited images and optional museum visit.'],
  ['Traditional Meal of Kerala', ProductType.MEALS, 'MEALS', ProductStatus.DRAFT, 4, 4.5, 'Traditional Kerala meal experience served on the Kochi-Munnar route.'],
  ['Bus Tickets from Bangalore to Munnar', ProductType.TRANSFER, 'POINT_TO_POINT', ProductStatus.LIVE, 5, 5, 'Overnight semi-sleeper bus transfer between Bangalore and Munnar.'],
] as const;

async function main() {
  const tenant = await prisma.tenant.upsert({ where: { slug: 'blue-mountain-adventures' }, update: {}, create: { name: 'Blue Mountain Adventures', slug: 'blue-mountain-adventures', kind: TenantKind.VENDOR } });
  await prisma.tenant.upsert({ where: { slug: 'demo-travel-agent' }, update: {}, create: { name: 'Demo Travel Agent', slug: 'demo-travel-agent', kind: TenantKind.TRAVEL_AGENT } });
  const demoPassword = process.env.DEMO_PASSWORD;
  if (!demoPassword) throw new Error('DEMO_PASSWORD must be configured before seeding demo users.');
  const passwordHash = await hash(demoPassword, 10);
  const vendorUser = await prisma.user.upsert({ where: { email: 'vendor@voya.demo' }, update: { passwordHash, tenantId: tenant.id, role: UserRole.VENDOR, organizationRole: OrganizationRole.OWNER, active: true }, create: { email: 'vendor@voya.demo', passwordHash, fullName: 'Binu Mathew', role: UserRole.VENDOR, organizationRole: OrganizationRole.OWNER, tenantId: tenant.id } });
  const adminUser = await prisma.user.upsert({ where: { email: 'admin@voya.demo' }, update: { passwordHash, role: UserRole.ADMIN, active: true }, create: { email: 'admin@voya.demo', passwordHash, fullName: 'Voya Admin', role: UserRole.ADMIN } });
  await prisma.vendorProfile.upsert({ where: { tenantId: tenant.id }, update: {}, create: { tenantId: tenant.id, legalBusinessName: 'Blue Mountain Adventures Pvt. Ltd.', operatingCity: 'Munnar', operatingRegion: 'Kerala', gstin: '32AACCB1234F1Z5', category: 'Trekking, Nature & Wildlife', verificationStatus: VendorVerificationStatus.VERIFIED, readinessScore: 81, payoutAccountMasked: 'HDFC •••• 4821', documentStatus: { gstin: { status: 'VERIFIED' }, pan: { status: 'VERIFIED' }, bankProof: { status: 'PENDING' }, tradeLicense: { status: 'PENDING' } } } });
  await mkdir(join(process.cwd(), 'storage', 'private', 'vendor-documents'), { recursive: true });
  const demoPdf = Buffer.from('%PDF-1.4\n% Voya demo document\n');
  for (const [type, label] of [['GSTIN', 'gstin-certificate.pdf'], ['PAN', 'pan-card.pdf'], ['BANK_PROOF', 'bank-proof.pdf'], ['TRADE_LICENSE', 'trade-license.pdf']] as const) {
    const storageKey = `private/vendor-documents/demo-${type.toLowerCase()}.pdf`;
    await writeFile(join(process.cwd(), 'storage', storageKey), demoPdf);
    const asset = await prisma.fileAsset.upsert({ where: { storageKey }, update: {}, create: { tenantId: tenant.id, storageKey, originalName: label, mimeType: 'application/pdf', sizeBytes: demoPdf.length, visibility: 'PRIVATE', purpose: 'VENDOR_DOCUMENT', entityType: 'VendorDocument', createdById: vendorUser.id } });
    const doc = await prisma.vendorDocument.upsert({ where: { tenantId_type: { tenantId: tenant.id, type } }, update: { currentStatus: 'VERIFIED' }, create: { tenantId: tenant.id, type, currentStatus: 'VERIFIED' } });
    if (!(await prisma.vendorDocumentVersion.findFirst({ where: { vendorDocumentId: doc.id } }))) await prisma.vendorDocumentVersion.create({ data: { vendorDocumentId: doc.id, versionNumber: 1, fileAssetId: asset.id, status: 'VERIFIED', createdById: vendorUser.id, reviewedById: adminUser.id, reviewedAt: new Date() } });
  }
  const products: Record<string, { id: string }> = {};
  for (const [name, type, subType, status, rank, starRating, description] of samples) {
    let product = await prisma.product.findFirst({ where: { tenantId: tenant.id, revisions: { some: { productName: name } } } });
    const revisionStatus = status === ProductStatus.LIVE ? ProductRevisionStatus.PUBLISHED : ProductRevisionStatus.DRAFT;
    if (!product) {
      product = await prisma.product.create({ data: { tenantId: tenant.id, productCode: `SEED-${slug(name)}`, status, revisions: { create: { versionNumber: 1, status: revisionStatus, productName: name, type, subType, description, shortDescription: name, highlights: ['Service as described'], channels: ['B2B', 'B2C'], labels: ['Demo'], subCategory: 'Experiences', rank, starRating, cityName: 'Munnar', countryName: 'INDIA', stateName: 'Kerala', address: 'Munnar, Kerala', terms: ['Cancellation terms apply as per the selected rate plan.'], importantInfo: ['Carry a valid photo ID.'], thingsToCarry: ['Comfortable footwear', 'Water bottle'], createdById: vendorUser.id } } } });
      const revision = await prisma.productRevision.findFirstOrThrow({ where: { productId: product.id, versionNumber: 1 } });
      if (revisionStatus === ProductRevisionStatus.PUBLISHED) await prisma.product.update({ where: { id: product.id }, data: { currentRevisionId: revision.id } });
    }
    products[name] = product;
  }
  const ensureVariant = async (productId: string, variantCode: string, name: string, fields: Record<string, unknown> = {}) => prisma.productVariant.upsert({ where: { productId_variantCode: { productId, variantCode } }, update: {}, create: { productId, variantCode, name, status: VariantStatus.ACTIVE, ...fields } });
  const trek = products['Sunrise Trek to Top Station'];
  const shared = await ensureVariant(trek.id, 'SUNRISE_SHARED_0515', 'Shared SUV · 05:15 pickup', { durationMinutes: 240, privateShared: 'Shared', vehicleType: 'SUV (Innova/Xylo)', pickupIncluded: true, pickupTimings: '05:15 AM', dropoffIncluded: true, dropoffTimings: '10:30 AM', pickupInput: 'Munnar town pickup point', inclusions: ['Trek guide', 'Breakfast', 'Entry support'], exclusions: ['Personal expenses', 'Travel insurance'], suitableFor: ['ADULT', 'CHILD', 'SENIOR'] });
  await ensureVariant(trek.id, 'SUNRISE_PRIVATE_SUV', 'Private SUV Experience', { durationMinutes: 240, privateShared: 'Private', vehicleType: 'SUV' });
  await ensureVariant(trek.id, 'SUNSET_TREK', 'Sunset Trek Variant', { durationMinutes: 240, privateShared: 'Shared', vehicleType: 'SUV' });
  const plan = await prisma.ratePlan.upsert({ where: { variantId_ratePlanCode: { variantId: shared.id, ratePlanCode: 'RP-DEMO-001' } }, update: {}, create: { variantId: shared.id, ratePlanCode: 'RP-DEMO-001', name: 'Standard B2B', status: RatePlanStatus.ACTIVE, description: 'Flexible per-person rate for the sunrise trek.', validFrom: days(-30), validTo: days(365), basePrice: 1499, minPax: 1, maxPax: 15, affiliates: ['Holidays'], instantConfirmation: true, cutOffMinutes: 120, adultRequired: true, minAdultRequired: 1, travellerRules: { create: [{ type: TravellerType.ADULT, displayName: 'Adult', minAge: 12, maxAge: 99, minCount: 1, maxCount: 15 }, { type: TravellerType.CHILD, displayName: 'Child', minAge: 5, maxAge: 11 }, { type: TravellerType.SENIOR, displayName: 'Senior', minAge: 60, maxAge: 99 }] }, cancellationRules: { create: [{ minDaysBefore: 6, chargeValue: 0, chargeType: ChargeType.PERCENTAGE }, { minDaysBefore: 1, maxDaysBefore: 5, chargeValue: 50, chargeType: ChargeType.PERCENTAGE }, { minDaysBefore: 0, maxDaysBefore: 0, chargeValue: 100, chargeType: ChargeType.PERCENTAGE }] } } });
  const ensureCommercial = async (ratePlan: { id: string; currency: string; validFrom: Date; validTo: Date; basePrice: any }, prices: Array<[TravellerType, number]> = []) => {
    const pricingUnit = prices.length ? PricingUnit.PER_PERSON : PricingUnit.PER_BOOKING;
    const version = await prisma.ratePlanCommercialVersion.upsert({ where: { ratePlanId_versionNumber: { ratePlanId: ratePlan.id, versionNumber: 1 } }, update: { status: CommercialVersionStatus.ACTIVE, supplierModel: SupplierCommercialModel.NET_RATE, pricingUnit, supplierBaseAmount: ratePlan.basePrice, bookingMode: BookingMode.INSTANT, currency: ratePlan.currency }, create: { ratePlanId: ratePlan.id, versionNumber: 1, status: CommercialVersionStatus.ACTIVE, effectiveFrom: ratePlan.validFrom, effectiveTo: ratePlan.validTo, supplierModel: SupplierCommercialModel.NET_RATE, pricingUnit, supplierBaseAmount: ratePlan.basePrice, bookingMode: BookingMode.INSTANT, currency: ratePlan.currency, createdById: vendorUser.id, sourcePayload: { seed: 'phase3-explicit-net-rate' } } });
    for (const [travellerType, amount] of prices) await prisma.ratePlanTravellerPrice.upsert({ where: { commercialVersionId_travellerType: { commercialVersionId: version.id, travellerType } }, update: { amount }, create: { commercialVersionId: version.id, travellerType, amount } });
  };
  await ensureCommercial(plan, [[TravellerType.ADULT, 1499], [TravellerType.CHILD, 999], [TravellerType.SENIOR, 1299]]);
  let schedule = await prisma.scheduleTemplate.findFirst({ where: { variantId: shared.id, scheduleCode: 'SEED-SUNRISE-SHARED' } });
  if (!schedule) schedule = await prisma.scheduleTemplate.create({ data: { variantId: shared.id, scheduleCode: 'SEED-SUNRISE-SHARED', name: 'Sunrise shared operating schedule', status: 'ACTIVE', operatingModel: 'MULTIPLE_SLOTS', timezone: 'Asia/Kolkata', effectiveFrom: days(-30), effectiveTo: days(365), operatingDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'], capacityUnit: 'PERSON', capacityUnitReviewRequired: false, defaultCapacity: 12, sourcePayload: { seed: 'phase4-operational-schedule' } } });
  await prisma.ratePlanSchedule.upsert({ where: { ratePlanId_scheduleTemplateId: { ratePlanId: plan.id, scheduleTemplateId: schedule.id } }, update: { active: true }, create: { ratePlanId: plan.id, scheduleTemplateId: schedule.id } });
  const seedSlots = [] as Array<{ id: string; startTime: string; endTime: string | null }>;
  for (const [index, startTime] of ['06:00', '09:30'].entries()) { const endTime = startTime === '06:00' ? '10:00' : '13:30'; let slot = await prisma.scheduleSlotTemplate.findFirst({ where: { scheduleTemplateId: schedule.id, startTime, archivedAt: null } }); if (!slot) slot = await prisma.scheduleSlotTemplate.create({ data: { scheduleTemplateId: schedule.id, slotCode: `SEED-${startTime.replace(':', '')}`, label: `Sunrise ${startTime}`, startTime, endTime, rank: index } }); seedSlots.push(slot); }
  for (let day = 0; day < 7; day++) for (const slot of seedSlots) { const serviceDate = days(day); const session = await prisma.serviceSession.upsert({ where: { scheduleTemplateId_serviceDate_sessionKey: { scheduleTemplateId: schedule.id, serviceDate, sessionKey: slot.slotCode } }, update: {}, create: { scheduleTemplateId: schedule.id, slotTemplateId: slot.id, serviceDate, sessionKey: slot.slotCode, localStartTime: slot.startTime, localEndTime: slot.endTime, startsAt: zonedTimeToUtc(serviceDate, slot.startTime, 'Asia/Kolkata'), endsAt: slot.endTime ? zonedTimeToUtc(serviceDate, slot.endTime, 'Asia/Kolkata') : null, status: 'OPEN', sourcePayload: { seed: 'phase4-operational-session' } } }); await prisma.inventoryState.upsert({ where: { sessionId: session.id }, update: {}, create: { sessionId: session.id, totalCapacity: 12, blockedCapacity: day === 5 ? (slot.startTime === '06:00' ? 12 : 10) : (slot.startTime === '06:00' ? 4 : 2), sourcePayload: { seed: 'phase4-operational-inventory' } } }); }
  const vehicle = await prisma.resource.upsert({ where: { tenantId_resourceCode: { tenantId: tenant.id, resourceCode: 'SEED-SUV-01' } }, update: { active: true, archivedAt: null }, create: { tenantId: tenant.id, resourceCode: 'SEED-SUV-01', name: 'Sunrise SUV 01', type: 'VEHICLE', allocationMode: 'EXCLUSIVE', sourcePayload: { seed: 'phase4-resource-example' } } });
  await prisma.scheduleResourceRequirement.upsert({ where: { requirementKey: `${schedule.id}:VEHICLE:${vehicle.id}` }, update: { required: false, active: true, archivedAt: null }, create: { scheduleTemplateId: schedule.id, resourceType: 'VEHICLE', specificResourceId: vehicle.id, quantity: 1, required: false, active: true, requirementKey: `${schedule.id}:VEHICLE:${vehicle.id}` } });
  const extras = [['Sunrise Trek to Top Station', 'SUNRISE_PRIVATE_SUV', 'Private SUV Experience', 4999], ['Sunrise Trek to Top Station', 'SUNSET_TREK', 'Sunset Trek Variant', 1799], ['Athirappilly Excursion from Kochi to Munnar', 'ATHI_STANDARD', 'Standard Waterfall Excursion', 899], ['Athirappilly Excursion from Kochi to Munnar', 'ATHI_PRIVATE', 'Private Vehicle Excursion', 3499], ['Photoshoot at Tata Tea Museum', 'PHOTO_BASIC', 'Basic Photoshoot', 1299], ['Photoshoot at Tata Tea Museum', 'PHOTO_PREMIUM', 'Premium Photoshoot', 2499], ['Traditional Meal of Kerala', 'MEAL_LUNCH', 'Kerala Lunch Experience', 999], ['Traditional Meal of Kerala', 'MEAL_DINNER', 'Kerala Dinner Experience', 1199], ['Bus Tickets from Bangalore to Munnar', 'BUS_SEMI_SLEEPER', 'Semi Sleeper Transfer', 1499]] as const;
  for (const [productName, code, name, price] of extras) { const product = products[productName]; const variant = await ensureVariant(product.id, code, name, { durationMinutes: 180, inclusions: ['Service as described'], exclusions: ['Personal expenses'] }); const extraPlan = await prisma.ratePlan.upsert({ where: { variantId_ratePlanCode: { variantId: variant.id, ratePlanCode: `SEED-${code}` } }, update: {}, create: { variantId: variant.id, ratePlanCode: `SEED-${code}`, name: 'Standard B2B', status: RatePlanStatus.ACTIVE, validFrom: days(-30), validTo: days(365), basePrice: price, minPax: 1, maxPax: 15, instantConfirmation: true, cutOffMinutes: 120 } }); await ensureCommercial(extraPlan); }
  const ensureGlobalRule = async (code: string, name: string, kind: CommercialRuleKind, config: Record<string, unknown>) => {
    const rule = await prisma.commercialRule.upsert({ where: { code_scopeType: { code, scopeType: CommercialScopeType.GLOBAL } }, update: {}, create: { code, name, kind, scopeType: CommercialScopeType.GLOBAL, createdById: adminUser.id } });
    await prisma.commercialRuleVersion.upsert({ where: { ruleId_versionNumber: { ruleId: rule.id, versionNumber: 1 } }, update: { status: CommercialRuleVersionStatus.ACTIVE, config }, create: { ruleId: rule.id, versionNumber: 1, status: CommercialRuleVersionStatus.ACTIVE, effectiveFrom: days(-30), config, priority: 0, stackingMode: CommercialStackingMode.EXCLUSIVE, createdById: adminUser.id, activatedById: adminUser.id } });
  };
  await ensureGlobalRule('SEED-VOYA-REVENUE-ZERO', 'Seed explicit zero Voya revenue', CommercialRuleKind.VOYA_REVENUE, { model: 'MARKUP_FIXED', fixedAmount: '0' });
  await ensureGlobalRule('SEED-TAX-NONE', 'Seed explicit non-taxable commercial quote', CommercialRuleKind.TAX, { mode: 'NONE', rate: '0', taxableBase: 'AGENT_PRE_TAX', accountableParty: 'NONE', roundingPolicy: 'HALF_UP' });
  if (!(await prisma.promotion.findFirst({ where: { productId: trek.id, name: 'Low Occupancy Booster' } }))) await prisma.promotion.create({ data: { productId: trek.id, name: 'Low Occupancy Booster', discountPercent: 18, startsAt: new Date(), endsAt: new Date(Date.now() + 48 * 3600_000), maxDiscountedBookings: 10 } });
  const bookings = [['BK-77291', 'MakeMyTrip', 'Sunrise Trek to Top Station', 4, 5996, BookingStatus.CONFIRMED, 1], ['BK-77288', 'Klook', 'Sunrise Trek to Top Station', 2, 2998, BookingStatus.PENDING, 2], ['BK-77286', 'GetYourGuide', 'Photoshoot at Tata Tea Museum', 6, 18600, BookingStatus.PENDING, 3], ['BK-77280', 'Direct - Voya', 'Traditional Meal of Kerala', 3, 4500, BookingStatus.CONFIRMED, 4], ['BK-77275', 'Viator', 'Athirappilly Excursion from Kochi to Munnar', 3, 2697, BookingStatus.CANCELLED, 1]] as const;
  for (const [bookingCode, channel, productName, pax, amount, status, day] of bookings) await prisma.booking.upsert({ where: { bookingCode }, update: {}, create: { tenantId: tenant.id, productId: products[productName].id, ratePlanId: productName === 'Sunrise Trek to Top Station' ? plan.id : null, bookingCode, channel, serviceDate: days(day), pax, paxBreakdown: { adult: pax }, amount, status, customerName: `Demo Guest ${bookingCode.slice(-2)}`, customerEmail: `guest${bookingCode.slice(-2)}@example.com` } });
  for (const p of [{ reference: 'PO-2026-001', amount: 184220, status: PayoutStatus.SCHEDULED, dueDate: days(4) }, { reference: 'PO-2026-000', amount: 42900, status: PayoutStatus.IN_TRANSIT, dueDate: days(2) }, { reference: 'PO-2026-099', amount: 126500, status: PayoutStatus.PAID, dueDate: days(-7) }]) if (!(await prisma.payout.findFirst({ where: { tenantId: tenant.id, reference: p.reference } }))) await prisma.payout.create({ data: { tenantId: tenant.id, ...p } });
  console.log('Seeded demo vendor and admin users from DEMO_PASSWORD.');
}
main().catch((e) => { console.error(e); process.exit(1); }).finally(() => prisma.$disconnect());
