import { ProductRevisionStatus, ProductStatus, ProductType, UserRole, VariantStatus } from '@prisma/client';
import { CatalogueService } from './catalogue.service';

const vendor = { sub: 'u1', email: 'vendor@test', role: UserRole.VENDOR, tenantId: 't1' } as any;
const admin = { sub: 'a1', email: 'admin@test', role: UserRole.ADMIN, tenantId: null } as any;
const revision = { id: 'r1', productId: 'p1', versionNumber: 1, status: ProductRevisionStatus.DRAFT, productName: 'Test product', type: ProductType.ACTIVITY, subType: 'TOUR', description: 'Description', shortDescription: null, terms: [], faqs: [], highlights: [], channels: [], highlightedPriority: null, isHotelLinked: false, attachedHotelIds: [], howToRedeem: [], subCategory: null, persuasions: [], labels: [], rank: null, starRating: null, safetyMeasures: [], importantInfo: [], thingsToCarry: [], additionalInfo: [], metaname: null, cityCode: null, lat: null, lon: null, address: null, cityName: 'Munnar', countryName: 'INDIA', stateName: 'Kerala', sourcePayload: null, rejectionReason: null, submittedAt: null, reviewedAt: null, reviewedById: null, createdById: 'u1' };

function service() {
  const tx: any = { $queryRaw: jest.fn(), product: { create: jest.fn(), update: jest.fn(), findUniqueOrThrow: jest.fn() }, productRevision: { create: jest.fn(), findFirst: jest.fn(), aggregate: jest.fn().mockResolvedValue({ _max: { versionNumber: 1 } }), update: jest.fn(), updateMany: jest.fn(), findUniqueOrThrow: jest.fn() }, productVariant: { create: jest.fn(), update: jest.fn(), updateMany: jest.fn(), findUniqueOrThrow: jest.fn() }, productMedia: { create: jest.fn(), createMany: jest.fn(), update: jest.fn(), findFirst: jest.fn() }, fileAsset: { create: jest.fn() } };
  const prisma: any = { product: { findFirst: jest.fn(), findFirstOrThrow: jest.fn() }, productRevision: { findFirst: jest.fn(), findMany: jest.fn() }, productVariant: { findFirst: jest.fn(), findMany: jest.fn(), update: jest.fn() }, $transaction: jest.fn(async (cb: any) => cb(tx)) };
  const audit: any = { write: jest.fn() }; const outbox: any = { enqueue: jest.fn() }; const storage: any = { save: jest.fn(), remove: jest.fn() };
  return { service: new CatalogueService(prisma, audit, outbox, storage), prisma, tx, audit, outbox, storage };
}

describe('catalogue hierarchy and revision state machine', () => {
  it('creates a Product root and stores initial content only in revision one', async () => {
    const s = service(); const product = { id: 'p1', tenantId: 't1', productCode: 'P-1', status: ProductStatus.DRAFT };
    s.tx.product.create.mockResolvedValue(product); s.prisma.product.findFirst.mockResolvedValue(product); s.prisma.product.findFirstOrThrow.mockResolvedValue({ ...product, revisions: [revision] });
    const result = await s.service.create(vendor, { productCode: 'P-1', initialRevision: { productName: 'Test product', type: ProductType.ACTIVITY, subType: 'TOUR', description: 'Description', cityName: 'Munnar', countryName: 'INDIA', stateName: 'Kerala' } });
    expect(result.id).toBe('p1'); expect(s.tx.productRevision.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ productId: 'p1', versionNumber: 1, createdById: 'u1' }) })); expect(s.audit.write).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ action: 'PRODUCT_CREATED', entityType: 'Product' }));
  });
  it('rejects Product creation without revision v1', async () => { const s = service(); await expect(s.service.create(vendor, { productCode: 'P-1' } as any)).rejects.toMatchObject({ status: 400 }); expect(s.tx.product.create).not.toHaveBeenCalled(); });
  it('returns the existing working revision instead of creating a second one', async () => { const s = service(); s.prisma.product.findFirst.mockResolvedValue({ id: 'p1', tenantId: 't1' }); s.tx.productRevision.findFirst.mockResolvedValue(revision); await expect(s.service.createRevision(vendor, 'p1')).resolves.toEqual(revision); expect(s.tx.productRevision.create).not.toHaveBeenCalled(); });
  it('clones published content using max existing version plus one', async () => { const s = service(); const published = { ...revision, status: ProductRevisionStatus.PUBLISHED, versionNumber: 1, id: 'r1', media: [] }; s.prisma.product.findFirst.mockResolvedValue({ id: 'p1', tenantId: 't1' }); s.tx.productRevision.findFirst.mockResolvedValueOnce(null).mockResolvedValueOnce(published); s.tx.productRevision.aggregate.mockResolvedValue({ _max: { versionNumber: 2 } }); s.tx.productRevision.create.mockResolvedValue({ ...revision, id: 'r3', versionNumber: 3 }); await expect(s.service.createRevision(vendor, 'p1')).resolves.toMatchObject({ versionNumber: 3 }); expect(s.tx.productRevision.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ versionNumber: 3, status: ProductRevisionStatus.DRAFT, productId: 'p1' }) })); });
  it('keeps rejected revisions immutable', async () => { const s = service(); s.prisma.productRevision.findFirst.mockResolvedValue({ ...revision, status: ProductRevisionStatus.REJECTED }); s.tx.productRevision.updateMany.mockResolvedValue({ count: 0 }); await expect(s.service.updateRevision(vendor, 'r1', { description: 'changed' } as any)).rejects.toMatchObject({ status: 409 }); s.tx.productRevision.findFirst.mockResolvedValue({ ...revision, status: ProductRevisionStatus.REJECTED }); await expect(s.service.submitRevision(vendor, 'r1')).rejects.toMatchObject({ status: 409 }); });
  it('submits only DRAFT revisions and emits audit plus outbox records', async () => { const s = service(); s.tx.productRevision.findFirst.mockResolvedValue(revision); s.tx.productRevision.updateMany.mockResolvedValue({ count: 1 }); s.tx.productRevision.findUniqueOrThrow.mockResolvedValue({ ...revision, status: ProductRevisionStatus.UNDER_REVIEW }); await expect(s.service.submitRevision(vendor, 'r1')).resolves.toMatchObject({ status: ProductRevisionStatus.UNDER_REVIEW }); expect(s.audit.write).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ action: 'PRODUCT_REVISION_SUBMITTED' })); expect(s.outbox.enqueue).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ eventType: 'PRODUCT_SUBMITTED', aggregateType: 'ProductRevision' })); });
  it('rejects non-draft submission without mutating state', async () => { const s = service(); s.tx.productRevision.findFirst.mockResolvedValue({ ...revision, status: ProductRevisionStatus.PUBLISHED }); await expect(s.service.submitRevision(vendor, 'r1')).rejects.toMatchObject({ status: 409 }); expect(s.tx.productRevision.updateMany).not.toHaveBeenCalled(); });
  it('publishes a submitted revision and supersedes the previous current revision', async () => { const s = service(); const candidate = { ...revision, status: ProductRevisionStatus.UNDER_REVIEW, product: { id: 'p1', tenantId: 't1', currentRevisionId: 'old' } }; s.tx.productRevision.findFirst.mockResolvedValue(candidate); s.tx.productRevision.updateMany.mockResolvedValue({ count: 1 }); s.tx.productRevision.update.mockResolvedValue({}); s.tx.product.update.mockResolvedValue({}); s.tx.product.findUniqueOrThrow.mockResolvedValue({ id: 'p1', status: ProductStatus.LIVE, currentRevisionId: 'r1' }); await expect(s.service.review(admin, 'r1', 'publish')).resolves.toMatchObject({ status: ProductStatus.LIVE }); expect(s.tx.productRevision.updateMany).toHaveBeenNthCalledWith(1, { where: { id: 'old', productId: 'p1', status: ProductRevisionStatus.PUBLISHED }, data: { status: ProductRevisionStatus.SUPERSEDED } }); expect(s.tx.productRevision.updateMany).toHaveBeenNthCalledWith(2, { where: { id: 'r1', productId: 'p1', status: ProductRevisionStatus.UNDER_REVIEW }, data: expect.objectContaining({ status: ProductRevisionStatus.PUBLISHED }) }); expect(s.tx.product.update).toHaveBeenCalledWith({ where: { id: 'p1' }, data: { currentRevisionId: 'r1', status: ProductStatus.LIVE } }); });
  it('rejects a submitted revision only with a reason', async () => { const s = service(); await expect(s.service.review(admin, 'r1', 'reject', { reason: 'no' })).rejects.toMatchObject({ status: 409 }); expect(s.tx.productRevision.updateMany).not.toHaveBeenCalled(); });
  it('prevents vendor-side review even when a revision is submitted', async () => { const s = service(); await expect(s.service.review(vendor, 'r1', 'publish')).rejects.toMatchObject({ status: 409 }); });
  it('archives variants instead of deleting their commercial history', async () => { const s = service(); s.prisma.productVariant.findFirst.mockResolvedValue({ id: 'v1', productId: 'p1', product: { tenantId: 't1' }, status: VariantStatus.ACTIVE, version: 1, archivedAt: null }); s.tx.productVariant.updateMany.mockResolvedValue({ count: 1 }); s.tx.productVariant.findUniqueOrThrow.mockResolvedValue({ id: 'v1', status: VariantStatus.ARCHIVED, version: 2, archivedAt: new Date() }); await expect(s.service.archiveVariant(vendor, 'v1', { expectedVersion: 1 })).resolves.toMatchObject({ status: VariantStatus.ARCHIVED }); expect(s.tx.productVariant.updateMany).toHaveBeenCalledWith(expect.objectContaining({ where: { id: 'v1', version: 1, status: { not: VariantStatus.ARCHIVED }, archivedAt: null }, data: expect.objectContaining({ status: VariantStatus.ARCHIVED, version: { increment: 1 } }) })); expect(s.audit.write).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ action: 'PRODUCT_VARIANT_ARCHIVED' })); expect(s.outbox.enqueue).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ eventType: 'PRODUCT_VARIANT_ARCHIVED' })); });
  it('does not allow variant code or status edits through the update endpoint', async () => { const s = service(); s.prisma.productVariant.findFirst.mockResolvedValue({ id: 'v1', productId: 'p1', product: { tenantId: 't1' }, status: VariantStatus.ACTIVE, version: 1, archivedAt: null }); await expect(s.service.updateVariant(vendor, 'v1', { variantCode: 'CHANGED', expectedVersion: 1 } as any)).rejects.toMatchObject({ status: 409 }); expect(s.tx.productVariant.update).not.toHaveBeenCalled(); });
  it('writes create variant audit and outbox records transactionally', async () => { const s = service(); s.prisma.product.findFirst.mockResolvedValue({ id: 'p1', tenantId: 't1' }); s.tx.productVariant.create.mockResolvedValue({ id: 'v1', variantCode: 'V1', name: 'Shared', status: VariantStatus.ACTIVE }); await expect(s.service.createVariant(vendor, 'p1', { variantCode: 'V1', name: 'Shared' } as any)).resolves.toMatchObject({ id: 'v1' }); expect(s.audit.write).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ action: 'PRODUCT_VARIANT_CREATED' })); expect(s.outbox.enqueue).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ eventType: 'PRODUCT_VARIANT_CREATED' })); });
  it('increments variant version on editable updates', async () => { const s = service(); s.prisma.productVariant.findFirst.mockResolvedValue({ id: 'v1', productId: 'p1', product: { tenantId: 't1' }, status: VariantStatus.ACTIVE, version: 3, archivedAt: null, name: 'Old' }); s.tx.productVariant.updateMany.mockResolvedValue({ count: 1 }); s.tx.productVariant.findUniqueOrThrow.mockResolvedValue({ id: 'v1', version: 4, status: VariantStatus.ACTIVE, name: 'New' }); await expect(s.service.updateVariant(vendor, 'v1', { name: 'New', expectedVersion: 3 })).resolves.toMatchObject({ version: 4 }); expect(s.tx.productVariant.updateMany).toHaveBeenCalledWith({ where: { id: 'v1', version: 3, status: { not: VariantStatus.ARCHIVED }, archivedAt: null }, data: { name: 'New', version: { increment: 1 } } }); });
  it('rejects invalid media signatures before storage', async () => { const s = service(); await expect(s.service.uploadMedia(vendor, 'r1', { buffer: Buffer.from('<svg>'), size: 5, originalname: 'x.svg' }, { kind: 'IMAGE' } as any)).rejects.toMatchObject({ status: 409 }); expect(s.storage.save).not.toHaveBeenCalled(); });
});
