import { validate } from 'class-validator';
import { ProductRevisionStatus, ProductStatus, ProductType, UserRole, VariantStatus } from '@prisma/client';
import { ArchiveVariantDto, CreateProductRevisionDto, UpdateVariantDto } from './catalogue.dto';
import { CatalogueService } from './catalogue.service';

const vendor = { sub: 'u1', email: 'vendor@test', role: UserRole.VENDOR, tenantId: 't1' } as any;
const admin = { sub: 'a1', email: 'admin@test', role: UserRole.ADMIN, tenantId: null } as any;
const baseRevision = { id: 'r1', productId: 'p1', versionNumber: 1, status: ProductRevisionStatus.DRAFT, productName: 'Test', type: ProductType.ACTIVITY, subType: 'TOUR', description: 'Description', media: [], faqs: [], sourcePayload: null } as any;

function make() {
  const tx: any = { productRevision: { findFirst: jest.fn(), findUnique: jest.fn(), update: jest.fn(), updateMany: jest.fn(), create: jest.fn(), aggregate: jest.fn().mockResolvedValue({ _max: { versionNumber: 2 } }), findUniqueOrThrow: jest.fn() }, productMedia: { create: jest.fn(), findFirst: jest.fn(), update: jest.fn(), createMany: jest.fn() }, fileAsset: { create: jest.fn() }, productVariant: { updateMany: jest.fn(), findUniqueOrThrow: jest.fn() }, product: { update: jest.fn(), findUniqueOrThrow: jest.fn() }, $queryRaw: jest.fn() };
  const prisma: any = { productRevision: { findFirst: jest.fn(), findFirstOrThrow: jest.fn() }, productMedia: { create: jest.fn() }, fileAsset: { findFirst: jest.fn() }, productVariant: { findFirst: jest.fn() }, product: { findFirst: jest.fn().mockResolvedValue({ id: 'p1', tenantId: 't1' }) }, $transaction: jest.fn((cb: any) => cb(tx)) };
  const storage: any = { save: jest.fn().mockResolvedValue({ storageKey: 'product-media/x.jpg', sizeBytes: 10 }), remove: jest.fn() };
  const audit: any = { write: jest.fn() }; const outbox: any = { enqueue: jest.fn() };
  return { service: new CatalogueService(prisma, audit, outbox, storage), prisma, tx, storage, audit };
}

describe('Phase 2.2 revision and media immutability', () => {
  it('updates a DRAFT revision under a row lock and audits the result', async () => { const s = make(); s.prisma.productRevision.findFirst.mockResolvedValue(baseRevision); s.tx.productRevision.findUnique.mockResolvedValue(baseRevision); s.tx.productRevision.update.mockResolvedValue({ ...baseRevision, description: 'Updated' }); await expect(s.service.updateRevision(vendor, 'r1', { description: 'Updated' } as any)).resolves.toMatchObject({ description: 'Updated' }); expect(s.tx.$queryRaw).toHaveBeenCalled(); expect(s.tx.productRevision.update).toHaveBeenCalledWith(expect.objectContaining({ where: { id: 'r1' } })); expect(s.audit.write).toHaveBeenCalled(); });
  it('rejects an update when submit wins before the row lock is released', async () => { const s = make(); s.prisma.productRevision.findFirst.mockResolvedValue({ ...baseRevision, status: ProductRevisionStatus.DRAFT }); s.tx.productRevision.findUnique.mockResolvedValue({ ...baseRevision, status: ProductRevisionStatus.UNDER_REVIEW }); await expect(s.service.updateRevision(vendor, 'r1', { description: 'stale' } as any)).rejects.toMatchObject({ status: 409 }); expect(s.tx.productRevision.update).not.toHaveBeenCalled(); });
  it.each([ProductRevisionStatus.UNDER_REVIEW, ProductRevisionStatus.REJECTED, ProductRevisionStatus.PUBLISHED, ProductRevisionStatus.SUPERSEDED])('blocks external media on %s revisions', async (status) => { const s = make(); s.prisma.productRevision.findFirst.mockResolvedValue({ ...baseRevision, status }); await expect(s.service.addMedia(vendor, 'r1', { kind: 'IMAGE', externalUrl: 'https://example.com/a.jpg' })).rejects.toMatchObject({ status: 409 }); expect(s.tx.productMedia.create).not.toHaveBeenCalled(); });
  it.each([ProductRevisionStatus.UNDER_REVIEW, ProductRevisionStatus.REJECTED, ProductRevisionStatus.PUBLISHED])('blocks media archive on %s revisions', async (status) => { const s = make(); s.prisma.productRevision.findFirst.mockResolvedValue({ ...baseRevision, status }); await expect(s.service.archiveMedia(vendor, 'r1', 'm1')).rejects.toMatchObject({ status: 409 }); expect(s.tx.productMedia.update).not.toHaveBeenCalled(); });
  it('adds external media to DRAFT in a transaction with audit metadata', async () => { const s = make(); s.prisma.productRevision.findFirst.mockResolvedValue(baseRevision); s.tx.productRevision.findFirst.mockResolvedValue(baseRevision); s.tx.productMedia.create.mockResolvedValue({ id: 'm1', revisionId: 'r1', kind: 'IMAGE' }); await expect(s.service.addMedia(vendor, 'r1', { kind: 'IMAGE', externalUrl: 'https://example.com/a.jpg' })).resolves.toMatchObject({ id: 'm1' }); expect(s.audit.write).toHaveBeenCalledWith(expect.anything(), expect.objectContaining({ action: 'PRODUCT_MEDIA_ADDED', afterState: expect.objectContaining({ productId: 'p1', revisionId: 'r1', mediaId: 'm1', kind: 'IMAGE' }) })); });
  it('cleans physical storage when media transaction fails', async () => { const s = make(); s.prisma.productRevision.findFirst.mockResolvedValue(baseRevision); s.tx.productRevision.findFirst.mockResolvedValue(baseRevision); s.tx.fileAsset.create.mockRejectedValue(new Error('db failure')); await expect(s.service.uploadMedia(vendor, 'r1', { buffer: Buffer.from([0xff, 0xd8, 0xff, 0x00]), size: 4, originalname: 'claimed.png' }, { kind: 'IMAGE' } as any)).rejects.toThrow('db failure'); expect(s.storage.remove).toHaveBeenCalledWith('product-media/x.jpg'); });
  it('does not accept upload media on UNDER_REVIEW even when the file is valid', async () => { const s = make(); s.prisma.productRevision.findFirst.mockResolvedValue({ ...baseRevision, status: ProductRevisionStatus.UNDER_REVIEW }); await expect(s.service.uploadMedia(vendor, 'r1', { buffer: Buffer.from([0xff, 0xd8, 0xff]), size: 3 }, { kind: 'IMAGE' } as any)).rejects.toMatchObject({ status: 409 }); expect(s.storage.save).not.toHaveBeenCalled(); });
  it('defaults correction source to a newer rejected revision', async () => { const s = make(); const rejected = { ...baseRevision, id: 'r2', versionNumber: 2, status: ProductRevisionStatus.REJECTED, description: 'Vendor correction', media: [] }; s.tx.productRevision.findFirst.mockResolvedValueOnce(null).mockResolvedValueOnce(null).mockResolvedValueOnce(rejected); s.tx.productRevision.create.mockResolvedValue({ id: 'r3', productId: 'p1', versionNumber: 3, status: ProductRevisionStatus.DRAFT }); await expect(s.service.createRevision(vendor, 'p1')).resolves.toMatchObject({ versionNumber: 3 }); expect(s.tx.productRevision.create).toHaveBeenCalledWith(expect.objectContaining({ data: expect.objectContaining({ description: 'Vendor correction', versionNumber: 3 }) })); });
  it('rejects an explicit source revision belonging to another Product', async () => { const s = make(); s.tx.productRevision.findFirst.mockResolvedValueOnce(null).mockResolvedValueOnce(null); await expect(s.service.createRevision(vendor, 'p1', { sourceRevisionId: 'other-product-revision' })).rejects.toMatchObject({ status: 409 }); expect(s.tx.productRevision.create).not.toHaveBeenCalled(); });
  it('rejects stale Variant updates atomically', async () => { const s = make(); s.prisma.productVariant.findFirst.mockResolvedValue({ id: 'v1', productId: 'p1', product: { tenantId: 't1' }, status: VariantStatus.ACTIVE, archivedAt: null, version: 3 }); s.tx.productVariant.updateMany.mockResolvedValue({ count: 0 }); await expect(s.service.updateVariant(vendor, 'v1', { expectedVersion: 2, name: 'stale' })).rejects.toMatchObject({ status: 409 }); });
  it('rejects the second archive with a stale expected version', async () => { const s = make(); s.prisma.productVariant.findFirst.mockResolvedValue({ id: 'v1', productId: 'p1', product: { tenantId: 't1' }, status: VariantStatus.ACTIVE, archivedAt: null, version: 3 }); s.tx.productVariant.updateMany.mockResolvedValue({ count: 0 }); await expect(s.service.archiveVariant(vendor, 'v1', { expectedVersion: 3 })).rejects.toMatchObject({ status: 409 }); });
  it('requires expectedVersion and omits variantCode from update DTO', async () => { const updateErrors = await validate(Object.assign(new UpdateVariantDto(), { name: 'x' })); expect(updateErrors.some((error) => error.property === 'expectedVersion')).toBe(true); expect('variantCode' in new UpdateVariantDto()).toBe(false); const archiveErrors = await validate(new ArchiveVariantDto()); expect(archiveErrors.some((error) => error.property === 'expectedVersion')).toBe(true); expect(new CreateProductRevisionDto()).toBeDefined(); });
  it('keeps the product live while a corrected revision remains a draft', async () => { const s = make(); const published = { ...baseRevision, id: 'r1', status: ProductRevisionStatus.PUBLISHED }; const rejected = { ...baseRevision, id: 'r2', versionNumber: 2, status: ProductRevisionStatus.REJECTED, media: [] }; s.tx.productRevision.findFirst.mockResolvedValueOnce(null).mockResolvedValueOnce(published).mockResolvedValueOnce(rejected).mockResolvedValueOnce(rejected); s.tx.productRevision.create.mockResolvedValue({ id: 'r3', productId: 'p1', versionNumber: 3, status: ProductRevisionStatus.DRAFT }); await expect(s.service.createRevision(vendor, 'p1', { sourceRevisionId: 'r2' })).resolves.toMatchObject({ status: ProductRevisionStatus.DRAFT }); expect(s.tx.product.update).not.toHaveBeenCalled(); });
});
