"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { apiRequest } from "@/services/apiClient";

type SettingsValue = Record<string, unknown>;

export function SettingsSubmodule({ title, description, href }: { title: string; description: string; href?: string }) {
  const section = title.toLowerCase(); const [value, setValue] = useState<SettingsValue>({}); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  useEffect(() => { void apiRequest<{ value: SettingsValue }>(`/settings/${section}`).then((result) => setValue(result.value)).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : "Unable to load settings")).finally(() => setLoading(false)); }, [section]);
  async function save(event: React.FormEvent) { event.preventDefault(); setSaving(true); setMessage(""); setError(""); try { await apiRequest(`/settings/${section}`, { method: "PATCH", body: JSON.stringify({ value }) }); setMessage("Settings saved"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save settings"); } finally { setSaving(false); } }
  const set = (key: string, next: unknown) => setValue((current) => ({ ...current, [key]: next }));
  return <div><div className="page-heading"><div><p className="eyebrow">ADMINISTRATION / SETTINGS</p><h2>{title}</h2><p className="subtext">{description}</p></div>{href && <Link className="button-link" href={href}>Manage {title.toLowerCase()}</Link>}</div><form className="panel form-grid" onSubmit={save}>{loading ? <div className="page-loading">Loading settings…</div> : <>{section === "currencies" && <><label>Base currency<input maxLength={3} value={String(value.baseCurrency ?? "INR")} onChange={(event) => set("baseCurrency", event.target.value.toUpperCase())} /></label><label>Supported currencies<input value={Array.isArray(value.supportedCurrencies) ? value.supportedCurrencies.join(", ") : ""} onChange={(event) => set("supportedCurrencies", event.target.value.split(",").map((item) => item.trim().toUpperCase()).filter(Boolean))} /></label></>}{section === "notifications" && <><label className="checkbox-label"><input type="checkbox" checked={Boolean(value.emailBookings)} onChange={(event) => set("emailBookings", event.target.checked)} /> Booking notifications</label><label className="checkbox-label"><input type="checkbox" checked={Boolean(value.emailCancellations)} onChange={(event) => set("emailCancellations", event.target.checked)} /> Cancellation notifications</label><label className="checkbox-label"><input type="checkbox" checked={Boolean(value.emailPayments)} onChange={(event) => set("emailPayments", event.target.checked)} /> Payment notifications</label></>}{section === "taxes" && <><label>Calculation mode<select value={String(value.calculationMode ?? "exclusive")} onChange={(event) => set("calculationMode", event.target.value)}><option value="exclusive">Exclusive</option><option value="inclusive">Inclusive</option></select></label><label className="checkbox-label"><input type="checkbox" checked={Boolean(value.displayOnInvoice)} onChange={(event) => set("displayOnInvoice", event.target.checked)} /> Display tax on invoices</label></>}{error && <p className="form-error">{error}</p>}{message && <p className="notice success">{message}</p>}<div className="form-actions"><button className="primary" disabled={saving}>{saving ? "Saving…" : "Save settings"}</button></div></>}</form></div>;
}
