CREATE TYPE "SupplierTier" AS ENUM ('ELITE', 'PREFERRED', 'STANDARD', 'WATCHLIST', 'RESTRICTED');
CREATE TYPE "SupplierQualityPolicyStatus" AS ENUM ('DRAFT', 'ACTIVE', 'RETIRED');
CREATE TYPE "SupplierQualityDimension" AS ENUM ('CONFIRMATION_SLA', 'CANCELLATION_RELIABILITY', 'FULFILMENT_QUALITY', 'INVENTORY_RELIABILITY', 'TRAVELLER_OUTCOME', 'CATALOGUE_QUALITY');
CREATE TYPE "SupplierQualityMetricCode" AS ENUM ('CONFIRMATION_WITHIN_SLA_RATE', 'VENDOR_RESPONSE_WITHIN_SLA_RATE', 'AVG_VENDOR_RESPONSE_MINUTES', 'CONFIRMATION_OVERDUE_RATE', 'VENDOR_CANCELLATION_RATE', 'SHORT_NOTICE_VENDOR_CANCELLATION_RATE', 'VOUCHER_READY_BEFORE_SERVICE_RATE', 'AVG_FULFILMENT_TURNAROUND_MINUTES', 'LAST_MINUTE_STOP_SELL_RATE', 'LIVE_PRODUCT_IMAGE_COVERAGE_RATE', 'CUSTOMER_RATING', 'NPS', 'COMPLAINT_RATE');
CREATE TYPE "SupplierMetricDirection" AS ENUM ('HIGHER_BETTER', 'LOWER_BETTER');
CREATE TYPE "SupplierMetricMissingDataTreatment" AS ENUM ('EXCLUDE', 'WARN', 'FAIL');
CREATE TYPE "SupplierMetricStatus" AS ENUM ('PASS', 'WARN', 'FAIL', 'INSUFFICIENT_DATA', 'UNAVAILABLE', 'UNASSESSED');
CREATE TYPE "SupplierQualityIssueSeverity" AS ENUM ('INFO', 'WARNING', 'CRITICAL');
CREATE TYPE "SupplierQualityIssueStatus" AS ENUM ('OPEN', 'ACKNOWLEDGED', 'RESOLVED', 'DISMISSED');

CREATE TABLE "SupplierQualityPolicy" ("id" TEXT NOT NULL,"versionNumber" INTEGER NOT NULL,"status" "SupplierQualityPolicyStatus" NOT NULL DEFAULT 'DRAFT',"name" TEXT NOT NULL,"measurementWindowDays" INTEGER NOT NULL,"shortNoticeDays" INTEGER NOT NULL,"lastMinuteStopSellDays" INTEGER NOT NULL,"createdById" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"activatedById" TEXT,"activatedAt" TIMESTAMP(3),"retiredAt" TIMESTAMP(3),"lockVersion" INTEGER NOT NULL DEFAULT 1,CONSTRAINT "SupplierQualityPolicy_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SupplierQualityMetricRule" ("id" TEXT NOT NULL,"policyId" TEXT NOT NULL,"metricCode" "SupplierQualityMetricCode" NOT NULL,"dimension" "SupplierQualityDimension" NOT NULL,"enabled" BOOLEAN NOT NULL DEFAULT true,"direction" "SupplierMetricDirection" NOT NULL,"weight" DOUBLE PRECISION NOT NULL,"targetValue" DOUBLE PRECISION NOT NULL,"warningValue" DOUBLE PRECISION NOT NULL,"minimumSampleSize" INTEGER NOT NULL DEFAULT 1,"missingDataTreatment" "SupplierMetricMissingDataTreatment" NOT NULL DEFAULT 'EXCLUDE',"passScore" DOUBLE PRECISION NOT NULL DEFAULT 100,"warnScore" DOUBLE PRECISION NOT NULL DEFAULT 50,"failScore" DOUBLE PRECISION NOT NULL DEFAULT 0,"rank" INTEGER NOT NULL DEFAULT 0,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SupplierQualityMetricRule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SupplierTierRule" ("id" TEXT NOT NULL,"policyId" TEXT NOT NULL,"tier" "SupplierTier" NOT NULL,"minimumScore" DOUBLE PRECISION NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "SupplierTierRule_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SupplierQualitySnapshot" ("id" TEXT NOT NULL,"vendorTenantId" TEXT NOT NULL,"policyId" TEXT,"windowStart" TIMESTAMP(3) NOT NULL,"windowEnd" TIMESTAMP(3) NOT NULL,"overallScore" DOUBLE PRECISION,"recommendedTier" "SupplierTier","currentTierAtCalculation" "SupplierTier","generatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"metrics" JSONB NOT NULL,"snapshotKey" TEXT NOT NULL,CONSTRAINT "SupplierQualitySnapshot_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SupplierQualityMetricSnapshot" ("id" TEXT NOT NULL,"snapshotId" TEXT NOT NULL,"metricCode" "SupplierQualityMetricCode" NOT NULL,"dimension" "SupplierQualityDimension" NOT NULL,"rawValue" DOUBLE PRECISION,"numerator" INTEGER,"denominator" INTEGER,"sampleSize" INTEGER NOT NULL,"unit" TEXT NOT NULL,"status" "SupplierMetricStatus" NOT NULL,"score" DOUBLE PRECISION,"sourceTrace" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "SupplierQualityMetricSnapshot_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SupplierTierAssignment" ("id" TEXT NOT NULL,"vendorTenantId" TEXT NOT NULL,"tier" "SupplierTier" NOT NULL,"sourceSnapshotId" TEXT,"reason" TEXT NOT NULL,"assignedById" TEXT NOT NULL,"assignedAt" TIMESTAMP(3) NOT NULL,"effectiveFrom" TIMESTAMP(3) NOT NULL,"effectiveTo" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "SupplierTierAssignment_pkey" PRIMARY KEY ("id"));
CREATE TABLE "SupplierQualityIssue" ("id" TEXT NOT NULL,"vendorTenantId" TEXT NOT NULL,"snapshotId" TEXT NOT NULL,"metricCode" "SupplierQualityMetricCode" NOT NULL,"dimension" "SupplierQualityDimension" NOT NULL,"severity" "SupplierQualityIssueSeverity" NOT NULL,"status" "SupplierQualityIssueStatus" NOT NULL DEFAULT 'OPEN',"title" TEXT NOT NULL,"details" JSONB NOT NULL,"openedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"acknowledgedAt" TIMESTAMP(3),"acknowledgedById" TEXT,"resolvedAt" TIMESTAMP(3),"resolvedById" TEXT,"resolutionReason" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "SupplierQualityIssue_pkey" PRIMARY KEY ("id"));
