import { useEffect, useState } from 'react';
import { api, type CommercialVersion, type RatePlan } from '../api';
import { Badge, Field, Panel } from './Ui';

const travellerTypes = ['ADULT', 'CHILD', 'SENIOR'] as const;
type CommercialResponse = { readiness: { ready: boolean; reasonCodes: string[]; activeVersion?: CommercialVersion | null; draftVersion?: CommercialVersion | null }; versions: CommercialVersion[] };
export default function CommercialEditor({ plan, onRefresh, setError }: { plan: RatePlan; onRefresh: () => void; setError: (value: string) => void }) {
  const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [data, setData] = useState<CommercialResponse | null>(null); const [supplierModel, setSupplierModel] = useState('NET_RATE'); const [pricingUnit, setPricingUnit] = useState('PER_PERSON'); const [bookingMode, setBookingMode] = useState('INSTANT'); const [amount, setAmount] = useState('0'); const [commission, setCommission] = useState(''); const [prices, setPrices] = useState<Record<string, string>>({ ADULT: '', CHILD: '', SENIOR: '' });
  const readiness = data?.readiness || plan.commercialReadiness;
  async function load() { try { const result = await api.request<CommercialResponse>(`/rate-plans/${plan.id}/commercial`); setData(result); const draft = result.readiness.draftVersion; if (draft) { setSupplierModel(draft.supplierModel || 'NET_RATE'); setPricingUnit(draft.pricingUnit || 'PER_PERSON'); setBookingMode(draft.bookingMode || 'INSTANT'); setAmount(String(draft.supplierBaseAmount ?? '')); setCommission(draft.supplierCommissionPercent == null ? '' : String(draft.supplierCommissionPercent)); setPrices(Object.fromEntries(travellerTypes.map((t) => [t, String(draft.travellerPrices.find((p) => p.travellerType === t)?.amount || '')]))); } } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void load(); }, [plan.id]);
  async function save(activate: boolean) { setBusy(true); setError(''); try { const draft = data?.readiness.draftVersion; const payload = { effectiveFrom: draft?.effectiveFrom || new Date().toISOString(), effectiveTo: draft?.effectiveTo || plan.validTo, supplierModel, pricingUnit, bookingMode, supplierBaseAmount: amount, supplierCommissionPercent: commission || undefined, currency: plan.currency, travellerPrices: pricingUnit === 'PER_PERSON' ? travellerTypes.filter((t) => prices[t]).map((t) => ({ travellerType: t, amount: prices[t] })) : [] }; const version = draft ? await api.request<CommercialVersion>(`/rate-plan-commercial-versions/${draft.id}`, { method: 'PATCH', body: JSON.stringify(payload) }) : await api.request<CommercialVersion>(`/rate-plans/${plan.id}/commercial/versions`, { method: 'POST', body: JSON.stringify(payload) }); if (activate) await api.request(`/rate-plan-commercial-versions/${version.id}/activate`, { method: 'POST' }); setOpen(false); await load(); onRefresh(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <Panel title={`Commercial terms · ${plan.name}`} action={readiness ? <Badge value={readiness.ready ? 'READY' : 'NEEDS_REVIEW'} /> : undefined}><div className="rate-meta"><span>Supplier terms are versioned and confidential</span><span>{readiness?.activeVersion ? `Active v${readiness.activeVersion.versionNumber}` : 'No active version'}</span><span>{readiness?.draftVersion ? `Draft v${readiness.draftVersion.versionNumber}` : 'No draft'}</span></div>{readiness?.reasonCodes?.length ? <p className="muted">Readiness: {readiness.reasonCodes.join(', ')}</p> : null}<button className="btn small" onClick={() => setOpen(!open)}>{open ? 'Close editor' : 'Edit supplier terms'}</button>{open && <><div className="form-grid four"><Field label="Supplier model"><select value={supplierModel} onChange={(e) => setSupplierModel(e.target.value)}><option>NET_RATE</option><option>COMMISSIONABLE</option></select></Field><Field label="Pricing unit"><select value={pricingUnit} onChange={(e) => setPricingUnit(e.target.value)}><option>PER_PERSON</option><option>PER_BOOKING</option><option>PER_UNIT</option><option>GROUP</option></select></Field><Field label="Booking mode"><select value={bookingMode} onChange={(e) => setBookingMode(e.target.value)}><option>INSTANT</option><option>VENDOR_CONFIRMATION</option><option>MANUAL_ON_REQUEST</option></select></Field><Field label="Supplier base amount"><input inputMode="decimal" value={amount} onChange={(e) => setAmount(e.target.value)} /></Field>{supplierModel === 'COMMISSIONABLE' ? <Field label="Supplier commission %"><input inputMode="decimal" value={commission} onChange={(e) => setCommission(e.target.value)} /></Field> : null}</div>{pricingUnit === 'PER_PERSON' && <div className="form-grid three">{travellerTypes.map((type) => <Field key={type} label={`${type} price`}><input inputMode="decimal" value={prices[type]} onChange={(e) => setPrices({ ...prices, [type]: e.target.value })} /></Field>)}</div>}<div className="actions"><button className="btn" disabled={busy} onClick={() => void save(false)}>Save draft</button><button className="btn primary" disabled={busy} onClick={() => void save(true)}>Save & activate</button></div></>}</Panel>;
}
