import { useEffect, useState } from 'react';
import { api } from '../api';
import { ErrorBox, Field } from './Ui';

type Rule = { id: string; activityId: string; name: string; appliesTo: string; adjustmentType: 'PERCENTAGE' | 'ABSOLUTE'; adjustment: number | string; startsAt: string; endsAt: string; active: boolean };
const blank = (activityId: string): Omit<Rule, 'id'> => ({ activityId, name: '', appliesTo: 'All listings', adjustmentType: 'PERCENTAGE', adjustment: 0, startsAt: new Date().toISOString().slice(0, 10), endsAt: new Date(Date.now() + 365 * 86400000).toISOString().slice(0, 10), active: true });

export default function PricingRules({ activityId }: { activityId: string }) {
  const [rules, setRules] = useState<Rule[]>([]), [editing, setEditing] = useState<Rule | null>(null), [form, setForm] = useState(blank(activityId)), [open, setOpen] = useState(false), [error, setError] = useState('');
  async function load() { if (!activityId) return; try { setRules(await api.request<Rule[]>(`/pricing-rules?activityId=${activityId}`)); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void load(); }, [activityId]);
  function start(rule?: Rule) { setEditing(rule || null); setForm(rule ? { ...rule, adjustment: Number(rule.adjustment), startsAt: rule.startsAt.slice(0, 10), endsAt: rule.endsAt.slice(0, 10) } : blank(activityId)); setOpen(true); setError(''); }
  async function save() { try { if (!form.name.trim()) throw new Error('Rule name is required.'); if (form.endsAt <= form.startsAt) throw new Error('End date must be after start date.'); const saved = editing ? await api.request<Rule>(`/pricing-rules/${editing.id}`, { method: 'PATCH', body: JSON.stringify(form) }) : await api.request<Rule>('/pricing-rules', { method: 'POST', body: JSON.stringify(form) }); setRules(x => editing ? x.map(r => r.id === saved.id ? saved : r) : [...x, saved]); setOpen(false); } catch (e) { setError((e as Error).message); } }
  async function remove(id: string) { if (!window.confirm('Delete this pricing rule?')) return; try { await api.request(`/pricing-rules/${id}`, { method: 'DELETE' }); setRules(x => x.filter(r => r.id !== id)); } catch (e) { setError((e as Error).message); } }
  async function toggle(rule: Rule) { const saved = await api.request<Rule>(`/pricing-rules/${rule.id}`, { method: 'PATCH', body: JSON.stringify({ active: !rule.active }) }); setRules(x => x.map(r => r.id === saved.id ? saved : r)); }
  return <>{error && <ErrorBox error={error} />}<div className="pricing-rule-toolbar"><button className="btn accent" onClick={() => start()}>+ Add Pricing Rule</button></div>{rules.map(r => <div className="rule-row" key={r.id}><b>{r.name}</b><span>{r.appliesTo}</span><strong>{r.adjustmentType === 'PERCENTAGE' ? `${Number(r.adjustment) > 0 ? '+' : ''}${r.adjustment}%` : `${Number(r.adjustment) > 0 ? '+' : ''}₹${r.adjustment}`}</strong><button className={`badge ${r.active ? 'live' : ''}`} onClick={() => void toggle(r)}>{r.active ? 'Active' : 'Inactive'}</button><button className="btn small" onClick={() => start(r)}>Edit</button><button className="btn small" onClick={() => void remove(r.id)}>Delete</button></div>)}{!rules.length && <p className="muted">No pricing rules configured for this activity.</p>}{open && <div className="modal-backdrop"><div className="modal-card"><h3>{editing ? 'Edit Pricing Rule' : 'Add Pricing Rule'}</h3><div className="form-grid two"><Field label="Rule name"><input value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></Field><Field label="Applies to"><input value={form.appliesTo} onChange={e => setForm({ ...form, appliesTo: e.target.value })} /></Field><Field label="Adjustment type"><select value={form.adjustmentType} onChange={e => setForm({ ...form, adjustmentType: e.target.value as Rule['adjustmentType'] })}><option value="PERCENTAGE">Percentage</option><option value="ABSOLUTE">Fixed amount</option></select></Field><Field label="Adjustment"><input type="number" min={0} value={form.adjustment} onChange={e => setForm({ ...form, adjustment: Number(e.target.value) })} /></Field><Field label="Start date"><input type="date" value={form.startsAt} onChange={e => setForm({ ...form, startsAt: e.target.value })} /></Field><Field label="End date"><input type="date" value={form.endsAt} onChange={e => setForm({ ...form, endsAt: e.target.value })} /></Field></div><label className="check"><input type="checkbox" checked={form.active} onChange={e => setForm({ ...form, active: e.target.checked })} /> Active</label><div className="modal-actions"><button className="btn" onClick={() => setOpen(false)}>Cancel</button><button className="btn primary" onClick={() => void save()}>Save Rule</button></div></div></div>}</>;
}
