import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { ChannelApiCredential, ChannelCredentialStatus, DistributionCapability, DistributionChannelType, Prisma } from '@prisma/client';
import { createHash, randomBytes } from 'crypto';
import { AuditService } from '../audit/audit.service';
import { AuthUser } from '../common/auth.types';
import { OutboxService } from '../outbox/outbox.service';
import { PrismaService } from '../prisma/prisma.service';
import { ChannelContractService } from './channel-contract.service';
import { ChannelEligibilityService } from './channel-eligibility.service';
import { ChannelMappingService } from './channel-mapping.service';
import { CreateChannelDto, CreateCredentialDto, UpdateChannelDto } from './distribution.dto';

@Injectable()
export class DistributionService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService, private readonly outbox: OutboxService, private readonly contracts: ChannelContractService, private readonly mappings: ChannelMappingService, private readonly eligibility: ChannelEligibilityService) {}
  channels() { return this.prisma.distributionChannel.findMany({ include: { contracts: { where: { status: 'ACTIVE' }, orderBy: { versionNumber: 'desc' }, take: 1 }, _count: { select: { mappings: true, productMappings: true, variantMappings: true, credentials: true } } }, orderBy: { code: 'asc' } }); }
  async createChannel(user: AuthUser, dto: CreateChannelDto) {
    const code = dto.code.trim(); const name = dto.name.trim(); if (!name) throw new ConflictException('Channel name must be non-empty');
    try { return await this.prisma.$transaction(async (tx) => { const channel = await tx.distributionChannel.create({ data: { code, name, type: dto.type, description: dto.description?.trim() || null, active: dto.active ?? true } }); await this.audit.write(tx, { actor: user, action: 'DISTRIBUTION_CHANNEL_CREATED', entityType: 'DistributionChannel', entityId: channel.id, afterState: { code: channel.code, type: channel.type, active: channel.active } }); await this.outbox.enqueue(tx, { eventType: 'DISTRIBUTION_CHANNEL_CREATED', aggregateType: 'DistributionChannel', aggregateId: channel.id, payload: { channelId: channel.id, code: channel.code } }); return channel; }); } catch (error: any) { if (error?.code === 'P2002') throw new ConflictException('Distribution channel code already exists'); throw error; }
  }
  async updateChannel(user: AuthUser, id: string, dto: UpdateChannelDto) {
    return this.prisma.$transaction(async (tx) => {
      const current = await tx.distributionChannel.findUnique({ where: { id } }); if (!current) throw new NotFoundException('Distribution channel not found'); if (dto.expectedVersion == null) throw new ConflictException({ code: 'CHANNEL_VERSION_REQUIRED', message: 'expectedVersion is required for channel updates' });
      if (current.code === 'VOYA_AGENT' && dto.type && dto.type !== DistributionChannelType.INTERNAL_MARKETPLACE) throw new ConflictException('VOYA_AGENT channel type is protected'); if (current.active && dto.active === false && !dto.confirmDisable) throw new ConflictException({ code: 'CHANNEL_DISABLE_CONFIRMATION_REQUIRED', message: 'Disabling a live channel requires confirmation' });
      const changed = await tx.distributionChannel.updateMany({ where: { id, version: dto.expectedVersion }, data: { name: dto.name == null ? undefined : dto.name.trim(), type: dto.type, description: dto.description == null ? undefined : dto.description.trim(), active: dto.active, version: { increment: 1 } } }); if (changed.count !== 1) throw new ConflictException({ code: 'CHANNEL_VERSION_MISMATCH', message: 'Distribution channel changed; reload and retry' });
      const channel = await tx.distributionChannel.findUniqueOrThrow({ where: { id } }); await this.audit.write(tx, { actor: user, action: 'DISTRIBUTION_CHANNEL_UPDATED', entityType: 'DistributionChannel', entityId: id, afterState: { active: channel.active, type: channel.type, version: channel.version } }); await this.outbox.enqueue(tx, { eventType: 'DISTRIBUTION_CHANNEL_CHANGED', aggregateType: 'DistributionChannel', aggregateId: id, payload: { channelId: id, active: channel.active, version: channel.version } }); return channel;
    });
  }
  contractsList(channelId?: string) { return this.contracts.list(channelId); }
  createContract(user: AuthUser, channelId: string, dto: any) { return this.contracts.create(user, channelId, dto); }
  updateContract(user: AuthUser, id: string, dto: any) { return this.contracts.update(user, id, dto); }
  activateContract(user: AuthUser, id: string) { return this.contracts.activate(user, id); }
  retireContract(user: AuthUser, id: string) { return this.contracts.retire(user, id); }
  productMapping(user: AuthUser, dto: any) { return this.mappings.product(user, dto); }
  variantMapping(user: AuthUser, dto: any) { return this.mappings.variant(user, dto); }
  rateMapping(user: AuthUser, dto: any) { return this.mappings.rate(user, dto); }
  inventoryRule(user: AuthUser, dto: any) { return this.mappings.inventory(user, dto); }
  mappingList(channelId?: string) { return this.mappings.list(channelId); }
  async mappingWorkspace(channelId?: string) { const where = channelId ? { channelId } : {}; return Promise.all([this.prisma.productChannelMapping.findMany({ where, include: { channel: true, product: { select: { id: true, productCode: true, status: true } } }, orderBy: { updatedAt: 'desc' } }), this.prisma.variantChannelMapping.findMany({ where, include: { channel: true, variant: { select: { id: true, variantCode: true, name: true, productId: true } } }, orderBy: { updatedAt: 'desc' } }), this.prisma.ratePlanChannelMapping.findMany({ where, include: { channel: true, ratePlan: { select: { id: true, ratePlanCode: true, name: true, status: true, variantId: true, variant: { select: { productId: true } } } }, inventoryRule: true }, orderBy: { updatedAt: 'desc' } })]).then(([products, variants, rates]) => ({ products, variants, rates })); }
  inventoryList(channelId?: string) { return this.mappings.inventoryList(channelId); }
  async createCredential(user: AuthUser, dto: CreateCredentialDto) {
    const name = dto.name.trim(); if (!name) throw new ConflictException({ code: 'CHANNEL_CREDENTIAL_NAME_REQUIRED', message: 'Credential name must be non-empty' }); const expiresAt = dto.expiresAt ? new Date(dto.expiresAt) : null; if (expiresAt && expiresAt <= new Date()) throw new ConflictException({ code: 'CHANNEL_CREDENTIAL_EXPIRY_INVALID', message: 'Credential expiry must be in the future' });
    const secret = randomBytes(32).toString('base64url'); const keyPrefix = `voya_${randomBytes(8).toString('hex')}`; const apiKey = `${keyPrefix}.${secret}`; const keyHash = createHash('sha256').update(apiKey).digest('hex');
    const credential = await this.prisma.$transaction(async (tx) => { const channel = await tx.distributionChannel.findUnique({ where: { id: dto.channelId }, include: { contracts: { where: { status: 'ACTIVE' }, orderBy: { versionNumber: 'desc' }, take: 1 } } }); if (!channel) throw new NotFoundException('Distribution channel not found'); const contract = channel.contracts[0]; if (!channel.active || !contract) throw new ConflictException({ code: 'CHANNEL_CONTRACT_NOT_ACTIVE', message: 'An active channel contract is required for credentials' }); const unsupported = dto.scopes.filter((scope) => !contract.capabilities.includes(scope)); if (unsupported.length) throw new ConflictException({ code: 'CHANNEL_CREDENTIAL_SCOPE_NOT_ALLOWED', message: 'Requested credential scope is not allowed by the active contract', unsupported }); const created = await tx.channelApiCredential.create({ data: { channelId: dto.channelId, name, keyPrefix, keyHash, scopes: [...new Set(dto.scopes)], expiresAt, createdById: user.sub } }); await this.audit.write(tx, { actor: user, action: 'CHANNEL_CREDENTIAL_CREATED', entityType: 'ChannelApiCredential', entityId: created.id, afterState: { channelId: dto.channelId, keyPrefix, scopes: created.scopes } }); await this.outbox.enqueue(tx, { eventType: 'CHANNEL_CREDENTIAL_CREATED', aggregateType: 'ChannelApiCredential', aggregateId: created.id, payload: { channelId: dto.channelId, keyPrefix, scopes: created.scopes } }); return created; });
    return { id: credential.id, channelId: credential.channelId, name: credential.name, keyPrefix: credential.keyPrefix, scopes: credential.scopes, status: credential.status, expiresAt: credential.expiresAt, createdAt: credential.createdAt, apiKey, secretShownOnce: true };
  }
  credentials(channelId?: string) { return this.prisma.channelApiCredential.findMany({ where: channelId ? { channelId } : undefined, select: { id: true, channelId: true, name: true, keyPrefix: true, scopes: true, status: true, expiresAt: true, lastUsedAt: true, version: true, createdAt: true, revokedAt: true }, orderBy: { createdAt: 'desc' } }); }
  async revokeCredential(user: AuthUser, id: string) {
    return this.prisma.$transaction(async (tx) => { const current = await tx.channelApiCredential.findUnique({ where: { id } }); if (!current) throw new NotFoundException('Channel credential not found'); if (current.status !== ChannelCredentialStatus.ACTIVE) return { id: current.id, status: current.status, revokedAt: current.revokedAt, idempotent: true }; const changed = await tx.channelApiCredential.updateMany({ where: { id, status: ChannelCredentialStatus.ACTIVE }, data: { status: ChannelCredentialStatus.REVOKED, revokedById: user.sub, revokedAt: new Date(), version: { increment: 1 } } }); if (changed.count !== 1) return { id: current.id, status: ChannelCredentialStatus.REVOKED, idempotent: true }; const credential = await tx.channelApiCredential.findUniqueOrThrow({ where: { id } }); await this.audit.write(tx, { actor: user, action: 'CHANNEL_CREDENTIAL_REVOKED', entityType: 'ChannelApiCredential', entityId: id, afterState: { status: credential.status, keyPrefix: credential.keyPrefix } }); await this.outbox.enqueue(tx, { eventType: 'CHANNEL_CREDENTIAL_REVOKED', aggregateType: 'ChannelApiCredential', aggregateId: id, payload: { channelId: credential.channelId, keyPrefix: credential.keyPrefix } }); return { id: credential.id, status: credential.status, revokedAt: credential.revokedAt, idempotent: false }; });
  }
  overview() { return Promise.all([this.prisma.distributionChannel.count({ where: { active: true } }), this.prisma.channelContract.count({ where: { status: 'ACTIVE' } }), this.prisma.productChannelMapping.count({ where: { status: 'ACTIVE' } }), this.prisma.variantChannelMapping.count({ where: { status: 'ACTIVE' } }), this.prisma.ratePlanChannelMapping.count({ where: { status: 'ACTIVE' } })]).then(([activeChannels, activeContracts, mappedProducts, mappedVariants, mappedRatePlans]) => ({ activeChannels, activeContracts, mappedProducts, mappedVariants, mappedRatePlans })); }
  readiness(input: { channelId: string; productId: string; variantId: string; ratePlanId: string; currency?: string; units?: number }) { return this.eligibility.evaluate(input); }
}
