import { Injectable, NotFoundException } from '@nestjs/common';
import { ChannelMappingStatus, CommercialVersionStatus, ProductRevisionStatus, ProductStatus, RatePlanStatus, TenantKind, VariantStatus, VendorVerificationStatus } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { DistributionAuthContext } from './distribution.types';

@Injectable()
export class DistributionCatalogService {
  constructor(private readonly prisma: PrismaService) {}
  async products(auth: DistributionAuthContext, externalProductCode?: string) {
    const now = new Date();
    const productMappings = await this.prisma.productChannelMapping.findMany({ where: { channelId: auth.channelId, status: ChannelMappingStatus.ACTIVE, ...(externalProductCode ? { externalProductCode: externalProductCode.trim() } : {}) }, include: { product: { include: { tenant: { include: { vendorProfile: true } }, currentRevision: { include: { media: { where: { archivedAt: null }, include: { fileAsset: { select: { id: true, visibility: true } } }, orderBy: { rank: 'asc' } } } } } } }, orderBy: { externalProductCode: 'asc' } });
    const variantMappings = await this.prisma.variantChannelMapping.findMany({ where: { channelId: auth.channelId, status: ChannelMappingStatus.ACTIVE }, include: { variant: true } });
    const rateMappings = await this.prisma.ratePlanChannelMapping.findMany({ where: { channelId: auth.channelId, status: ChannelMappingStatus.ACTIVE, ratePlan: { status: RatePlanStatus.ACTIVE } }, include: { ratePlan: { include: { commercialVersions: { where: { status: CommercialVersionStatus.ACTIVE, effectiveFrom: { lte: now }, OR: [{ effectiveTo: null }, { effectiveTo: { gt: now } }] }, orderBy: { versionNumber: 'desc' }, take: 1 } } } } });
    return productMappings.filter((mapping) => mapping.product.status === ProductStatus.LIVE && mapping.product.currentRevision?.status === ProductRevisionStatus.PUBLISHED && mapping.product.tenant.kind === TenantKind.VENDOR && mapping.product.tenant.vendorProfile?.verificationStatus === VendorVerificationStatus.VERIFIED).map((mapping) => {
      const revision: any = mapping.product.currentRevision;
      const variants = variantMappings.filter((item) => item.variant.productId === mapping.productId && item.variant.status === VariantStatus.ACTIVE && !item.variant.archivedAt).map((item) => {
        const rates = rateMappings.filter((rate) => rate.ratePlan.variantId === item.variantId);
        return { externalVariantCode: item.externalVariantCode, voyaVariantId: item.variantId, name: item.variant.name, description: item.variant.description, durationMinutes: item.variant.durationMinutes, privateShared: item.variant.privateShared, vehicleType: item.variant.vehicleType, pickupIncluded: item.variant.pickupIncluded, pickupType: item.variant.pickupType, pickupTimings: item.variant.pickupTimings, dropoffIncluded: item.variant.dropoffIncluded, dropoffTimings: item.variant.dropoffTimings, inclusions: item.variant.inclusions, exclusions: item.variant.exclusions, ratePlans: rates.map((rate: any) => { const commercial = rate.ratePlan.commercialVersions[0]; if (commercial && !auth.allowedCurrencies.includes(commercial.currency.toUpperCase())) return null; return { externalRatePlanCode: rate.externalRatePlanCode, voyaRatePlanId: rate.ratePlanId, name: rate.ratePlan.name, description: rate.ratePlan.description, validFrom: rate.ratePlan.validFrom, validTo: rate.ratePlan.validTo, unitType: rate.ratePlan.unitType, currentCommercial: commercial ? { effectiveFrom: commercial.effectiveFrom, effectiveTo: commercial.effectiveTo, currency: commercial.currency, bookingMode: commercial.bookingMode } : null }; }).filter(Boolean) };
      });
      return { externalProductCode: mapping.externalProductCode, voyaProductId: mapping.productId, revisionId: revision.id, revisionVersion: revision.versionNumber, name: revision.productName, type: revision.type, subType: revision.subType, subCategory: revision.subCategory, description: revision.description, shortDescription: revision.shortDescription, terms: revision.terms, highlights: revision.highlights, location: { cityCode: revision.cityCode, cityName: revision.cityName, stateName: revision.stateName, countryName: revision.countryName, address: revision.address, lat: revision.lat, lon: revision.lon }, media: (revision.media ?? []).map((media: any) => media.externalUrl ? { kind: media.kind, externalUrl: media.externalUrl, description: media.description, seoTitle: media.seoTitle, seoDescription: media.seoDescription, rank: media.rank } : media.fileAsset?.visibility === 'PUBLIC' ? { kind: media.kind, publicUrl: `/api/files/public/${media.fileAsset.id}/content`, description: media.description, seoTitle: media.seoTitle, seoDescription: media.seoDescription, rank: media.rank } : null).filter(Boolean), variants };
    });
  }
  async product(auth: DistributionAuthContext, externalProductCode: string) { const items = await this.products(auth, externalProductCode); if (!items.length) throw new NotFoundException('Mapped product not found'); return items[0]; }
}
