import { Injectable } from '@nestjs/common';
import { DistributionEventType, Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { EventsQueryDto } from './distribution.dto';
import { DistributionAuthContext } from './distribution.types';

const cursorEncode = (createdAt: Date, id: string) => Buffer.from(`${createdAt.toISOString()}|${id}`).toString('base64url');
const cursorDecode = (value?: string) => { if (!value) return null; const [createdAt, id] = Buffer.from(value, 'base64url').toString().split('|'); return createdAt && id ? { createdAt: new Date(createdAt), id } : null; };

@Injectable()
export class DistributionEventService {
  constructor(private readonly prisma: PrismaService) {}
  adminList(channelId?: string, type?: DistributionEventType, resourceType?: string) { return this.prisma.distributionEvent.findMany({ where: { ...(channelId ? { channelId } : {}), ...(type ? { type } : {}), ...(resourceType ? { resourceType } : {}) }, orderBy: [{ createdAt: 'desc' }, { id: 'desc' }], take: 200, select: { id: true, channelId: true, type: true, resourceType: true, resourceId: true, externalResourceCode: true, payload: true, occurredAt: true, createdAt: true, sourceOutboxEventId: true } }); }
  async list(auth: DistributionAuthContext, query: EventsQueryDto) { const cursor = cursorDecode(query.cursor); const events = await this.prisma.distributionEvent.findMany({ where: { channelId: auth.channelId, ...(cursor ? { OR: [{ createdAt: { gt: cursor.createdAt } }, { createdAt: cursor.createdAt, id: { gt: cursor.id } }] } : {}) }, orderBy: [{ createdAt: 'asc' }, { id: 'asc' }], take: query.limit + 1 }); const items = events.slice(0, query.limit).map((event) => ({ id: event.id, type: event.type, resourceType: event.resourceType, resourceId: event.resourceId, externalResourceCode: event.externalResourceCode, payload: event.payload, occurredAt: event.occurredAt, createdAt: event.createdAt })); const last = items.at(-1); return { items, nextCursor: events.length > query.limit && last ? cursorEncode(last.createdAt, last.id) : null }; }
}

@Injectable()
export class DistributionEventProjectorService {
  private readonly consumerKey = 'distribution-v1';
  constructor(private readonly prisma: PrismaService) {}
  private classify(event: any): DistributionEventType | null { const value = `${event.eventType} ${event.aggregateType}`.toUpperCase(); if (value.includes('QUALITY') || value.includes('DEMAND') || value.includes('FINANCE') || value.includes('SETTLEMENT')) return null; if (value.includes('MAPPING') || value.includes('CHANNEL')) return DistributionEventType.MAPPING_CHANGED; if (value.includes('PRODUCT') || value.includes('REVISION')) return DistributionEventType.PRODUCT_CHANGED; if (value.includes('VARIANT')) return DistributionEventType.VARIANT_CHANGED; if (value.includes('RATE') || value.includes('COMMERCIAL')) return DistributionEventType.RATE_CHANGED; if (value.includes('INVENTORY') || value.includes('SESSION') || value.includes('SCHEDULE') || value.includes('RESOURCE')) return DistributionEventType.AVAILABILITY_CHANGED; if (value.includes('BOOKING')) return DistributionEventType.BOOKING_CHANGED; return null; }
  private async routes(tx: Prisma.TransactionClient, event: any, type: DistributionEventType) {
    const payload = (event.payload || {}) as any; const route = (channelId: string, externalResourceCode: string | null) => ({ channelId, externalResourceCode });
    if (event.aggregateType === 'Booking') { const row = await tx.booking.findUnique({ where: { id: event.aggregateId! }, select: { distributionChannelId: true } }); return row?.distributionChannelId ? [route(row.distributionChannelId, null)] : []; }
    if (event.aggregateType === 'DistributionChannel' || payload.channelId && (event.aggregateType === 'DistributionChannel' || event.aggregateType.includes('ChannelMapping'))) return [route(payload.channelId || event.aggregateId, payload.externalProductCode || payload.externalVariantCode || payload.externalRatePlanCode || null)];
    if (event.aggregateType === 'Product' || event.aggregateType === 'ProductRevision') { const productId = payload.productId || event.aggregateId; const rows = await tx.productChannelMapping.findMany({ where: { productId, status: 'ACTIVE' }, select: { channelId: true, externalProductCode: true } }); return rows.map((row) => route(row.channelId, row.externalProductCode)); }
    if (event.aggregateType === 'ProductVariant') { const variantId = payload.variantId || event.aggregateId; const rows = await tx.variantChannelMapping.findMany({ where: { variantId, status: 'ACTIVE' }, select: { channelId: true, externalVariantCode: true } }); return rows.map((row) => route(row.channelId, row.externalVariantCode)); }
    let ratePlanIds: string[] = [];
    if (event.aggregateType === 'RatePlan' || event.aggregateType === 'RatePlanCommercialVersion') { const version = event.aggregateType === 'RatePlanCommercialVersion' && !payload.ratePlanId ? await tx.ratePlanCommercialVersion.findUnique({ where: { id: event.aggregateId! }, select: { ratePlanId: true } }) : null; const id = payload.ratePlanId || version?.ratePlanId || event.aggregateId; ratePlanIds = id ? [id] : []; }
    if (event.aggregateType === 'ScheduleTemplate' || event.aggregateType === 'ScheduleSlotTemplate') { const rows = await tx.ratePlanSchedule.findMany({ where: { scheduleTemplateId: event.aggregateId, active: true }, select: { ratePlanId: true } }); ratePlanIds = rows.map((row) => row.ratePlanId); }
    if (event.aggregateType === 'ServiceSession') { const session = await tx.serviceSession.findUnique({ where: { id: event.aggregateId! }, select: { scheduleTemplateId: true } }); if (session) { const rows = await tx.ratePlanSchedule.findMany({ where: { scheduleTemplateId: session.scheduleTemplateId, active: true }, select: { ratePlanId: true } }); ratePlanIds = rows.map((row) => row.ratePlanId); } }
    if (event.aggregateType === 'InventoryState') { const session = await tx.serviceSession.findFirst({ where: { inventoryState: { id: event.aggregateId! } }, select: { scheduleTemplateId: true } }); if (session) { const rows = await tx.ratePlanSchedule.findMany({ where: { scheduleTemplateId: session.scheduleTemplateId, active: true }, select: { ratePlanId: true } }); ratePlanIds = rows.map((row) => row.ratePlanId); } }
    if (event.aggregateType === 'CommercialRule' || event.aggregateType === 'CommercialRuleVersion') { const channelId = payload.channelId; if (channelId) return [route(channelId, null)]; const rows = await tx.ratePlanChannelMapping.findMany({ where: { status: 'ACTIVE' }, select: { channelId: true, externalRatePlanCode: true } }); return rows.map((row) => route(row.channelId, row.externalRatePlanCode)); }
    if (!ratePlanIds.length && payload.ratePlanId) ratePlanIds = [payload.ratePlanId];
    if (ratePlanIds.length) { const rows = await tx.ratePlanChannelMapping.findMany({ where: { ratePlanId: { in: ratePlanIds }, status: 'ACTIVE' }, select: { channelId: true, externalRatePlanCode: true } }); return rows.map((row) => route(row.channelId, row.externalRatePlanCode)); }
    return [];
  }
  async project(limit = 100) {
    return this.prisma.$transaction(async (tx) => { const [lock] = await tx.$queryRaw<Array<{ locked: boolean }>>`SELECT pg_try_advisory_xact_lock(hashtext(${this.consumerKey})) AS locked`; if (!lock?.locked) return { inspected: 0, projected: 0, cursor: null, busy: true }; const cursor = await tx.distributionProjectionCursor.findUnique({ where: { consumerKey: this.consumerKey } }); const events = await tx.outboxEvent.findMany({ where: cursor?.lastCreatedAt ? { OR: [{ createdAt: { gt: cursor.lastCreatedAt } }, { createdAt: cursor.lastCreatedAt, id: { gt: cursor.lastEventId ?? '' } }] } : {}, orderBy: [{ createdAt: 'asc' }, { id: 'asc' }], take: limit }); let projected = 0; for (const event of events) { const type = this.classify(event); if (!type) continue; for (const target of await this.routes(tx, event, type)) { const channel = await tx.distributionChannel.findUnique({ where: { id: target.channelId }, select: { id: true } }); if (!channel) continue; await tx.distributionEvent.create({ data: { channelId: target.channelId, sourceOutboxEventId: event.id, type, resourceType: event.aggregateType, resourceId: event.aggregateId || event.id, externalResourceCode: target.externalResourceCode, occurredAt: event.createdAt, payload: { resourceType: event.aggregateType, resourceId: event.aggregateId || event.id, changeType: type } } }).catch((error: any) => { if (error?.code !== 'P2002') throw error; }); projected += 1; } } const last = events.at(-1); if (last) await tx.distributionProjectionCursor.upsert({ where: { consumerKey: this.consumerKey }, update: { lastCreatedAt: last.createdAt, lastEventId: last.id }, create: { consumerKey: this.consumerKey, lastCreatedAt: last.createdAt, lastEventId: last.id } }); return { inspected: events.length, projected, cursor: last ? { lastCreatedAt: last.createdAt, lastEventId: last.id } : cursor ?? null }; }, { maxWait: 30000, timeout: 30000 });
  }
}
