import { ChannelContractStatus, ChannelInventoryExposureMode, ChannelMappingStatus, DistributionCapability, DistributionChannelType, DistributionEventType, TravellerType } from '@prisma/client';
import { Type } from 'class-transformer';
import { IsArray, IsBoolean, IsDateString, IsEnum, IsInt, IsOptional, IsString, IsUUID, Matches, Max, Min, ValidateNested } from 'class-validator';

export class CreateChannelDto { @IsString() @Matches(/^[A-Z0-9_\-]{2,80}$/) code!: string; @IsString() name!: string; @IsEnum(DistributionChannelType) type!: DistributionChannelType; @IsOptional() @IsString() description?: string; @IsOptional() @IsBoolean() active?: boolean; }
export class UpdateChannelDto { @IsOptional() @IsString() name?: string; @IsOptional() @IsEnum(DistributionChannelType) type?: DistributionChannelType; @IsOptional() @IsString() description?: string; @IsOptional() @IsBoolean() active?: boolean; @IsOptional() @IsBoolean() confirmDisable?: boolean; @IsOptional() @IsInt() @Min(1) expectedVersion?: number; }
export class CreateContractDto { @IsString() name!: string; @IsDateString() effectiveFrom!: string; @IsOptional() @IsDateString() effectiveTo?: string; @IsArray() @IsEnum(DistributionCapability, { each: true }) capabilities!: DistributionCapability[]; @IsArray() @IsString({ each: true }) allowedCurrencies!: string[]; @Type(() => Number) @IsInt() @Min(1) availabilityHorizonDays!: number; @IsOptional() metadata?: Record<string, unknown>; }
export class UpdateContractDto extends CreateContractDto { @Type(() => Number) @IsInt() @Min(1) expectedLockVersion!: number; }
export class MappingDto { @IsUUID() channelId!: string; @IsUUID() productId!: string; @IsString() externalProductCode!: string; @IsOptional() @IsEnum(ChannelMappingStatus) status?: ChannelMappingStatus; @Type(() => Number) @IsInt() @Min(1) expectedVersion?: number; }
export class VariantMappingDto { @IsUUID() channelId!: string; @IsUUID() variantId!: string; @IsString() externalVariantCode!: string; @IsOptional() @IsEnum(ChannelMappingStatus) status?: ChannelMappingStatus; @Type(() => Number) @IsInt() @Min(1) expectedVersion?: number; }
export class RateMappingDto { @IsUUID() channelId!: string; @IsUUID() ratePlanId!: string; @IsString() externalRatePlanCode!: string; @IsOptional() @IsEnum(ChannelMappingStatus) status?: ChannelMappingStatus; @Type(() => Number) @IsInt() @Min(1) expectedVersion?: number; }
export class InventoryRuleDto { @IsUUID() ratePlanChannelMappingId!: string; @IsEnum(ChannelInventoryExposureMode) exposureMode!: ChannelInventoryExposureMode; @Type(() => Number) @IsInt() @Min(0) capacityBuffer = 0; @IsOptional() @Type(() => Number) @IsInt() @Min(1) maxPublishedCapacity?: number; @IsOptional() @Type(() => Number) @IsInt() @Min(1) maxUnitsPerQuote?: number; @Type(() => Number) @IsInt() @Min(1) expectedVersion?: number; }
export class CreateCredentialDto { @IsUUID() channelId!: string; @IsString() name!: string; @IsArray() @IsEnum(DistributionCapability, { each: true }) scopes!: DistributionCapability[]; @IsOptional() @IsDateString() expiresAt?: string; }
export class EventsQueryDto { @IsOptional() @IsString() cursor?: string; @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(100) limit = 50; }
export class AvailabilityQueryDto { @IsString() externalProductCode!: string; @IsOptional() @IsString() externalVariantCode?: string; @IsString() externalRatePlanCode!: string; @Matches(/^\d{4}-\d{2}-\d{2}$/, { message: 'dateFrom must use YYYY-MM-DD' }) dateFrom!: string; @Matches(/^\d{4}-\d{2}-\d{2}$/, { message: 'dateTo must use YYYY-MM-DD' }) dateTo!: string; }
export class QuoteTravellerDto { @IsEnum(TravellerType) type!: TravellerType; @Type(() => Number) @IsInt() @Min(0) quantity!: number; }
export class QuoteDto { @IsString() externalRatePlanCode!: string; @IsUUID() sessionId!: string; @ValidateNested({ each: true }) @Type(() => QuoteTravellerDto) travellers!: QuoteTravellerDto[]; @Type(() => Number) @IsInt() @Min(1) units = 1; @IsOptional() @IsString() currency?: string; }
export const capabilityValues = Object.values(DistributionCapability);
