"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { apiRequest } from "@/services/apiClient";
import type { PaginatedResponse, PaginationMeta } from "@/types/api";
import { DataTable } from "@/components/table/DataTable";
import { PaginationControls } from "@/components/table/PaginationControls";
import { EmptyState, ErrorPanel, LoadingTable } from "@/components/feedback/Feedback";

type Voucher = { id: string; code: string; discountMinor?: number; discountPercent?: number; redemptionCount: number; maxRedemptions?: number; isActive: boolean; validTo?: string };
const initialMeta: PaginationMeta = { page: 1, pageSize: 25, totalItems: 0, totalPages: 1, hasNextPage: false, hasPreviousPage: false };

export function VoucherList() {
  const [rows, setRows] = useState<Voucher[]>([]); const [search, setSearch] = useState(""); const [isActive, setIsActive] = useState(""); const [sortBy, setSortBy] = useState("createdAt"); const [sortOrder, setSortOrder] = useState<"asc" | "desc">("desc"); const [page, setPage] = useState(1); const [meta, setMeta] = useState<PaginationMeta>(initialMeta); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  useEffect(() => { const params = new URLSearchParams(window.location.search); setSearch(params.get("search") ?? ""); setIsActive(params.get("isActive") ?? ""); setSortBy(params.get("sortBy") ?? "createdAt"); setSortOrder(params.get("sortOrder") === "asc" ? "asc" : "desc"); setPage(Math.max(1, Number(params.get("page") ?? "1"))); const size = Number(params.get("pageSize") ?? "25"); if ([10, 25, 50, 100].includes(size)) setMeta((current) => ({ ...current, pageSize: size })); }, []);
  const syncUrl = useCallback((next: Partial<{ page: number; pageSize: number; search: string; isActive: string; sortBy: string; sortOrder: "asc" | "desc" }>) => { const value = { page, pageSize: meta.pageSize, search, isActive, sortBy, sortOrder, ...next }; const params = new URLSearchParams({ page: String(value.page), pageSize: String(value.pageSize), sortBy: value.sortBy, sortOrder: value.sortOrder }); if (value.search) params.set("search", value.search); if (value.isActive) params.set("isActive", value.isActive); window.history.replaceState(null, "", `${window.location.pathname}?${params}`); }, [isActive, meta.pageSize, page, search, sortBy, sortOrder]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const params = new URLSearchParams({ page: String(page), pageSize: String(meta.pageSize), sortBy, sortOrder }); if (search) params.set("search", search); if (isActive) params.set("isActive", isActive); const result = await apiRequest<PaginatedResponse<Voucher>>(`/vouchers?${params}`); setRows(result.data); setMeta(result.meta); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load vouchers"); } finally { setLoading(false); } }, [isActive, meta.pageSize, page, search, sortBy, sortOrder]);
  useEffect(() => { void load(); }, [load]);
  const archive = async (row: Voucher) => { if (!window.confirm(`Deactivate voucher ${row.code}?`)) return; try { await apiRequest(`/vouchers/${row.id}`, { method: "DELETE" }); setNotice(`Voucher ${row.code} deactivated`); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to deactivate voucher"); } };
  const clear = () => { setSearch(""); setIsActive(""); setSortBy("createdAt"); setSortOrder("desc"); setPage(1); syncUrl({ page: 1, search: "", isActive: "", sortBy: "createdAt", sortOrder: "desc" }); };
  return <div><div className="page-heading"><div><p className="eyebrow">PRICING</p><h2>Vouchers</h2><p className="subtext">Manage discount codes and redemption limits.</p></div><Link className="primary button-link" href="/vouchers/new">Create voucher</Link></div>{notice && <p className="notice success" role="status">{notice}</p>}<section className="panel"><div className="toolbar"><input aria-label="Search vouchers" value={search} placeholder="Search code…" onChange={(event) => { setSearch(event.target.value); setPage(1); syncUrl({ page: 1, search: event.target.value }); }} /><select aria-label="Filter vouchers status" value={isActive} onChange={(event) => { setIsActive(event.target.value); setPage(1); syncUrl({ page: 1, isActive: event.target.value }); }}><option value="">All statuses</option><option value="true">Active</option><option value="false">Inactive</option></select><select aria-label="Sort vouchers" value={sortBy} onChange={(event) => { setSortBy(event.target.value); setPage(1); syncUrl({ page: 1, sortBy: event.target.value }); }}><option value="createdAt">Created date</option><option value="code">Code</option><option value="validTo">Valid to</option></select><select aria-label="Sort direction vouchers" value={sortOrder} onChange={(event) => { const value = event.target.value as "asc" | "desc"; setSortOrder(value); setPage(1); syncUrl({ page: 1, sortOrder: value }); }}><option value="desc">Descending</option><option value="asc">Ascending</option></select><button type="button" onClick={clear}>Clear filters</button></div>{loading ? <LoadingTable /> : error ? <ErrorPanel message={error} onRetry={() => void load()} /> : rows.length === 0 ? <EmptyState title="No vouchers found" /> : <DataTable rows={rows} columns={[{ key: "code", label: "Code", render: (row) => <strong>{row.code}</strong> }, { key: "discount", label: "Discount", render: (row) => row.discountPercent ? `${row.discountPercent}%` : `${((row.discountMinor ?? 0) / 100).toFixed(2)}` }, { key: "redemptions", label: "Redemptions", render: (row) => `${row.redemptionCount}${row.maxRedemptions ? ` / ${row.maxRedemptions}` : ""}` }, { key: "status", label: "Status", render: (row) => <span className={`status ${row.isActive ? "confirmed" : "cancelled"}`}>{row.isActive ? "ACTIVE" : "INACTIVE"}</span> }]} actions={(row) => <><Link href={`/vouchers/${row.id}`}>View</Link><Link href={`/vouchers/${row.id}/edit`}>Edit</Link><button type="button" onClick={() => void archive(row)}>{row.isActive ? "Deactivate" : "Archive"}</button></>} />}{!loading && !error && <PaginationControls meta={meta} onPageChange={(nextPage) => { setPage(nextPage); syncUrl({ page: nextPage }); }} onPageSizeChange={(size) => { setPage(1); setMeta((current) => ({ ...current, pageSize: size })); syncUrl({ page: 1, pageSize: size }); }} />}</section></div>;
}
