import { test, expect } from "@playwright/test";

async function advanceBooking(page: import("@playwright/test").Page, stage: string) {
  const confirmation = page.getByRole("heading", { name: "Booking created" });
  if (await confirmation.isVisible().catch(() => false)) return;
  const next = page.getByRole("button", { name: "Next", exact: true });
  await expect(next).toBeVisible();
  await next.click();
  await expect(page.locator("legend").filter({ hasText: stage }).or(confirmation)).toBeVisible();
}

async function submitBooking(page: import("@playwright/test").Page) {
  const confirmation = page.getByRole("heading", { name: "Booking created" });
  const submit = page.getByRole("button", { name: "Create hold" });
  await expect(confirmation.or(submit)).toBeVisible();
  if (await submit.isVisible()) await submit.click();
  await expect(confirmation).toBeVisible();
}

test("authenticated catalogue workflow", async ({ page }) => {
  test.setTimeout(300_000);
  const consoleErrors: string[] = [];
  page.on("console", (message) => { if (message.type() === "error") consoleErrors.push(message.text()); });
  const password = process.env.E2E_PASSWORD;
  test.skip(!password, "E2E_PASSWORD is required for the authenticated workflow");
  await page.goto("/login");
  await page.getByLabel("Password").fill(password!);
  await page.getByRole("button", { name: "Sign in" }).click();
  await expect(page).toHaveURL(/\/dashboard$/);
  await expect(page.getByRole("navigation", { name: "Primary navigation" })).toBeVisible();
  await expect(page.getByText("Published activities", { exact: true })).toBeVisible();
  await expect(page.getByText("Open bookings", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Toggle sidebar" }).click();
  await page.reload();
  await expect(page.locator("aside.sidebar.collapsed")).toBeVisible();
  await page.getByRole("button", { name: "Toggle sidebar" }).click();
  await page.getByRole("navigation", { name: "Primary navigation" }).getByRole("link", { name: /Activities/ }).click();
  await expect(page).toHaveURL(/\/activities(?:\?.*)?$/);
  await page.goto("/destinations");
  await page.getByLabel("Filter destinations country").fill("India");
  await expect(page).toHaveURL(/country=India/);
  const categoryName = `Playwright Category ${Date.now()}`;
  await page.goto("/activity-categories");
  await page.getByRole("link", { name: /Create categorie/i }).click();
  await page.getByLabel("Name").fill(categoryName);
  await page.getByLabel("Slug").fill(`playwright-category-${Date.now()}`);
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page).toHaveURL(/\/activity-categories$/);
  const categoryRow = page.locator("tr").filter({ hasText: categoryName });
  await expect(categoryRow).toBeVisible();
  await categoryRow.getByRole("link", { name: "Edit" }).click();
  await page.getByLabel("Name").fill(`${categoryName} Updated`);
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page).toHaveURL(/\/activity-categories$/);
  const updatedCategoryRow = page.locator("tr").filter({ hasText: `${categoryName} Updated` });
  await expect(updatedCategoryRow).toBeVisible();
  page.once("dialog", (dialog) => void dialog.accept());
  await updatedCategoryRow.getByRole("button", { name: "Archive" }).click();
  await expect(page.getByRole("status")).toContainText("archived");

  const supplierName = `Playwright Supplier ${Date.now()}`;
  await page.goto("/suppliers/new");
  await page.getByLabel("Company").fill(supplierName);
  await page.getByLabel("Contact person").fill("Supplier Contact");
  await page.getByLabel("Email").fill(`supplier-${Date.now()}@example.test`);
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page).toHaveURL(/\/suppliers$/);
  await page.getByLabel("Search Suppliers").fill(supplierName);
  const supplierRow = page.locator("tr").filter({ hasText: supplierName });
  await expect(supplierRow).toBeVisible();
  await supplierRow.getByRole("link", { name: "Edit" }).click();
  await page.getByLabel("Contact person").fill("Updated Supplier Contact");
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page).toHaveURL(/\/suppliers$/);
  await page.getByLabel("Search Suppliers").fill(supplierName);
  const updatedSupplierRow = page.locator("tr").filter({ hasText: supplierName });
  await expect(updatedSupplierRow).toContainText("Updated Supplier Contact");
  page.once("dialog", (dialog) => void dialog.accept());
  await updatedSupplierRow.getByRole("button", { name: "Archive" }).click();

  await page.goto("/activities");
  await page.getByRole("link", { name: "Create activity" }).click();
  const activityName = `Playwright Verification Activity ${Date.now()}`;
  await page.getByLabel("Name").fill(activityName);
  await page.getByLabel("Slug").fill(`playwright-verification-${Date.now()}`);
  await page.getByRole("textbox", { name: "Destination" }).fill("Hyderabad");
  await page.getByLabel("Category").selectOption({ label: "Heritage & Culture" });
  await page.getByLabel("Destination record").selectOption({ label: "Hyderabad" });
  await page.getByLabel("Timezone").fill("Asia/Kolkata");
  await page.getByLabel("Duration (minutes)").fill("120");
  await page.getByLabel("Summary").fill("Created by authenticated browser verification.");
  await page.getByLabel("Description").fill("Created by authenticated browser verification.");
  await page.getByRole("button", { name: "Save activity" }).click();
  await expect(page).toHaveURL(/\/activities$/);
  await expect(page.getByText(activityName, { exact: true })).toBeVisible();
  await page.locator("tr").filter({ hasText: activityName }).getByRole("link", { name: "Edit" }).click();
  await page.getByLabel("Summary").fill("Updated by authenticated browser verification.");
  await page.getByRole("button", { name: "Save activity" }).click();
  await expect(page).toHaveURL(/\/activities$/);

  const variantName = `Playwright Variant ${Date.now()}`;
  await page.goto("/activity-variants/new");
  await page.getByLabel("Activity").selectOption({ label: activityName });
  await page.getByLabel("Name").fill(variantName);
  await page.getByLabel("Description").fill("Created by authenticated browser verification.");
  await page.getByRole("button", { name: "Save variant" }).click();
  await expect(page).toHaveURL(/\/activity-variants$/, { timeout: 30_000 });
  await page.getByLabel("Filter variants activity").selectOption({ label: activityName });
  await expect(page).toHaveURL(/activityId=.+/);
  const variantRow = page.locator("tr").filter({ hasText: variantName });
  const variantHref = await variantRow.getByRole("link", { name: "View" }).getAttribute("href");
  await page.goto(variantHref!);
  await page.goto(`${page.url()}/edit`);
  await expect(page).toHaveURL(/\/edit$/);
  await page.getByLabel("Description").fill("Updated by authenticated browser verification.");
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page).toHaveURL(/\/activity-variants\/.+$/);
  await expect(page.getByRole("heading", { name: variantName, exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Audit history", exact: true })).toBeVisible();

  await page.goto("/schedules/new");
  await page.getByLabel("Activity").selectOption({ label: activityName });
  await page.getByLabel("Variant").selectOption({ label: variantName });
  const scheduleStart = new Date(Date.now() + 86_400_000);
  const scheduleEnd = new Date(scheduleStart.getTime() + 2 * 60 * 60 * 1000);
  await page.getByLabel("Starts at").fill(scheduleStart.toISOString().slice(0, 16));
  await page.getByLabel("Ends at").fill(scheduleEnd.toISOString().slice(0, 16));
  await page.getByRole("button", { name: "Save schedule" }).click();
  await expect(page).toHaveURL(/\/schedules$/);
  await page.getByLabel("Filter schedules activity").selectOption({ label: activityName });
  await expect(page).toHaveURL(/activityId=.+/);
  const scheduleRow = page.locator("tr").filter({ hasText: activityName }).first();
  await expect(page.getByRole("columnheader", { name: "Booked" })).toBeVisible();
  await expect(page.getByRole("columnheader", { name: "Held" })).toBeVisible();
  await expect(page.getByRole("columnheader", { name: "Available" })).toBeVisible();
  await page.getByLabel("Select all rows").check();
  page.once("dialog", (dialog) => void dialog.accept());
  await page.getByRole("button", { name: "Deactivate selected" }).click();
  await expect(page.getByRole("status")).toContainText("deactivated");
  await page.getByLabel("Select all rows").check();
  page.once("dialog", (dialog) => void dialog.accept());
  await page.getByRole("button", { name: "Activate selected", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("activated");
  await scheduleRow.getByRole("link", { name: "View" }).click();
  await expect(page.getByRole("heading", { name: "Manual capacity adjustment", exact: true })).toBeVisible({ timeout: 30_000 });
  await page.getByLabel("New capacity").fill("12");
  await page.getByLabel("Reason").fill("Browser capacity verification");
  await page.getByRole("button", { name: "Adjust capacity" }).click();
  await expect(page.getByRole("status")).toContainText("Capacity adjusted");

  await page.goto("/price-plans/new");
  await page.getByLabel("Activity").selectOption({ label: activityName });
  await page.getByLabel("Variant").selectOption({ label: variantName });
  await page.getByLabel("Plan name").fill(`Playwright Plan ${Date.now()}`);
  await page.getByLabel("Adult minor units").fill("1000");
  await page.getByLabel("Child minor units").fill("500");
  await page.getByRole("button", { name: "Save price plan" }).click();
  await expect(page).toHaveURL(/\/price-plans$/);
  await page.getByLabel("Filter price plans activity").selectOption({ label: activityName });
  await expect(page).toHaveURL(/activityId=.+/);
  await page.getByText("Columns", { exact: true }).click();
  await page.getByRole("checkbox", { name: "Tax" }).uncheck();
  await expect(page.getByRole("columnheader", { name: "Tax" })).toHaveCount(0);

  await page.goto("/blackout-dates/new");
  const blackoutActivity = page.getByLabel("Activity ID");
  await expect(blackoutActivity.locator("option").nth(1)).toHaveAttribute("value", /.+/);
  const blackoutActivityName = (await blackoutActivity.locator("option").nth(1).textContent())?.trim() ?? "";
  await blackoutActivity.selectOption({ index: 1 });
  const blackoutDate = new Date(Date.now() + (10 + (Math.floor(Date.now() / 1000) % 300)) * 86_400_000).toISOString().slice(0, 10);
  await page.getByLabel("Date").fill(blackoutDate);
  await page.getByLabel("Reason").fill("Browser blackout verification");
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page).toHaveURL(/\/blackout-dates$/);
  await page.getByLabel("Filter Blackout Dates activity").selectOption({ label: blackoutActivityName });
  await expect(page).toHaveURL(/activityId=.+/);
  await page.getByLabel("Filter blackout dates from").fill(blackoutDate);
  await expect(page).toHaveURL(/from=.+/);
  await page.getByLabel("Filter blackout dates to").fill(blackoutDate);
  await expect(page).toHaveURL(/to=.+/);

  await page.goto("/activities");
  await page.locator("tr").filter({ hasText: activityName }).getByRole("link", { name: "View" }).click();
  await expect(page.getByRole("heading", { name: "Variants", exact: true })).toBeVisible({ timeout: 30_000 });
  await expect(page.getByRole("heading", { name: "Availability and schedules", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Pricing", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Bookings", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Audit history", exact: true })).toBeVisible();
  const publish = page.getByRole("button", { name: "Publish" });
  if (await publish.isVisible()) await publish.click();
  await expect(page.getByText("PUBLISHED", { exact: true }).first()).toBeVisible();
  await page.goto("/availability");
  await page.getByLabel("Availability view").selectOption("calendar");
  await expect(page).toHaveURL(/view=calendar/);
  await page.getByLabel("Filter availability state").selectOption("AVAILABLE");
  await expect(page).toHaveURL(/availabilityStatus=AVAILABLE/);
  const destinationFilter = page.getByLabel("Filter availability by destination");
  if (await destinationFilter.locator("option").count() > 1) {
    await destinationFilter.selectOption({ index: 1 });
    await expect(page).toHaveURL(/destinationId=.+/);
  }

  await page.goto("/bookings/new");
  await page.getByLabel("Activity").selectOption({ label: activityName });
  await page.getByRole("button", { name: "Next", exact: true }).click();
  await expect(page.getByLabel("Departure").locator("option").nth(1)).toHaveAttribute("value", /.+/);
  await page.getByLabel("Departure").selectOption({ index: 1 });
  await advanceBooking(page, "2. Availability");
  await advanceBooking(page, "3. Customer");
  const firstCustomer = `Playwright Confirm ${Date.now()}`;
  await page.getByLabel("Customer name").fill(firstCustomer);
  await page.getByLabel("Customer email").fill(`confirm-${Date.now()}@example.test`);
  await advanceBooking(page, "4. Passengers");
  await advanceBooking(page, "5. Pricing");
  await advanceBooking(page, "6. Voucher");
  await advanceBooking(page, "7. Payment");
  await advanceBooking(page, "8. Review");
  await submitBooking(page);
  const viewBookingLink = page.getByRole("link", { name: "View booking" });
  const bookingHref = await viewBookingLink.getAttribute("href");
  expect(bookingHref).toMatch(/^\/bookings\/(?!new$).+/);
  await page.goto(bookingHref!);
  await expect(page).toHaveURL(/\/bookings\/(?!new$).+/);
  const firstBookingId = page.url().split("/").pop()!;
  await page.getByRole("link", { name: "Back to bookings" }).click();
  await page.getByLabel("Search bookings").fill(firstCustomer);
  const firstRow = page.locator("tr").filter({ hasText: firstCustomer });
  await expect(firstRow).toBeVisible();
  await firstRow.getByRole("link", { name: "View" }).click();
  await page.getByRole("link", { name: "Edit" }).click();
  await expect(page.getByRole("heading", { name: /Edit ACT-/ })).toBeVisible({ timeout: 30_000 });
  await page.getByRole("button", { name: "Cancel" }).click();
  await expect(page).toHaveURL(/\/bookings\/.+/);
  await page.locator("main").getByRole("button", { name: "Confirm" }).first().click();
  await expect(page.locator("main").getByText("CONFIRMED", { exact: true }).first()).toBeVisible();
  await page.getByLabel("Amount (minor units)").fill("100");
  await page.getByRole("button", { name: "Create payment" }).click();
  await expect(page.locator("main").getByText(/PENDING/)).toBeVisible();
  await page.getByLabel("Invoice number").fill(`INV-${Date.now()}`);
  const invoiceNumber = await page.getByLabel("Invoice number").inputValue();
  await page.getByRole("button", { name: "Create invoice" }).click();
  await expect(page.locator("main").getByText(invoiceNumber, { exact: true })).toBeVisible();
  const passengerFirstName = `Browser Passenger ${Date.now()}`;
  await page.goto("/passengers/new");
  await page.getByLabel("Booking ID *").fill(firstBookingId);
  await page.getByLabel("First name *").fill(passengerFirstName);
  await page.getByLabel("Last name *").fill("Verification");
  await page.getByRole("button", { name: "Save passenger" }).click();
  await expect(page).toHaveURL(/\/passengers$/);
  await page.getByLabel("Search passengers").fill(passengerFirstName);
  const passengerRow = page.locator("tr").filter({ hasText: passengerFirstName });
  await expect(passengerRow).toBeVisible();
  await passengerRow.getByRole("link", { name: "View" }).click();
  await expect(page.getByRole("heading", { name: new RegExp(passengerFirstName) })).toBeVisible({ timeout: 30_000 });
  await page.getByRole("link", { name: "Edit" }).click();
  await page.getByLabel("Last name *").fill("Updated");
  await page.getByRole("button", { name: "Save passenger" }).click();
  await expect(page).toHaveURL(/\/passengers\/.+/);
  await page.goto(`/payments?search=${encodeURIComponent(firstCustomer)}&status=PENDING`);
  await expect(page.getByLabel("Filter Payments status")).toHaveValue("PENDING");
  const paymentRow = page.locator("tbody tr").filter({ hasText: firstCustomer }).first();
  await expect(paymentRow).toBeVisible();
  await paymentRow.getByRole("link", { name: "View" }).click();
  await page.getByRole("button", { name: "Capture" }).click();
  await expect(page.locator("main").getByText("CAPTURED", { exact: true })).toBeVisible();
  await page.getByLabel("Amount (minor units)").fill("50");
  await page.getByLabel("Reason").fill("Browser refund verification");
  await page.getByRole("button", { name: "Request refund" }).click();
  await page.goto("/refunds");
  await page.getByLabel("Filter Refunds status").selectOption("REQUESTED");
  await expect(page).toHaveURL(/status=REQUESTED/);
  await page.goto("/invoices");
  await page.getByLabel("Search Invoices").fill(firstCustomer);
  await expect(page).toHaveURL(/search=.+/);
  await page.goto("/customers");
  await page.getByLabel("Search customers").fill(firstCustomer);
  const customerRow = page.locator("tr").filter({ hasText: firstCustomer });
  await expect(customerRow).toBeVisible();
  await customerRow.getByRole("link", { name: "View" }).click();
  await expect(page.getByRole("heading", { name: "Notes", exact: true })).toBeVisible({ timeout: 30_000 });
  await expect(page.getByRole("heading", { name: "Bookings", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Passengers", exact: true })).toBeVisible();
  await expect(page.getByRole("heading", { name: "Payment history", exact: true })).toBeVisible();

  await page.goto("/bookings/new");
  await page.getByLabel("Activity").selectOption({ label: activityName });
  await page.getByRole("button", { name: "Next", exact: true }).click();
  await expect(page.getByLabel("Departure").locator("option").nth(1)).toHaveAttribute("value", /.+/);
  await page.getByLabel("Departure").selectOption({ index: 1 });
  await advanceBooking(page, "2. Availability");
  await advanceBooking(page, "3. Customer");
  const secondCustomer = `Playwright Cancel ${Date.now()}`;
  await page.getByLabel("Customer name").fill(secondCustomer);
  await page.getByLabel("Customer email").fill(`cancel-${Date.now()}@example.test`);
  await advanceBooking(page, "4. Passengers");
  await advanceBooking(page, "5. Pricing");
  await advanceBooking(page, "6. Voucher");
  await advanceBooking(page, "7. Payment");
  await advanceBooking(page, "8. Review");
  await submitBooking(page);
  await page.getByRole("link", { name: "Back to bookings" }).click();
  await expect(page).toHaveURL(/\/bookings$/);
  await page.getByLabel("Search bookings").fill(secondCustomer);
  const secondRow = page.locator("tr").filter({ hasText: secondCustomer });
  await expect(secondRow).toBeVisible();
  await secondRow.getByRole("link", { name: "View" }).click();
  await page.locator("main").getByRole("button", { name: "Cancel" }).first().click();
  await expect(page.locator("main").getByText("CANCELLED", { exact: true }).first()).toBeVisible();
  await page.goto("/reports/bookings");
  await expect(page.getByRole("heading", { name: "Booking Report", exact: true })).toBeVisible();
  await page.getByLabel("Filter Booking Report status").selectOption("CANCELLED");
  await expect(page).toHaveURL(/status=CANCELLED/);
  const reportDownload = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export CSV" }).click();
  await expect((await reportDownload).suggestedFilename()).toBe("bookings-report.csv");
  await page.goto("/reports/revenue");
  await expect(page.getByRole("heading", { name: "Revenue Report", exact: true })).toBeVisible();
  await page.getByLabel("Revenue report from").fill("2026-01-01");
  await expect(page).toHaveURL(/from=2026-01-01/);
  const revenueDownload = page.waitForEvent("download");
  await page.getByRole("button", { name: "Export CSV" }).click();
  await expect((await revenueDownload).suggestedFilename()).toBe("revenue-report.csv");

  await page.goto("/settings/notifications");
  await page.getByRole("heading", { name: "Notifications", exact: true }).waitFor();
  await page.getByLabel("Booking notifications").check();
  await page.getByRole("button", { name: "Save settings" }).click();
  await expect(page.getByText("Settings saved", { exact: true })).toBeVisible();
  await page.goto("/customers");
  await page.getByLabel("Filter customers country").fill("India");
  await expect(page).toHaveURL(/country=India/);
  await page.goto("/settings/users");
  await page.getByLabel("Search users").fill("Demo Admin");
  await expect(page).toHaveURL(/search=Demo(?:%20|\+)Admin/);
  await expect(page.getByRole("columnheader", { name: "Last login" })).toBeVisible();
  await page.goto("/settings/roles");
  await page.getByLabel("Filter roles status").selectOption("ACTIVE");
  await expect(page).toHaveURL(/status=ACTIVE/);
  await expect(page.getByRole("heading", { name: "Roles & Permissions", exact: true })).toBeVisible();
  const browserAgent = `Playwright Agent ${Date.now()}`;
  await page.goto("/agents/new");
  await page.getByLabel("Company").fill(browserAgent);
  await page.getByLabel("Contact person").fill("Browser Agent Contact");
  await page.getByLabel("Email").fill(`agent-${Date.now()}@example.test`);
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page).toHaveURL(/\/agents$/);
  await page.goto("/agent-commissions/new");
  const commissionAgent = page.getByLabel("Agent ID");
  await expect(commissionAgent.locator("option").nth(1)).toHaveAttribute("value", /.+/);
  await commissionAgent.selectOption({ label: browserAgent });
  await page.getByLabel("Commission percent").fill("7.5");
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page).toHaveURL(/\/agent-commissions$/);
  const commissionAgentFilter = page.getByLabel("Filter Agent Commissions agent");
  if (await commissionAgentFilter.locator("option").count() > 1) {
    await commissionAgentFilter.selectOption({ index: 1 });
    await expect(page).toHaveURL(/agentId=.+/);
  }
  await page.getByLabel("Filter Agent Commissions status").selectOption("ACTIVE");
  await expect(page).toHaveURL(/status=ACTIVE/);
  const voucherCode = `PW${Date.now()}`;
  await page.goto("/vouchers/new");
  await page.getByLabel("Code").fill(voucherCode);
  await page.getByLabel("Discount percent").fill("10");
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page).toHaveURL(/\/vouchers$/);
  const voucherRow = page.locator("tr").filter({ hasText: voucherCode });
  await expect(voucherRow).toBeVisible();
  await voucherRow.getByRole("link", { name: "Edit" }).click();
  await page.getByLabel("Discount percent").fill("15");
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page).toHaveURL(/\/vouchers\/.+$/);
  await expect(page.getByRole("heading", { name: voucherCode, exact: true })).toBeVisible();
  await page.goto("/vouchers");
  const updatedVoucherRow = page.locator("tr").filter({ hasText: voucherCode });
  await expect(updatedVoucherRow).toBeVisible();
  page.once("dialog", (dialog) => void dialog.accept());
  await updatedVoucherRow.getByRole("button", { name: "Deactivate" }).click();
  await expect(page.getByRole("status")).toContainText("deactivated");
  await page.goto("/taxes");
  await page.getByLabel("Sort Taxes").selectOption("createdAt");
  await page.getByLabel("Sort direction Taxes").selectOption("desc");
  await expect(page).toHaveURL(/sortBy=createdAt/);
  const taxName = `Playwright Tax ${Date.now()}`;
  await page.getByRole("link", { name: "Create tax" }).click();
  await page.getByLabel("Name").fill(taxName);
  await page.getByLabel("Rate percent").fill("5");
  await page.getByRole("button", { name: "Save", exact: true }).click();
  await expect(page).toHaveURL(/\/taxes$/);
  const taxRow = page.locator("tr").filter({ hasText: taxName });
  await expect(taxRow).toBeVisible();
  page.once("dialog", (dialog) => void dialog.accept());
  await taxRow.getByRole("button", { name: "Archive" }).click();
  await expect(page.getByRole("status")).toContainText("archived");
  expect(consoleErrors).toEqual([]);
});
