import { Body, Controller, Delete, Get, Param, Patch, Post, Query, UseGuards } from "@nestjs/common";
import { ApiHeader, ApiTags } from "@nestjs/swagger";
import { UserRole } from "@prisma/client";
import { AccessTokenGuard } from "../../auth/auth.guard";
import { Roles } from "../../auth/roles.decorator";
import { RolesGuard } from "../../auth/roles.guard";
import { TenantAccessGuard } from "../../auth/tenant.guard";
import { TenantContext, TenantContextValue } from "../../common/tenant-context";
import { BulkGenerateScheduleDto, BulkScheduleStatusDto, CapacityAdjustmentDto, CreateScheduleDto, DuplicateScheduleDto, ScheduleQueryDto, UpdateScheduleDto } from "./dto/schedule.dto";
import { SchedulesService } from "./schedules.service";
@ApiTags("schedules") @ApiHeader({ name: "x-tenant-id", required: true }) @Controller("schedules") @UseGuards(AccessTokenGuard, TenantAccessGuard, RolesGuard)
export class SchedulesController { constructor(private readonly schedules: SchedulesService) {} @Get() list(@TenantContext() context: TenantContextValue, @Query() query: ScheduleQueryDto) { return this.schedules.list(context.tenantId, query); } @Post() @Roles(UserRole.PARTNER_ADMIN, UserRole.ACTIVITY_MANAGER) create(@TenantContext() context: TenantContextValue, @Body() dto: CreateScheduleDto) { return this.schedules.create(context.tenantId, dto); } @Post("bulk-generate") @Roles(UserRole.PARTNER_ADMIN, UserRole.ACTIVITY_MANAGER) bulkGenerate(@TenantContext() context: TenantContextValue, @Body() dto: BulkGenerateScheduleDto) { return this.schedules.bulkGenerate(context.tenantId, context.userId, dto); } @Patch("bulk-status") @Roles(UserRole.PARTNER_ADMIN, UserRole.ACTIVITY_MANAGER) bulkStatus(@TenantContext() context: TenantContextValue, @Body() dto: BulkScheduleStatusDto) { return this.schedules.bulkStatus(context.tenantId, context.userId, dto); } @Get(":id") get(@TenantContext() context: TenantContextValue, @Param("id") id: string) { return this.schedules.get(context.tenantId, id); } @Post(":id/duplicate") @Roles(UserRole.PARTNER_ADMIN, UserRole.ACTIVITY_MANAGER) duplicate(@TenantContext() context: TenantContextValue, @Param("id") id: string, @Body() dto: DuplicateScheduleDto) { return this.schedules.duplicate(context.tenantId, context.userId, id, dto); } @Patch(":id") @Roles(UserRole.PARTNER_ADMIN, UserRole.ACTIVITY_MANAGER) update(@TenantContext() context: TenantContextValue, @Param("id") id: string, @Body() dto: UpdateScheduleDto) { return this.schedules.update(context.tenantId, id, dto); } @Patch(":id/capacity") @Roles(UserRole.PARTNER_ADMIN, UserRole.ACTIVITY_MANAGER) adjustCapacity(@TenantContext() context: TenantContextValue, @Param("id") id: string, @Body() dto: CapacityAdjustmentDto) { return this.schedules.adjustCapacity(context.tenantId, context.userId, id, dto); } @Delete(":id") @Roles(UserRole.PARTNER_ADMIN) remove(@TenantContext() context: TenantContextValue, @Param("id") id: string) { return this.schedules.remove(context.tenantId, id); } }
