import { Transform, Type } from "class-transformer"; import { ArrayMaxSize, ArrayMinSize, IsArray, IsBoolean, IsDateString, IsEnum, IsInt, IsIn, IsOptional, IsString, IsUUID, Max, Min } from "class-validator";
import { ScheduleType } from "@prisma/client";
export class ScheduleQueryDto { @IsOptional() @Type(() => Number) @IsInt() @Min(1) page = 1; @IsOptional() @Type(() => Number) @IsInt() @Min(1) @Max(100) pageSize = 25; @IsOptional() @IsString() search?: string; @IsOptional() @IsString() activityId?: string; @IsOptional() @IsString() variantId?: string; @IsOptional() @IsString() destinationId?: string; @IsOptional() @IsIn(["AVAILABLE", "FULL", "INACTIVE"]) availabilityStatus?: "AVAILABLE" | "FULL" | "INACTIVE"; @IsOptional() @Transform(({ value }) => value === true || value === "true" ? true : value === false || value === "false" ? false : value) @IsBoolean() bookable?: boolean; @IsOptional() @IsDateString() from?: string; @IsOptional() @IsDateString() to?: string; @IsOptional() @IsIn(["startsAt", "endsAt", "createdAt", "capacity"]) sortBy = "startsAt"; @IsOptional() @IsIn(["asc", "desc"]) sortOrder: "asc" | "desc" = "asc"; }
export class CreateScheduleDto { @IsString() activityId!: string; @IsOptional() @IsString() variantId?: string; @IsDateString() startsAt!: string; @IsDateString() endsAt!: string; @IsOptional() @IsString() timezone?: string; @IsInt() @Min(1) capacity!: number; @IsOptional() @IsBoolean() isBookable?: boolean; @IsOptional() @IsInt() @Min(0) cutoffMinutes?: number; @IsOptional() @IsEnum(ScheduleType) scheduleType?: ScheduleType; }
export class UpdateScheduleDto { @IsOptional() @IsString() variantId?: string; @IsOptional() @IsDateString() startsAt?: string; @IsOptional() @IsDateString() endsAt?: string; @IsOptional() @IsString() timezone?: string; @IsOptional() @IsInt() @Min(1) capacity?: number; @IsOptional() @IsBoolean() isBookable?: boolean; @IsOptional() @IsInt() @Min(0) cutoffMinutes?: number; }
export class CapacityAdjustmentDto { @IsInt() @Min(0) capacity!: number; @IsString() reason!: string; }
export class BulkGenerateScheduleDto { @IsString() activityId!: string; @IsOptional() @IsString() variantId?: string; @IsDateString() startsAt!: string; @IsDateString() endsAt!: string; @IsOptional() @IsString() timezone?: string; @IsInt() @Min(1) capacity!: number; @IsOptional() @IsBoolean() isBookable?: boolean; @IsOptional() @IsInt() @Min(0) cutoffMinutes?: number; @IsIn(["DAILY", "WEEKLY"]) recurrence!: "DAILY" | "WEEKLY"; @IsInt() @Min(1) @Max(30) interval = 1; @IsOptional() @IsInt() @Min(1) @Max(100) occurrences?: number; @IsOptional() @IsDateString() until?: string; @IsOptional() @IsBoolean() preview?: boolean; }
export class BulkScheduleStatusDto { @IsArray() @ArrayMinSize(1) @ArrayMaxSize(100) @IsUUID("4", { each: true }) ids!: string[]; @IsBoolean() isBookable!: boolean; }
export class DuplicateScheduleDto { @IsDateString() startsAt!: string; @IsDateString() endsAt!: string; }
