import { useEffect, useState } from 'react';
import { API_BASE, api } from '../../api';
import { Badge, Field } from '../Ui';
import type { FulfilmentForm, WizardStepProps } from './types';
import { splitList } from './types';

function listField(value: string, set: (value: string) => void, label: string, disabled: boolean, hint = 'Separate items with commas') {
  return <Field label={label} hint={hint}><textarea rows={2} value={value} onChange={(e) => set(e.target.value)} disabled={disabled} /></Field>;
}

export default function ExperienceStep({ snapshot, locked, revisionForm: form, onRevisionChange: set, fulfilment, onFulfilmentChange, onRefresh, onError }: WizardStepProps) {
  const revision = snapshot.revision;
  const advancedMetadata = <details className="advanced-details"><summary>Advanced marketplace metadata</summary><Field label="SEO title"><input value={form.metaname} onChange={(e) => set('metaname', e.target.value)} disabled={locked} placeholder="Search-friendly experience title" /></Field></details>;
  return <div className="experience-step-stack">{advancedMetadata}
    <div className="experience-step-card"><div className="experience-card-heading"><div><h3>2 · Experience</h3><p>Describe what the traveller will experience and how it is fulfilled.</p></div><Badge value={revision?.status || 'DRAFT'} /></div><div className="experience-divider" /><section className="experience-subcard"><h4>Experience description</h4><Field label="Full description *"><textarea rows={6} value={form.description} onChange={(e) => set('description', e.target.value)} disabled={locked} placeholder="Describe the experience, flow and what the traveller can expect." /></Field><div className="experience-form-grid two">{listField(form.highlights, (v) => set('highlights', v), 'Highlights', locked)}{listField(form.importantInfo, (v) => set('importantInfo', v), 'Important information', locked)}{listField(form.thingsToCarry, (v) => set('thingsToCarry', v), 'Things to carry', locked)}{listField(form.safetyMeasures, (v) => set('safetyMeasures', v), 'Safety measures', locked)}</div></section><section className="experience-subcard"><h4>Location & meeting instructions</h4><div className="experience-form-grid two"><Field label="Meeting point"><input value={form.meetingPoint} onChange={(e) => set('meetingPoint', e.target.value)} disabled={locked} placeholder="Landmark, venue or pickup instructions" /></Field><Field label="Address"><input value={form.address} onChange={(e) => set('address', e.target.value)} disabled={locked} placeholder="Full address" /></Field><Field label="Latitude"><input type="number" step="any" value={form.lat} onChange={(e) => set('lat', e.target.value)} disabled={locked} /></Field><Field label="Longitude"><input type="number" step="any" value={form.lon} onChange={(e) => set('lon', e.target.value)} disabled={locked} /></Field></div></section></div>
    {revision && <MediaSection revision={revision} locked={locked} onRefresh={onRefresh} onError={onError} />}
    {revision && <BookingQuestionsSection revision={revision} locked={locked} onRefresh={onRefresh} onError={onError} />}
    {revision && <FulfilmentSection value={fulfilment} locked={locked} onChange={onFulfilmentChange} onSave={async () => { try { await api.request(`/product-revisions/${revision.id}`, { method: 'PATCH', body: JSON.stringify({ fulfilmentPolicy: fulfilmentPayload(fulfilment) }) }); await onRefresh(); } catch (e) { onError(e instanceof Error ? e.message : String(e)); } }} />}
  </div>;
}

function fulfilmentPayload(value: FulfilmentForm) {
  const kinds = value.mode === 'AUTO' ? [] : value.mode === 'PNR_ONLY' ? ['PNR_REFERENCE'] : value.mode === 'TICKET_QR' ? (value.requiredEvidenceKinds.filter((kind) => ['TICKET_FILE', 'QR_TOKEN'].includes(kind)).length ? value.requiredEvidenceKinds.filter((kind) => ['TICKET_FILE', 'QR_TOKEN'].includes(kind)) : ['TICKET_FILE']) : value.requiredEvidenceKinds;
  return { ...value, requiredEvidenceKinds: kinds, evidenceMatchMode: value.mode === 'PNR_ONLY' ? 'ALL' : value.mode === 'TICKET_QR' ? 'ANY' : value.evidenceMatchMode, voucherNotes: splitList(value.voucherNotes) };
}

function MediaSection({ revision, locked, onRefresh, onError }: { revision: NonNullable<WizardStepProps['snapshot']['revision']>; locked: boolean; onRefresh: () => Promise<void>; onError: (message: string) => void }) {
  const [url, setUrl] = useState(''); const [description, setDescription] = useState(''); const [file, setFile] = useState<File | null>(null); const [busy, setBusy] = useState(false);
  async function run(action: () => Promise<void>) { setBusy(true); try { await action(); } catch (e) { onError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  return <section className="experience-step-card"><div className="experience-card-heading"><div><h3>Media</h3><p>Use real ProductRevision media so the catalogue remains portable across channels.</p></div><span className="experience-pill">{revision.media?.length || 0} assets</span></div><div className="media-preview-grid">{revision.media?.map((media) => <div className="media-preview-card" key={media.id}>{media.externalUrl ? <a className="media-placeholder" href={media.externalUrl} target="_blank" rel="noreferrer">Open external image</a> : <img src={`${API_BASE}/files/public/${media.fileAssetId}/content`} alt={media.description || 'Experience media'} />}{!locked && <div className="media-preview-footer"><small>{media.description || 'Image'}</small><button type="button" className="link-button" onClick={() => void run(async () => { await api.request(`/product-revisions/${revision.id}/media/${media.id}`, { method: 'DELETE' }); await onRefresh(); })}>Remove</button></div>}</div>)}</div>{!locked && <div className="experience-subcard media-entry"><div className="experience-form-grid two"><Field label="External image URL"><input type="url" value={url} onChange={(e) => setUrl(e.target.value)} placeholder="https://…" /></Field><Field label="Upload JPEG, PNG or WebP"><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => setFile(e.target.files?.[0] || null)} /></Field><Field label="Description"><input value={description} onChange={(e) => setDescription(e.target.value)} placeholder="What does this image show?" /></Field></div><div className="experience-footer-actions"><button type="button" className="btn" disabled={busy || !url} onClick={() => void run(async () => { await api.request(`/product-revisions/${revision.id}/media`, { method: 'POST', body: JSON.stringify({ kind: 'IMAGE', externalUrl: url, description }) }); setUrl(''); await onRefresh(); })}>Add external image</button><button type="button" className="btn primary" disabled={busy || !file} onClick={() => void run(async () => { const body = new FormData(); body.append('file', file!); body.append('kind', 'IMAGE'); body.append('description', description); await api.request(`/product-revisions/${revision.id}/media/upload`, { method: 'POST', body }); setFile(null); await onRefresh(); })}>Upload image</button></div></div>}</section>;
}

function BookingQuestionsSection({ revision, locked, onRefresh, onError }: { revision: NonNullable<WizardStepProps['snapshot']['revision']>; locked: boolean; onRefresh: () => Promise<void>; onError: (message: string) => void }) {
  const [code, setCode] = useState(''); const [label, setLabel] = useState(''); const [type, setType] = useState('TEXT'); const [required, setRequired] = useState(false); const [busy, setBusy] = useState(false);
  async function add() { if (!code.trim() || !label.trim()) return; setBusy(true); try { await api.request(`/product-revisions/${revision.id}/booking-questions`, { method: 'POST', body: JSON.stringify({ code: code.trim(), label: label.trim(), type, required, rank: revision.bookingQuestions?.length || 0 }) }); setCode(''); setLabel(''); await onRefresh(); } catch (e) { onError(e instanceof Error ? e.message : String(e)); } finally { setBusy(false); } }
  return <section className="experience-step-card"><div className="experience-card-heading"><div><h3>Booking questions</h3><p>Capture structured traveller information at booking time.</p></div><span className="experience-pill">{revision.bookingQuestions?.length || 0} questions</span></div>{revision.bookingQuestions?.map((question) => <div className="question-row" key={question.id}><div><b>{question.label}</b><small>{question.code} · {question.type} · {question.required ? 'Required' : 'Optional'}</small></div>{!locked && <button type="button" className="link-button" onClick={() => void (async () => { try { await api.request(`/booking-questions/${question.id}`, { method: 'DELETE' }); await onRefresh(); } catch (e) { onError(e instanceof Error ? e.message : String(e)); } })()}>Archive</button>}</div>)}{!locked && <div className="experience-subcard"><div className="experience-form-grid three"><Field label="Code"><input value={code} onChange={(e) => setCode(e.target.value)} placeholder="lead_phone" /></Field><Field label="Label"><input value={label} onChange={(e) => setLabel(e.target.value)} placeholder="Lead traveller phone" /></Field><Field label="Type"><select value={type} onChange={(e) => setType(e.target.value)}><option>TEXT</option><option>NUMBER</option><option>BOOLEAN</option><option>SELECT</option></select></Field></div><label className="wizard-check"><input type="checkbox" checked={required} onChange={(e) => setRequired(e.target.checked)} /> Required</label><button type="button" className="btn" disabled={busy || !code || !label} onClick={() => void add()}>Add question</button></div>}</section>;
}

function FulfilmentSection({ value, locked, onChange, onSave }: { value: FulfilmentForm; locked: boolean; onChange: (next: FulfilmentForm) => void; onSave: () => Promise<void> }) {
  const [busy, setBusy] = useState(false);
  useEffect(() => { if (value.mode === 'PNR_ONLY' && value.requiredEvidenceKinds.join() !== 'PNR_REFERENCE') onChange({ ...value, requiredEvidenceKinds: ['PNR_REFERENCE'], evidenceMatchMode: 'ALL' }); if (value.mode === 'AUTO' && value.requiredEvidenceKinds.length) onChange({ ...value, requiredEvidenceKinds: [], evidenceMatchMode: 'ALL' }); }, [value.mode]);
  return <section className="experience-step-card"><div className="experience-card-heading"><div><h3>Fulfilment</h3><p>Define how supplier confirmation becomes a customer-ready voucher.</p></div><span className="experience-pill">{value.mode || 'Not configured'}</span></div><div className="experience-form-grid two"><Field label="Fulfilment mode"><select value={value.mode} onChange={(e) => onChange({ ...value, mode: e.target.value as FulfilmentForm['mode'] })} disabled={locked}><option value="">Select a mode</option><option value="AUTO">Generate automatically after confirmation</option><option value="AFTER_FULFILMENT">Wait for supplier fulfilment evidence</option><option value="PNR_ONLY">PNR or reference required</option><option value="TICKET_QR">Supplier ticket or QR required</option></select></Field><Field label="Operations contact"><input value={value.operationsContactName} onChange={(e) => onChange({ ...value, operationsContactName: e.target.value })} disabled={locked} /></Field><Field label="Operations phone"><input value={value.operationsContactPhone} onChange={(e) => onChange({ ...value, operationsContactPhone: e.target.value })} disabled={locked} /></Field><Field label="Operations email"><input type="email" value={value.operationsContactEmail} onChange={(e) => onChange({ ...value, operationsContactEmail: e.target.value })} disabled={locked} /></Field></div><Field label="Voucher notes"><textarea rows={3} value={value.voucherNotes} onChange={(e) => onChange({ ...value, voucherNotes: e.target.value })} disabled={locked} /></Field>{!locked && <button type="button" className="btn" disabled={busy} onClick={() => void (async () => { setBusy(true); try { await onSave(); } finally { setBusy(false); } })()}>{busy ? 'Saving…' : 'Save fulfilment'}</button>}</section>;
}
