import { useEffect, useState } from 'react';
import { api, type ProductReadiness } from '../../api';
import { Badge } from '../Ui';
import type { WizardStep, WizardStepProps } from './types';

const sectionLabels: Array<[keyof ProductReadiness['sections'], string, WizardStep]> = [['basicInfo', 'Basic information', 1], ['experience', 'Experience', 2], ['options', 'Options', 3], ['rates', 'Rates & rules', 4], ['availability', 'Availability', 5], ['mediaFulfilment', 'Media & fulfilment', 2]];
const reasonLabels: Record<string, string> = { PRODUCT_NAME_MISSING: 'Product name is missing', PRODUCT_TYPE_MISSING: 'Product type is missing', PRODUCT_SUBTYPE_MISSING: 'Product type classification is missing', SUBCATEGORY_MISSING: 'Sub-category is missing', DESTINATION_MISSING: 'Complete city, state and country', MEETING_MODEL_MISSING: 'Meeting model is missing', EXPERIENCE_DESCRIPTION_MISSING: 'Full description is missing', MEETING_POINT_MISSING: 'Meeting point is missing for this model', OPTIONS_MISSING: 'No option has been created', RATE_PLAN_MISSING: 'No active rate plan exists', CANCELLATION_RULES_MISSING: 'Cancellation policy is missing', NO_ACTIVE_COMMERCIAL_VERSION: 'No active commercial version exists', COMMERCIAL_VERSION_MISSING: 'Commercial terms need configuration', SUPPLIER_MODEL_MISSING: 'Supplier model is missing', PRICING_UNIT_MISSING: 'Pricing unit is missing', BOOKING_MODE_MISSING: 'Booking mode is missing', SUPPLIER_BASE_AMOUNT_MISSING: 'Supplier base amount is missing', TRAVELLER_PRICE_MISSING: 'Traveller prices are missing', CONFIRMATION_SLA_MISSING: 'Confirmation SLA is required', VOYA_REVENUE_RULE_MISSING: 'Voya revenue rule is not configured', TAX_CONFIGURATION_MISSING: 'Tax configuration is not configured', RATE_PLAN_NOT_MAPPED: 'A ready rate plan is not mapped to a schedule', SCHEDULE_MISSING: 'No active operating schedule exists', FUTURE_AVAILABILITY_MISSING: 'No future inventory with available capacity exists', COVER_IMAGE_MISSING: 'Cover image is missing', FULFILMENT_POLICY_MISSING: 'Fulfilment policy is missing' };

export default function ReviewSubmitStep({ snapshot, onError, onRefresh, onRevisionChange: _set, onFulfilmentChange: _fulfilment, revisionForm: _form, locked, onNavigate }: WizardStepProps & { onNavigate: (step: WizardStep) => void }) {
  const [data, setData] = useState<ProductReadiness | null>(null); const [loading, setLoading] = useState(false);
  async function load() { if (!snapshot.product) return; setLoading(true); try { setData(await api.request<ProductReadiness>(`/products/${snapshot.product.id}/readiness`)); } catch (e) { onError(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [snapshot.product?.id, snapshot.revision?.id, snapshot.revision?.status, snapshot.variants.length, snapshot.schedules.length]);
  return <div className="experience-step-card"><div className="experience-card-heading"><div><h3>6 · Review & submit</h3><p>Check that your experience is ready for Voya review.</p></div>{data && <Badge value={data.ready ? 'READY' : 'NEEDS_REVIEW'} />}</div>{!snapshot.product && <div className="experience-empty">Save the draft first to ask the server for readiness.</div>}{snapshot.product && <>{loading && <p className="experience-help">Checking canonical product readiness…</p>}{data && <div className="readiness-grid">{sectionLabels.map(([key, label, step]) => { const item = data.sections[key]; return <div className={`readiness-card ${item.ready ? 'ready' : 'attention'}`} key={key}><div className="experience-card-heading"><b>{label}</b><span className={`experience-pill ${item.ready ? 'success' : 'warning'}`}>{item.ready ? 'Complete' : 'Needs attention'}</span></div>{item.ready ? <p>Configured and available to submit.</p> : <ul>{item.reasonCodes.map((code) => <li key={code}>{reasonLabels[code] || code.replaceAll('_', ' ').toLowerCase()}</li>)}</ul>}<button type="button" className="link-button" onClick={() => onNavigate(step)}>{item.ready ? 'Edit' : 'Fix this section'}</button></div>; })}</div>}<button type="button" className="btn" onClick={() => void load()} disabled={loading}>Refresh readiness</button>{locked && <div className="experience-notice"><b>This revision is read-only.</b> It is already under review or published; create a new working revision to make changes.</div>}</>}</div>;
}
