import { EligibilityService } from './eligibility.service';
import { CutoffService } from './cutoff.service';

const date = new Date('2026-10-10T00:00:00.000Z');
const commercialResult = { ready: true, commercialEligibility: 'ALLOWED', finalAmount: '100.00', agentFacingAmount: '100.00', bookingMode: 'INSTANT', reasonCodes: [], ratePlanCommercialVersionId: 'cv1', currency: 'INR' };

function fixture(overrides: any = {}, cutoffService: any = { evaluate: jest.fn().mockReturnValue({ eligible: true, cutoffAt: null }) }) {
  const plan: any = { id: 'rp1', variantId: 'v1', status: 'ACTIVE', validFrom: new Date('2020-01-01'), validTo: new Date('2030-01-01'), cutOffMinutes: 0, dateLevelCutoffTime: null, minPax: 1, maxPax: 10, adultRequired: true, minAdultRequired: 1, travellerRules: [{ type: 'ADULT', minCount: 1, maxCount: 10 }], channelMappings: [{ enabled: true, channel: { code: 'VOYA_AGENT', active: true } }], scheduleMappings: [{ scheduleTemplateId: 's1', active: true }], variant: { id: 'v1', status: 'ACTIVE', archivedAt: null, product: { id: 'p1', currentRevisionId: 'rev1', status: 'LIVE', currentRevision: { id: 'rev1', status: 'PUBLISHED', fulfilmentPolicy: { mode: 'AUTO', requiredEvidenceKinds: [], evidenceMatchMode: 'ALL', reviewRequired: false } }, tenant: { kind: 'VENDOR', vendorProfile: { verificationStatus: 'VERIFIED' } } } } };
  const session: any = { id: 'ss1', scheduleTemplateId: 's1', serviceDate: date, startsAt: new Date('2026-10-10T10:00:00Z'), status: 'OPEN', archivedAt: null, version: 1, inventoryState: { totalCapacity: 10, blockedCapacity: 0, heldCapacity: 0, confirmedCapacity: 0, version: 1 }, scheduleTemplate: { variantId: 'v1', status: 'ACTIVE', archivedAt: null, effectiveFrom: new Date('2020-01-01'), effectiveTo: null, capacityUnit: 'PERSON', capacityUnitReviewRequired: false, timezone: 'Asia/Kolkata' } };
  const agent: any = { id: 'agent1', kind: 'TRAVEL_AGENT', agentProfile: { verificationStatus: 'APPROVED' } };
  const nextPlan = { ...plan, ...overrides.plan, variant: { ...plan.variant, ...overrides.plan?.variant, product: { ...plan.variant.product, ...overrides.plan?.variant?.product, tenant: { ...plan.variant.product.tenant, ...overrides.plan?.variant?.product?.tenant }, currentRevision: { ...plan.variant.product.currentRevision, ...overrides.plan?.variant?.product?.currentRevision } } } };
  const nextSession = { ...session, ...overrides.session, inventoryState: { ...session.inventoryState, ...overrides.session?.inventoryState }, scheduleTemplate: { ...session.scheduleTemplate, ...overrides.session?.scheduleTemplate } };
  const tx: any = { ratePlan: { findUnique: jest.fn().mockResolvedValue(nextPlan) }, serviceSession: { findUnique: jest.fn().mockResolvedValue(nextSession) }, tenant: { findUnique: jest.fn().mockResolvedValue({ ...agent, ...overrides.agent, agentProfile: { ...agent.agentProfile, ...overrides.agent?.agentProfile } }) } };
  const root: any = { ratePlan: { findUnique: jest.fn(() => { throw new Error('root client used'); }) }, serviceSession: { findUnique: jest.fn(() => { throw new Error('root client used'); }) }, tenant: { findUnique: jest.fn(() => { throw new Error('root client used'); }) } };
  const commercial: any = { evaluateInternal: jest.fn().mockResolvedValue(overrides.commercial ?? commercialResult), projectForAgent: jest.fn((value) => value) };
  const resources: any = { resourceReadiness: jest.fn().mockResolvedValue({ ready: true, reasonCodes: [] }) };
  return { service: new EligibilityService(root, commercial, resources, cutoffService), tx, commercial, resources, input: { agentTenantId: 'agent1', ratePlanId: 'rp1', sessionId: 'ss1', travellers: [{ travellerType: 'ADULT', quantity: 1 }], now: new Date('2026-10-09T08:00:00Z') } };
}

describe('EligibilityService Phase 5.1 closure', () => {
  it('uses the supplied transaction client for all authoritative reads and dependencies', async () => { const f = fixture(); const result = await f.service.evaluate(f.input as any, { client: f.tx }); expect(result.eligible).toBe(true); expect(f.tx.ratePlan.findUnique).toHaveBeenCalled(); expect(f.tx.serviceSession.findUnique).toHaveBeenCalled(); expect(f.tx.tenant.findUnique).toHaveBeenCalled(); expect(f.commercial.evaluateInternal).toHaveBeenCalledWith(expect.anything(), f.tx); expect(f.resources.resourceReadiness).toHaveBeenCalledWith('ss1', f.tx); });
  it.each([['PENDING', 'AGENT_NOT_APPROVED'], ['SUSPENDED', 'AGENT_SUSPENDED']])('rejects %s agents', async (status, code) => { const f = fixture({ agent: { agentProfile: { verificationStatus: status } } }); const result = await f.service.evaluate(f.input as any, { client: f.tx }); expect(result.gates.find((g) => g.gate === 'AGENT_GOVERNANCE')?.code).toBe(code); expect(result.eligible).toBe(false); });
  it('rejects a non-agent tenant', async () => { const f = fixture({ agent: { kind: 'VENDOR' } }); expect((await f.service.evaluate(f.input as any, { client: f.tx })).gates.find((g) => g.gate === 'AGENT_GOVERNANCE')?.code).toBe('AGENT_NOT_APPROVED'); });
  it.each([[{ vendorProfile: { verificationStatus: 'PENDING' } }, 'VENDOR_NOT_VERIFIED'], [{ vendorProfile: { verificationStatus: 'SUSPENDED' } }, 'VENDOR_SUSPENDED']])('enforces vendor governance', async (vendor, code) => { const f = fixture({ plan: { variant: { product: { tenant: { kind: 'VENDOR', ...vendor } } } } }); expect((await f.service.evaluate(f.input as any, { client: f.tx })).gates.find((g) => g.gate === 'VENDOR')?.code).toBe(code); });
  it('requires the current published revision, active variant, active rate plan and enabled channel', async () => { for (const [overrides, code, gate] of [[{ plan: { variant: { product: { status: 'DRAFT' } } } }, 'PRODUCT_NOT_LIVE', 'PRODUCT'], [{ plan: { variant: { status: 'INACTIVE' } } }, 'VARIANT_NOT_ACTIVE', 'VARIANT'], [{ plan: { status: 'INACTIVE' } }, 'RATEPLAN_NOT_ACTIVE', 'RATE_PLAN'], [{ plan: { channelMappings: [{ enabled: false, channel: { code: 'VOYA_AGENT', active: true } }] } }, 'MARKETPLACE_CHANNEL_DISABLED', 'CHANNEL']] as any[]) { const f = fixture(overrides); expect((await f.service.evaluate(f.input as any, { client: f.tx })).gates.find((g) => g.gate === gate)?.code).toBe(code); } });
  it('enforces every traveller rule, including omitted configured types, and combines duplicates', async () => { const f = fixture({ plan: { travellerRules: [{ type: 'ADULT', minCount: 1, maxCount: 10 }, { type: 'CHILD', minCount: 1, maxCount: 2 }] } }); const result = await f.service.evaluate({ ...f.input, travellers: [{ travellerType: 'ADULT', quantity: 1 }, { travellerType: 'ADULT', quantity: 1 }] } as any, { client: f.tx }); expect(result.gates.find((g) => g.gate === 'TRAVELLER')?.code).toBe('TRAVELLER_COUNT_INVALID'); expect(f.commercial.evaluateInternal).not.toHaveBeenCalled(); });
  it('separates UNIT capacity failure from inventory evaluation', async () => { const f = fixture({ plan: { travellerRules: [{ type: 'ADULT', minCount: 1, maxCount: 10 }] }, session: { scheduleTemplate: { capacityUnit: 'UNIT' } } }); const result = await f.service.evaluate(f.input as any, { client: f.tx }); expect(result.gates.find((g) => g.gate === 'CAPACITY')).toMatchObject({ status: 'FAIL', code: 'UNIT_QUANTITY_REQUIRED' }); expect(result.gates.find((g) => g.gate === 'INVENTORY')).toMatchObject({ status: 'NOT_EVALUATED' }); });
  it('requires units for UNIT capacity and preserves the requested quantity when supplied', async () => { const f = fixture({ session: { scheduleTemplate: { capacityUnit: 'UNIT' } } }); const result = await f.service.evaluate({ ...f.input, units: 2 } as any, { client: f.tx }); expect(result.eligible).toBe(true); expect(result.gates.find((g) => g.gate === 'CAPACITY')).toMatchObject({ status: 'PASS', details: { requiredCapacity: 2, capacityUnit: 'UNIT' } }); expect(result.gates.find((g) => g.gate === 'INVENTORY')).toMatchObject({ status: 'PASS', details: { requiredCapacity: 2 } }); });
  it('fails a missing cutoff reference and accepts the timezone-aware date-level fallback', async () => { const realCutoff = new CutoffService(); const missing = fixture({ session: { startsAt: null }, plan: { dateLevelCutoffTime: null } }, realCutoff); const missingResult = await missing.service.evaluate(missing.input as any, { client: missing.tx }); expect(missingResult.eligible).toBe(false); expect(missingResult.gates.find((g) => g.gate === 'CUTOFF')).toMatchObject({ status: 'FAIL', code: 'CUTOFF_REFERENCE_MISSING' }); const explicit = fixture({ session: { startsAt: null }, plan: { dateLevelCutoffTime: '10:00', cutOffMinutes: 60 } }, realCutoff); const before = await explicit.service.evaluate({ ...explicit.input, now: new Date('2026-10-09T04:29:00Z') } as any, { client: explicit.tx }); expect(before.gates.find((g) => g.gate === 'CUTOFF')).toMatchObject({ status: 'PASS', details: { cutoffAt: '2026-10-10T03:30:00.000Z' } }); const after = await explicit.service.evaluate({ ...explicit.input, now: new Date('2026-10-10T03:30:00Z') } as any, { client: explicit.tx }); expect(after.gates.find((g) => g.gate === 'CUTOFF')).toMatchObject({ status: 'FAIL', code: 'CUTOFF_PASSED' }); });
  it('returns PRICE_NOT_CALCULABLE while retaining commercial diagnostics', async () => { const f = fixture({ commercial: { ...commercialResult, finalAmount: 'NaN', reasonCodes: ['TAX_CONFIGURATION_MISSING'] } }); const result = await f.service.evaluate(f.input as any, { client: f.tx }); expect(result.gates.find((g) => g.gate === 'COMMERCIAL')).toMatchObject({ status: 'FAIL', code: 'PRICE_NOT_CALCULABLE' }); expect(result.gates.find((g) => g.gate === 'COMMERCIAL')?.details).toMatchObject({ reasonCodes: ['TAX_CONFIGURATION_MISSING'] }); });
  it.each([['BLACKOUT', 'SESSION_BLACKOUT'], ['CLOSED', 'SESSION_CLOSED'], ['ARCHIVED', 'SESSION_ARCHIVED']])('rejects %s sessions', async (status, code) => { const f = fixture({ session: { status } }); expect((await f.service.evaluate(f.input as any, { client: f.tx })).gates.find((g) => g.gate === 'SESSION')?.code).toBe(code); });
  it('rejects insufficient inventory and unavailable resources without writing', async () => { const f = fixture({ session: { inventoryState: { totalCapacity: 0 } } }); f.resources.resourceReadiness.mockResolvedValue({ ready: false, reasonCodes: ['RESOURCE_REQUIREMENT_UNASSIGNED'] }); const result = await f.service.evaluate(f.input as any, { client: f.tx }); expect(result.gates.find((g) => g.gate === 'INVENTORY')?.code).toBe('INSUFFICIENT_INVENTORY'); expect(result.gates.find((g) => g.gate === 'RESOURCES')?.code).toBe('RESOURCE_NOT_READY'); expect(f.tx).not.toHaveProperty('booking'); });
});
