/**
 * Safe, reusable request examples used by Swagger UI.
 *
 * The identifiers are deliberately obvious placeholders. Replace them with
 * IDs returned by the preceding GET endpoint when exercising a workflow.
 */
const swaggerDemoSuffix = Date.now().toString(36).toUpperCase();
const swaggerDemoEmail = process.env.SWAGGER_DEMO_EMAIL || '';
const swaggerDemoPassword = process.env.SWAGGER_DEMO_PASSWORD || process.env.DEMO_PASSWORD || '';

export const swaggerExamples = {
  auth: {
    login: { email: swaggerDemoEmail, password: swaggerDemoPassword },
    register: { fullName: 'Demo Supplier User', email: '', password: swaggerDemoPassword },
  },
  vendor: {
    updateProfile: {
      legalBusinessName: 'Blue Mountain Adventures Pvt. Ltd.',
      operatingCity: 'Munnar',
      operatingRegion: 'Kerala',
      gstin: '32AACCB1234F1Z5',
      category: 'Trekking, Nature & Wildlife',
      payoutAccountMasked: 'HDFC •••• 4821',
      payoutAccountHolder: 'Blue Mountain Adventures Pvt. Ltd.',
      payoutBankName: 'HDFC Bank',
      payoutBranch: 'Munnar',
      payoutIfsc: 'HDFC0001234',
      payoutCurrency: 'INR',
      payoutAccountType: 'CURRENT',
    },
  },
  catalogue: {
    createProduct: {
      productCode: `DEMO-SUNRISE-TREK-${swaggerDemoSuffix}`,
      initialRevision: {
        productName: 'Sunrise Trek to Top Station',
        type: 'ACTIVITY',
        subType: 'TICKET_ONLY',
        subCategory: 'Outdoor Experiences',
        shortDescription: 'Guided sunrise trek through the Munnar highlands.',
        description: 'A guided early-morning trek with sunrise viewpoints, breakfast, and local guide support.',
        highlights: ['Sunrise viewpoint', 'Local trek guide', 'Breakfast included'],
        importantInfo: ['Weather dependent', 'Carry a valid photo ID'],
        thingsToCarry: ['Comfortable footwear', 'Water bottle'],
        terms: ['Cancellation terms apply as per the selected rate plan.'],
        cityName: 'Munnar',
        stateName: 'Kerala',
        countryName: 'INDIA',
        address: 'Munnar, Kerala',
        lat: 10.0889,
        lon: 77.0595,
        starRating: 4.8,
        channels: ['B2B', 'B2C'],
        labels: ['Demo', 'Nature'],
        rank: 1,
      },
    },
    createRevision: { sourceRevisionId: 'replace-with-published-or-rejected-revision-id' },
    updateRevision: {
      productName: 'Sunrise Trek to Top Station',
      shortDescription: 'Updated guided sunrise trek with breakfast.',
      highlights: ['Sunrise viewpoint', 'Local trek guide', 'Breakfast included', 'Small groups'],
      description: 'Updated customer-facing description for the working product revision.',
      cityName: 'Munnar',
      stateName: 'Kerala',
      countryName: 'INDIA',
      starRating: 4.8,
    },
    media: {
      kind: 'IMAGE',
      externalUrl: 'https://images.example.com/voya/sunrise-trek-hero.jpg',
      description: 'Sunrise viewpoint at Top Station',
      seoTitle: 'Sunrise Trek to Top Station in Munnar',
      seoDescription: 'Guided sunrise trek and viewpoint experience in Munnar.',
      rank: 1,
    },
    mediaUpload: {
      kind: 'IMAGE',
      description: 'Sunrise viewpoint at Top Station',
      seoTitle: 'Sunrise Trek to Top Station in Munnar',
      seoDescription: 'Guided sunrise trek and viewpoint experience in Munnar.',
      rank: 1,
    },
    variant: {
      variantCode: `SUNRISE_SHARED_DEMO-${swaggerDemoSuffix}`,
      name: 'Shared SUV · 05:15 pickup',
      description: 'Shared SUV transfer and guided sunrise trek.',
      durationMinutes: 240,
      privateShared: 'Shared',
      vehicleType: 'SUV',
      pickupIncluded: true,
      pickupType: 'Munnar town pickup',
      pickupInput: 'Munnar town pickup point',
      pickupTimings: '05:15 AM',
      dropoffIncluded: true,
      dropoffTimings: '10:30 AM',
      inclusions: ['Trek guide', 'Breakfast', 'Entry support'],
      exclusions: ['Personal expenses', 'Travel insurance'],
      suitableFor: ['ADULT', 'CHILD', 'SENIOR'],
    },
    updateVariant: {
      name: 'Shared SUV · 05:15 pickup updated',
      description: 'Updated operational variant description.',
      pickupIncluded: true,
      pickupTimings: '05:15 AM',
      expectedVersion: 1,
    },
    archiveVariant: { expectedVersion: 1 },
    rejectRevision: { reason: 'Please add the meeting point and update the cancellation copy.' },
  },
  ratePlans: {
    create: {
      ratePlanCode: `RP-DEMO-${swaggerDemoSuffix}`,
      name: 'Standard B2B',
      status: 'ACTIVE',
      description: 'Flexible per-person rate for the sunrise trek.',
      validFrom: '2026-09-01T00:00:00.000Z',
      validTo: '2026-12-31T23:59:59.000Z',
      currency: 'INR',
      minPax: 1,
      maxPax: 15,
      cutOffMinutes: 120,
      adultRequired: true,
      minAdultRequired: 1,
      travellerRules: [
        { type: 'ADULT', displayName: 'Adult', minAge: 12, maxAge: 99, minCount: 1, maxCount: 15 },
        { type: 'CHILD', displayName: 'Child', minAge: 5, maxAge: 11, minCount: 0, maxCount: 5 },
      ],
      cancellationRules: [
        { minDaysBefore: 6, chargeValue: 0, chargeType: 'PERCENTAGE' },
        { minDaysBefore: 1, maxDaysBefore: 5, chargeValue: 50, chargeType: 'PERCENTAGE' },
        { minDaysBefore: 0, maxDaysBefore: 0, chargeValue: 100, chargeType: 'PERCENTAGE' },
      ],
    },
    update: {
      name: 'Standard B2B updated',
      description: 'Updated rate-plan description.',
      validFrom: '2026-09-01T00:00:00.000Z',
      validTo: '2026-12-31T23:59:59.000Z',
      status: 'ACTIVE',
      currency: 'INR',
      minPax: 1,
      maxPax: 15,
    },
  },
  commercial: {
    vendorVersion: {
      effectiveFrom: '2026-09-01T00:00:00.000Z',
      effectiveTo: '2026-12-31T23:59:59.000Z',
      supplierModel: 'NET_RATE',
      currency: 'INR',
      pricingUnit: 'PER_PERSON',
      supplierBaseAmount: '1499',
      supplierCommissionPercent: '0',
      bookingMode: 'INSTANT',
      travellerPrices: [
        { travellerType: 'ADULT', amount: '1499' },
        { travellerType: 'CHILD', amount: '999' },
      ],
    },
    rule: {
      code: `DEMO-VOYA-REVENUE-${swaggerDemoSuffix}`,
      name: 'Demo Voya revenue markup',
      kind: 'VOYA_REVENUE',
      scopeType: 'GLOBAL',
    },
    ruleVersion: {
      effectiveFrom: '2026-09-01T00:00:00.000Z',
      effectiveTo: '2026-12-31T23:59:59.000Z',
      priority: 10,
      stackingMode: 'EXCLUSIVE',
      config: { model: 'MARKUP_PERCENT', percent: '10' },
    },
    agentGroup: { code: `DEMO-PREFERRED-AGENTS-${swaggerDemoSuffix}`, name: 'Demo Preferred Agents' },
    agentMember: { agentTenantId: 'replace-with-agent-tenant-id' },
    quote: {
      ratePlanId: 'replace-with-rate-plan-id',
      serviceDate: '2026-09-20T00:00:00.000Z',
      units: 1,
      travellers: [
        { travellerType: 'ADULT', quantity: 2 },
        { travellerType: 'CHILD', quantity: 1 },
      ],
      channel: 'B2B',
    },
  },
  inventory: {
    preview: {
      scheduleTemplateId: 'replace-with-schedule-template-id',
      dateFrom: '2026-09-20T00:00:00.000Z',
      dateTo: '2026-09-26T23:59:59.000Z',
      slotTemplateIds: ['replace-with-slot-template-id'],
      proposal: { newTotalCapacity: 12, newBlockedCapacity: 2, sessionStatus: 'OPEN' },
    },
    apply: {
      scheduleTemplateId: 'replace-with-schedule-template-id',
      expectedScheduleVersion: 1,
      rows: [
        {
          sessionId: 'replace-with-service-session-id',
          newTotalCapacity: 12,
          newBlockedCapacity: 2,
          expectedInventoryVersion: 1,
          expectedSessionVersion: 1,
        },
      ],
    },
  },
  schedules: {
    create: {
      scheduleCode: `DEMO-MORNING-SLOTS-${swaggerDemoSuffix}`,
      name: 'Demo morning operating schedule',
      operatingModel: 'MULTIPLE_SLOTS',
      timezone: 'Asia/Kolkata',
      effectiveFrom: '2026-09-01T00:00:00.000Z',
      effectiveTo: '2026-12-31T23:59:59.000Z',
      operatingDays: ['MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY', 'SATURDAY', 'SUNDAY'],
      capacityUnit: 'PERSON',
      defaultCapacity: 12,
      slots: [
        { slotCode: 'DEMO-0900', label: 'Morning slot', startTime: '09:00', endTime: '12:00', rank: 0 },
        { slotCode: 'DEMO-1400', label: 'Afternoon slot', startTime: '14:00', endTime: '17:00', rank: 1 },
      ],
    },
    update: { name: 'Demo morning operating schedule updated', defaultCapacity: 14, expectedVersion: 1 },
    version: { expectedVersion: 1 },
    slot: { slotCode: 'DEMO-1630', label: 'Late afternoon slot', startTime: '16:30', endTime: '18:30', rank: 2, expectedVersion: 1 },
    updateSlot: { label: 'Late afternoon slot updated', startTime: '16:30', endTime: '18:30', expectedVersion: 1 },
    mapRatePlan: { ratePlanId: 'replace-with-rate-plan-id', expectedVersion: 1 },
    exception: { serviceDate: '2026-09-20T00:00:00.000Z', type: 'CLOSED', reason: 'Operational closure for maintenance', expectedVersion: 1 },
    materialize: { dateFrom: '2026-09-20T00:00:00.000Z', dateTo: '2026-09-26T23:59:59.000Z', expectedVersion: 1 },
    requirement: { resourceType: 'VEHICLE', specificResourceId: 'replace-with-resource-id', quantity: 1, required: true, expectedVersion: 1 },
    updateRequirement: { quantity: 2, required: true, expectedVersion: 1 },
  },
  resources: {
    create: { resourceCode: `DEMO-SUV-${swaggerDemoSuffix}`, name: 'Demo Sunrise SUV', type: 'VEHICLE', allocationMode: 'EXCLUSIVE', capacity: 6 },
    update: { name: 'Demo Sunrise SUV updated', capacity: 6, active: true, expectedVersion: 1 },
    allocate: { resourceId: 'replace-with-resource-id', quantity: 1, expectedVersion: 1 },
  },
  admin: {
    vendorVerification: { status: 'VERIFIED', reason: 'Business details and documents verified.' },
    documentReview: { status: 'VERIFIED', reason: 'Document reviewed and accepted.' },
  },
} as const;
