import { ConflictException, ForbiddenException, Injectable, NotFoundException } from '@nestjs/common';
import { BookingFulfilmentStatus, BookingStatus, FilePurpose, FileVisibility, FulfilmentEvidenceKind, FulfilmentEvidenceStatus, Prisma, RedemptionMethod, UserRole, VoucherGenerationStatus, VoucherShareChannel, VoucherShareStatus, VoucherVersionStatus } from '@prisma/client';
import { AuthUser } from '../common/auth.types';
import { AuditService } from '../audit/audit.service';
import { OutboxService } from '../outbox/outbox.service';
import { PrismaService } from '../prisma/prisma.service';
import { StorageService } from '../storage/storage.service';
import { CompleteBookingDto, EvidenceUploadDto, FulfilmentQueryDto, ReferenceEvidenceDto, VoucherShareDto } from './fulfilment.dto';
import { evidenceFingerprint, validateEvidenceShape } from './fulfilment.types';
import { FulfilmentReadinessService } from './fulfilment-readiness.service';
import { VoucherGenerationService } from './voucher-generation.service';

const include = { booking: { include: { operationalSnapshot: true, travellers: { orderBy: { sequence: 'asc' as const } }, redemption: true } }, evidence: { orderBy: [{ kind: 'asc' as const }, { versionNumber: 'desc' as const }] }, vouchers: { orderBy: { versionNumber: 'desc' as const } }, shares: { orderBy: { createdAt: 'desc' as const }, take: 20 } };

@Injectable()
export class FulfilmentService {
  constructor(private readonly prisma: PrismaService, private readonly storage: StorageService, private readonly audit: AuditService, private readonly outbox: OutboxService, private readonly readiness: FulfilmentReadinessService, private readonly generation: VoucherGenerationService) {}

  async vendorList(user: AuthUser, query: FulfilmentQueryDto = {}) { const tenantId = this.vendor(user); const rows: any[] = await this.prisma.bookingFulfilment.findMany({ where: { ...(query.status ? { status: query.status } : {}), ...(query.generationStatus ? { generationStatus: query.generationStatus } : {}), ...(query.mode ? { mode: query.mode } : {}), booking: { vendorTenantId: tenantId, recordType: 'CANONICAL', ...(query.serviceDate ? { serviceDate: new Date(query.serviceDate) } : {}) } }, include, orderBy: { updatedAt: 'desc' }, take: 300 }); return rows.map((row) => this.projection(row)); }
  async adminList(query: FulfilmentQueryDto = {}) { const rows: any[] = await this.prisma.bookingFulfilment.findMany({ where: { ...(query.status ? { status: query.status } : {}), ...(query.generationStatus ? { generationStatus: query.generationStatus } : {}), ...(query.mode ? { mode: query.mode } : {}), ...(query.vendorTenantId ? { booking: { vendorTenantId: query.vendorTenantId } } : {}), ...(query.serviceDate ? { booking: { ...(query.vendorTenantId ? { vendorTenantId: query.vendorTenantId } : {}), serviceDate: new Date(query.serviceDate) } } : {}) }, include, orderBy: { updatedAt: 'desc' }, take: 500 }); return rows.map((row) => this.projection(row)); }
  async vendorDetail(user: AuthUser, bookingId: string) { return this.projection(await this.loadVendor(user, bookingId)); }
  async adminDetail(bookingId: string) { const row = await this.prisma.bookingFulfilment.findUnique({ where: { bookingId }, include }); if (!row) throw new NotFoundException('Fulfilment not found'); return this.projection(row); }

  async addReference(user: AuthUser, bookingId: string, kind: FulfilmentEvidenceKind, dto: ReferenceEvidenceDto) { const reference = dto.referenceValue?.trim() || ''; if (!reference) throw new ConflictException(kind === FulfilmentEvidenceKind.PNR_REFERENCE ? 'PNR_REFERENCE_REQUIRED' : 'QR_TOKEN_REQUIRED'); if (!( [FulfilmentEvidenceKind.PNR_REFERENCE, FulfilmentEvidenceKind.QR_TOKEN] as string[]).includes(kind)) throw new ConflictException('EVIDENCE_FILE_REQUIRED'); return this.writeEvidence(user, bookingId, kind, reference, null, dto.travellerVisible ?? false); }
  async upload(user: AuthUser, bookingId: string, kind: FulfilmentEvidenceKind, file: any, dto: EvidenceUploadDto) { if (!( [FulfilmentEvidenceKind.TICKET_FILE, FulfilmentEvidenceKind.SUPPLIER_ATTACHMENT] as string[]).includes(kind)) throw new ConflictException('REFERENCE_EVIDENCE_REQUIRED'); const detected = this.detectFile(file); const saved = await this.storage.save(file.buffer, FilePurpose.FULFILMENT_DOCUMENT, detected.extension); try { return await this.writeEvidence(user, bookingId, kind, null, { ...saved, originalName: file.originalname || `fulfilment${detected.extension}`, mimeType: detected.mimeType }, dto.travellerVisible ?? false); } catch (error) { await this.storage.remove(saved.storageKey); throw error; } }
  async replaceReference(user: AuthUser, evidenceId: string, dto: ReferenceEvidenceDto & { kind: FulfilmentEvidenceKind }) { const current: any = await this.prisma.fulfilmentEvidence.findUnique({ where: { id: evidenceId }, include: { fulfilment: { include: { booking: true } } } }); if (!current) throw new NotFoundException('Fulfilment evidence not found'); if (current.kind !== dto.kind) throw new ConflictException('Evidence kind cannot change during replacement'); if (!( [FulfilmentEvidenceKind.PNR_REFERENCE, FulfilmentEvidenceKind.QR_TOKEN] as string[]).includes(dto.kind)) throw new ConflictException('EVIDENCE_FILE_REQUIRED'); const reference = dto.referenceValue?.trim() || ''; if (!reference) throw new ConflictException(dto.kind === FulfilmentEvidenceKind.PNR_REFERENCE ? 'PNR_REFERENCE_REQUIRED' : 'QR_TOKEN_REQUIRED'); return this.writeEvidence(user, current.fulfilment.bookingId, dto.kind, reference, null, dto.travellerVisible ?? current.travellerVisible, evidenceId); }
  async retryVendor(user: AuthUser, bookingId: string) { const row: any = await this.loadVendor(user, bookingId); return this.generation.retry(row.id, user); }
  async retryAdmin(user: AuthUser, bookingId: string) { const row: any = await this.prisma.bookingFulfilment.findUnique({ where: { bookingId }, include: { booking: true } }); if (!row) throw new NotFoundException('Fulfilment not found'); return this.generation.retry(row.id, user); }

  async voucher(user: AuthUser, bookingId: string) {
    const where: any = { id: bookingId, recordType: 'CANONICAL' }; if (user.role === UserRole.VENDOR) where.vendorTenantId = this.vendor(user); else if (user.role === UserRole.TRAVEL_AGENT) where.agentTenantId = user.tenantId; else if (![UserRole.ADMIN, UserRole.SUB_ADMIN].includes(user.role)) throw new ForbiddenException('Fulfilment access required');
    const booking: any = await this.prisma.booking.findFirst({ where, include: { operationalSnapshot: true, travellers: { orderBy: { sequence: 'asc' } }, fulfilment: { include: { evidence: { where: { status: FulfilmentEvidenceStatus.CURRENT } }, vouchers: { where: { status: VoucherVersionStatus.CURRENT }, include: { fileAsset: true } } } } } }); if (!booking) throw new NotFoundException('Booking not found');
    const fulfilment = booking.fulfilment; const readiness = fulfilment ? this.readiness.evaluate({ booking, fulfilment, evidence: fulfilment.evidence }) : { ready: false, reasonCodes: ['FULFILMENT_POLICY_SNAPSHOT_MISSING'], evidenceTrace: [] }; const current = fulfilment?.vouchers?.[0] ?? null; const terminal = [BookingStatus.CANCELLED, BookingStatus.VENDOR_REJECTED, BookingStatus.MANUAL_REJECTED, BookingStatus.CONFIRMATION_EXPIRED].includes(booking.status); const reason = terminal ? 'BOOKING_TERMINAL' : current ? undefined : fulfilment?.generationStatus === VoucherGenerationStatus.FAILED ? 'VOUCHER_GENERATION_FAILED' : readiness.ready ? 'VOUCHER_NOT_READY' : 'FULFILMENT_EVIDENCE_PENDING';
    const travellerEvidence = (fulfilment?.evidence ?? []).filter((item: any) => item.status === FulfilmentEvidenceStatus.CURRENT && item.travellerVisible).map((item: any) => ({ kind: item.kind, versionNumber: item.versionNumber, ...(item.referenceValue ? { referenceValue: item.referenceValue } : {}), ...(item.fileAssetId ? { fileId: item.fileAssetId } : {}) }));
    return { bookingCode: booking.bookingCode, readiness, reason, travellerEvidence, currentVoucher: current ? { id: current.id, version: current.versionNumber, voucherCode: current.voucherCode, generatedAt: current.generatedAt, fileId: current.fileAssetId, contentFingerprint: current.contentFingerprint } : null };
  }

  async share(user: AuthUser, bookingId: string, dto: VoucherShareDto) {
    if (user.role !== UserRole.TRAVEL_AGENT || !user.tenantId) throw new ForbiddenException('Agent voucher sharing required');
    const recipient = dto.recipient?.trim(); if (dto.channel === VoucherShareChannel.EMAIL && (!recipient || !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(recipient))) throw new ConflictException('VALID_EMAIL_RECIPIENT_REQUIRED'); if (dto.channel === VoucherShareChannel.WHATSAPP && (!recipient || !/^\+[1-9]\d{7,14}$/.test(recipient))) throw new ConflictException('VALID_E164_PHONE_REQUIRED'); if (dto.channel === VoucherShareChannel.DOWNLOAD && recipient) throw new ConflictException('DOWNLOAD_RECIPIENT_NOT_ALLOWED');
    const booking: any = await this.prisma.booking.findFirst({ where: { id: bookingId, agentTenantId: user.tenantId, recordType: 'CANONICAL' }, include: { fulfilment: { include: { vouchers: { where: { status: VoucherVersionStatus.CURRENT } } } } } }); if (!booking) throw new NotFoundException('Booking not found'); const voucher = booking.fulfilment?.vouchers?.[0]; if (!voucher || [BookingStatus.CANCELLED, BookingStatus.VENDOR_REJECTED, BookingStatus.MANUAL_REJECTED, BookingStatus.CONFIRMATION_EXPIRED].includes(booking.status)) throw new ConflictException(booking.status === BookingStatus.CANCELLED ? 'BOOKING_CANCELLED' : 'VOUCHER_NOT_READY');
    const queued = dto.channel !== VoucherShareChannel.DOWNLOAD; const recipientMasked = recipient ? `${recipient.slice(0, 2)}***${recipient.slice(-2)}` : null; const event = await this.prisma.$transaction(async (tx) => { const row = await tx.voucherShareEvent.create({ data: { bookingId, fulfilmentId: booking.fulfilment.id, voucherVersionId: voucher.id, channel: dto.channel, status: queued ? VoucherShareStatus.QUEUED : VoucherShareStatus.RECORDED, recipientMasked, actorUserId: user.sub } }); await this.audit.write(tx, { actor: user, tenantId: user.tenantId, action: 'VOUCHER_SHARED', entityType: 'VoucherVersion', entityId: voucher.id, metadata: { channel: dto.channel, shareEventId: row.id, status: row.status } }); if (queued) await this.outbox.enqueue(tx, { tenantId: user.tenantId, eventType: 'VOUCHER_SHARE_REQUESTED', aggregateType: 'VoucherShareEvent', aggregateId: row.id, payload: { bookingId, voucherVersionId: voucher.id, channel: dto.channel, recipientMasked } }); return row; }); return { status: event.status, shareEventId: event.id, voucherVersion: voucher.versionNumber };
  }

  async manifest(user: AuthUser, serviceDate: string, filters: { productId?: string; variantId?: string; scheduleId?: string; sessionId?: string } = {}) { const tenantId = this.vendor(user); const rows: any[] = await this.prisma.bookingFulfilment.findMany({ where: { booking: { vendorTenantId: tenantId, recordType: 'CANONICAL', serviceDate: new Date(serviceDate), status: { in: [BookingStatus.CONFIRMED, BookingStatus.REDEEMED, BookingStatus.COMPLETED] }, ...(filters.productId ? { productId: filters.productId } : {}), ...(filters.variantId ? { variantId: filters.variantId } : {}), ...(filters.sessionId ? { sessionId: filters.sessionId } : {}), ...(filters.scheduleId ? { session: { scheduleTemplateId: filters.scheduleId } } : {}) } }, include }); const sessions = new Map<string, any>(); for (const row of rows) { const snapshot: any = row.booking.operationalSnapshot; const session = snapshot?.sessionSnapshot ?? {}; const sessionKey = row.booking.sessionId ?? 'unscheduled'; if (!sessions.has(sessionKey)) sessions.set(sessionKey, { sessionId: row.booking.sessionId, localStartTime: session.localStartTime ?? null, timezone: session.timezone ?? row.booking.serviceTimezone, product: snapshot?.productSnapshot ?? {}, variant: snapshot?.variantSnapshot ?? {}, pickupGroups: [] }); const sessionGroup = sessions.get(sessionKey); const pickupKey = this.pickupIdentity(snapshot?.pickupSnapshot); let group = sessionGroup.pickupGroups.find((item: any) => item.key === pickupKey); if (!group) { group = { key: pickupKey, meetingPoint: snapshot?.pickupSnapshot ?? null, bookings: [] }; sessionGroup.pickupGroups.push(group); } group.bookings.push(this.manifestBooking(row)); } return { serviceDate, sessions: [...sessions.values()] }; }
  async manifestCsv(user: AuthUser, serviceDate: string, filters: any = {}) { const data = await this.manifest(user, serviceDate, filters); const headers = ['serviceDate', 'localStartTime', 'product', 'variant', 'session', 'bookingCode', 'pax', 'leadTravellerName', 'pickupMeetingPoint', 'pnr', 'voucherStatus', 'checkInStatus']; const lines = [headers.join(',')]; for (const session of data.sessions) for (const group of session.pickupGroups) for (const row of group.bookings) lines.push([serviceDate, session.localStartTime, session.product?.productName, session.variant?.name, session.sessionId, row.bookingCode, row.pax, row.leadTravellerName, JSON.stringify(row.meetingPoint ?? ''), row.pnrReference, row.voucherStatus, row.checkInStatus].map((value) => this.csv(value)).join(',')); return `${lines.join('\r\n')}\r\n`; }
  async checkIn(user: AuthUser, bookingId: string, notes?: string) { const tenantId = this.vendor(user); return this.prisma.$transaction(async (tx) => { const rows = await tx.$queryRawUnsafe<any[]>(`SELECT "id" FROM "public"."Booking" WHERE "id" = $1 FOR UPDATE`, bookingId); if (!rows[0]) throw new NotFoundException('Booking not found'); const booking: any = await tx.booking.findFirst({ where: { id: bookingId, vendorTenantId: tenantId, recordType: 'CANONICAL' }, include: { fulfilment: { include: { evidence: { where: { status: FulfilmentEvidenceStatus.CURRENT } }, vouchers: { where: { status: VoucherVersionStatus.CURRENT } } } }, operationalSnapshot: true, redemption: true } }); if (!booking) throw new NotFoundException('Booking not found'); if (booking.redemption) return booking.redemption; if (booking.status !== BookingStatus.CONFIRMED) throw new ConflictException(booking.status === BookingStatus.CANCELLED ? 'BOOKING_CANCELLED' : 'CHECKIN_REQUIRES_CONFIRMED'); const readiness = this.readiness.evaluate({ booking, fulfilment: booking.fulfilment, evidence: booking.fulfilment?.evidence ?? [] }); if (!readiness.ready) throw new ConflictException('FULFILMENT_NOT_READY_FOR_CHECKIN'); const redemption = await tx.bookingRedemption.create({ data: { bookingId, fulfilmentId: booking.fulfilment.id, voucherVersionId: booking.fulfilment.vouchers?.[0]?.id ?? null, method: RedemptionMethod.MANUAL, actorUserId: user.sub, notes: notes?.trim() || null } }); await tx.booking.update({ where: { id: bookingId }, data: { status: BookingStatus.REDEEMED, version: { increment: 1 } } }); await tx.bookingEvent.create({ data: { bookingId, eventType: 'BOOKING_REDEEMED', fromStatus: BookingStatus.CONFIRMED, toStatus: BookingStatus.REDEEMED, actorUserId: user.sub, actorRole: user.role, metadata: { redemptionId: redemption.id } } }); await this.audit.write(tx, { actor: user, tenantId, action: 'BOOKING_REDEEMED', entityType: 'BookingRedemption', entityId: redemption.id }); await this.outbox.enqueue(tx, { tenantId, eventType: 'BOOKING_REDEEMED', aggregateType: 'Booking', aggregateId: bookingId, payload: { bookingCode: booking.bookingCode } }); return redemption; }, { timeout: 30000, maxWait: 30000 }); }
  async complete(user: AuthUser, bookingId: string, dto: CompleteBookingDto) { const tenantId = this.vendor(user); return this.prisma.$transaction(async (tx) => { const rows = await tx.$queryRawUnsafe<any[]>(`SELECT "id" FROM "public"."Booking" WHERE "id" = $1 FOR UPDATE`, bookingId); if (!rows[0]) throw new NotFoundException('Booking not found'); const booking: any = await tx.booking.findFirst({ where: { id: bookingId, vendorTenantId: tenantId, recordType: 'CANONICAL' }, include: { operationalSnapshot: true } }); if (!booking) throw new NotFoundException('Booking not found'); if (booking.status !== BookingStatus.REDEEMED) throw new ConflictException('COMPLETION_REQUIRES_REDEEMED'); const session: any = booking.operationalSnapshot?.sessionSnapshot; const end = session?.endsAt ? new Date(session.endsAt) : null; if (end && new Date() < end) throw new ConflictException('SERVICE_NOT_ENDED'); if (!end && !dto.reason?.trim()) throw new ConflictException('COMPLETION_REASON_REQUIRED_WITHOUT_END_TIME'); const updated = await tx.booking.update({ where: { id: bookingId }, data: { status: BookingStatus.COMPLETED, version: { increment: 1 } } }); await tx.bookingEvent.create({ data: { bookingId, eventType: 'BOOKING_COMPLETED', fromStatus: BookingStatus.REDEEMED, toStatus: BookingStatus.COMPLETED, actorUserId: user.sub, actorRole: user.role, reason: dto.reason?.trim() || null } }); await this.audit.write(tx, { actor: user, tenantId, action: 'BOOKING_COMPLETED', entityType: 'Booking', entityId: bookingId, reason: dto.reason }); await this.outbox.enqueue(tx, { tenantId, eventType: 'BOOKING_COMPLETED', aggregateType: 'Booking', aggregateId: bookingId, payload: { bookingCode: booking.bookingCode } }); return updated; }, { timeout: 30000, maxWait: 30000 }); }

  private async writeEvidence(user: AuthUser, bookingId: string, kind: FulfilmentEvidenceKind, referenceValue: string | null, file: any, travellerVisible: boolean, replacementId?: string) {
    const tenantId = this.vendor(user);
    if (!validateEvidenceShape(kind, referenceValue, file ? 'uploaded' : null).valid) throw new ConflictException(kind === FulfilmentEvidenceKind.PNR_REFERENCE ? 'PNR_REFERENCE_REQUIRED' : kind === FulfilmentEvidenceKind.QR_TOKEN ? 'QR_TOKEN_REQUIRED' : 'EVIDENCE_FILE_REQUIRED');
    return this.prisma.$transaction(async (tx) => {
      const ownership: any = await tx.bookingFulfilment.findUnique({ where: { bookingId }, select: { id: true, booking: { select: { id: true, vendorTenantId: true, status: true } } } });
      if (!ownership || ownership.booking.vendorTenantId !== tenantId) throw new NotFoundException('Fulfilment not found');
      if ([BookingStatus.CANCELLED, BookingStatus.VENDOR_REJECTED, BookingStatus.MANUAL_REJECTED, BookingStatus.CONFIRMATION_EXPIRED].includes(ownership.booking.status)) throw new ConflictException('BOOKING_TERMINAL');
      await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "public"."BookingFulfilment" WHERE "id" = ${ownership.id} FOR UPDATE`);
      const fulfilment: any = await tx.bookingFulfilment.findUnique({ where: { id: ownership.id }, include: { booking: { include: { operationalSnapshot: true } }, evidence: true, vouchers: { where: { status: VoucherVersionStatus.CURRENT } } } });
      if (!fulfilment) throw new NotFoundException('Fulfilment not found');
      const current = fulfilment.evidence.find((item: any) => item.kind === kind && item.status === FulfilmentEvidenceStatus.CURRENT);
      const versionNumber = (fulfilment.evidence.filter((item: any) => item.kind === kind).reduce((max: number, item: any) => Math.max(max, item.versionNumber), 0) || 0) + 1;
      if (current) await tx.fulfilmentEvidence.update({ where: { id: current.id }, data: { status: FulfilmentEvidenceStatus.SUPERSEDED, supersededAt: new Date() } });
      const evidence = await tx.fulfilmentEvidence.create({ data: { fulfilmentId: fulfilment.id, kind, versionNumber, status: FulfilmentEvidenceStatus.CURRENT, referenceValue: referenceValue?.trim() || null, fileAssetId: file ? undefined : null, travellerVisible: Boolean(travellerVisible && kind !== FulfilmentEvidenceKind.SUPPLIER_ATTACHMENT), replacesEvidenceId: replacementId ?? current?.id ?? null, createdById: user.sub } });
      if (file) { const asset = await tx.fileAsset.create({ data: { tenantId, storageKey: file.storageKey, originalName: file.originalName, mimeType: file.mimeType, sizeBytes: file.sizeBytes, visibility: FileVisibility.PRIVATE, purpose: FilePurpose.FULFILMENT_DOCUMENT, entityType: 'FulfilmentEvidence', entityId: evidence.id, createdById: user.sub } }); await tx.fulfilmentEvidence.update({ where: { id: evidence.id }, data: { fileAssetId: asset.id } }); }
      const allEvidence = await tx.fulfilmentEvidence.findMany({ where: { fulfilmentId: fulfilment.id } }); const readiness = this.readiness.evaluate({ booking: fulfilment.booking, fulfilment, evidence: allEvidence });
      if (fulfilment.vouchers.length) await tx.voucherVersion.updateMany({ where: { fulfilmentId: fulfilment.id, status: VoucherVersionStatus.CURRENT }, data: { status: VoucherVersionStatus.SUPERSEDED, supersededAt: new Date() } });
      const nextStatus = readiness.ready ? BookingFulfilmentStatus.READY_FOR_VOUCHER : BookingFulfilmentStatus.WAITING_EVIDENCE; const updated = await tx.bookingFulfilment.update({ where: { id: fulfilment.id }, data: { status: nextStatus, generationStatus: readiness.ready ? VoucherGenerationStatus.PENDING : VoucherGenerationStatus.NOT_REQUESTED, generationRequestedAt: readiness.ready ? new Date() : null, generationToken: null, generationClaimedAt: null, generationLeaseExpiresAt: null, lastGenerationError: null, version: { increment: 1 } } });
      const action = current ? 'FULFILMENT_EVIDENCE_REPLACED' : 'FULFILMENT_EVIDENCE_ADDED'; await this.audit.write(tx, { actor: user, tenantId, action, entityType: 'FulfilmentEvidence', entityId: evidence.id, metadata: { kind, versionNumber, travellerVisible: evidence.travellerVisible } }); await this.outbox.enqueue(tx, { tenantId: fulfilment.booking.vendorTenantId, eventType: 'FULFILMENT_EVIDENCE_RECEIVED', aggregateType: 'FulfilmentEvidence', aggregateId: evidence.id, payload: { bookingId, kind, versionNumber } }); if (readiness.ready) await this.outbox.enqueue(tx, { tenantId: fulfilment.booking.vendorTenantId, eventType: 'VOUCHER_GENERATION_REQUESTED', aggregateType: 'BookingFulfilment', aggregateId: fulfilment.id, payload: { bookingId, reason: current ? 'evidence replaced' : 'evidence complete' } });
      return { fulfilment: updated, evidence: await tx.fulfilmentEvidence.findUniqueOrThrow({ where: { id: evidence.id } }) };
    }, { timeout: 30000, maxWait: 30000 });
  }
  private async loadVendor(user: AuthUser, bookingId: string) { const tenantId = this.vendor(user); const row: any = await this.prisma.bookingFulfilment.findFirst({ where: { bookingId, booking: { vendorTenantId: tenantId, recordType: 'CANONICAL' } }, include }); if (!row) throw new NotFoundException('Fulfilment not found'); return row; }
  private projection(row: any) { const readiness = this.readiness.evaluate({ booking: row.booking, fulfilment: row, evidence: row.evidence }); return { id: row.id, bookingId: row.bookingId, bookingCode: row.booking.bookingCode, status: row.status, mode: row.mode, generationStatus: row.generationStatus, generationAttempts: row.generationAttempts, lastGenerationError: row.lastGenerationError, readiness, evidence: row.evidence.map((item: any) => ({ id: item.id, kind: item.kind, versionNumber: item.versionNumber, status: item.status, referenceValue: item.referenceValue, fileAssetId: item.fileAssetId, travellerVisible: item.travellerVisible, createdAt: item.createdAt })), vouchers: row.vouchers.map((item: any) => ({ id: item.id, version: item.versionNumber, status: item.status, voucherCode: item.voucherCode, fileId: item.fileAssetId, generatedAt: item.generatedAt })), booking: { serviceDate: row.booking.serviceDate, status: row.booking.status, pax: row.booking.pax, snapshot: row.booking.operationalSnapshot } }; }
  private manifestBooking(row: any) { const currentEvidence = row.evidence.filter((item: any) => item.status === FulfilmentEvidenceStatus.CURRENT); const readiness = this.readiness.evaluate({ booking: row.booking, fulfilment: row, evidence: currentEvidence }); const pnr = currentEvidence.find((item: any) => item.kind === FulfilmentEvidenceKind.PNR_REFERENCE && item.travellerVisible); const currentVoucher = row.vouchers.find((item: any) => item.status === VoucherVersionStatus.CURRENT); return { bookingCode: row.booking.bookingCode, pax: row.booking.pax, leadTravellerName: row.booking.travellers.find((item: any) => item.isLead)?.fullName ?? null, meetingPoint: row.booking.operationalSnapshot?.pickupSnapshot ?? null, fulfilmentStatus: row.status, fulfilmentReadiness: readiness, pnrReference: pnr?.referenceValue ?? null, voucherStatus: currentVoucher ? 'READY' : row.generationStatus, voucherVersion: currentVoucher?.versionNumber ?? null, checkInStatus: row.booking.redemption ? 'REDEEMED' : row.booking.status }; }
  private pickupIdentity(pickup: any) { return pickup ? JSON.stringify({ type: pickup.type ?? null, label: pickup.label ?? pickup.name ?? pickup.address ?? null, address: pickup.address ?? null }) : 'COMMON_MEETING_POINT'; }
  private csv(value: unknown) { const text = value == null ? '' : String(value); return /[",\r\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text; }
  private vendor(user: AuthUser) { if (user.role !== UserRole.VENDOR || !user.tenantId) throw new ForbiddenException('Vendor fulfilment access required'); return user.tenantId; }
  private detectFile(file: any) { if (!file?.buffer?.length) throw new ConflictException('A file is required'); if (file.size > 10 * 1024 * 1024) throw new ConflictException('Fulfilment files must be 10 MB or smaller'); const b = file.buffer; const detected = b.subarray(0, 5).toString() === '%PDF-' ? { mimeType: 'application/pdf', extension: '.pdf' } : b[0] === 0xff && b[1] === 0xd8 && b[2] === 0xff ? { mimeType: 'image/jpeg', extension: '.jpg' } : b.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a])) ? { mimeType: 'image/png', extension: '.png' } : null; if (!detected || (file.mimetype && file.mimetype !== detected.mimeType)) throw new ConflictException('Unsupported or spoofed fulfilment file; valid PDF, JPEG, or PNG required'); return detected; }
}
