CREATE UNIQUE INDEX "SupplierQualityMetricRule_policyId_metricCode_key" ON "SupplierQualityMetricRule"("policyId", "metricCode");
CREATE UNIQUE INDEX "SupplierTierRule_policyId_tier_key" ON "SupplierTierRule"("policyId", "tier");
CREATE UNIQUE INDEX "SupplierQualitySnapshot_snapshotKey_key" ON "SupplierQualitySnapshot"("snapshotKey");
CREATE UNIQUE INDEX "SupplierQualityMetricSnapshot_snapshotId_metricCode_key" ON "SupplierQualityMetricSnapshot"("snapshotId", "metricCode");
CREATE UNIQUE INDEX "SupplierTierAssignment_current_vendor_key" ON "SupplierTierAssignment"("vendorTenantId") WHERE "effectiveTo" IS NULL;
CREATE UNIQUE INDEX "SupplierQualityIssue_open_vendor_metric_key" ON "SupplierQualityIssue"("vendorTenantId", "metricCode") WHERE "status" IN ('OPEN','ACKNOWLEDGED');
CREATE INDEX "SupplierQualityPolicy_status_idx" ON "SupplierQualityPolicy"("status");
CREATE INDEX "SupplierQualityPolicy_activatedAt_idx" ON "SupplierQualityPolicy"("activatedAt");
CREATE INDEX "SupplierQualityMetricRule_policyId_enabled_rank_idx" ON "SupplierQualityMetricRule"("policyId", "enabled", "rank");
CREATE INDEX "SupplierTierRule_policyId_minimumScore_idx" ON "SupplierTierRule"("policyId", "minimumScore");
CREATE INDEX "SupplierQualitySnapshot_vendorTenantId_generatedAt_idx" ON "SupplierQualitySnapshot"("vendorTenantId", "generatedAt");
CREATE INDEX "SupplierQualitySnapshot_vendorTenantId_windowStart_windowEnd_idx" ON "SupplierQualitySnapshot"("vendorTenantId", "windowStart", "windowEnd");
CREATE INDEX "SupplierQualityMetricSnapshot_metricCode_status_idx" ON "SupplierQualityMetricSnapshot"("metricCode", "status");
CREATE INDEX "SupplierTierAssignment_vendorTenantId_effectiveFrom_idx" ON "SupplierTierAssignment"("vendorTenantId", "effectiveFrom");
CREATE INDEX "SupplierTierAssignment_vendorTenantId_effectiveTo_idx" ON "SupplierTierAssignment"("vendorTenantId", "effectiveTo");
CREATE INDEX "SupplierQualityIssue_vendorTenantId_status_createdAt_idx" ON "SupplierQualityIssue"("vendorTenantId", "status", "createdAt");
CREATE INDEX "SupplierQualityIssue_metricCode_status_idx" ON "SupplierQualityIssue"("metricCode", "status");
ALTER TABLE "SupplierQualityMetricRule" ADD CONSTRAINT "SupplierQualityMetricRule_policyId_fkey" FOREIGN KEY ("policyId") REFERENCES "SupplierQualityPolicy"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SupplierTierRule" ADD CONSTRAINT "SupplierTierRule_policyId_fkey" FOREIGN KEY ("policyId") REFERENCES "SupplierQualityPolicy"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SupplierQualitySnapshot" ADD CONSTRAINT "SupplierQualitySnapshot_policyId_fkey" FOREIGN KEY ("policyId") REFERENCES "SupplierQualityPolicy"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "SupplierQualityMetricSnapshot" ADD CONSTRAINT "SupplierQualityMetricSnapshot_snapshotId_fkey" FOREIGN KEY ("snapshotId") REFERENCES "SupplierQualitySnapshot"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "SupplierQualityIssue" ADD CONSTRAINT "SupplierQualityIssue_snapshotId_fkey" FOREIGN KEY ("snapshotId") REFERENCES "SupplierQualitySnapshot"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
