"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { apiRequest } from "@/services/apiClient";
import { listCustomers, type CustomerRecord } from "@/services/customerService";
import type { PaginationMeta } from "@/types/api";
import { DataTable } from "@/components/table/DataTable";
import { PaginationControls } from "@/components/table/PaginationControls";
import { EmptyState, ErrorPanel, LoadingTable } from "@/components/feedback/Feedback";

const initialMeta: PaginationMeta = { page: 1, pageSize: 25, totalItems: 0, totalPages: 1, hasNextPage: false, hasPreviousPage: false };

export function CustomerList() {
  const [rows, setRows] = useState<CustomerRecord[]>([]); const [search, setSearch] = useState(""); const [country, setCountry] = useState(""); const [status, setStatus] = useState(""); const [sortBy, setSortBy] = useState("name"); const [sortOrder, setSortOrder] = useState<"asc" | "desc">("asc"); const [page, setPage] = useState(1); const [meta, setMeta] = useState(initialMeta); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  useEffect(() => { const params = new URLSearchParams(window.location.search); setSearch(params.get("search") ?? ""); setCountry(params.get("country") ?? ""); setStatus(params.get("status") ?? ""); setSortBy(params.get("sortBy") ?? "name"); setSortOrder(params.get("sortOrder") === "desc" ? "desc" : "asc"); setPage(Math.max(1, Number(params.get("page") ?? "1"))); const size = Number(params.get("pageSize") ?? "25"); if ([10, 25, 50, 100].includes(size)) setMeta((current) => ({ ...current, pageSize: size })); }, []);
  const syncUrl = useCallback((next: Partial<{ page: number; pageSize: number; search: string; country: string; status: string; sortBy: string; sortOrder: "asc" | "desc" }>) => { const value = { page, pageSize: meta.pageSize, search, country, status, sortBy, sortOrder, ...next }; const params = new URLSearchParams({ page: String(value.page), pageSize: String(value.pageSize), sortBy: value.sortBy, sortOrder: value.sortOrder }); for (const [key, item] of Object.entries({ search: value.search, country: value.country, status: value.status })) if (item) params.set(key, item); window.history.replaceState(null, "", `${window.location.pathname}?${params}`); }, [country, meta.pageSize, page, search, sortBy, sortOrder, status]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const params = new URLSearchParams({ page: String(page), pageSize: String(meta.pageSize), sortBy, sortOrder }); for (const [key, value] of Object.entries({ search, country, status })) if (value) params.set(key, value); const result = await listCustomers(params.toString()); setRows(result.data); setMeta(result.meta); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load customers"); } finally { setLoading(false); } }, [country, meta.pageSize, page, search, sortBy, sortOrder, status]);
  useEffect(() => { void load(); }, [load]);
  const archive = async (id: string) => { if (!window.confirm("Archive this customer?")) return; try { await apiRequest(`/customers/${id}`, { method: "DELETE" }); setMessage("Customer archived"); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to archive customer"); } };
  const update = (key: "search" | "country" | "status", value: string) => { setPage(1); if (key === "search") setSearch(value); if (key === "country") setCountry(value); if (key === "status") setStatus(value); syncUrl({ page: 1, [key]: value }); };
  const clear = () => { setSearch(""); setCountry(""); setStatus(""); setPage(1); syncUrl({ page: 1, search: "", country: "", status: "" }); };
  return <div><div className="page-heading"><div><p className="eyebrow">BOOKINGS / CUSTOMERS</p><h2>Customers</h2><p className="subtext">Manage profiles and booking history.</p></div><Link className="primary button-link" href="/customers/new">Create customer</Link></div>{message && <p className="notice success" role="status">{message}</p>}<section className="panel"><div className="toolbar"><input aria-label="Search customers" placeholder="Search name, email or phone..." value={search} onChange={(event) => update("search", event.target.value)} /><input aria-label="Filter customers country" placeholder="Country" value={country} onChange={(event) => update("country", event.target.value)} /><select aria-label="Filter customers status" value={status} onChange={(event) => update("status", event.target.value)}><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option><option value="ARCHIVED">Archived</option></select><select aria-label="Sort customers" value={sortBy} onChange={(event) => { setSortBy(event.target.value); setPage(1); syncUrl({ page: 1, sortBy: event.target.value }); }}><option value="name">Name</option><option value="email">Email</option><option value="createdAt">Created date</option></select><select aria-label="Sort direction customers" value={sortOrder} onChange={(event) => { const value = event.target.value as "asc" | "desc"; setSortOrder(value); setPage(1); syncUrl({ page: 1, sortOrder: value }); }}><option value="asc">Ascending</option><option value="desc">Descending</option></select><button type="button" onClick={clear}>Clear filters</button></div>{loading ? <LoadingTable /> : error ? <ErrorPanel message={error} onRetry={() => void load()} /> : rows.length === 0 ? <EmptyState title="No customers found" /> : <DataTable rows={rows} columns={[{ key: "name", label: "Customer", render: (row) => <><strong>{row.name}</strong><small>{row.email}</small></> }, { key: "country", label: "Country", render: (row) => row.country ?? "—" }, { key: "bookings", label: "Bookings", render: (row) => row._count?.bookings ?? 0 }, { key: "totalSpent", label: "Total spent", render: (row) => `${((row.totalSpentMinor ?? 0) / 100).toFixed(2)} INR` }, { key: "lastBooking", label: "Last booking", render: (row) => row.lastBookingAt ? new Date(row.lastBookingAt).toLocaleDateString() : "—" }, { key: "status", label: "Status", render: (row) => <span className="status confirmed">{row.status ?? "ACTIVE"}</span> }]} actions={(row) => <><Link href={`/customers/${row.id}`}>View</Link><Link href={`/customers/${row.id}/edit`}>Edit</Link><button type="button" onClick={() => void archive(row.id)}>Archive</button></>} />}{!loading && !error && <PaginationControls meta={meta} onPageChange={(nextPage) => { setPage(nextPage); syncUrl({ page: nextPage }); }} onPageSizeChange={(size) => { setPage(1); setMeta((current) => ({ ...current, pageSize: size })); syncUrl({ page: 1, pageSize: size }); }} />}</section></div>;
}
