import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { Prisma, ResourceAllocationMode, SessionStatus } from '@prisma/client';
import { AuditService } from '../audit/audit.service';
import { AuthUser } from '../common/auth.types';
import { requireTenant } from '../common/tenant';
import { OutboxService } from '../outbox/outbox.service';
import { PrismaService } from '../prisma/prisma.service';
import { ResourceDto, SessionResourceAllocationDto, UpdateResourceDto } from './resources.dto';

type DbClient = PrismaService | Prisma.TransactionClient;

@Injectable()
export class ResourcesService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService, private readonly outbox: OutboxService) {}

  list(user: AuthUser) { return this.prisma.resource.findMany({ where: { tenantId: requireTenant(user) }, orderBy: { resourceCode: 'asc' } }); }

  async create(user: AuthUser, dto: ResourceDto) { const tenantId = requireTenant(user); this.validate(dto); return this.prisma.$transaction(async (tx) => { const resource = await tx.resource.create({ data: { tenantId, resourceCode: dto.resourceCode.trim(), name: dto.name.trim(), type: dto.type, allocationMode: dto.allocationMode, capacity: dto.capacity } }); await this.audit.write(tx, { actor: user, tenantId, action: 'RESOURCE_CREATED', entityType: 'Resource', entityId: resource.id, afterState: resource }); await this.outbox.enqueue(tx, { tenantId, eventType: 'RESOURCE_CREATED', aggregateType: 'Resource', aggregateId: resource.id, payload: { resourceCode: resource.resourceCode } }); return resource; }).catch((error) => { if (error?.code === 'P2002') throw new ConflictException('A resource with this resourceCode already exists'); throw error; }); }

  async update(user: AuthUser, id: string, dto: UpdateResourceDto) {
    const tenantId = requireTenant(user); if (dto.expectedVersion == null) throw new ConflictException('Resource expectedVersion is required');
    return this.prisma.$transaction(async (tx) => { const resource = await this.lockResource(tx, id, tenantId); if (resource.archivedAt) throw new ConflictException('Archived resources are immutable'); if (resource.version !== dto.expectedVersion) throw new ConflictException('Resource changed; reload and retry.'); const nextMode = dto.allocationMode ?? resource.allocationMode; const nextCapacity = dto.capacity !== undefined ? dto.capacity : resource.capacity; this.validate({ allocationMode: nextMode, capacity: nextCapacity }); if ((dto.type && dto.type !== resource.type) || (dto.allocationMode && dto.allocationMode !== resource.allocationMode)) { const [requirements, allocations] = await Promise.all([tx.scheduleResourceRequirement.count({ where: { specificResourceId: id } }), tx.sessionResourceAllocation.count({ where: { resourceId: id } })]); if (requirements || allocations) throw new ConflictException('RESOURCE_TYPE_OR_MODE_IMMUTABLE'); } if (dto.capacity !== undefined && dto.capacity !== resource.capacity) await this.assertCapacityFits(tx, id, dto.capacity); const result = await tx.resource.updateMany({ where: { id, tenantId, version: dto.expectedVersion }, data: { ...(dto.name !== undefined ? { name: dto.name.trim() } : {}), ...(dto.type !== undefined ? { type: dto.type } : {}), ...(dto.allocationMode !== undefined ? { allocationMode: dto.allocationMode } : {}), ...(dto.capacity !== undefined ? { capacity: dto.capacity } : {}), ...(dto.active !== undefined ? { active: dto.active } : {}), version: { increment: 1 } } }); if (result.count !== 1) throw new ConflictException('Resource changed; reload and retry.'); const saved = await tx.resource.findUniqueOrThrow({ where: { id } }); await this.audit.write(tx, { actor: user, tenantId, action: 'RESOURCE_UPDATED', entityType: 'Resource', entityId: id, beforeState: resource, afterState: saved }); await this.outbox.enqueue(tx, { tenantId, eventType: 'RESOURCE_UPDATED', aggregateType: 'Resource', aggregateId: id, payload: { version: saved.version } }); return saved; });
  }

  async archive(user: AuthUser, id: string, expectedVersion?: number) { const tenantId = requireTenant(user); if (expectedVersion == null) throw new ConflictException('Resource expectedVersion is required'); return this.prisma.$transaction(async (tx) => { const resource = await this.lockResource(tx, id, tenantId); if (resource.archivedAt) throw new ConflictException('Resource is already archived'); if (resource.version !== expectedVersion) throw new ConflictException('Resource changed; reload and retry.'); const saved = await tx.resource.update({ where: { id }, data: { active: false, archivedAt: new Date(), version: { increment: 1 } } }); await this.audit.write(tx, { actor: user, tenantId, action: 'RESOURCE_ARCHIVED', entityType: 'Resource', entityId: id, beforeState: resource, afterState: saved }); await this.outbox.enqueue(tx, { tenantId, eventType: 'RESOURCE_ARCHIVED', aggregateType: 'Resource', aggregateId: id, payload: {} }); return saved; }); }

  async requirements(user: AuthUser, scheduleId: string) { const tenantId = requireTenant(user); const schedule = await this.prisma.scheduleTemplate.findFirst({ where: { id: scheduleId, variant: { product: { tenantId } } } }); if (!schedule) throw new NotFoundException('Schedule not found'); return this.prisma.scheduleResourceRequirement.findMany({ where: { scheduleTemplateId: scheduleId }, include: { specificResource: true }, orderBy: { createdAt: 'asc' } }); }
  async sessionResources(user: AuthUser, sessionId: string) { const tenantId = requireTenant(user); const session = await this.prisma.serviceSession.findFirst({ where: { id: sessionId, scheduleTemplate: { variant: { product: { tenantId } } } } }); if (!session) throw new NotFoundException('Session not found'); return this.prisma.sessionResourceAllocation.findMany({ where: { sessionId }, include: { resource: true }, orderBy: { createdAt: 'asc' } }); }

  async allocate(user: AuthUser, sessionId: string, dto: SessionResourceAllocationDto) {
    const tenantId = requireTenant(user);
    return this.prisma.$transaction(async (tx) => { const session = await tx.serviceSession.findFirst({ where: { id: sessionId, scheduleTemplate: { variant: { product: { tenantId } } } }, include: { scheduleTemplate: { include: { resourceRequirements: { where: { active: true, archivedAt: null } } } } } }); if (!session) throw new NotFoundException('Session not found'); const resource = await this.lockResource(tx, dto.resourceId, tenantId); this.assertResource(resource, session, dto.quantity); const existing = await tx.sessionResourceAllocation.findUnique({ where: { sessionId_resourceId: { sessionId, resourceId: resource.id } } }); const other = await tx.sessionResourceAllocation.findMany({ where: { resourceId: resource.id, status: 'ACTIVE', sessionId: { not: sessionId }, session: { startsAt: { lt: session.endsAt! }, endsAt: { gt: session.startsAt! }, status: { notIn: [SessionStatus.ARCHIVED] } } }, include: { session: true } }); const overlapQuantity = other.reduce((sum, allocation) => sum + allocation.quantity, 0); if (resource.allocationMode === ResourceAllocationMode.EXCLUSIVE && other.length) throw new ConflictException('RESOURCE_EXCLUSIVE_OVERLAP'); if (resource.allocationMode !== ResourceAllocationMode.EXCLUSIVE && resource.capacity != null && overlapQuantity + dto.quantity > resource.capacity) throw new ConflictException('RESOURCE_CAPACITY_EXCEEDED'); const allocation = existing ? await tx.sessionResourceAllocation.update({ where: { id: existing.id }, data: { quantity: dto.quantity, status: 'ACTIVE', releasedAt: null, version: { increment: 1 } } }) : await tx.sessionResourceAllocation.create({ data: { sessionId, resourceId: resource.id, quantity: dto.quantity } }); await this.audit.write(tx, { actor: user, tenantId, action: 'SESSION_RESOURCE_ALLOCATED', entityType: 'SessionResourceAllocation', entityId: allocation.id, metadata: { sessionId, resourceId: resource.id, quantity: dto.quantity } }); await this.outbox.enqueue(tx, { tenantId, eventType: 'SESSION_RESOURCE_ALLOCATED', aggregateType: 'ServiceSession', aggregateId: sessionId, payload: { resourceId: resource.id, quantity: dto.quantity } }); return allocation; });
  }

  async releaseAllocation(user: AuthUser, sessionId: string, resourceId: string) { const tenantId = requireTenant(user); return this.prisma.$transaction(async (tx) => { const session = await tx.serviceSession.findFirst({ where: { id: sessionId, scheduleTemplate: { variant: { product: { tenantId } } } } }); if (!session) throw new NotFoundException('Session not found'); const allocation = await tx.sessionResourceAllocation.findUnique({ where: { sessionId_resourceId: { sessionId, resourceId } } }); if (!allocation) throw new NotFoundException('Session resource allocation not found'); if (allocation.status === 'RELEASED') return allocation; const saved = await tx.sessionResourceAllocation.update({ where: { id: allocation.id }, data: { status: 'RELEASED', releasedAt: new Date(), version: { increment: 1 } } }); await this.audit.write(tx, { actor: user, tenantId, action: 'SESSION_RESOURCE_RELEASED', entityType: 'SessionResourceAllocation', entityId: allocation.id, beforeState: allocation, afterState: saved }); await this.outbox.enqueue(tx, { tenantId, eventType: 'SESSION_RESOURCE_RELEASED', aggregateType: 'ServiceSession', aggregateId: sessionId, payload: { resourceId } }); return saved; }); }

  async resourceReadiness(sessionId: string, client: DbClient = this.prisma) {
    const session = await client.serviceSession.findUnique({ where: { id: sessionId }, include: { scheduleTemplate: { include: { resourceRequirements: { where: { required: true, active: true, archivedAt: null } }, variant: { include: { product: true } } } }, resourceAllocations: { where: { status: 'ACTIVE' }, include: { resource: true } } } }); if (!session) return { ready: false, reasonCodes: ['SESSION_NOT_FOUND'] }; if (session.startsAt && session.endsAt && session.endsAt <= session.startsAt) return { ready: false, reasonCodes: ['SESSION_TIME_INVALID'] }; const tenantId = session.scheduleTemplate.variant.product.tenantId; const reasonCodes: string[] = [];
    for (const requirement of session.scheduleTemplate.resourceRequirements) { if (requirement.specificResourceId) { const resource = await client.resource.findUnique({ where: { id: requirement.specificResourceId } }); if (!resource || resource.tenantId !== tenantId || resource.type !== requirement.resourceType || !resource.active || resource.archivedAt) reasonCodes.push('RESOURCE_ARCHIVED'); } const candidates = session.resourceAllocations.filter((allocation) => allocation.resource.tenantId === tenantId && allocation.resource.type === requirement.resourceType && (!requirement.specificResourceId || allocation.resourceId === requirement.specificResourceId)); if (candidates.reduce((sum, allocation) => sum + allocation.quantity, 0) < requirement.quantity) reasonCodes.push('RESOURCE_REQUIREMENT_UNASSIGNED'); for (const allocation of candidates) { const resource = allocation.resource; if (!resource.active || resource.archivedAt) reasonCodes.push('RESOURCE_ARCHIVED'); if (session.startsAt && session.endsAt) { const overlaps = await client.sessionResourceAllocation.findMany({ where: { resourceId: resource.id, status: 'ACTIVE', sessionId: { not: session.id }, session: { startsAt: { lt: session.endsAt }, endsAt: { gt: session.startsAt } } } }); if (resource.allocationMode === ResourceAllocationMode.EXCLUSIVE && overlaps.length) reasonCodes.push('RESOURCE_CAPACITY_EXCEEDED'); if (resource.allocationMode !== ResourceAllocationMode.EXCLUSIVE && resource.capacity != null && overlaps.reduce((sum, item) => sum + item.quantity, 0) + allocation.quantity > resource.capacity) reasonCodes.push('RESOURCE_CAPACITY_EXCEEDED'); } } }
    return { ready: reasonCodes.length === 0, reasonCodes: [...new Set(reasonCodes)] };
  }

  private async lockResource(tx: Prisma.TransactionClient, id: string, tenantId: string) { const rows = await tx.$queryRawUnsafe<any[]>(`SELECT * FROM "Resource" WHERE "id" = $1 AND "tenantId" = $2 FOR UPDATE`, id, tenantId); if (!rows[0]) throw new NotFoundException('Resource not found'); return rows[0]; }
  private assertResource(resource: any, session: any, quantity: number) { if (!resource || resource.archivedAt || !resource.active) throw new ConflictException('RESOURCE_ARCHIVED'); if (quantity < 1) throw new ConflictException('RESOURCE_QUANTITY_INVALID'); if (resource.allocationMode !== ResourceAllocationMode.EXCLUSIVE && (resource.capacity == null || resource.capacity <= 0)) throw new ConflictException('RESOURCE_CAPACITY_EXCEEDED'); if (!session.startsAt || !session.endsAt || session.endsAt <= session.startsAt) throw new ConflictException('SESSION_TIME_INVALID'); }
  private validate(dto: { allocationMode?: ResourceAllocationMode; capacity?: number | null }) { const bounded = dto.allocationMode === ResourceAllocationMode.SHARED || dto.allocationMode === ResourceAllocationMode.CAPACITY; if (bounded && (!dto.capacity || dto.capacity < 1)) throw new ConflictException('SHARED/CAPACITY resources require a positive capacity'); if (dto.capacity != null && dto.capacity < 1) throw new ConflictException('Resource capacity must be positive'); }
  private async assertCapacityFits(tx: Prisma.TransactionClient, resourceId: string, capacity: number) { const allocations = await tx.sessionResourceAllocation.findMany({ where: { resourceId, status: 'ACTIVE' }, include: { session: true } }); for (const allocation of allocations) { const overlaps = allocations.filter((other) => other.id !== allocation.id && other.session.startsAt && other.session.endsAt && allocation.session.startsAt && allocation.session.endsAt && other.session.startsAt < allocation.session.endsAt && other.session.endsAt > allocation.session.startsAt); const sum = overlaps.reduce((total, other) => total + other.quantity, 0) + allocation.quantity; if (sum > capacity) throw new ConflictException('RESOURCE_CAPACITY_EXCEEDED'); } }
}
