import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { createHash, randomUUID } from 'crypto';
import { FinancialEventStatus, FinancialEventType, PaymentCollectionMode, PayoutAttemptStatus, PayoutRecordType, PayoutStatus, Prisma, SettlementAllocationStatus, SettlementBatchStatus, SettlementEligibilityTrigger, SettlementHoldScope, SettlementHoldStatus, UserRole } from '@prisma/client';
import { AuditService } from '../audit/audit.service';
import { AuthUser } from '../common/auth.types';
import { requireTenant } from '../common/tenant';
import { OutboxService } from '../outbox/outbox.service';
import { PrismaService } from '../prisma/prisma.service';
import { CancellationResolutionDto, FailPayoutDto, FinanceConfigurationDto, ReconcilePayoutDto, ReleasePayoutDto, SettlementBatchDto, SettlementHoldDto, SettlementPreviewDto, VendorAdjustmentDto, VendorSettlementPolicyDto } from './finance.dto';

const settlementTypes = [FinancialEventType.BOOKING_CONFIRMED, FinancialEventType.VENDOR_ADJUSTMENT];

@Injectable()
export class FinanceService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService, private readonly outbox: OutboxService) {}

  configuration() { return this.prisma.financeConfiguration.upsert({ where: { id: 'default' }, update: {}, create: { id: 'default' } }); }
  async updateConfiguration(user: AuthUser, dto: FinanceConfigurationDto) {
    const current = await this.configuration();
    if (dto.expectedVersion && dto.expectedVersion !== current.version) throw new ConflictException('FINANCE_CONFIGURATION_VERSION_MISMATCH');
    const updated = await this.prisma.financeConfiguration.update({ where: { id: 'default' }, data: { paymentCollectionMode: dto.paymentCollectionMode, baseCurrency: dto.baseCurrency?.trim().toUpperCase() || current.baseCurrency, version: { increment: 1 }, updatedById: user.sub } });
    await this.audit.write(this.prisma, { actor: user, action: 'FINANCE_CONFIGURATION_UPDATED', entityType: 'FinanceConfiguration', entityId: 'default', afterState: updated });
    return updated;
  }
  policies() { return this.prisma.vendorSettlementPolicy.findMany({ orderBy: { createdAt: 'asc' } }); }
  async updatePolicy(user: AuthUser, vendorTenantId: string, dto: VendorSettlementPolicyDto) {
    await this.vendor(vendorTenantId);
    const existing = await this.prisma.vendorSettlementPolicy.findUnique({ where: { vendorTenantId } });
    if (dto.expectedVersion && existing && dto.expectedVersion !== existing.version) throw new ConflictException('SETTLEMENT_POLICY_VERSION_MISMATCH');
    const result = await this.prisma.vendorSettlementPolicy.upsert({ where: { vendorTenantId }, update: { cycleMode: dto.cycleMode, eligibilityTrigger: dto.eligibilityTrigger, settlementDelayDays: dto.settlementDelayDays, weeklyDay: dto.weeklyDay ?? null, active: dto.active ?? existing?.active ?? false, reviewRequired: dto.reviewRequired ?? existing?.reviewRequired ?? true, version: { increment: 1 } }, create: { vendorTenantId, cycleMode: dto.cycleMode, eligibilityTrigger: dto.eligibilityTrigger, settlementDelayDays: dto.settlementDelayDays, weeklyDay: dto.weeklyDay ?? null, active: dto.active ?? false, reviewRequired: dto.reviewRequired ?? true } });
    await this.audit.write(this.prisma, { actor: user, tenantId: vendorTenantId, action: 'SETTLEMENT_POLICY_UPDATED', entityType: 'VendorSettlementPolicy', entityId: result.id, afterState: result });
    return result;
  }

  async preview(user: AuthUser, dto: SettlementPreviewDto) {
    const vendorTenantId = this.scopeVendor(user, dto.vendorTenantId);
    const config = await this.configuration();
    const policy = await this.prisma.vendorSettlementPolicy.findUnique({ where: { vendorTenantId } });
    const events: any[] = await this.prisma.financialEvent.findMany({ where: { vendorTenantId, type: { in: settlementTypes }, status: FinancialEventStatus.POSTED, ...(dto.currency ? { currency: dto.currency.toUpperCase() } : {}), ...(dto.periodFrom || dto.periodTo ? { occurredAt: { ...(dto.periodFrom ? { gte: new Date(dto.periodFrom) } : {}), ...(dto.periodTo ? { lte: new Date(dto.periodTo) } : {}) } } : {}) }, include: { booking: { include: { economicsSnapshot: true, cancellation: { include: { refund: true } } } }, settlementAllocations: { where: { status: { in: [SettlementAllocationStatus.ALLOCATED, SettlementAllocationStatus.SETTLED] } } }, settlementHolds: { where: { status: SettlementHoldStatus.ACTIVE } } }, orderBy: { occurredAt: 'asc' } });
    const eligibleLines: any[] = []; const blocked: any[] = []; const grouped = new Map<string, any>();
    for (const event of events) {
      if (event.settlementAllocations?.length) continue;
      const booking = event.booking;
      if (event.type === FinancialEventType.VENDOR_ADJUSTMENT && !booking) { if (event.settlementHolds?.length) { blocked.push({ eventId: event.id, reasonCodes: ['SETTLEMENT_HOLD_ACTIVE'] }); continue; } this.addStandalone(grouped, event); continue; }
      if (!booking) { blocked.push({ eventId: event.id, reasonCodes: ['BOOKING_MISSING'] }); continue; }
      const reasons = this.blockReasons(event, booking, policy);
      if (reasons.length) { blocked.push({ eventId: event.id, bookingId: booking.id, reasonCodes: reasons }); continue; }
      const base = event.vendorAmount ?? this.decimal((booking.economicsSnapshot as any)?.vendorPayable);
      if (!booking.economicsSnapshot && !event.vendorAmount) { blocked.push({ eventId: event.id, bookingId: booking.id, reasonCodes: ['ECONOMICS_SNAPSHOT_MISSING'] }); continue; }
      const key = booking.id; const line = grouped.get(key) ?? { bookingId: key, lineType: 'BOOKING', currency: event.currency, sourceEventIds: [], grossBookingValue: this.decimal(booking.amount), vendorPayableBase: this.decimal(base), adjustmentAmount: this.zero(), taxInformational: this.zero(), components: this.vendorComponents(event, booking) };
      line.sourceEventIds.push(event.id); grouped.set(key, line);
    }
    for (const event of events.filter((e) => e.type === FinancialEventType.VENDOR_ADJUSTMENT && !e.bookingId && !e.settlementAllocations?.length)) this.addStandalone(grouped, event);
    for (const line of grouped.values()) { line.netVendorPayable = line.vendorPayableBase.plus(line.adjustmentAmount); line.explanation = { reason: line.netVendorPayable.eq(0) ? 'ZERO_NET_NO_PAYOUT' : 'ELIGIBLE_VENDOR_PAYABLE', sourceEventIds: line.sourceEventIds }; if (line.netVendorPayable.lt(0)) blocked.push({ bookingId: line.bookingId, reasonCodes: ['NEGATIVE_NET_PAYABLE'], line }); else eligibleLines.push(line); }
    const totals = eligibleLines.reduce((a, line) => ({ grossBookingValue: a.grossBookingValue.plus(line.grossBookingValue), vendorBasePayable: a.vendorBasePayable.plus(line.vendorPayableBase), adjustmentTotal: a.adjustmentTotal.plus(line.adjustmentAmount), netPayable: a.netPayable.plus(line.netVendorPayable) }), { grossBookingValue: this.zero(), vendorBasePayable: this.zero(), adjustmentTotal: this.zero(), netPayable: this.zero() });
    const response: any = { vendorTenantId, currency: dto.currency?.toUpperCase() ?? config.baseCurrency, paymentCollectionMode: config.paymentCollectionMode, policy, eligibleLines: eligibleLines.map(this.publicLine), blocked, totals: this.moneyObject(totals), eligible: eligibleLines.length > 0 && blocked.length === 0, generatedAt: new Date().toISOString() };
    response.previewFingerprint = this.fingerprint({ vendorTenantId, currency: response.currency, policyVersion: policy?.version ?? null, eligibleLines: response.eligibleLines, blocked, totals: response.totals });
    return this.isVendor(user) ? this.vendorPreviewProjection(response) : response;
  }

  async createBatch(user: AuthUser, dto: SettlementBatchDto) {
    const preview: any = await this.preview(user, dto); if (dto.expectedPreviewFingerprint && dto.expectedPreviewFingerprint !== preview.previewFingerprint) throw new ConflictException('SETTLEMENT_PREVIEW_STALE');
    if (preview.blocked?.length) throw new ConflictException({ code: 'SETTLEMENT_PREVIEW_BLOCKED', blocked: preview.blocked });
    const vendorTenantId = preview.vendorTenantId; const config = await this.configuration(); const policy = await this.prisma.vendorSettlementPolicy.findUnique({ where: { vendorTenantId } });
    const net = this.decimal(preview.totals.netPayable); if (net.lt(0)) throw new ConflictException('NEGATIVE_NET_PAYABLE');
    const status = net.eq(0) ? SettlementBatchStatus.CLOSED_NO_PAYOUT : config.paymentCollectionMode === PaymentCollectionMode.VOYA_COLLECTS ? SettlementBatchStatus.READY_FOR_PAYOUT : SettlementBatchStatus.PAYOUT_BLOCKED;
    try {
      return await this.prisma.$transaction(async (tx) => {
        const sourceIds = preview.eligibleLines.flatMap((line: any) => line.sourceEventIds); if (sourceIds.length) { const locked: any[] = await tx.$queryRawUnsafe(`SELECT "id" FROM "FinancialEvent" WHERE "id" = ANY($1::text[]) FOR UPDATE`, sourceIds); if (locked.length !== sourceIds.length) throw new ConflictException('SETTLEMENT_SOURCE_EVENT_MISSING'); }
        const batch: any = await tx.settlementBatch.create({ data: { batchCode: `SET-${new Date().toISOString().slice(0, 10).replace(/-/g, '')}-${randomUUID().slice(0, 8).toUpperCase()}`, vendorTenantId, currency: preview.currency, policySnapshot: (policy ?? { vendorTenantId, reviewRequired: true }) as any, periodFrom: dto.periodFrom ? new Date(dto.periodFrom) : null, periodTo: dto.periodTo ? new Date(dto.periodTo) : null, status, grossBookingValue: this.decimal(preview.totals.grossBookingValue), vendorBasePayable: this.decimal(preview.totals.vendorBasePayable), adjustmentTotal: this.decimal(preview.totals.adjustmentTotal), netPayable: net, eventCount: sourceIds.length, lineCount: preview.eligibleLines.length, previewFingerprint: preview.previewFingerprint, createdById: user.sub } });
        for (const line of preview.eligibleLines) { const created: any = await tx.settlementLine.create({ data: { batchId: batch.id, bookingId: line.bookingId, lineType: line.lineType, currency: line.currency, grossBookingValue: this.decimal(line.grossBookingValue), vendorPayableBase: this.decimal(line.vendorPayableBase), adjustmentAmount: this.decimal(line.adjustmentAmount), netVendorPayable: this.decimal(line.netVendorPayable), taxInformational: this.decimal(line.taxInformational), components: line.components as any } }); for (const eventId of line.sourceEventIds) await tx.settlementEventAllocation.create({ data: { batchId: batch.id, lineId: created.id, financialEventId: eventId } }); }
        await tx.financialEvent.create({ data: { eventKey: `settlement-batch:${batch.id}`, vendorTenantId, type: FinancialEventType.SETTLEMENT_BATCH_CREATED, status: FinancialEventStatus.POSTED, currency: preview.currency, amount: net, vendorAmount: net, settlementBatchId: batch.id, components: { batchCode: batch.batchCode, lineCount: batch.lineCount, eventCount: batch.eventCount }, actorUserId: user.sub, occurredAt: new Date() } });
        if (status === SettlementBatchStatus.READY_FOR_PAYOUT) await tx.payout.create({ data: { tenantId: vendorTenantId, recordType: PayoutRecordType.CANONICAL, settlementBatchId: batch.id, amount: net, status: PayoutStatus.READY_TO_RELEASE, dueDate: new Date(), currency: preview.currency } });
        await this.audit.write(tx, { actor: user, tenantId: vendorTenantId, action: 'SETTLEMENT_BATCH_CREATED', entityType: 'SettlementBatch', entityId: batch.id, metadata: { netPayable: net.toString(), status } });
        await this.outbox.enqueue(tx, { tenantId: vendorTenantId, eventType: 'SETTLEMENT_BATCH_CREATED', aggregateType: 'SettlementBatch', aggregateId: batch.id, payload: { batchCode: batch.batchCode, amount: net.toString(), status } });
        return tx.settlementBatch.findUnique({ where: { id: batch.id }, include: { lines: true, payout: true, financialEvents: true } });
      }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable, timeout: 30000, maxWait: 30000 });
    } catch (error: any) { if (error?.code === 'P2002') throw new ConflictException('SETTLEMENT_EVENT_ALREADY_ALLOCATED'); throw error; }
  }

  async adjustment(user: AuthUser, dto: VendorAdjustmentDto) { const amount = this.signed(dto.signedAmount); if (!dto.reason?.trim() || !dto.reference?.trim()) throw new ConflictException('ADJUSTMENT_REASON_AND_REFERENCE_REQUIRED'); const vendor = await this.vendor(dto.vendorTenantId); let booking: any = null; if (dto.bookingId) { booking = await this.prisma.booking.findFirst({ where: { id: dto.bookingId, vendorTenantId: dto.vendorTenantId } }); if (!booking) throw new NotFoundException('Booking not found'); } const currency = (dto.currency ?? booking?.currency ?? (await this.configuration()).baseCurrency).toUpperCase(); const event = await this.prisma.financialEvent.create({ data: { eventKey: `vendor-adjustment:${randomUUID()}`, bookingId: dto.bookingId ?? null, vendorTenantId: vendor.id, agentTenantId: booking?.agentTenantId ?? null, type: FinancialEventType.VENDOR_ADJUSTMENT, status: FinancialEventStatus.POSTED, currency, amount, vendorAmount: amount, components: { adjustmentKind: 'MANUAL', signedAmount: amount.toString() }, reason: dto.reason.trim(), reference: dto.reference.trim(), actorUserId: user.sub, occurredAt: new Date() } }); await this.audit.write(this.prisma, { actor: user, tenantId: vendor.id, action: 'VENDOR_ADJUSTMENT_CREATED', entityType: 'FinancialEvent', entityId: event.id, reason: dto.reason, metadata: { signedAmount: amount.toString(), reference: dto.reference } }); return event; }

  async resolveCancellation(user: AuthUser, cancellationId: string, dto: CancellationResolutionDto) { const final = this.nonNegative(dto.finalVendorPayable); if (!dto.reason?.trim() || !dto.reference?.trim()) throw new ConflictException('CANCELLATION_RESOLUTION_REASON_AND_REFERENCE_REQUIRED'); const cancellation: any = await this.prisma.bookingCancellation.findUnique({ where: { id: cancellationId }, include: { booking: { include: { economicsSnapshot: true } }, vendorSettlementResolution: true } }); if (!cancellation) throw new NotFoundException('Cancellation not found'); const original = this.decimal(cancellation.booking.economicsSnapshot?.vendorPayable); if (final.gt(original)) throw new ConflictException('FINAL_VENDOR_PAYABLE_EXCEEDS_ORIGINAL'); if (cancellation.vendorSettlementResolution) { if (this.decimal(cancellation.vendorSettlementResolution.finalVendorPayable).eq(final) && cancellation.vendorSettlementResolution.reference === dto.reference) return cancellation.vendorSettlementResolution; throw new ConflictException('CANCELLATION_SETTLEMENT_RESOLUTION_IMMUTABLE'); } const delta = final.minus(original); return this.prisma.$transaction(async (tx) => { const event: any = await tx.financialEvent.create({ data: { eventKey: `cancellation-vendor-adjustment:${cancellationId}`, bookingId: cancellation.bookingId, vendorTenantId: cancellation.booking.vendorTenantId, agentTenantId: cancellation.booking.agentTenantId, cancellationId, type: FinancialEventType.VENDOR_ADJUSTMENT, status: FinancialEventStatus.POSTED, currency: cancellation.booking.currency, amount: delta, vendorAmount: delta, components: { adjustmentKind: 'CANCELLATION_VENDOR_LIABILITY', originalVendorPayable: original.toString(), finalVendorPayable: final.toString(), signedDelta: delta.toString() }, reason: dto.reason.trim(), reference: dto.reference.trim(), actorUserId: user.sub, occurredAt: new Date() } }); const resolution = await tx.cancellationVendorSettlementResolution.create({ data: { cancellationId, bookingId: cancellation.bookingId, vendorTenantId: cancellation.booking.vendorTenantId, originalVendorPayable: original, finalVendorPayable: final, vendorAdjustmentAmount: delta, financialEventId: event.id, reason: dto.reason.trim(), reference: dto.reference.trim(), resolvedById: user.sub } }); await this.audit.write(tx, { actor: user, tenantId: cancellation.booking.vendorTenantId, action: 'CANCELLATION_VENDOR_SETTLEMENT_RESOLVED', entityType: 'BookingCancellation', entityId: cancellationId, reason: dto.reason, afterState: resolution }); return resolution; }); }

  async createHold(user: AuthUser, dto: SettlementHoldDto) { const populated = [dto.vendorTenantId, dto.bookingId, dto.financialEventId].filter(Boolean); if (dto.scope === SettlementHoldScope.VENDOR ? populated.length !== 1 || !dto.vendorTenantId : dto.scope === SettlementHoldScope.BOOKING ? populated.length !== 1 || !dto.bookingId : populated.length !== 1 || !dto.financialEventId) throw new ConflictException('SETTLEMENT_HOLD_SCOPE_SHAPE_INVALID'); let vendorTenantId = dto.vendorTenantId; if (dto.bookingId) { const booking = await this.prisma.booking.findUnique({ where: { id: dto.bookingId }, select: { vendorTenantId: true } }); if (!booking) throw new NotFoundException('Booking not found'); vendorTenantId = booking.vendorTenantId; } if (dto.financialEventId) { const event = await this.prisma.financialEvent.findUnique({ where: { id: dto.financialEventId }, select: { vendorTenantId: true } }); if (!event) throw new NotFoundException('Financial event not found'); vendorTenantId = event.vendorTenantId; } await this.vendor(vendorTenantId!); const hold = await this.prisma.settlementHold.create({ data: { scope: dto.scope, vendorTenantId: vendorTenantId!, bookingId: dto.bookingId ?? null, financialEventId: dto.financialEventId ?? null, reason: dto.reason.trim(), reference: dto.reference?.trim() || null, createdById: user.sub } }); await this.audit.write(this.prisma, { actor: user, tenantId: vendorTenantId, action: 'SETTLEMENT_HOLD_CREATED', entityType: 'SettlementHold', entityId: hold.id, reason: dto.reason }); return hold; }
  async releaseHold(user: AuthUser, id: string, reason?: string) { const hold = await this.prisma.settlementHold.findUnique({ where: { id } }); if (!hold) throw new NotFoundException('Settlement hold not found'); if (hold.status === SettlementHoldStatus.RELEASED) return hold; const result = await this.prisma.settlementHold.update({ where: { id }, data: { status: SettlementHoldStatus.RELEASED, releasedAt: new Date(), releasedById: user.sub, releaseReason: reason?.trim() || null } }); await this.audit.write(this.prisma, { actor: user, tenantId: hold.vendorTenantId, action: 'SETTLEMENT_HOLD_RELEASED', entityType: 'SettlementHold', entityId: id, reason }); return result; }

  async recordRelease(user: AuthUser, id: string, dto: ReleasePayoutDto) { return this.payoutTransition(user, id, async (tx: any, payout: any) => { const config = await tx.financeConfiguration.findUnique({ where: { id: 'default' } }); if (config?.paymentCollectionMode !== PaymentCollectionMode.VOYA_COLLECTS) throw new ConflictException('PAYMENT_COLLECTION_MODEL_NOT_VOYA_COLLECTS'); if (payout.status === PayoutStatus.RELEASED) { if (payout.reference === dto.externalReference) return payout; throw new ConflictException('PAYOUT_ALREADY_RELEASED_DIFFERENT_REFERENCE'); } if (payout.status !== PayoutStatus.READY_TO_RELEASE) throw new ConflictException(`PAYOUT_NOT_READY:${payout.status}`); const attempt = await this.nextAttempt(tx, payout, PayoutAttemptStatus.RELEASE_RECORDED, dto.externalReference, undefined, user.sub); const updated = await tx.payout.update({ where: { id }, data: { status: PayoutStatus.RELEASED, reference: dto.externalReference, releasedAt: new Date(), releasedById: user.sub, version: { increment: 1 } } }); await tx.settlementBatch.update({ where: { id: payout.settlementBatchId }, data: { status: SettlementBatchStatus.RELEASED, releasedAt: new Date(), version: { increment: 1 } } }); await tx.financialEvent.create({ data: { eventKey: `payout-released:${id}:${attempt.id}`, vendorTenantId: payout.tenantId, settlementBatchId: payout.settlementBatchId, payoutId: id, type: FinancialEventType.PAYOUT_RELEASED, status: FinancialEventStatus.POSTED, currency: payout.currency, amount: payout.amount, vendorAmount: payout.amount, components: { externalReference: dto.externalReference }, reference: dto.externalReference, actorUserId: user.sub, occurredAt: new Date() } }); await this.audit.write(tx, { actor: user, tenantId: payout.tenantId, action: 'PAYOUT_RELEASE_RECORDED', entityType: 'Payout', entityId: id, metadata: { externalReference: dto.externalReference } }); return updated; }); }
  async recordFailure(user: AuthUser, id: string, dto: FailPayoutDto) { return this.payoutTransition(user, id, async (tx: any, payout: any) => { if (payout.recordType !== PayoutRecordType.CANONICAL) throw new ConflictException('CANONICAL_PAYOUT_REQUIRED'); const attempt = await this.nextAttempt(tx, payout, PayoutAttemptStatus.FAILED, undefined, dto.failureReason, user.sub); const updated = await tx.payout.update({ where: { id }, data: { status: PayoutStatus.RELEASE_FAILED, failureReason: dto.failureReason.trim(), version: { increment: 1 } } }); await tx.settlementBatch.update({ where: { id: payout.settlementBatchId }, data: { status: SettlementBatchStatus.RECONCILIATION_REQUIRED, version: { increment: 1 } } }); await this.audit.write(tx, { actor: user, tenantId: payout.tenantId, action: 'PAYOUT_RELEASE_FAILED', entityType: 'Payout', entityId: id, reason: dto.failureReason, metadata: { attemptId: attempt.id } }); return updated; }); }
  async retry(user: AuthUser, id: string) { return this.payoutTransition(user, id, async (tx: any, payout: any) => { if (payout.recordType !== PayoutRecordType.CANONICAL) throw new ConflictException('CANONICAL_PAYOUT_REQUIRED'); if (payout.status !== PayoutStatus.RELEASE_FAILED) throw new ConflictException('PAYOUT_NOT_FAILED'); const result = await tx.payout.update({ where: { id }, data: { status: PayoutStatus.READY_TO_RELEASE, failureReason: null, version: { increment: 1 } } }); await tx.settlementBatch.update({ where: { id: payout.settlementBatchId }, data: { status: SettlementBatchStatus.READY_FOR_PAYOUT, version: { increment: 1 } } }); await this.audit.write(tx, { actor: user, tenantId: payout.tenantId, action: 'PAYOUT_RETRY_READY', entityType: 'Payout', entityId: id }); return result; }); }
  async reconcile(user: AuthUser, id: string, dto: ReconcilePayoutDto) { const confirmed = this.nonNegative(dto.confirmedAmount); return this.payoutTransition(user, id, async (tx: any, payout: any) => { if (payout.recordType !== PayoutRecordType.CANONICAL) throw new ConflictException('CANONICAL_PAYOUT_REQUIRED'); if (![PayoutStatus.RELEASED, PayoutStatus.RECONCILIATION_REQUIRED].includes(payout.status)) throw new ConflictException('PAYOUT_NOT_RECONCILABLE'); const matches = confirmed.eq(payout.amount); const result = await tx.payout.update({ where: { id }, data: { status: matches ? PayoutStatus.RECONCILED : PayoutStatus.RECONCILIATION_REQUIRED, reconciledAt: matches ? new Date() : null, reconciledById: user.sub, reconciledAmount: confirmed, reconciliationReference: dto.reconciliationReference, reconciliationNote: dto.note ?? null, version: { increment: 1 } } }); await tx.settlementBatch.update({ where: { id: payout.settlementBatchId }, data: { status: matches ? SettlementBatchStatus.RECONCILED : SettlementBatchStatus.RECONCILIATION_REQUIRED, reconciledAt: matches ? new Date() : null, version: { increment: 1 } } }); await this.audit.write(tx, { actor: user, tenantId: payout.tenantId, action: matches ? 'PAYOUT_RECONCILED' : 'PAYOUT_RECONCILIATION_REQUIRED', entityType: 'Payout', entityId: id, reason: dto.note, metadata: { confirmedAmount: confirmed.toString(), expectedAmount: payout.amount.toString(), reference: dto.reconciliationReference } }); return result; }); }

  listBatches(vendorTenantId?: string) { return this.prisma.settlementBatch.findMany({ where: vendorTenantId ? { vendorTenantId } : {}, include: { lines: true, payout: true }, orderBy: { createdAt: 'desc' }, take: 200 }); }
  batch(id: string) { return this.prisma.settlementBatch.findUniqueOrThrow({ where: { id }, include: { lines: { include: { allocations: true } }, payout: true, financialEvents: true } }); }
  events(vendorTenantId?: string) { return this.prisma.financialEvent.findMany({ where: vendorTenantId ? { vendorTenantId } : {}, orderBy: { occurredAt: 'desc' }, take: 500 }); }
  payouts(vendorTenantId?: string) { return this.prisma.payout.findMany({ where: { recordType: PayoutRecordType.CANONICAL, ...(vendorTenantId ? { tenantId: vendorTenantId } : {}) }, include: { settlementBatch: true, attempts: true }, orderBy: { createdAt: 'desc' } }); }
  async vendorSettlements(user: AuthUser) { const vendorTenantId = requireTenant(user); const [batches, payouts, legacyPayouts] = await Promise.all([this.prisma.settlementBatch.findMany({ where: { vendorTenantId }, include: { lines: true, payout: true }, orderBy: { createdAt: 'desc' } }), this.prisma.payout.findMany({ where: { tenantId: vendorTenantId, recordType: PayoutRecordType.CANONICAL }, include: { settlementBatch: true, attempts: true }, orderBy: { createdAt: 'desc' } }), this.prisma.payout.findMany({ where: { tenantId: vendorTenantId, recordType: PayoutRecordType.LEGACY }, orderBy: { dueDate: 'desc' } })]); return { batches: batches.map((b: any) => ({ ...b, lines: b.lines.map(this.publicLine) })), payouts, legacyPayouts }; }

  private async payoutTransition(user: AuthUser, id: string, work: (tx: any, payout: any) => Promise<any>) { return this.prisma.$transaction(async (tx) => { await tx.$queryRawUnsafe(`SELECT "id" FROM "Payout" WHERE "id" = $1 FOR UPDATE`, id); const payout = await tx.payout.findUnique({ where: { id } }); if (!payout) throw new NotFoundException('Payout not found'); return work(tx, payout); }, { isolationLevel: Prisma.TransactionIsolationLevel.Serializable, timeout: 30000, maxWait: 30000 }); }
  private async nextAttempt(tx: any, payout: any, status: PayoutAttemptStatus, reference?: string, failureReason?: string, actorUserId = 'system') { const last = await tx.payoutAttempt.findFirst({ where: { payoutId: payout.id }, orderBy: { attemptNumber: 'desc' } }); return tx.payoutAttempt.create({ data: { payoutId: payout.id, attemptNumber: (last?.attemptNumber ?? 0) + 1, status, amount: payout.amount, currency: payout.currency, externalReference: reference ?? null, failureReason: failureReason ?? null, actorUserId, occurredAt: new Date() } }); }
  private blockReasons(event: any, booking: any, policy: any): string[] { const reasons: string[] = []; if (!policy) reasons.push('SETTLEMENT_POLICY_MISSING'); else { if (policy.reviewRequired) reasons.push('SETTLEMENT_POLICY_REVIEW_REQUIRED'); if (!policy.active) reasons.push('SETTLEMENT_POLICY_INACTIVE'); const trigger = policy.eligibilityTrigger; if (trigger === SettlementEligibilityTrigger.SERVICE_COMPLETED && booking.status !== 'COMPLETED') reasons.push('SERVICE_NOT_COMPLETED'); if (trigger === SettlementEligibilityTrigger.SERVICE_REDEEMED && !['REDEEMED', 'COMPLETED'].includes(booking.status)) reasons.push('SERVICE_NOT_REDEEMED'); if (trigger === SettlementEligibilityTrigger.BOOKING_CONFIRMED && !['CONFIRMED', 'COMPLETED', 'REDEEMED', 'CANCELLED'].includes(booking.status)) reasons.push('BOOKING_NOT_CONFIRMED'); } if (booking.cancellation?.financialState === 'REFUND_FAILED') reasons.push('REFUND_EXCEPTION'); if (booking.status === 'CANCELLED' && !booking.vendorSettlementResolution) reasons.push('CANCELLATION_VENDOR_LIABILITY_UNRESOLVED'); if (event.settlementHolds?.length) reasons.push('SETTLEMENT_HOLD_ACTIVE'); return reasons; }
  private addStandalone(grouped: Map<string, any>, event: any) { const key = `event:${event.id}`; grouped.set(key, { bookingId: null, lineType: 'ADJUSTMENT', currency: event.currency, sourceEventIds: [event.id], grossBookingValue: this.zero(), vendorPayableBase: this.zero(), adjustmentAmount: this.decimal(event.vendorAmount ?? event.amount), taxInformational: this.zero(), components: { adjustment: true, reason: event.reason, reference: event.reference } }); }
  private vendorComponents(event: any, booking: any) { const c = event.components ?? {}; return { bookingValue: String(booking.amount), supplierGrossBasis: c.supplierGrossBasis ?? null, supplierCommission: c.supplierCommission ?? null, baseVendorPayable: String(event.vendorAmount ?? c.vendorPayable ?? 0), taxInformational: c.taxAmount ?? null, promotionAmount: c.promotionAmount ?? null, promotionFunder: c.promotionFunder ?? null }; }
  private publicLine(line: any) { return { ...line, grossBookingValue: String(line.grossBookingValue), vendorPayableBase: String(line.vendorPayableBase), adjustmentAmount: String(line.adjustmentAmount), netVendorPayable: String(line.netVendorPayable ?? 0), taxInformational: String(line.taxInformational) }; }
  private vendorPreviewProjection(response: any) { return { ...response, eligibleLines: response.eligibleLines.map((line: any) => ({ ...line, components: { bookingValue: line.components.bookingValue, baseVendorPayable: line.components.baseVendorPayable, taxInformational: line.components.taxInformational, promotionAmount: line.components.promotionAmount, promotionFunder: line.components.promotionFunder } })) }; }
  private moneyObject(value: any) { return Object.fromEntries(Object.entries(value).map(([key, amount]) => [key, String(amount)])); }
  private decimal(value: any) { return value === null || value === undefined || value === '' ? new Prisma.Decimal(0) : new Prisma.Decimal(String(value)); }
  private zero() { return new Prisma.Decimal(0); }
  private nonNegative(value: string) { const amount = this.decimal(value); if (!amount || amount.lt(0)) throw new ConflictException('AMOUNT_MUST_BE_NON_NEGATIVE'); return amount; }
  private signed(value: string) { if (!/^-?(?:0|[1-9]\d*)(?:\.\d{1,4})?$/.test(value)) throw new ConflictException('SIGNED_AMOUNT_INVALID'); return new Prisma.Decimal(value); }
  private fingerprint(value: unknown) { return createHash('sha256').update(JSON.stringify(value)).digest('hex'); }
  private isVendor(user: AuthUser) { return user.role === UserRole.VENDOR; }
  private scopeVendor(user: AuthUser, requested?: string) { if (this.isVendor(user)) return requireTenant(user); if (!requested) throw new ConflictException('vendorTenantId is required'); return requested; }
  private async vendor(id: string) { const vendor = await this.prisma.tenant.findUnique({ where: { id } }); if (!vendor) throw new NotFoundException('Vendor tenant not found'); return vendor; }
}
