"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { listActivities } from "@/services/activityService";
import { apiRequest } from "@/services/apiClient";
import { createBooking, createPayment } from "@/services/bookingService";
import type { Activity } from "@/types/activity";

type Passenger = { type: "ADULT" | "CHILD" | "INFANT"; firstName: string; lastName: string };
type PartnerOption = { id: string; company: string };
const labels = ["Activity and schedule", "Availability", "Customer", "Passengers", "Pricing", "Voucher", "Payment", "Review", "Confirmation"];

export function BookingForm() {
  const router = useRouter(); const [activities, setActivities] = useState<Activity[]>([]); const [agents, setAgents] = useState<PartnerOption[]>([]); const [suppliers, setSuppliers] = useState<PartnerOption[]>([]); const [step, setStep] = useState(1); const [form, setForm] = useState({ activityId: "", scheduleId: "", agentId: "", supplierId: "", source: "DIRECT", customerName: "", customerEmail: "", customerPhone: "", voucherCode: "", notes: "", idempotencyKey: "" }); const [passengers, setPassengers] = useState<Passenger[]>([{ type: "ADULT", firstName: "Guest", lastName: "Customer" }]); const [paymentMethod, setPaymentMethod] = useState<"CARD" | "BANK_TRANSFER" | "CASH" | "MOCK">("MOCK"); const [payNow, setPayNow] = useState(false); const [now, setNow] = useState(0); const [error, setError] = useState(""); const [saving, setSaving] = useState(false); const [confirmation, setConfirmation] = useState<{ id: string; reference: string } | null>(null);
  useEffect(() => { setNow(Date.now()); setForm((current) => ({ ...current, idempotencyKey: `booking-${crypto.randomUUID()}` })); void listActivities({ page: 1, pageSize: 100, sortBy: "createdAt", sortOrder: "desc" }).then((result) => setActivities(result.data)).catch(() => setError("Unable to load activities")); void Promise.all([apiRequest<{ data: PartnerOption[] }>("/agents?page=1&pageSize=100&sortBy=company&sortOrder=asc"), apiRequest<{ data: PartnerOption[] }>("/suppliers?page=1&pageSize=100&sortBy=company&sortOrder=asc")]).then(([agentResult, supplierResult]) => { setAgents(agentResult.data); setSuppliers(supplierResult.data); }).catch(() => undefined); }, []);
  const selected = activities.find((activity) => activity.id === form.activityId); const availableSchedules = selected?.schedules.filter((schedule) => now > 0 && new Date(schedule.startsAt).getTime() > now && schedule.capacity > schedule.bookedSeats) ?? []; const selectedSchedule = availableSchedules.find((schedule) => schedule.id === form.scheduleId); const price = selected?.pricePlans?.[0];
  const subtotal = price ? passengers.reduce((sum, passenger) => sum + (passenger.type === "ADULT" ? price.adultMinor : passenger.type === "CHILD" ? price.childMinor : price.infantMinor), 0) : 0; const estimate = { subtotal, tax: 0, total: subtotal };
  const updatePassenger = (index: number, patch: Partial<Passenger>) => setPassengers((current) => current.map((passenger, passengerIndex) => passengerIndex === index ? { ...passenger, ...patch } : passenger));
  const next = () => { setError(""); if (step === 1 && (!form.activityId || !form.scheduleId)) return setError("Select an activity and departure before continuing"); if (step === 3 && (!form.customerName || !form.customerEmail)) return setError("Customer name and email are required"); if (step === 4 && passengers.some((passenger) => !passenger.firstName || !passenger.lastName)) return setError("Complete every passenger name before continuing"); setStep((current) => Math.min(8, current + 1)); };
  async function submit(event: FormEvent) { event.preventDefault(); setSaving(true); setError(""); try { const { agentId, supplierId, ...baseForm } = form; const bookingPayload = { ...baseForm, ...(agentId ? { agentId } : {}), ...(supplierId ? { supplierId } : {}) }; const booking = await createBooking({ ...bookingPayload, passengers }); if (payNow && booking.totalMinor > 0) await createPayment({ bookingId: booking.id, amountMinor: booking.totalMinor, currency: booking.currency, method: paymentMethod, idempotencyKey: `payment-${booking.id}-${form.idempotencyKey}` }); setConfirmation({ id: booking.id, reference: booking.reference }); setStep(9); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to create booking"); } finally { setSaving(false); } }
  if (step === 9 && confirmation) return <div><div className="page-heading"><div><p className="eyebrow">BOOKINGS / CONFIRMATION</p><h2>Booking created</h2><p className="subtext">Reference {confirmation.reference}</p></div></div><section className="panel"><p className="notice success">The booking hold was created safely. {payNow ? "A pending payment was also created." : "You can collect payment from the booking details page."}</p><div className="form-actions"><Link className="primary button-link" href={`/bookings/${confirmation.id}`}>View booking</Link><Link className="button-link" href="/bookings">Back to bookings</Link></div></section></div>;
  return <div><div className="page-heading"><div><p className="eyebrow">BOOKINGS / NEW</p><h2>Create booking</h2><p className="subtext">Complete the protected booking workflow one step at a time.</p></div></div><section className="stepper" aria-label="Booking steps">{labels.slice(0, 8).map((label, index) => <span className={step === index + 1 ? "active" : step > index + 1 ? "complete" : ""} key={label}>{index + 1}. {label}</span>)}</section><form className="panel form-grid" onSubmit={submit}>
    {step === 1 && <fieldset><legend>1. Activity and schedule</legend><label>Activity<select value={form.activityId} onChange={(event) => setForm({ ...form, activityId: event.target.value, scheduleId: "" })} required><option value="">Select activity</option>{activities.map((activity) => <option key={activity.id} value={activity.id}>{activity.name}</option>)}</select></label><label>Departure<select value={form.scheduleId} onChange={(event) => setForm({ ...form, scheduleId: event.target.value })} required><option value="">Select departure</option>{availableSchedules.map((schedule) => <option key={schedule.id} value={schedule.id}>{new Date(schedule.startsAt).toLocaleString()} · {Math.max(0, schedule.capacity - schedule.bookedSeats)} left</option>)}</select></label><label>Booking source<select value={form.source} onChange={(event) => setForm({ ...form, source: event.target.value })}><option value="DIRECT">Direct</option><option value="AGENT">Agent</option><option value="SUPPLIER">Supplier</option><option value="PARTNER">Partner</option></select></label><label>Agent (optional)<select value={form.agentId} onChange={(event) => setForm({ ...form, agentId: event.target.value })}><option value="">No agent</option>{agents.map((agent) => <option key={agent.id} value={agent.id}>{agent.company}</option>)}</select></label><label>Supplier (optional)<select value={form.supplierId} onChange={(event) => setForm({ ...form, supplierId: event.target.value })}><option value="">No supplier</option>{suppliers.map((supplier) => <option key={supplier.id} value={supplier.id}>{supplier.company}</option>)}</select></label>{selected && availableSchedules.length === 0 && <small className="notice">No future departures with remaining capacity.</small>}</fieldset>}
    {step === 2 && <fieldset><legend>2. Availability</legend>{selectedSchedule ? <div className="detail-grid"><div><span>Activity</span><strong>{selected?.name}</strong></div><div><span>Departure</span><strong>{new Date(selectedSchedule.startsAt).toLocaleString()}</strong></div><div><span>Capacity</span><strong>{selectedSchedule.capacity}</strong></div><div><span>Remaining</span><strong>{Math.max(0, selectedSchedule.capacity - selectedSchedule.bookedSeats)}</strong></div></div> : <p className="notice error">Choose a departure in step 1.</p>}</fieldset>}
    {step === 3 && <fieldset><legend>3. Customer</legend><label>Customer name<input value={form.customerName} onChange={(event) => setForm({ ...form, customerName: event.target.value })} required /></label><label>Customer email<input type="email" value={form.customerEmail} onChange={(event) => setForm({ ...form, customerEmail: event.target.value })} required /></label><label>Customer phone<input value={form.customerPhone} onChange={(event) => setForm({ ...form, customerPhone: event.target.value })} /></label></fieldset>}
    {step === 4 && <fieldset><legend>4. Passengers</legend>{passengers.map((passenger, index) => <div className="form-grid" key={index}><label>Passenger {index + 1} type<select aria-label={`Passenger ${index + 1} type`} value={passenger.type} onChange={(event) => updatePassenger(index, { type: event.target.value as Passenger["type"] })}><option value="ADULT">Adult</option><option value="CHILD">Child</option><option value="INFANT">Infant</option></select></label><label>First name<input aria-label={`Passenger ${index + 1} first name`} value={passenger.firstName} onChange={(event) => updatePassenger(index, { firstName: event.target.value })} required /></label><label>Last name<input aria-label={`Passenger ${index + 1} last name`} value={passenger.lastName} onChange={(event) => updatePassenger(index, { lastName: event.target.value })} required /></label>{passengers.length > 1 && <button type="button" onClick={() => setPassengers((current) => current.filter((_, passengerIndex) => passengerIndex !== index))}>Remove passenger</button>}</div>)}<button type="button" onClick={() => setPassengers((current) => [...current, { type: "ADULT", firstName: "", lastName: "" }])}>Add passenger</button></fieldset>}
    {step === 5 && <fieldset><legend>5. Pricing</legend><div className="detail-grid"><div><span>Adult price</span><strong>{price ? `${price.currency} ${(price.adultMinor / 100).toFixed(2)}` : "Price plan required"}</strong></div><div><span>Passengers</span><strong>{passengers.length}</strong></div><div><span>Estimated subtotal</span><strong>{price ? `${price.currency} ${(estimate.subtotal / 100).toFixed(2)}` : "—"}</strong></div><div><span>Estimated total</span><strong>{price ? `${price.currency} ${(estimate.total / 100).toFixed(2)}` : "—"}</strong></div></div></fieldset>}
    {step === 6 && <fieldset><legend>6. Voucher or discount</legend><label>Voucher code<input value={form.voucherCode} onChange={(event) => setForm({ ...form, voucherCode: event.target.value.toUpperCase() })} /></label><label>Notes<textarea value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} rows={3} /></label></fieldset>}
    {step === 7 && <fieldset><legend>7. Payment</legend><label className="checkbox-label"><input type="checkbox" checked={payNow} onChange={(event) => setPayNow(event.target.checked)} /> Create a pending payment after the booking hold</label>{payNow && <label>Payment method<select value={paymentMethod} onChange={(event) => setPaymentMethod(event.target.value as typeof paymentMethod)}><option value="MOCK">Mock provider</option><option value="CARD">Card</option><option value="BANK_TRANSFER">Bank transfer</option><option value="CASH">Cash</option></select></label>}</fieldset>}
    {step === 8 && <fieldset><legend>8. Review</legend><div className="detail-grid"><div><span>Activity</span><strong>{selected?.name}</strong></div><div><span>Customer</span><strong>{form.customerName} · {form.customerEmail}</strong></div><div><span>Passengers</span><strong>{passengers.length}</strong></div><div><span>Payment</span><strong>{payNow ? paymentMethod : "Collect later"}</strong></div></div><label>Idempotency key<input value={form.idempotencyKey} onChange={(event) => setForm({ ...form, idempotencyKey: event.target.value })} required /></label></fieldset>}
    {error && <div className="notice error">{error}</div>}<div className="form-actions"><button type="button" onClick={() => step === 1 ? router.back() : setStep((current) => current - 1)}>Back</button>{step < 8 ? <button type="button" className="primary" onClick={next}>Next</button> : <button className="primary" disabled={saving}>{saving ? "Creating…" : "Create hold"}</button>}</div>
  </form></div>;
}
