"use client";

import Link from "next/link";
import { useState } from "react";
import { adjustScheduleCapacity, duplicateSchedule } from "@/services/inventoryService";
import type { ScheduleRecord } from "@/services/inventoryService";

export function ScheduleDetails({ schedule }: { schedule: ScheduleRecord }) {
  const [capacity, setCapacity] = useState(String(schedule.capacity)); const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(""); const [error, setError] = useState("");
  async function adjust(event: React.FormEvent) { event.preventDefault(); setSaving(true); setError(""); setMessage(""); try { await adjustScheduleCapacity(schedule.id, { capacity: Number(capacity), reason }); setMessage("Capacity adjusted and recorded in audit history"); setReason(""); } catch (value) { setError(value instanceof Error ? value.message : "Unable to adjust capacity"); } finally { setSaving(false); } }
  async function duplicate() { const startsAt = new Date(schedule.startsAt); const endsAt = new Date(schedule.endsAt); startsAt.setUTCDate(startsAt.getUTCDate() + 1); endsAt.setUTCDate(endsAt.getUTCDate() + 1); setSaving(true); setError(""); setMessage(""); try { await duplicateSchedule(schedule.id, { startsAt: startsAt.toISOString(), endsAt: endsAt.toISOString() }); setMessage("Schedule duplicated safely for the next day"); } catch (value) { setError(value instanceof Error ? value.message : "Unable to duplicate schedule"); } finally { setSaving(false); } }
  return <div><div className="page-heading"><div><p className="eyebrow">INVENTORY / SCHEDULES</p><h2>{schedule.activity.name}</h2><p className="subtext">{new Date(schedule.startsAt).toLocaleString()} to {new Date(schedule.endsAt).toLocaleString()}</p></div><div className="form-actions"><Link className="primary button-link" href={`/schedules/${schedule.id}/edit`}>Edit schedule</Link><button type="button" onClick={() => void duplicate()} disabled={saving}>Duplicate next day</button></div></div>{error && <p className="notice error" role="alert">{error}</p>}{message && <p className="notice success" role="status">{message}</p>}<section className="panel detail-grid"><div><span>Capacity</span><strong>{schedule.capacity}</strong></div><div><span>Booked</span><strong>{schedule.bookedSeats}</strong></div><div><span>Available</span><strong>{Math.max(0, schedule.capacity - schedule.bookedSeats)}</strong></div><div><span>Status</span><strong>{schedule.isBookable ? "BOOKABLE" : "INACTIVE"}</strong></div></section><form className="panel form-grid" onSubmit={adjust}><h3>Manual capacity adjustment</h3><label>New capacity<input type="number" min={schedule.bookedSeats} value={capacity} onChange={(event) => setCapacity(event.target.value)} required /></label><label>Reason<textarea value={reason} onChange={(event) => setReason(event.target.value)} required /></label><button className="primary" disabled={saving}>{saving ? "Saving…" : "Adjust capacity"}</button></form></div>;
}
