import { CommercialCalculatorService } from './commercial-calculator.service';

const tax = (mode = 'NONE', rate = '0') => ({ rule: { id: 'tax', kind: 'TAX', scopeType: 'GLOBAL', versions: [{ id: 'tax-v1', priority: 1, stackingMode: 'EXCLUSIVE', effectiveFrom: '2026-09-01' }] }, config: { mode, rate, taxableBase: 'AGENT_PRE_TAX', accountableParty: 'NONE', roundingPolicy: 'HALF_UP' } });
const voya = (config: any = { model: 'MARKUP_FIXED', fixedAmount: '0' }) => ({ rule: { id: 'voya', kind: 'VOYA_REVENUE', scopeType: 'GLOBAL', versions: [{ id: 'voya-v1', priority: 1, stackingMode: 'EXCLUSIVE', effectiveFrom: '2026-09-01' }] }, config });
const version = (overrides: any = {}) => ({ id: 'v1', versionNumber: 1, currency: 'INR', supplierModel: 'NET_RATE', pricingUnit: 'PER_PERSON', supplierBaseAmount: '100', bookingMode: 'INSTANT', travellerPrices: [{ travellerType: 'ADULT', amount: '100' }], ...overrides });
const input = (overrides: any = {}) => ({ ratePlanId: 'rp', serviceDate: new Date('2026-09-11'), units: 1, travellers: [{ travellerType: 'ADULT', quantity: 2 }], ...overrides });

describe('CommercialCalculatorService Phase 3.1 correctness', () => {
  const calculator = new CommercialCalculatorService();
  it('calculates per-person net basis', () => expect(calculator.calculate(input(), version(), []).supplier).toMatchObject({ grossBasis: '200.00', vendorPayable: '200.00' }));
  it('calculates per-booking units', () => expect(calculator.calculate(input({ units: 3 }), version({ pricingUnit: 'PER_BOOKING', supplierBaseAmount: '125' }), []).supplier?.grossBasis).toBe('375.00'));
  it('calculates commissionable supplier terms', () => expect(calculator.calculate(input(), version({ supplierModel: 'COMMISSIONABLE', supplierCommissionPercent: '10' }), []).supplier).toMatchObject({ commission: '20.00', vendorPayable: '180.00' }));
  it('rejects unsupported supplier models at calculation', () => expect(calculator.calculate(input(), version({ supplierModel: 'HYBRID' }), []).reasonCodes).toContain('SUPPLIER_MODEL_UNSUPPORTED'));
  it('keeps Voya revenue when applying NET_PLUS_MARKUP', () => { const result = calculator.calculate(input({ agentTenantId: 'a1', travellers: [{ travellerType: 'ADULT', quantity: 1 }] }), version({ supplierBaseAmount: '1000', travellerPrices: [{ travellerType: 'ADULT', amount: '1000' }] }), [voya({ model: 'MARKUP_FIXED', fixedAmount: '150' }), { rule: { id: 'agent', kind: 'AGENT_COMMERCIAL', scopeType: 'AGENT', versions: [{ id: 'av1', priority: 1, stackingMode: 'EXCLUSIVE', effectiveFrom: '2026-09-01' }] }, config: { model: 'NET_PLUS_MARKUP', markupAmount: '100' } }, tax()]); expect(result.voya?.revenue).toBe('150.00'); expect(result.agent).toMatchObject({ markup: '100.00', facingAmount: '1250.00' }); });
  it('does not add selling-price commission twice', () => { const result = calculator.calculate(input({ agentTenantId: 'a1' }), version(), [voya(), { rule: { id: 'agent', kind: 'AGENT_COMMERCIAL', scopeType: 'AGENT', versions: [{ id: 'av1', priority: 1, stackingMode: 'EXCLUSIVE', effectiveFrom: '2026-09-01' }] }, config: { model: 'SELLING_PRICE_COMMISSION', commissionPercent: '10' } }, tax()]); expect(result.agent).toMatchObject({ commission: '20.00', facingAmount: '200.00' }); expect(result.finalAmount).toBe('200.00'); });
  it('extracts inclusive tax without adding it again', () => { const result = calculator.calculate(input(), version(), [voya(), tax('INCLUSIVE', '10')]); expect(result.tax?.amount).toBe('18.18'); expect(result.finalAmount).toBe('200.00'); });
  it('adds exclusive tax', () => { const result = calculator.calculate(input(), version(), [voya(), tax('EXCLUSIVE', '10')]); expect(result.tax?.amount).toBe('20.00'); expect(result.finalAmount).toBe('220.00'); });
  it('requires an applicable tax rule', () => expect(calculator.calculate(input(), version(), [voya()]).reasonCodes).toContain('TAX_CONFIGURATION_MISSING'));
  it('accepts explicit NONE tax configuration', () => { const result = calculator.calculate(input({ agentTenantId: 'a1' }), version(), [voya(), tax() , { rule: { id: 'agent', kind: 'AGENT_COMMERCIAL', scopeType: 'AGENT', versions: [{ id: 'av1', priority: 1, stackingMode: 'EXCLUSIVE', effectiveFrom: '2026-09-01' }] }, config: { model: 'NET_PLUS_MARKUP', markupAmount: '0' } }, { rule: { id: 'elig', kind: 'ELIGIBILITY', scopeType: 'AGENT', versions: [{ id: 'ev1', priority: 1, stackingMode: 'EXCLUSIVE', effectiveFrom: '2026-09-01' }] }, config: { decision: 'ALLOW' } }]); expect(result.reasonCodes).not.toContain('TAX_CONFIGURATION_MISSING'); });
  it('applies PRE_TAX promotion before tax', () => { const result = calculator.calculate(input(), version(), [voya(), tax('EXCLUSIVE', '10'), { rule: { id: 'p', kind: 'PROMOTION', scopeType: 'GLOBAL', versions: [{ id: 'pv', priority: 1, stackingMode: 'EXCLUSIVE', effectiveFrom: '2026-09-01' }] }, config: { discountType: 'FIXED', value: '50', funder: 'VOYA', applicationStage: 'PRE_TAX' } }]); expect(result.calculationOutputs).toMatchObject({ promotionPreTax: '50.00', taxAmount: '15.00' }); expect(result.finalAmount).toBe('165.00'); });
  it('applies POST_TAX promotion after tax', () => { const result = calculator.calculate(input(), version(), [voya(), tax('EXCLUSIVE', '10'), { rule: { id: 'p', kind: 'PROMOTION', scopeType: 'GLOBAL', versions: [{ id: 'pv', priority: 1, stackingMode: 'EXCLUSIVE', effectiveFrom: '2026-09-01' }] }, config: { discountType: 'FIXED', value: '50', funder: 'VOYA', applicationStage: 'POST_TAX' } }]); expect(result.calculationOutputs).toMatchObject({ taxAmount: '20.00', promotionPostTax: '50.00' }); expect(result.finalAmount).toBe('170.00'); });
  it('returns promotion funder and breakdown', () => { const result = calculator.calculate(input(), version(), [voya(), tax(), { rule: { id: 'p', kind: 'PROMOTION', scopeType: 'GLOBAL', versions: [{ id: 'pv', priority: 1, stackingMode: 'EXCLUSIVE', effectiveFrom: '2026-09-01' }] }, config: { discountType: 'FIXED', value: '20', funder: 'VOYA', applicationStage: 'POST_TAX' } }]); expect(result.promotionFunder).toBe('VOYA'); expect(result.promotionFundingBreakdown.VOYA).toBe('20.00'); });
  it('handles shared promotion funding', () => { const result = calculator.calculate(input(), version(), [voya(), tax(), { rule: { id: 'p', kind: 'PROMOTION', scopeType: 'GLOBAL', versions: [{ id: 'pv', priority: 1, stackingMode: 'EXCLUSIVE', effectiveFrom: '2026-09-01' }] }, config: { discountType: 'FIXED', value: '20', funder: 'SHARED', applicationStage: 'POST_TAX', funding: { vendorPercent: '50', voyaPercent: '50', agentPercent: '0' } } }]); expect(result.promotionFundingBreakdown).toMatchObject({ SUPPLIER: '10.00', VOYA: '10.00' }); });
  it('applies FOC only after threshold', () => { const rule = { rule: { id: 'f', kind: 'FOC', scopeType: 'GLOBAL', versions: [{ id: 'fv', priority: 1, stackingMode: 'EXCLUSIVE', effectiveFrom: '2026-09-01' }] }, config: { enabled: true, qualifyingQuantity: 10, freeQuantity: 1, appliesTo: 'ADULT', funder: 'SUPPLIER' } }; expect(calculator.calculate(input({ travellers: [{ travellerType: 'ADULT', quantity: 9 }] }), version(), [voya(), tax(), rule]).foc).toMatchObject({ applied: false, freeChargeableQuantity: 0 }); expect(calculator.calculate(input({ travellers: [{ travellerType: 'ADULT', quantity: 10 }] }), version(), [voya(), tax(), rule]).foc).toMatchObject({ applied: true, freeChargeableQuantity: 1, discountAmount: '100.00' }); });
  it('does not make an FOC booking zero', () => { const rule = { rule: { id: 'f', kind: 'FOC', scopeType: 'GLOBAL', versions: [{ id: 'fv', priority: 1, stackingMode: 'EXCLUSIVE', effectiveFrom: '2026-09-01' }] }, config: { enabled: true, qualifyingQuantity: 10, freeQuantity: 1, appliesTo: 'ADULT', funder: 'SUPPLIER' } }; expect(calculator.calculate(input({ travellers: [{ travellerType: 'ADULT', quantity: 10 }] }), version(), [voya(), tax(), rule]).finalAmount).toBe('900.00'); });
  it('reports unsupported FOC pricing unit', () => { const rule = { rule: { id: 'f', kind: 'FOC', scopeType: 'GLOBAL', versions: [{ id: 'fv' }] }, config: { enabled: true, qualifyingQuantity: 2, freeQuantity: 1, appliesTo: 'ADULT', funder: 'SUPPLIER' } }; expect(calculator.calculate(input(), version({ pricingUnit: 'PER_BOOKING' }), [voya(), tax(), rule]).reasonCodes).toContain('FOC_UNSUPPORTED_PRICING_UNIT'); });
  it('resolves eligibility ALLOW/DENY/UNCONFIGURED result states', () => { const allow = { rule: { id: 'e', kind: 'ELIGIBILITY', scopeType: 'AGENT', versions: [{ id: 'ev' }] }, config: { decision: 'ALLOW' } }; const deny = { ...allow, config: { decision: 'DENY' } }; expect(calculator.calculate(input({ agentTenantId: 'a' }), version(), [voya(), tax(), allow]).commercialEligibility).toBe('ALLOWED'); expect(calculator.calculate(input({ agentTenantId: 'a' }), version(), [voya(), tax(), deny]).commercialEligibility).toBe('DENIED'); expect(calculator.calculate(input({ agentTenantId: 'a' }), version(), [voya(), tax()]).commercialEligibility).toBe('UNCONFIGURED'); });
  it('supports all canonical booking modes as values', () => { for (const mode of ['INSTANT', 'VENDOR_CONFIRMATION', 'MANUAL_ON_REQUEST']) expect(calculator.calculate(input(), version({ bookingMode: mode }), [voya(), tax()]).bookingMode).toBe(mode); });
  it('reports absent Voya revenue explicitly', () => expect(calculator.calculate(input(), version(), [tax()]).reasonCodes).toContain('VOYA_REVENUE_RULE_MISSING'));
});
