import { BadRequestException } from '@nestjs/common';
import { CommercialRuleKind } from '@prisma/client';
import { AgentCommercialRuleConfig, AgentEligibilityRuleConfig, CommercialRuleConfig, FocRuleConfig, PromotionRuleConfig, TaxRuleConfig, VoyaRevenueRuleConfig } from './commercial.dto';

const decimal = (value: unknown) => typeof value === 'string' && /^\d+(\.\d{1,4})?$/.test(value);
const allowed: Record<CommercialRuleKind, string[]> = { VOYA_REVENUE: ['model', 'fixedAmount', 'percent'], AGENT_COMMERCIAL: ['model', 'markupAmount', 'commissionPercent', 'price'], TAX: ['mode', 'rate', 'taxableBase', 'accountableParty', 'roundingPolicy', 'explicitBase'], PROMOTION: ['discountType', 'value', 'funder', 'applicationStage', 'funding'], FOC: ['enabled', 'qualifyingQuantity', 'freeQuantity', 'appliesTo', 'funder'], ELIGIBILITY: ['decision'] };
const fail = (message: string): never => { throw new BadRequestException({ code: 'INVALID_RULE_CONFIG', message }); };
export function validateRuleConfig(kind: CommercialRuleKind, raw: unknown): CommercialRuleConfig {
  if (!raw || typeof raw !== 'object' || Array.isArray(raw)) fail('config must be an object');
  const config = raw as Record<string, any>;
  for (const key of Object.keys(config)) if (!allowed[kind].includes(key)) fail(`unsupported field: ${key}`);
  const percent = (name: string, required = false) => { if (required && !decimal(config[name])) fail(`${name} must be a decimal string`); if (config[name] !== undefined && (!decimal(config[name]) || Number(config[name]) > 100)) fail(`${name} must be between 0 and 100`); };
  if (kind === 'VOYA_REVENUE') { if (!['MARKUP_FIXED', 'MARKUP_PERCENT', 'COMMISSION_PERCENT'].includes(config.model)) fail('unsupported Voya revenue model'); if (config.model === 'MARKUP_FIXED' && !decimal(config.fixedAmount)) fail('fixedAmount is required'); if (config.model !== 'MARKUP_FIXED') percent('percent', true); return config as VoyaRevenueRuleConfig; }
  if (kind === 'AGENT_COMMERCIAL') { if (!['NET_PLUS_MARKUP', 'SELLING_PRICE_COMMISSION', 'AGENT_SPECIFIC_PRICE'].includes(config.model)) fail('unsupported agent commercial model'); if (config.model === 'NET_PLUS_MARKUP' && !decimal(config.markupAmount)) fail('markupAmount is required'); if (config.model === 'SELLING_PRICE_COMMISSION') percent('commissionPercent', true); if (config.model === 'AGENT_SPECIFIC_PRICE' && !decimal(config.price)) fail('price is required'); return config as AgentCommercialRuleConfig; }
  if (kind === 'TAX') { if (!['EXCLUSIVE', 'INCLUSIVE', 'NONE'].includes(config.mode) || !['AGENT_PRE_TAX', 'SUPPLIER_BASIS', 'VENDOR_PAYABLE', 'EXPLICIT_BASE'].includes(config.taxableBase) || !['VENDOR', 'VOYA', 'AGENT', 'NONE'].includes(config.accountableParty) || !['HALF_UP', 'HALF_EVEN', 'DOWN', 'UP'].includes(config.roundingPolicy)) fail('tax config requires mode, rate base, accountable party and rounding policy'); if (config.mode !== 'NONE') percent('rate', true); if (config.taxableBase === 'EXPLICIT_BASE' && !decimal(config.explicitBase)) fail('explicitBase is required'); return config as TaxRuleConfig; }
  if (kind === 'PROMOTION') { if (!['FIXED', 'PERCENT'].includes(config.discountType) || !decimal(config.value) || !['SUPPLIER', 'VOYA', 'AGENT', 'SHARED'].includes(config.funder) || !['PRE_TAX', 'POST_TAX'].includes(config.applicationStage)) fail('invalid promotion config'); if (config.discountType === 'PERCENT' && Number(config.value) > 100) fail('promotion percent must be <= 100'); if (config.funder === 'SHARED') { const f = config.funding; if (!f || !decimal(f.vendorPercent) || !decimal(f.voyaPercent) || !decimal(f.agentPercent) || Number(f.vendorPercent) + Number(f.voyaPercent) + Number(f.agentPercent) !== 100) fail('shared promotion funding must total 100%'); } return config as PromotionRuleConfig; }
  if (kind === 'FOC') { if (typeof config.enabled !== 'boolean' || !Number.isInteger(config.qualifyingQuantity) || config.qualifyingQuantity < 1 || !Number.isInteger(config.freeQuantity) || config.freeQuantity < 1 || config.freeQuantity >= config.qualifyingQuantity || !config.appliesTo || !['SUPPLIER', 'VOYA', 'AGENT', 'SHARED'].includes(config.funder)) fail('invalid FOC config: freeQuantity must be at least 1 and less than qualifyingQuantity'); return config as FocRuleConfig; }
  if (config.decision !== 'ALLOW' && config.decision !== 'DENY') fail('eligibility decision must be ALLOW or DENY');
  return config as AgentEligibilityRuleConfig;
}
