import { BookingFulfilmentStatus, BookingMode, BookingStatus, FulfilmentEvidenceKind, FulfilmentEvidenceStatus, FulfilmentMode, UserRole, VoucherGenerationStatus, VoucherVersionStatus } from '@prisma/client';
import { randomUUID } from 'crypto';
import { AuditService } from '../src/audit/audit.service';
import { RequestContextService } from '../src/common/request-context.service';
import { FilesService } from '../src/files/files.service';
import { FulfilmentLifecycleService } from '../src/fulfilment/fulfilment-lifecycle.service';
import { FulfilmentReadinessService } from '../src/fulfilment/fulfilment-readiness.service';
import { FulfilmentService } from '../src/fulfilment/fulfilment.service';
import { VoucherGenerationService } from '../src/fulfilment/voucher-generation.service';
import { OutboxService } from '../src/outbox/outbox.service';
import { PrismaService } from '../src/prisma/prisma.service';
import { StorageService } from '../src/storage/storage.service';

const prefix = `phase8-${randomUUID()}`;
const assert = (value: unknown, message: string) => { if (!value) throw new Error(`FAIL: ${message}`); };
const auth = (user: any, tenantId = user.tenantId): any => ({ sub: user.id, email: user.email, role: user.role, tenantId, organizationRole: user.organizationRole });
const expectForbidden = async (action: () => Promise<unknown>, message: string) => { const error = await action().then(() => null).catch((e) => e); assert(error?.status === 403 || error?.getStatus?.() === 403, message); };

async function main() {
  const prisma = new PrismaService(); await prisma.$connect();
  const storage = new StorageService(); const audit = new AuditService(new RequestContextService()); const outbox = new OutboxService(prisma); const readiness = new FulfilmentReadinessService();
  const generation = new VoucherGenerationService(prisma, storage, audit, outbox, readiness); const lifecycle = new FulfilmentLifecycleService(audit, outbox); const fulfilment = new FulfilmentService(prisma, storage, audit, outbox, readiness, generation); const files = new FilesService(prisma, storage);
  const bookingIds: string[] = []; const fileKeys: string[] = []; const results: Record<string, string> = {};
  try {
    const agentUser = await prisma.user.findUniqueOrThrow({ where: { email: 'agent@voya.demo' } }); const vendorUser = await prisma.user.findUniqueOrThrow({ where: { email: 'vendor@voya.demo' } }); const vendorB = await prisma.user.findFirst({ where: { role: UserRole.VENDOR, tenantId: { not: vendorUser.tenantId } } });
    const plan: any = await prisma.ratePlan.findFirst({ where: { status: 'ACTIVE', variant: { product: { currentRevisionId: { not: null } } }, scheduleMappings: { some: { active: true } } }, include: { variant: { include: { product: { include: { currentRevision: true } } } }, scheduleMappings: { where: { active: true }, include: { scheduleTemplate: true } } }, orderBy: { updatedAt: 'desc' } });
    assert(plan && vendorUser.tenantId && agentUser.tenantId, 'fixture rate plan, vendor and agent exist');
    const session: any = await prisma.serviceSession.findFirst({ where: { scheduleTemplateId: { in: plan.scheduleMappings.map((item: any) => item.scheduleTemplateId) }, status: 'OPEN', serviceDate: { gte: new Date(Date.now() + 86400000) } }, include: { scheduleTemplate: true } });
    assert(session, 'a future service session exists');
    const vendor = auth(vendorUser); const agent = auth(agentUser); const policy = { id: `policy-${prefix}`, revisionId: plan.variant.product.currentRevisionId, version: 1, mode: FulfilmentMode.AUTO, requiredEvidenceKinds: [], evidenceMatchMode: 'ALL', reviewRequired: false, operationsContact: { name: 'Voya Operations', phone: '+91 9000000000' }, emergencyContact: { name: 'Duty Manager', phone: '+91 9111111111' }, howToRedeem: ['Show this voucher at the meeting point'], voucherNotes: ['Arrive 15 minutes early'] };
    const booking: any = await prisma.booking.create({ data: { recordType: 'CANONICAL', bookingCode: `VY-${prefix.slice(-12).toUpperCase()}`, vendorTenantId: vendorUser.tenantId, agentTenantId: agentUser.tenantId, agentUserId: agentUser.id, productId: plan.variant.product.id, productRevisionId: plan.variant.product.currentRevisionId, variantId: plan.variant.id, ratePlanId: plan.id, sessionId: session.id, bookingMode: BookingMode.INSTANT, channel: 'VOYA_AGENT', serviceDate: session.serviceDate, serviceTimezone: session.scheduleTemplate.timezone, pax: 1, paxBreakdown: { ADULT: 1 }, capacityConsumption: 1, amount: 100, currency: 'INR', status: BookingStatus.CONFIRMED, confirmedAt: new Date(), customerName: 'Phase 8 Demo Traveller', customerEmail: 'phase8@example.com', idempotencyKey: `${prefix}-key`, requestFingerprint: `${prefix}-request` } }); bookingIds.push(booking.id);
    await prisma.bookingSnapshot.create({ data: { bookingId: booking.id, productRevisionId: plan.variant.product.currentRevisionId, scheduleTemplateId: session.scheduleTemplateId, sessionId: session.id, productSnapshot: { productName: 'Phase 8 Demo Activity' }, variantSnapshot: { name: plan.variant.name }, ratePlanSnapshot: { ratePlanCode: plan.ratePlanCode }, sessionSnapshot: { serviceDate: session.serviceDate.toISOString(), localStartTime: '09:00', timezone: session.scheduleTemplate.timezone, startsAt: new Date(Date.now() + 86400000).toISOString(), endsAt: new Date(Date.now() - 60000).toISOString() }, travellerSummary: { ADULT: 1 }, capacityUnit: session.scheduleTemplate.capacityUnit, capacityConsumption: 1, bookingMode: BookingMode.INSTANT, cancellationPolicySnapshot: [], cancellationPolicyFingerprint: `${prefix}-cancel`, cancellationAcknowledgedAt: new Date(), questionsSnapshot: [], bookingAnswers: {}, agentSnapshot: { tenantId: agentUser.tenantId, tenantName: 'Demo Agent' }, channelSnapshot: {}, confirmationPolicySnapshot: {}, fulfilmentPolicySnapshot: policy, pickupSnapshot: { address: 'Main meeting point' } } });
    await prisma.bookingTraveller.create({ data: { bookingId: booking.id, travellerType: 'ADULT', sequence: 1, quantity: 1, fullName: 'Phase 8 Demo Traveller', email: 'phase8@example.com', phone: '+919999999999', isLead: true } });
    const aggregate: any = await prisma.bookingFulfilment.create({ data: { bookingId: booking.id, mode: FulfilmentMode.AUTO, status: BookingFulfilmentStatus.READY_FOR_VOUCHER, generationStatus: VoucherGenerationStatus.PENDING, generationRequestedAt: new Date() } });
    const aggregateCheck: any = await prisma.bookingFulfilment.findUniqueOrThrow({ where: { id: aggregate.id } }); assert(aggregateCheck.mode === FulfilmentMode.AUTO, 'booking fulfilment aggregate is persisted'); results.snapshotAndAggregate = 'PASS';

    const modeChecks = [
      [FulfilmentMode.AUTO, [], true],
      [FulfilmentMode.PNR_ONLY, [], false],
      [FulfilmentMode.PNR_ONLY, [{ kind: FulfilmentEvidenceKind.PNR_REFERENCE, status: 'CURRENT' }], true],
      [FulfilmentMode.TICKET_QR, [{ kind: FulfilmentEvidenceKind.QR_TOKEN, status: 'CURRENT' }], true],
      [FulfilmentMode.AFTER_FULFILMENT, [{ kind: FulfilmentEvidenceKind.PNR_REFERENCE, status: 'CURRENT' }], false],
    ] as const;
    for (const [mode, evidence, expected] of modeChecks) assert(readiness.evaluate({ booking, fulfilment: { mode }, policy: { ...policy, mode, requiredEvidenceKinds: mode === FulfilmentMode.AFTER_FULFILMENT ? [FulfilmentEvidenceKind.PNR_REFERENCE, FulfilmentEvidenceKind.TICKET_FILE] : [] }, evidence }).ready === expected, `${mode} readiness is correct`); results.readinessMatrix = 'PASS';

    const finalized: any = await generation.processNext(); assert(finalized.processed && finalized.voucherId, 'voucher generation publishes a current version'); const voucher: any = await prisma.voucherVersion.findUniqueOrThrow({ where: { id: finalized.voucherId }, include: { fileAsset: true } }); assert(voucher.status === VoucherVersionStatus.CURRENT && voucher.fileAsset.entityType === 'VoucherVersion', 'voucher version and private file asset are linked'); assert(voucher.versionNumber === finalized.generatedPayload.voucherVersion && voucher.voucherCode === finalized.generatedPayload.voucherCode && voucher.generatedAt.toISOString() === finalized.generatedPayload.generatedAt, 'VoucherVersion identity matches the generated PDF payload'); results.voucherVersioning = 'PASS';
    const vendorFile = await files.content(vendor, voucher.fileAssetId); assert(vendorFile.buffer.length > 0, 'vendor can retrieve its voucher file'); await expectForbidden(() => files.content({ ...agent, tenantId: vendorB?.tenantId ?? 'wrong-tenant' }, voucher.fileAssetId), 'cross-tenant agent voucher access is denied'); results.fileAuthorization = 'PASS';

    const failed = await generation.retry(aggregate.id); assert(failed.generationStatus === VoucherGenerationStatus.PENDING, 'successful voucher can be explicitly retried'); const failure: any = await generation.processNext({ forceFailure: true }); assert(failure.status === VoucherGenerationStatus.FAILED, 'worker failure is recorded without changing booking state'); const afterFailure: any = await prisma.booking.findUniqueOrThrow({ where: { id: booking.id } }); assert(afterFailure.status === BookingStatus.CONFIRMED, 'voucher failure leaves booking confirmed'); results.workerFailureRetry = 'PASS';
    await generation.retry(aggregate.id); const retried: any = await generation.processNext(); assert(!retried.stale && retried.voucherId, 'retry can publish a new voucher version'); results.retryPublish = 'PASS';

    const beforeEvidence: any = await prisma.bookingFulfilment.findUniqueOrThrow({ where: { id: aggregate.id }, include: { evidence: true } }); await prisma.bookingSnapshot.update({ where: { bookingId: booking.id }, data: { fulfilmentPolicySnapshot: { ...policy, mode: FulfilmentMode.PNR_ONLY } } }); await prisma.bookingFulfilment.update({ where: { id: aggregate.id }, data: { mode: FulfilmentMode.PNR_ONLY, status: BookingFulfilmentStatus.WAITING_EVIDENCE, generationStatus: VoucherGenerationStatus.NOT_REQUESTED } }); const evidenceResult: any = await fulfilment.addReference(vendor, booking.id, FulfilmentEvidenceKind.PNR_REFERENCE, { referenceValue: 'PNR-PHASE8-001', travellerVisible: true } as any); assert(evidenceResult.evidence.status === FulfilmentEvidenceStatus.CURRENT && evidenceResult.evidence.versionNumber === 1, 'PNR evidence is versioned and becomes current'); const replaced: any = await fulfilment.replaceReference(vendor, evidenceResult.evidence.id, { kind: FulfilmentEvidenceKind.PNR_REFERENCE, referenceValue: 'PNR-PHASE8-002', travellerVisible: true } as any); assert(replaced.evidence.versionNumber === 2 && replaced.evidence.replacesEvidenceId === evidenceResult.evidence.id, 'reference replacement preserves lineage'); const afterEvidence: any = await prisma.bookingFulfilment.findUniqueOrThrow({ where: { id: aggregate.id }, include: { evidence: true } }); assert(beforeEvidence.evidence.length === 0 && afterEvidence.evidence.filter((item: any) => item.status === FulfilmentEvidenceStatus.CURRENT).length === 1, 'only one current evidence record exists'); results.evidenceVersioning = 'PASS';
    const attachment: any = await fulfilment.upload(vendor, booking.id, FulfilmentEvidenceKind.SUPPLIER_ATTACHMENT, { buffer: Buffer.from('%PDF-phase8'), size: 11, mimetype: 'application/pdf', originalname: 'supplier.pdf' }, { travellerVisible: true } as any); assert(attachment.evidence.fileAssetId, 'uploaded evidence returns its file asset'); await expectForbidden(() => files.content(agent, attachment.evidence.fileAssetId), 'non-traveller-visible supplier attachment is denied to agent'); results.fileEvidenceVisibility = 'PASS';

    const finalised: any = await generation.processNext(); assert(!finalised.stale && finalised.voucherId, 'voucher regenerates after evidence is replaced');
    const manifest: any = await fulfilment.manifest(vendor, session.serviceDate.toISOString().slice(0, 10)); assert(manifest.sessions.some((item: any) => item.pickupGroups.some((group: any) => group.bookings.some((row: any) => row.bookingCode === booking.bookingCode))), 'vendor manifest includes the canonical booking'); const csv = await fulfilment.manifestCsv(vendor, session.serviceDate.toISOString().slice(0, 10)); assert(csv.includes('bookingCode') && csv.includes(booking.bookingCode) && !csv.includes('phase8@example.com'), 'manifest CSV is operational and excludes email'); results.manifestPrivacy = 'PASS';
    const redemption: any = await fulfilment.checkIn(vendor, booking.id, 'Phase 8 verifier'); const redemptionAgain: any = await fulfilment.checkIn(vendor, booking.id); assert(redemption.id === redemptionAgain.id && (await prisma.booking.findUniqueOrThrow({ where: { id: booking.id } })).status === BookingStatus.REDEEMED, 'check-in is idempotent and transitions booking to redeemed'); const completed: any = await fulfilment.complete(vendor, booking.id, { reason: 'Service completed in verifier' }); assert(completed.status === BookingStatus.COMPLETED, 'completion requires redeemed and records completed'); results.checkInCompletion = 'PASS';
    const voided: any = await prisma.$transaction((tx) => lifecycle.voidForCancellationInTransaction(tx, booking.id, vendor, 'Phase 8 cancellation void test')); assert(voided?.status === BookingFulfilmentStatus.VOIDED, 'cancellation voids fulfilment and voucher generation'); const voidVoucher: any = await prisma.voucherVersion.findFirst({ where: { fulfilmentId: aggregate.id, status: VoucherVersionStatus.VOID } }); assert(voidVoucher, 'current voucher is voided by cancellation lifecycle'); results.cancellationRaceGuard = 'PASS';
    console.log(JSON.stringify({ passing: true, prefix, results, bookingId: booking.id, voucherVersions: await prisma.voucherVersion.count({ where: { fulfilmentId: aggregate.id } }), currentEvidence: await prisma.fulfilmentEvidence.count({ where: { fulfilmentId: aggregate.id, status: FulfilmentEvidenceStatus.CURRENT } }) }, null, 2));
  } finally {
    const ids = bookingIds; if (ids.length) { const fulfilmentIds = (await prisma.bookingFulfilment.findMany({ where: { bookingId: { in: ids } }, select: { id: true } }).catch(() => [] as any[])).map((row: any) => row.id); const voucherRows = await prisma.voucherVersion.findMany({ where: { bookingId: { in: ids } }, select: { id: true, fileAssetId: true } }).catch(() => [] as any[]); const evidenceRows = await prisma.fulfilmentEvidence.findMany({ where: { fulfilmentId: { in: fulfilmentIds } }, select: { id: true, fileAssetId: true } }).catch(() => [] as any[]); await prisma.voucherShareEvent.deleteMany({ where: { bookingId: { in: ids } } }).catch(() => undefined); await prisma.bookingRedemption.deleteMany({ where: { bookingId: { in: ids } } }).catch(() => undefined); await prisma.voucherVersion.deleteMany({ where: { bookingId: { in: ids } } }).catch(() => undefined); await prisma.fulfilmentEvidence.deleteMany({ where: { fulfilmentId: { in: fulfilmentIds } } }).catch(() => undefined); await prisma.bookingFulfilment.deleteMany({ where: { bookingId: { in: ids } } }).catch(() => undefined); await prisma.fileAsset.deleteMany({ where: { id: { in: [...voucherRows.map((row: any) => row.fileAssetId), ...evidenceRows.map((row: any) => row.fileAssetId)].filter(Boolean) } } }).catch(() => undefined); await prisma.bookingTraveller.deleteMany({ where: { bookingId: { in: ids } } }).catch(() => undefined); await prisma.bookingSnapshot.deleteMany({ where: { bookingId: { in: ids } } }).catch(() => undefined); await prisma.bookingEvent.deleteMany({ where: { bookingId: { in: ids } } }).catch(() => undefined); await prisma.booking.deleteMany({ where: { id: { in: ids } } }).catch(() => undefined); } for (const key of fileKeys.filter(Boolean)) await storage.remove(key); await prisma.$disconnect();
  }
}

main().catch((error) => { console.error(error?.stack || error?.message || error); process.exitCode = 1; });
