import { EvidenceMatchMode, FulfilmentMode, PrismaClient } from '@prisma/client';
import { CommercialCalculatorService } from '../src/commercial/commercial-calculator.service';
import { CommercialService } from '../src/commercial/commercial.service';
import { EligibilityService } from '../src/eligibility/eligibility.service';
import { CutoffService } from '../src/eligibility/cutoff.service';
import { MarketplaceService } from '../src/marketplace/marketplace.service';
import { MarketplaceRankingService } from '../src/marketplace/marketplace-ranking.service';
import { ResourcesService } from '../src/resources/resources.service';

async function main() {
  const prisma = new PrismaClient(); const audit = { write: async () => undefined } as any; const outbox = { enqueue: async () => undefined } as any; const commercial = new CommercialService(prisma as any, audit, outbox, new CommercialCalculatorService()); const resources = new ResourcesService(prisma as any, audit, outbox); const eligibility = new EligibilityService(prisma as any, commercial, resources, new CutoffService()); const marketplace = new MarketplaceService(prisma as any, eligibility, new MarketplaceRankingService());
  const snapshot = async () => ({ products: await prisma.product.count(), variants: await prisma.productVariant.count(), ratePlans: await prisma.ratePlan.count(), serviceSessions: await prisma.serviceSession.count(), inventoryStates: await prisma.inventoryState.count(), bookings: await prisma.booking.count(), inventoryHolds: await prisma.inventoryHold.count(), inventoryAllocations: await prisma.inventoryAllocation.count() });
  const agent = await prisma.tenant.findFirst({ where: { slug: 'demo-travel-agent', kind: 'TRAVEL_AGENT', agentProfile: { verificationStatus: 'APPROVED' } } });
  const plan: any = await prisma.ratePlan.findFirst({ where: { ratePlanCode: 'RP-DEMO-001', channelMappings: { some: { enabled: true, channel: { code: 'VOYA_AGENT' } } } }, include: { variant: { include: { product: true, schedules: true } } } });
  const tomorrow = new Date(); tomorrow.setUTCHours(0, 0, 0, 0); tomorrow.setUTCDate(tomorrow.getUTCDate() + 1);
  const controlledSchedule = plan?.variant.schedules.find((schedule: any) => schedule.scheduleCode === 'SEED-SUNRISE-SHARED');
  const candidateSessions: any[] = controlledSchedule ? await prisma.serviceSession.findMany({ where: { scheduleTemplateId: controlledSchedule.id, serviceDate: { gte: tomorrow }, status: 'OPEN', archivedAt: null }, include: { inventoryState: true }, orderBy: { serviceDate: 'asc' } }) : [];
  const session: any = candidateSessions.find((item) => Number(item.inventoryState?.totalCapacity ?? 0) - Number(item.inventoryState?.blockedCapacity ?? 0) - Number(item.inventoryState?.heldCapacity ?? 0) - Number(item.inventoryState?.confirmedCapacity ?? 0) >= 2) ?? candidateSessions[0];
  if (!agent || !plan || !session) throw new Error('Controlled Phase 5 fixture is incomplete; run npm run prisma:seed first.');
  const policyRevisionId = plan.variant.product.currentRevisionId; const originalFulfilmentPolicy: any = await prisma.productFulfilmentPolicy.findUnique({ where: { productRevisionId: policyRevisionId } }); await prisma.productFulfilmentPolicy.upsert({ where: { productRevisionId: policyRevisionId }, update: { mode: FulfilmentMode.AUTO, requiredEvidenceKinds: [], evidenceMatchMode: EvidenceMatchMode.ALL, reviewRequired: false }, create: { productRevisionId: policyRevisionId, mode: FulfilmentMode.AUTO, requiredEvidenceKinds: [], evidenceMatchMode: EvidenceMatchMode.ALL, reviewRequired: false, voucherNotes: [] } });
  const before = { counts: await snapshot(), state: await prisma.inventoryState.findUnique({ where: { sessionId: session.id }, select: { heldCapacity: true, confirmedCapacity: true, blockedCapacity: true } }) };
  const safeNow = session.startsAt ? new Date(new Date(session.startsAt).getTime() - 10_800_000) : new Date(new Date(session.serviceDate).getTime() - 86_400_000);
  const input = { agentTenantId: agent.id, ratePlanId: plan.id, sessionId: session.id, travellers: [{ travellerType: 'ADULT' as const, quantity: 2 }], now: safeNow, channelCode: 'VOYA_AGENT' };
  const passing = await eligibility.evaluate(input); if (!passing.eligible) throw new Error(`Expected controlled offer to pass: ${JSON.stringify(passing.gates.filter((g) => g.status === 'FAIL'))}`);
  const vendorId = plan.variant.product.tenantId;
  const originalSchedule = { capacityUnit: controlledSchedule.capacityUnit, capacityUnitReviewRequired: controlledSchedule.capacityUnitReviewRequired };
  const originalPlan = { dateLevelCutoffTime: plan.dateLevelCutoffTime };
  const originalSession = { startsAt: session.startsAt };
  const originalState = await prisma.inventoryState.findUniqueOrThrow({ where: { sessionId: session.id }, select: { totalCapacity: true, blockedCapacity: true, heldCapacity: true, confirmedCapacity: true } });
  const originalVendorProfile = await prisma.vendorProfile.findUniqueOrThrow({ where: { tenantId: vendorId }, select: { verificationStatus: true } });
  let missingCutoff = false; let explicitDateLevelCutoff = false; let unitQuantityRequired = false; let unitQuantityTwo = false;
  try {
    await prisma.serviceSession.update({ where: { id: session.id }, data: { status: 'BLACKOUT' } }); const blackout = await eligibility.evaluate(input); if (!blackout.gates.some((g) => g.code === 'SESSION_BLACKOUT')) throw new Error('BLACKOUT did not produce SESSION_BLACKOUT');
    await prisma.serviceSession.update({ where: { id: session.id }, data: { status: 'OPEN' } });
    const belowRequiredCapacity = originalState.blockedCapacity + originalState.heldCapacity + originalState.confirmedCapacity; await prisma.inventoryState.update({ where: { sessionId: session.id }, data: { totalCapacity: belowRequiredCapacity } }); const insufficient = await eligibility.evaluate(input); if (!insufficient.gates.some((g) => g.code === 'INSUFFICIENT_INVENTORY')) throw new Error('Below-required inventory did not produce INSUFFICIENT_INVENTORY'); await prisma.inventoryState.update({ where: { sessionId: session.id }, data: { totalCapacity: originalState.totalCapacity } });
    await prisma.vendorProfile.update({ where: { tenantId: vendorId }, data: { verificationStatus: 'SUSPENDED' } }); const suspended = await eligibility.evaluate(input); if (!suspended.gates.some((g) => g.code === 'VENDOR_SUSPENDED')) throw new Error('Suspended vendor did not produce VENDOR_SUSPENDED'); await prisma.vendorProfile.update({ where: { tenantId: vendorId }, data: { verificationStatus: originalVendorProfile.verificationStatus } });
    await prisma.serviceSession.update({ where: { id: session.id }, data: { startsAt: null } }); await prisma.ratePlan.update({ where: { id: plan.id }, data: { dateLevelCutoffTime: null } }); const missingCutoffResult = await eligibility.evaluate(input); if (missingCutoffResult.eligible || !missingCutoffResult.gates.some((g) => g.code === 'CUTOFF_REFERENCE_MISSING')) throw new Error('Missing cutoff reference was not rejected'); missingCutoff = true; await prisma.ratePlan.update({ where: { id: plan.id }, data: { dateLevelCutoffTime: '23:59' } }); const explicitCutoffResult = await eligibility.evaluate(input); if (!explicitCutoffResult.gates.some((g) => g.gate === 'CUTOFF' && g.status === 'PASS')) throw new Error('Explicit date-level cutoff did not pass before its local cutoff'); explicitDateLevelCutoff = true;
    await prisma.ratePlan.update({ where: { id: plan.id }, data: { dateLevelCutoffTime: originalPlan.dateLevelCutoffTime } }); await prisma.serviceSession.update({ where: { id: session.id }, data: { startsAt: originalSession.startsAt } });
    const unitCapacity = Math.max(originalState.totalCapacity, 2 + originalState.blockedCapacity + originalState.heldCapacity + originalState.confirmedCapacity); await prisma.scheduleTemplate.update({ where: { id: controlledSchedule.id }, data: { capacityUnit: 'UNIT', capacityUnitReviewRequired: false } }); await prisma.inventoryState.update({ where: { sessionId: session.id }, data: { totalCapacity: unitCapacity } }); const missingUnits = await eligibility.evaluate(input); if (missingUnits.eligible || !missingUnits.gates.some((g) => g.code === 'UNIT_QUANTITY_REQUIRED')) throw new Error('UNIT capacity without units was not rejected'); unitQuantityRequired = true; const unitsPass = await eligibility.evaluate({ ...input, units: 2 }); if (!unitsPass.eligible || !unitsPass.gates.some((g) => g.gate === 'CAPACITY' && g.status === 'PASS')) throw new Error('UNIT capacity with two units did not pass'); unitQuantityTwo = true;
    await prisma.scheduleTemplate.update({ where: { id: controlledSchedule.id }, data: originalSchedule }); await prisma.inventoryState.update({ where: { sessionId: session.id }, data: { totalCapacity: originalState.totalCapacity } });
    const search = await marketplace.search({ role: 'TRAVEL_AGENT', tenantId: agent.id, sub: 'phase5-verify', email: 'agent@voya.demo' }, { serviceDate: session.serviceDate.toISOString(), travellers: input.travellers, limit: 50 }); if (!search.products.length) throw new Error('Marketplace search returned no controlled eligible product');
  } finally { await prisma.serviceSession.update({ where: { id: session.id }, data: { status: 'OPEN', startsAt: originalSession.startsAt } }); await prisma.ratePlan.update({ where: { id: plan.id }, data: { dateLevelCutoffTime: originalPlan.dateLevelCutoffTime } }); await prisma.scheduleTemplate.update({ where: { id: controlledSchedule.id }, data: originalSchedule }); await prisma.inventoryState.update({ where: { sessionId: session.id }, data: { totalCapacity: originalState.totalCapacity } }); await prisma.vendorProfile.update({ where: { tenantId: vendorId }, data: { verificationStatus: originalVendorProfile.verificationStatus } }); if (originalFulfilmentPolicy) await prisma.productFulfilmentPolicy.update({ where: { id: originalFulfilmentPolicy.id }, data: { mode: originalFulfilmentPolicy.mode, requiredEvidenceKinds: originalFulfilmentPolicy.requiredEvidenceKinds, evidenceMatchMode: originalFulfilmentPolicy.evidenceMatchMode, reviewRequired: originalFulfilmentPolicy.reviewRequired, voucherNotes: originalFulfilmentPolicy.voucherNotes, emergencyContactName: originalFulfilmentPolicy.emergencyContactName, emergencyContactPhone: originalFulfilmentPolicy.emergencyContactPhone, emergencyContactEmail: originalFulfilmentPolicy.emergencyContactEmail, operationsContactName: originalFulfilmentPolicy.operationsContactName, operationsContactPhone: originalFulfilmentPolicy.operationsContactPhone, operationsContactEmail: originalFulfilmentPolicy.operationsContactEmail } }); else await prisma.productFulfilmentPolicy.delete({ where: { productRevisionId: policyRevisionId } }); }
  const after = { counts: await snapshot(), state: await prisma.inventoryState.findUnique({ where: { sessionId: session.id }, select: { heldCapacity: true, confirmedCapacity: true, blockedCapacity: true } }) }; if (JSON.stringify(before) !== JSON.stringify(after)) throw new Error(`Read-only search invariant changed: before=${JSON.stringify(before)} after=${JSON.stringify(after)}`);
  console.log(JSON.stringify({ passing: true, blackout: 'SESSION_BLACKOUT', insufficient: 'INSUFFICIENT_INVENTORY', suspendedVendor: 'VENDOR_SUSPENDED', missingCutoff, explicitDateLevelCutoff, unitQuantityRequired, unitQuantityTwo, readOnly: true, countsBefore: before.counts, countsAfter: after.counts, productCount: 1 }, null, 2)); await prisma.$disconnect();
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
