import { PrismaClient } from '@prisma/client';
import { InventoryService } from '../src/inventory/inventory.service';
import { InventoryReservationService } from '../src/inventory/inventory-reservation.service';
import { ResourcesService } from '../src/resources/resources.service';
import { ScheduleOperationalStateService } from '../src/schedules/schedule-operational-state.service';

const prisma = new PrismaClient();
const user: any = { sub: 'phase4-2-verifier', email: 'phase4-2-verifier@example.com', role: 'VENDOR', tenantId: '' };
const assert = (value: unknown, message: string) => { if (!value) throw new Error(`FAIL: ${message}`); };

async function expectCode(fn: () => Promise<unknown>, code: string) { let rejected = false; try { await fn(); } catch (error) { rejected = true; assert(String((error as Error).message).includes(code), `error is ${code}`); } assert(rejected, `expected ${code}`); }

async function main() {
  const variant = await prisma.productVariant.findFirst({ include: { product: true } }); assert(variant, 'an isolated verification variant exists'); user.tenantId = variant!.product.tenantId;
  const suffix = Date.now().toString();
  const schedule = await prisma.scheduleTemplate.create({ data: { variantId: variant!.id, scheduleCode: `PH42-${suffix}`, name: 'Phase 4.2 verification schedule', status: 'INACTIVE', operatingModel: 'MULTIPLE_SLOTS', timezone: 'Asia/Kolkata', effectiveFrom: new Date('2099-02-01T00:00:00.000Z'), effectiveTo: new Date('2099-02-02T00:00:00.000Z'), operatingDays: ['SUNDAY'], capacityUnit: 'PERSON', capacityUnitReviewRequired: false, defaultCapacity: 10, slotTemplates: { create: [{ slotCode: '09:00', startTime: '09:00', endTime: '10:00', rank: 0 }, { slotCode: '14:00', startTime: '14:00', endTime: '15:00', rank: 1 }] } }, include: { slotTemplates: true } });
  const date = new Date('2099-02-01T00:00:00.000Z'); const sessions = []; for (const slot of schedule.slotTemplates) { const session = await prisma.serviceSession.create({ data: { scheduleTemplateId: schedule.id, slotTemplateId: slot.id, serviceDate: date, sessionKey: slot.slotCode, localStartTime: slot.startTime, localEndTime: slot.endTime, startsAt: new Date(`2099-02-01T${slot.startTime}:00.000Z`), endsAt: new Date(`2099-02-01T${slot.endTime}:00.000Z`), status: 'OPEN' } }); await prisma.inventoryState.create({ data: { sessionId: session.id, totalCapacity: 10 } }); sessions.push(session); }
  const audit = { write: async () => undefined } as any; const outbox = { enqueue: async () => undefined } as any; const resources = new ResourcesService(prisma as any, audit, outbox); const operational = new ScheduleOperationalStateService(); const inventory = new InventoryService(prisma as any, audit, outbox, resources, operational); const reservations = new InventoryReservationService(prisma as any, audit, outbox, resources);
  try {
    let scheduleVersion = 1;
    const first = sessions[0]; const second = sessions[1];
    await inventory.bulkApply(user, { scheduleTemplateId: schedule.id, expectedScheduleVersion: scheduleVersion, rows: [{ sessionId: first.id, expectedInventoryVersion: 1, expectedSessionVersion: 1, sessionStatus: 'BLACKOUT', statusReason: 'Phase 4.2 blackout verification' }] }); scheduleVersion += 1;
    let state = await prisma.inventoryState.findUniqueOrThrow({ where: { sessionId: first.id } }); let session = await prisma.serviceSession.findUniqueOrThrow({ where: { id: first.id } }); assert(session.status === 'BLACKOUT', 'bulk BLACKOUT projects session status'); assert((await reservations.getAvailability(first.id)).availableCapacity === 0, 'BLACKOUT has zero effective availability');
    await inventory.bulkApply(user, { scheduleTemplateId: schedule.id, expectedScheduleVersion: scheduleVersion, rows: [{ sessionId: first.id, expectedInventoryVersion: state.version, expectedSessionVersion: session.version, sessionStatus: 'OPEN' }] }); scheduleVersion += 1; session = await prisma.serviceSession.findUniqueOrThrow({ where: { id: first.id } }); assert(session.status === 'OPEN', 'exact OPEN archives exact exception and reopens session');
    await prisma.$transaction(async (tx) => { await operational.setException(tx, { scheduleTemplateId: schedule.id, serviceDate: date, type: 'BLACKOUT', reason: 'global verification' }); await tx.scheduleTemplate.update({ where: { id: schedule.id }, data: { version: { increment: 1 } } }); }); scheduleVersion += 1; state = await prisma.inventoryState.findUniqueOrThrow({ where: { sessionId: first.id } }); session = await prisma.serviceSession.findUniqueOrThrow({ where: { id: first.id } }); const secondState = await prisma.inventoryState.findUniqueOrThrow({ where: { sessionId: second.id } }); const secondSession = await prisma.serviceSession.findUniqueOrThrow({ where: { id: second.id } });
    await expectCode(() => inventory.bulkApply(user, { scheduleTemplateId: schedule.id, expectedScheduleVersion: scheduleVersion, rows: [{ sessionId: first.id, expectedInventoryVersion: state.version, expectedSessionVersion: session.version, sessionStatus: 'OPEN' }] }), 'GLOBAL_EXCEPTION_REQUIRES_FULL_SCOPE');
    await inventory.bulkApply(user, { scheduleTemplateId: schedule.id, expectedScheduleVersion: scheduleVersion, rows: [{ sessionId: first.id, expectedInventoryVersion: state.version, expectedSessionVersion: session.version, sessionStatus: 'OPEN' }, { sessionId: second.id, expectedInventoryVersion: secondState.version, expectedSessionVersion: secondSession.version, sessionStatus: 'OPEN' }] }); scheduleVersion += 1; const openStatuses = await prisma.serviceSession.findMany({ where: { scheduleTemplateId: schedule.id }, select: { status: true } }); assert(openStatuses.every((item) => item.status === 'OPEN'), 'full-scope OPEN reopens every applicable session');
    const reviewedSchedule = await prisma.scheduleTemplate.create({ data: { variantId: variant!.id, scheduleCode: `PH42-REVIEW-${suffix}`, name: 'Phase 4.2 review gate schedule', status: 'INACTIVE', operatingModel: 'ALL_DAY', timezone: 'Asia/Kolkata', effectiveFrom: date, operatingDays: ['SUNDAY'], capacityUnit: 'PERSON', capacityUnitReviewRequired: true, defaultCapacity: 2 } }); const reviewedSession = await prisma.serviceSession.create({ data: { scheduleTemplateId: reviewedSchedule.id, serviceDate: date, sessionKey: 'DATE', status: 'OPEN' } }); await prisma.inventoryState.create({ data: { sessionId: reviewedSession.id, totalCapacity: 2 } }); const reviewedState = await prisma.inventoryState.findUniqueOrThrow({ where: { sessionId: reviewedSession.id } }); const hold = await prisma.inventoryHold.create({ data: { inventoryStateId: reviewedState.id, quantity: 1, expiresAt: new Date(Date.now() + 60_000), status: 'ACTIVE' } }); await expectCode(() => reservations.createHold({ sessionId: reviewedSession.id, quantity: 1 }), 'CAPACITY_UNIT_REVIEW_REQUIRED'); await expectCode(() => reservations.confirmDirect({ sessionId: reviewedSession.id, quantity: 1 }), 'CAPACITY_UNIT_REVIEW_REQUIRED'); await expectCode(() => reservations.convertHoldToConfirmed(hold.id), 'CAPACITY_UNIT_REVIEW_REQUIRED'); assert((await prisma.inventoryHold.findUniqueOrThrow({ where: { id: hold.id } })).status === 'ACTIVE', 'review-gated conversion leaves hold active'); await prisma.inventoryHold.delete({ where: { id: hold.id } }); await prisma.inventoryState.delete({ where: { sessionId: reviewedSession.id } }); await prisma.serviceSession.delete({ where: { id: reviewedSession.id } }); await prisma.scheduleTemplate.delete({ where: { id: reviewedSchedule.id } });
    console.log(JSON.stringify({ pass: true, bulkBlackout: 'projected', exactOpen: 'reopened', globalPartialOpen: 'rejected', globalFullOpen: 'reopened all', capacityReview: 'blocked hold/direct/convert' }, null, 2));
  } finally { await prisma.scheduleException.deleteMany({ where: { scheduleTemplateId: schedule.id } }); await prisma.inventoryAllocation.deleteMany({ where: { inventoryState: { sessionId: { in: sessions.map((item) => item.id) } } } }); await prisma.inventoryHold.deleteMany({ where: { inventoryState: { sessionId: { in: sessions.map((item) => item.id) } } } }); await prisma.inventoryState.deleteMany({ where: { sessionId: { in: sessions.map((item) => item.id) } } }); await prisma.serviceSession.deleteMany({ where: { id: { in: sessions.map((item) => item.id) } } }); await prisma.scheduleSlotTemplate.deleteMany({ where: { scheduleTemplateId: schedule.id } }); await prisma.scheduleTemplate.delete({ where: { id: schedule.id } }); }
}

main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
