import { INestApplication } from '@nestjs/common';
import { NestFactory } from '@nestjs/core';
import { BookingMode, BookingStatus, CancellationFinancialState, CancellationInitiator, Prisma } from '@prisma/client';
import { randomUUID } from 'crypto';
import { AppModule } from '../src/app.module';
import { AuditService } from '../src/audit/audit.service';
import { AuthUser } from '../src/common/auth.types';
import { RequestContextService } from '../src/common/request-context.service';
import { CancellationService } from '../src/bookings/cancellation.service';
import { AgentCancellationDto, OperationalCancellationDto } from '../src/bookings/cancellation.dto';
import { BookingProjectionService } from '../src/bookings/booking-projection.service';
import { BookingSnapshotService } from '../src/bookings/booking-snapshot.service';
import { BookingExpiryService } from '../src/bookings/booking-expiry.service';
import { BookingsService } from '../src/bookings/bookings.service';
import { CancellationPolicyService } from '../src/bookings/cancellation-policy.service';
import { CommercialCalculatorService } from '../src/commercial/commercial-calculator.service';
import { CommercialService } from '../src/commercial/commercial.service';
import { EligibilityService } from '../src/eligibility/eligibility.service';
import { CutoffService } from '../src/eligibility/cutoff.service';
import { InventoryReservationService } from '../src/inventory/inventory-reservation.service';
import { OutboxService } from '../src/outbox/outbox.service';
import { PrismaService } from '../src/prisma/prisma.service';
import { ResourcesService } from '../src/resources/resources.service';
import { StorageService } from '../src/storage/storage.service';

const prefix = `phase7-${randomUUID()}`;
const assert = (value: unknown, message: string) => { if (!value) throw new Error(`FAIL: ${message}`); };
const travellers = [{ travellerType: 'ADULT', quantity: 1 }];
const details = [{ travellerType: 'ADULT', quantity: 1, fullName: 'Phase 7 Lead', isLead: true }];
const include: any = { operationalSnapshot: true, economicsSnapshot: true, inventoryHolds: true, inventoryAllocations: true, travellers: true, events: true, cancellation: { include: { refund: true, financialEvents: true } } };

async function main() {
  const app: INestApplication = await NestFactory.create(AppModule, { logger: false });
  const prisma = app.get(PrismaService) as PrismaService;
  const requestContext = new RequestContextService(); const audit = new AuditService(requestContext); const outbox = new OutboxService(prisma); const resources = new ResourcesService(prisma, audit, outbox); const commercial = new CommercialService(prisma, audit, outbox, new CommercialCalculatorService()); const inventory = new InventoryReservationService(prisma, audit, outbox, resources); const eligibility = new EligibilityService(prisma, commercial, resources, new CutoffService()); const bookings = new BookingsService(prisma, new StorageService(), audit, outbox, eligibility, commercial, inventory, new CancellationPolicyService(), new BookingSnapshotService(), new BookingProjectionService()); const cancellation = new CancellationService(prisma, audit, outbox, inventory); const expiry = new BookingExpiryService(prisma, bookings);
  const created: string[] = []; const originalStates = new Map<string, any>(); let plan: any; let commercialVersion: any; let originalMode: BookingMode | null = null; let originalSla: number | null = null; let originalRules: any[] = []; let report: any = null;
  const counts = async () => ({ bookings: await prisma.booking.count(), cancellations: await prisma.bookingCancellation.count(), refunds: await prisma.refund.count(), financialEvents: await prisma.financialEvent.count(), holds: await prisma.inventoryHold.count(), allocations: await prisma.inventoryAllocation.count() });
  try {
    const agentUser = await prisma.user.findUniqueOrThrow({ where: { email: 'agent@voya.demo' } }); const vendorUser = await prisma.user.findUniqueOrThrow({ where: { email: 'vendor@voya.demo' } }); const adminUser = await prisma.user.findUniqueOrThrow({ where: { email: 'admin@voya.demo' } }); const asAuth = (user: any): AuthUser => ({ sub: user.id, email: user.email, role: user.role, tenantId: user.tenantId, organizationRole: user.organizationRole }); const agent = asAuth(agentUser); const vendor = asAuth(vendorUser); const admin = asAuth(adminUser);
    plan = await prisma.ratePlan.findFirstOrThrow({ where: { status: 'ACTIVE', channelMappings: { some: { enabled: true, channel: { code: 'VOYA_AGENT', active: true } } }, variant: { product: { currentRevisionId: { not: null } } } }, include: { variant: { include: { product: { include: { currentRevision: true } } } }, channelMappings: { where: { enabled: true, channel: { code: 'VOYA_AGENT' } }, include: { channel: true } }, scheduleMappings: { where: { active: true } } }, orderBy: { updatedAt: 'desc' } });
    commercialVersion = await prisma.ratePlanCommercialVersion.findFirstOrThrow({ where: { ratePlanId: plan.id, status: 'ACTIVE' }, orderBy: { versionNumber: 'desc' } }); originalMode = commercialVersion.bookingMode; originalSla = commercialVersion.confirmationSlaMinutes; originalRules = await prisma.cancellationRule.findMany({ where: { ratePlanId: plan.id }, orderBy: { minDaysBefore: 'asc' } });
    const sessions: any[] = await prisma.serviceSession.findMany({ where: { scheduleTemplateId: { in: plan.scheduleMappings.map((mapping: any) => mapping.scheduleTemplateId) }, status: 'OPEN', serviceDate: { gte: new Date(Date.now() + 86400000) }, scheduleTemplate: { capacityUnitReviewRequired: false, capacityUnit: 'PERSON' } }, include: { inventoryState: true, scheduleTemplate: true }, orderBy: [{ serviceDate: 'asc' }, { sessionKey: 'asc' }], take: 40 }); const usable = sessions.filter((session) => session.inventoryState && session.inventoryState.totalCapacity - session.inventoryState.blockedCapacity - session.inventoryState.heldCapacity - session.inventoryState.confirmedCapacity >= 2); assert(usable.length >= 8, `eight usable sessions available (found ${usable.length})`); for (const session of usable) originalStates.set(session.id, { totalCapacity: session.inventoryState.totalCapacity, blockedCapacity: session.inventoryState.blockedCapacity, heldCapacity: session.inventoryState.heldCapacity, confirmedCapacity: session.inventoryState.confirmedCapacity, version: session.inventoryState.version });
    const before = await counts();
    const setRules = async (rules: Array<{ minDaysBefore: number; maxDaysBefore?: number | null; chargeValue: string; chargeType: 'PERCENTAGE' | 'ABSOLUTE' }>) => { await prisma.cancellationRule.deleteMany({ where: { ratePlanId: plan.id } }); await prisma.cancellationRule.createMany({ data: rules.map((rule) => ({ ratePlanId: plan.id, minDaysBefore: rule.minDaysBefore, maxDaysBefore: rule.maxDaysBefore ?? null, chargeValue: new Prisma.Decimal(rule.chargeValue), chargeType: rule.chargeType })) }); };
    const create = async (session: any, label: string, mode: BookingMode) => { await prisma.ratePlanCommercialVersion.update({ where: { id: commercialVersion.id }, data: { bookingMode: mode, confirmationSlaMinutes: mode === BookingMode.INSTANT ? null : (originalSla || 60) } }); const preview: any = await bookings.preview(agent, { ratePlanId: plan.id, sessionId: session.id, travellers, travellerDetails: details }); assert(preview.eligible, `${label} preview eligible`); const key = `${prefix}-${label}-${randomUUID()}`; created.push(key); const result: any = await bookings.create(agent, { ratePlanId: plan.id, sessionId: session.id, travellers, travellerDetails: details, bookingAnswers: {}, customerName: `Phase 7 ${label}`, customerEmail: 'phase7@example.com', expectedQuoteFingerprint: preview.quoteFingerprint, expectedCancellationPolicyFingerprint: preview.cancellationPolicyFingerprint, expectedContextFingerprint: preview.contextFingerprint, cancellationPolicyAcknowledged: true }, key); return { id: result.id, preview, row: await prisma.booking.findUniqueOrThrow({ where: { id: result.id }, include }) }; };
    const rows: any = {};
    await setRules([{ minDaysBefore: 0, maxDaysBefore: null, chargeValue: '0', chargeType: 'PERCENTAGE' }]); rows.free = await create(usable[0], 'free', BookingMode.INSTANT); await setRules([{ minDaysBefore: 0, maxDaysBefore: null, chargeValue: '50', chargeType: 'PERCENTAGE' }]); rows.penalty = await create(usable[1], 'penalty', BookingMode.INSTANT); await setRules([{ minDaysBefore: 0, maxDaysBefore: null, chargeValue: '100', chargeType: 'PERCENTAGE' }]); rows.noRefund = await create(usable[2], 'no-refund', BookingMode.INSTANT);
    await setRules([{ minDaysBefore: 0, maxDaysBefore: null, chargeValue: '100', chargeType: 'PERCENTAGE' }]); const freePreview: any = await cancellation.agentPreview(agent, rows.free.id); assert(freePreview.eligible && new Prisma.Decimal(freePreview.cancellationCharge).eq(0) && new Prisma.Decimal(freePreview.refundEntitlement).eq(rows.free.row.economicsSnapshot.finalAmount), 'free cancellation uses snapshotted policy and full refund'); const freeCancel: any = await cancellation.agentCancel(agent, rows.free.id, { expectedCancellationFingerprint: freePreview.cancellationFingerprint, reasonCategory: 'CUSTOMER_REQUEST', reason: 'Phase 7 free cancellation', acknowledged: true }, `${prefix}-free-cancel`); const freeAgain: any = await cancellation.agentCancel(agent, rows.free.id, { expectedCancellationFingerprint: freePreview.cancellationFingerprint, reasonCategory: 'CUSTOMER_REQUEST', reason: 'Phase 7 free cancellation', acknowledged: true }, `${prefix}-free-cancel`); assert(freeCancel.id === freeAgain.id && freeCancel.status === BookingStatus.CANCELLED && freeCancel.financialState === CancellationFinancialState.REFUND_PENDING, 'agent cancellation is idempotent and preserves economics'); await cancellation.confirmRefund(admin, freeCancel.refund.id, { externalReference: `${prefix}-external-free` });
    const penaltyPreview: any = await cancellation.agentPreview(agent, rows.penalty.id); const penaltyAmount = new Prisma.Decimal(rows.penalty.row.economicsSnapshot.finalAmount.toString()); assert(penaltyPreview.eligible && new Prisma.Decimal(penaltyPreview.cancellationCharge).eq(penaltyAmount.div(2).toDecimalPlaces(2)) && new Prisma.Decimal(penaltyPreview.refundEntitlement).eq(penaltyAmount.div(2).toDecimalPlaces(2)), 'percentage penalty uses Decimal arithmetic'); const penaltyCancel: any = await cancellation.agentCancel(agent, rows.penalty.id, { expectedCancellationFingerprint: penaltyPreview.cancellationFingerprint, reasonCategory: 'CUSTOMER_REQUEST', reason: 'Phase 7 penalty cancellation', acknowledged: true }, `${prefix}-penalty-cancel`); await cancellation.failRefund(admin, penaltyCancel.refund.id, { reason: 'External processor unavailable' }); await cancellation.retryRefund(admin, penaltyCancel.refund.id); await cancellation.confirmRefund(admin, penaltyCancel.refund.id, { externalReference: `${prefix}-external-penalty` });
    const noRefundPreview: any = await cancellation.agentPreview(agent, rows.noRefund.id); assert(noRefundPreview.eligible && new Prisma.Decimal(noRefundPreview.cancellationCharge).eq(new Prisma.Decimal(rows.noRefund.row.economicsSnapshot.finalAmount.toString())) && new Prisma.Decimal(noRefundPreview.refundEntitlement).eq(0), '100 percent policy produces no refund'); const noRefundCancel: any = await cancellation.agentCancel(agent, rows.noRefund.id, { expectedCancellationFingerprint: noRefundPreview.cancellationFingerprint, reasonCategory: 'CUSTOMER_REQUEST', reason: 'Phase 7 no refund cancellation', acknowledged: true }, `${prefix}-no-refund-cancel`); assert(noRefundCancel.financialState === CancellationFinancialState.CANCELLED_NO_REFUND && !noRefundCancel.refund, 'no-refund cancellation creates no Refund instruction');
    await setRules(originalRules.map((rule) => ({ minDaysBefore: rule.minDaysBefore, maxDaysBefore: rule.maxDaysBefore, chargeValue: rule.chargeValue.toString(), chargeType: rule.chargeType }))); rows.vendor = await create(usable[3], 'vendor-cancel', BookingMode.INSTANT); const vendorResult: any = await cancellation.operationalCancel(vendor, rows.vendor.id, { reasonCategory: 'WEATHER', reason: 'Weather closure' }, CancellationInitiator.VENDOR, `${prefix}-vendor-cancel`); assert(vendorResult.status === BookingStatus.CANCELLED && vendorResult.financialState === CancellationFinancialState.CANCELLED_PENDING_FINANCIAL, 'vendor cancellation is operational and financially pending'); const vendorState = await prisma.inventoryState.findUniqueOrThrow({ where: { sessionId: usable[3].id } }); assert(vendorState.confirmedCapacity === originalStates.get(usable[3].id).confirmedCapacity, 'vendor cancellation releases confirmed capacity');
    rows.admin = await create(usable[4], 'admin-cancel', BookingMode.INSTANT); const adminResult: any = await cancellation.operationalCancel(admin, rows.admin.id, { reasonCategory: 'DUPLICATE', reason: 'Administrative correction' }, CancellationInitiator.ADMIN, `${prefix}-admin-cancel`); assert(adminResult.status === BookingStatus.CANCELLED && adminResult.financialState === CancellationFinancialState.CANCELLED_PENDING_FINANCIAL, 'admin cancellation is financially pending'); const adminAmount = rows.admin.row.economicsSnapshot.finalAmount.toString(); await cancellation.resolveFinancial(admin, adminResult.cancellation.id, { cancellationCharge: '0', refundEntitlement: adminAmount, reason: 'Finance approved full refund' });
    rows.pending = await create(usable[5], 'withdrawal', BookingMode.VENDOR_CONFIRMATION); const pendingPreview: any = await cancellation.agentPreview(agent, rows.pending.id); const pendingCancel: any = await cancellation.agentCancel(agent, rows.pending.id, { expectedCancellationFingerprint: pendingPreview.cancellationFingerprint, reasonCategory: 'CUSTOMER_REQUEST', reason: 'Customer withdrew request', acknowledged: true }, `${prefix}-withdrawal-cancel`); const pendingRow = await prisma.booking.findUniqueOrThrow({ where: { id: rows.pending.id }, include }); assert(pendingCancel.status === BookingStatus.CANCELLED && pendingRow.inventoryHolds[0].status === 'RELEASED' && pendingRow.inventoryAllocations.length === 0, 'pending withdrawal releases hold without allocation');
    const decisionRows: any[] = []; for (const [index, initiator] of [[6, CancellationInitiator.VENDOR], [7, CancellationInitiator.ADMIN]] as any[]) { const fixture = await create(usable[index], `double-${initiator.toLowerCase()}`, BookingMode.INSTANT); decisionRows.push(fixture); const dto: OperationalCancellationDto = { reasonCategory: initiator === CancellationInitiator.VENDOR ? 'VENDOR_OPERATIONAL' : 'OTHER', reason: 'Concurrent cancellation' }; const outcomes = await Promise.allSettled([cancellation.operationalCancel(initiator === CancellationInitiator.VENDOR ? vendor : admin, fixture.id, dto, initiator, `${prefix}-double-${index}`), cancellation.operationalCancel(initiator === CancellationInitiator.VENDOR ? vendor : admin, fixture.id, dto, initiator, `${prefix}-double-${index}`)]); const row = await prisma.booking.findUniqueOrThrow({ where: { id: fixture.id }, include }); assert(row.status === BookingStatus.CANCELLED && row.cancellation && row.inventoryAllocations.filter((allocation: any) => allocation.status === 'CONFIRMED').length === 0 && outcomes.some((outcome) => outcome.status === 'fulfilled'), `double ${initiator.toLowerCase()} cancellation releases once`); }
    const during = await counts(); report = { passing: true, prefix, before, during, flow: { freeSnapshotPolicy: 'PASS', penaltyDecimal: 'PASS', noRefund: 'PASS', historicalPolicyProtection: 'PASS', agentIdempotency: 'PASS', vendorCancellation: 'PASS', adminCancellation: 'PASS', pendingWithdrawal: 'PASS', refundConfirm: 'PASS', refundFailRetry: 'PASS', financeResolution: 'PASS', doubleCancelRace: 'PASS' }, cleanup: 'pending' };
  } finally {
    if (plan) { await prisma.ratePlanCommercialVersion.update({ where: { id: commercialVersion.id }, data: { bookingMode: originalMode, confirmationSlaMinutes: originalSla } }).catch(() => undefined); await prisma.cancellationRule.deleteMany({ where: { ratePlanId: plan.id } }).catch(() => undefined); if (originalRules.length) await prisma.cancellationRule.createMany({ data: originalRules.map((rule) => ({ id: rule.id, ratePlanId: plan.id, minDaysBefore: rule.minDaysBefore, maxDaysBefore: rule.maxDaysBefore, chargeValue: rule.chargeValue, chargeType: rule.chargeType })) }).catch(() => undefined); }
    const fixtures = await prisma.booking.findMany({ where: { idempotencyKey: { startsWith: prefix } }, select: { id: true } }); const ids = fixtures.map((row) => row.id); if (ids.length) { await prisma.$executeRawUnsafe(`DELETE FROM "public"."OutboxEvent" WHERE "aggregateId" = ANY($1::text[]) OR ("payload"->>'bookingId') = ANY($1::text[])`, ids).catch(() => undefined); await prisma.financialEvent.deleteMany({ where: { bookingId: { in: ids } } }).catch(() => undefined); await prisma.refund.deleteMany({ where: { bookingId: { in: ids } } }).catch(() => undefined); await prisma.bookingCancellation.deleteMany({ where: { bookingId: { in: ids } } }).catch(() => undefined); await prisma.inventoryAllocation.deleteMany({ where: { bookingId: { in: ids } } }).catch(() => undefined); await prisma.bookingEconomicsSnapshot.deleteMany({ where: { bookingId: { in: ids } } }).catch(() => undefined); await prisma.bookingSnapshot.deleteMany({ where: { bookingId: { in: ids } } }).catch(() => undefined); await prisma.inventoryHold.deleteMany({ where: { bookingId: { in: ids } } }).catch(() => undefined); await prisma.booking.deleteMany({ where: { id: { in: ids } } }).catch(() => undefined); }
    for (const [sessionId, state] of originalStates) await prisma.inventoryState.update({ where: { sessionId }, data: state }).catch(() => undefined); if (report) { report.after = await counts(); report.cleanup = 'complete'; console.log(JSON.stringify(report, null, 2)); } await app.close();
  }
}

main().catch((error) => { console.error(error?.stack || error?.message || error); process.exitCode = 1; });
