import { BookingFulfilmentStatus, BookingMode, BookingStatus, FulfilmentMode, Prisma, VoucherGenerationStatus, VoucherVersionStatus } from '@prisma/client';
import { randomUUID } from 'crypto';
import { AuditService } from '../src/audit/audit.service';
import { RequestContextService } from '../src/common/request-context.service';
import { FulfilmentLifecycleService } from '../src/fulfilment/fulfilment-lifecycle.service';
import { FulfilmentReadinessService } from '../src/fulfilment/fulfilment-readiness.service';
import { VoucherGenerationService } from '../src/fulfilment/voucher-generation.service';
import { OutboxService } from '../src/outbox/outbox.service';
import { PrismaService } from '../src/prisma/prisma.service';
import { StorageService } from '../src/storage/storage.service';

const prefix = `phase82-${randomUUID()}`;
const assert = (value: unknown, message: string) => { if (!value) throw new Error(`FAIL: ${message}`); };
const auth = (user: any) => ({ sub: user.id, email: user.email, role: user.role, tenantId: user.tenantId, organizationRole: user.organizationRole } as any);

async function main() {
  const prisma = new PrismaService(); await prisma.$connect();
  const storage = new StorageService(); const audit = new AuditService(new RequestContextService()); const outbox = new OutboxService(prisma); const readiness = new FulfilmentReadinessService();
  const generation = new VoucherGenerationService(prisma, storage, audit, outbox, readiness); const lifecycle = new FulfilmentLifecycleService(audit, outbox);
  let bookingId = ''; let fulfilmentId = ''; let vendor: any; let report: any;
  try {
    const vendorUser = await prisma.user.findUniqueOrThrow({ where: { email: 'vendor@voya.demo' } }); const agentUser = await prisma.user.findUniqueOrThrow({ where: { email: 'agent@voya.demo' } }); vendor = auth(vendorUser);
    const plan: any = await prisma.ratePlan.findFirstOrThrow({ where: { status: 'ACTIVE', variant: { product: { currentRevisionId: { not: null } } }, scheduleMappings: { some: { active: true } } }, include: { variant: { include: { product: true } }, scheduleMappings: { where: { active: true } } }, orderBy: { updatedAt: 'desc' } });
    const session: any = await prisma.serviceSession.findFirstOrThrow({ where: { scheduleTemplateId: { in: plan.scheduleMappings.map((item: any) => item.scheduleTemplateId) }, status: 'OPEN', serviceDate: { gte: new Date(Date.now() + 86400000) } }, include: { scheduleTemplate: true } });
    const policy = { id: `policy-${prefix}`, revisionId: plan.variant.product.currentRevisionId, version: 1, mode: FulfilmentMode.AUTO, requiredEvidenceKinds: [], evidenceMatchMode: 'ALL', reviewRequired: false, howToRedeem: ['Show the voucher at the meeting point'], voucherNotes: [] };
    const booking: any = await prisma.booking.create({ data: { recordType: 'CANONICAL', bookingCode: `VY-${prefix.slice(-12).toUpperCase()}`, vendorTenantId: vendorUser.tenantId, agentTenantId: agentUser.tenantId, agentUserId: agentUser.id, productId: plan.variant.product.id, productRevisionId: plan.variant.product.currentRevisionId, variantId: plan.variant.id, ratePlanId: plan.id, sessionId: session.id, bookingMode: BookingMode.INSTANT, channel: 'VOYA_AGENT', serviceDate: session.serviceDate, serviceTimezone: session.scheduleTemplate.timezone, pax: 1, paxBreakdown: { ADULT: 1 }, capacityConsumption: 1, amount: 100, currency: 'INR', status: BookingStatus.CONFIRMED, confirmedAt: new Date(), customerName: 'Phase 8.2 Concurrency Traveller', customerEmail: 'phase82@example.com', idempotencyKey: `${prefix}-key`, requestFingerprint: `${prefix}-request` } }); bookingId = booking.id;
    await prisma.bookingSnapshot.create({ data: { bookingId, productRevisionId: plan.variant.product.currentRevisionId, scheduleTemplateId: session.scheduleTemplateId, sessionId: session.id, productSnapshot: { productName: 'Phase 8.2 Activity' }, variantSnapshot: { name: plan.variant.name }, ratePlanSnapshot: { ratePlanCode: plan.ratePlanCode }, sessionSnapshot: { serviceDate: session.serviceDate.toISOString(), localStartTime: '09:00', timezone: session.scheduleTemplate.timezone, startsAt: new Date(Date.now() + 86400000).toISOString(), endsAt: new Date(Date.now() + 90000000).toISOString() }, travellerSummary: { ADULT: 1 }, capacityUnit: session.scheduleTemplate.capacityUnit, capacityConsumption: 1, bookingMode: BookingMode.INSTANT, cancellationPolicySnapshot: [], cancellationPolicyFingerprint: `${prefix}-cancel`, cancellationAcknowledgedAt: new Date(), questionsSnapshot: [], bookingAnswers: {}, agentSnapshot: { tenantId: agentUser.tenantId, tenantName: 'Demo Agent' }, channelSnapshot: {}, confirmationPolicySnapshot: {}, fulfilmentPolicySnapshot: policy, pickupSnapshot: { address: 'Main meeting point' } } });
    await prisma.bookingTraveller.create({ data: { bookingId, travellerType: 'ADULT', sequence: 1, quantity: 1, fullName: 'Phase 8.2 Concurrency Traveller', email: 'phase82@example.com', phone: '+919999999999', isLead: true } });
    const aggregate: any = await prisma.bookingFulfilment.create({ data: { bookingId, mode: FulfilmentMode.AUTO, status: BookingFulfilmentStatus.READY_FOR_VOUCHER, generationStatus: VoucherGenerationStatus.PENDING, generationRequestedAt: new Date() } }); fulfilmentId = aggregate.id;

    const doubleClaim = await Promise.all([generation.processNext(), generation.processNext()]); const completed = doubleClaim.filter((result: any) => result.processed && result.voucherId); const skipped = doubleClaim.filter((result: any) => !result.processed && result.reason === 'NO_PENDING_GENERATION');
    assert(completed.length === 1 && skipped.length === 1, 'two concurrent workers produce one claim and one no-pending result'); assert(await prisma.voucherVersion.count({ where: { fulfilmentId, status: VoucherVersionStatus.CURRENT } }) === 1, 'concurrent workers publish one current voucher');

    const oldVersion = (await prisma.bookingFulfilment.findUniqueOrThrow({ where: { id: fulfilmentId } })).version; const oldToken = `old-worker-${prefix}`; await prisma.bookingFulfilment.update({ where: { id: fulfilmentId }, data: { status: BookingFulfilmentStatus.READY_FOR_VOUCHER, generationStatus: VoucherGenerationStatus.PROCESSING, generationToken: oldToken, generationClaimedAt: new Date(Date.now() - 120000), generationLeaseExpiresAt: new Date(Date.now() - 60000), version: { increment: 1 } } }); const reclaimedVersion = (await prisma.bookingFulfilment.findUniqueOrThrow({ where: { id: fulfilmentId } })).version;
    const stale = await (generation as any).finalize(fulfilmentId, oldToken, reclaimedVersion - 1, {}, { storageKey: `${prefix}-stale.pdf`, sizeBytes: 1 }); assert(stale.stale && stale.status === 'STALE_GENERATION', 'stale worker cannot finalize after lease ownership changes'); const recovered: any = await generation.processNext(); assert(recovered.processed && recovered.voucherId && !recovered.stale, 'expired processing lease is reclaimed and finalized');

    const terminal: any = await prisma.$transaction((tx) => lifecycle.voidForTerminalOutcomeInTransaction(tx, bookingId, vendor, 'Phase 8.2 terminal tenant proof', 'COMPLETED')); assert(terminal.status === BookingFulfilmentStatus.VOIDED, 'terminal outcome voids fulfilment'); const auditRow: any = await prisma.auditLog.findFirst({ where: { entityId: fulfilmentId, action: 'VOUCHER_VOIDED' }, orderBy: { createdAt: 'desc' } }); const outboxRow: any = await prisma.outboxEvent.findFirst({ where: { aggregateId: fulfilmentId, eventType: 'VOUCHER_VOIDED' }, orderBy: { availableAt: 'desc' } }); assert(auditRow?.tenantId === vendor.tenantId && outboxRow?.tenantId === vendor.tenantId, 'terminal fulfilment audit and outbox use the booking vendor tenant');
    report = { passing: true, prefix, checks: { concurrentDoubleClaim: 'PASS', staleWorkerFinalizeGuard: 'PASS', expiredLeaseRecovery: 'PASS', terminalVendorTenantAudit: 'PASS' }, bookingId, fulfilmentId, currentVouchers: await prisma.voucherVersion.count({ where: { fulfilmentId, status: VoucherVersionStatus.CURRENT } }) };
  } finally {
    if (bookingId) { const fulfilments: any[] = await prisma.bookingFulfilment.findMany({ where: { bookingId }, select: { id: true } }).catch(() => []); const fids = fulfilments.map((row) => row.id); const vouchers: any[] = await prisma.voucherVersion.findMany({ where: { bookingId }, select: { id: true, fileAssetId: true } }).catch(() => []); const evidence: any[] = await prisma.fulfilmentEvidence.findMany({ where: { fulfilmentId: { in: fids } }, select: { id: true, fileAssetId: true } }).catch(() => []); const assets: any[] = await prisma.fileAsset.findMany({ where: { id: { in: [...vouchers.map((row) => row.fileAssetId), ...evidence.map((row) => row.fileAssetId)].filter(Boolean) } }, select: { id: true, storageKey: true } }).catch(() => []);
      await prisma.voucherShareEvent.deleteMany({ where: { bookingId } }).catch(() => undefined); await prisma.bookingRedemption.deleteMany({ where: { bookingId } }).catch(() => undefined); await prisma.voucherVersion.deleteMany({ where: { bookingId } }).catch(() => undefined); await prisma.fulfilmentEvidence.deleteMany({ where: { fulfilmentId: { in: fids } } }).catch(() => undefined); await prisma.bookingFulfilment.deleteMany({ where: { bookingId } }).catch(() => undefined); await prisma.fileAsset.deleteMany({ where: { id: { in: assets.map((row) => row.id) } } }).catch(() => undefined); await prisma.bookingTraveller.deleteMany({ where: { bookingId } }).catch(() => undefined); await prisma.bookingSnapshot.deleteMany({ where: { bookingId } }).catch(() => undefined); await prisma.bookingEvent.deleteMany({ where: { bookingId } }).catch(() => undefined); await prisma.booking.deleteMany({ where: { id: bookingId } }).catch(() => undefined); await prisma.auditLog.deleteMany({ where: { OR: [{ entityId: { in: [...fids, ...vouchers.map((row) => row.id)] } }, { metadata: { path: ['bookingId'], equals: bookingId } }] } }).catch(() => undefined); await prisma.outboxEvent.deleteMany({ where: { OR: [{ aggregateId: { in: fids } }, { payload: { path: ['bookingId'], equals: bookingId } }] } }).catch(() => undefined); for (const asset of assets) await storage.remove(asset.storageKey); }
    await prisma.$disconnect(); if (report) { console.log(JSON.stringify(report, null, 2)); }
  }
}

main().catch((error) => { console.error(error?.stack || error?.message || error); process.exitCode = 1; });
