import { PrismaClient } from '@prisma/client';
import { randomUUID } from 'crypto';

async function main() {
  const prisma = new PrismaClient();
  try {
    const counts = async () => ({ bookings: await prisma.booking.count(), snapshots: await prisma.bookingSnapshot.count(), economics: await prisma.bookingEconomicsSnapshot.count(), holds: await prisma.inventoryHold.count(), allocations: await prisma.inventoryAllocation.count(), travellers: await prisma.bookingTraveller.count(), events: await prisma.bookingEvent.count() });
    const legacy = await prisma.booking.findMany({ where: { recordType: 'LEGACY' }, select: { id: true, bookingCode: true, agentTenantId: true, agentUserId: true, productRevisionId: true, variantId: true, ratePlanId: true, sessionId: true, bookingMode: true, idempotencyKey: true, requestFingerprint: true, capacityConsumption: true } });
    const legacyModernRelations = await prisma.bookingSnapshot.count({ where: { booking: { recordType: 'LEGACY' } } }) + await prisma.bookingEconomicsSnapshot.count({ where: { booking: { recordType: 'LEGACY' } } }) + await prisma.inventoryHold.count({ where: { booking: { recordType: 'LEGACY' } } }) + await prisma.inventoryAllocation.count({ where: { booking: { recordType: 'LEGACY' } } });
    const legacyViolations = legacy.filter((row) => row.agentTenantId || row.agentUserId || row.productRevisionId || row.variantId || row.sessionId || row.bookingMode || row.idempotencyKey || row.requestFingerprint || row.capacityConsumption !== null).map((row) => row.bookingCode);
    const canonical = await prisma.booking.findMany({ where: { recordType: 'CANONICAL' }, select: { id: true, status: true, bookingMode: true, agentTenantId: true, idempotencyKey: true, requestFingerprint: true, confirmationDueAt: true } });
    const duplicateKeys = await prisma.$queryRawUnsafe<Array<{ agentTenantId: string; idempotencyKey: string; count: bigint }>>(`SELECT "agentTenantId", "idempotencyKey", COUNT(*) FROM "public"."Booking" WHERE "recordType" = 'CANONICAL' GROUP BY "agentTenantId", "idempotencyKey" HAVING COUNT(*) > 1`);
    const pendingLinkedHolds = await prisma.inventoryHold.count({ where: { bookingId: { not: null }, status: 'ACTIVE', booking: { status: { notIn: ['PENDING_VENDOR_CONFIRMATION', 'PENDING_MANUAL_REVIEW'] } } } });
    let concurrency: any = { status: 'SKIPPED', reason: 'No eligible future marketplace fixture was available.' };
    const fixtureAgent = await prisma.tenant.findFirst({ where: { kind: 'TRAVEL_AGENT', agentProfile: { verificationStatus: 'APPROVED' } } });
    const fixtureUser = fixtureAgent ? await prisma.user.findFirst({ where: { tenantId: fixtureAgent.id, role: 'TRAVEL_AGENT', active: true } }) : null;
    const fixturePlan: any = await prisma.ratePlan.findFirst({ where: { status: 'ACTIVE', channelMappings: { some: { enabled: true, channel: { code: 'VOYA_AGENT', active: true } } }, variant: { product: { currentRevisionId: { not: null } } } }, include: { variant: { include: { product: { include: { currentRevision: true } } } }, channelMappings: { where: { enabled: true, channel: { code: 'VOYA_AGENT' } }, include: { channel: true } }, scheduleMappings: { where: { active: true } } } });
    const fixtureSession: any = fixturePlan ? await prisma.serviceSession.findFirst({ where: { scheduleTemplateId: { in: fixturePlan.scheduleMappings.map((mapping: any) => mapping.scheduleTemplateId) }, status: 'OPEN', serviceDate: { gte: new Date() } }, include: { scheduleTemplate: true } }) : null;
    if (fixtureAgent && fixtureUser && fixturePlan?.variant?.product?.currentRevision && fixtureSession && fixturePlan.channelMappings[0]) {
      const key = `phase6-race-${randomUUID()}`; const fingerprint = `phase6-fingerprint-${randomUUID()}`; const make = () => prisma.booking.create({ data: { recordType: 'CANONICAL', bookingCode: `VY-${randomUUID().replace(/-/g, '').slice(0, 12).toUpperCase()}`, vendorTenantId: fixturePlan.variant.product.tenantId, agentTenantId: fixtureAgent.id, agentUserId: fixtureUser.id, productId: fixturePlan.variant.product.id, productRevisionId: fixturePlan.variant.product.currentRevision.id, variantId: fixturePlan.variant.id, ratePlanId: fixturePlan.id, sessionId: fixtureSession.id, distributionChannelId: fixturePlan.channelMappings[0].channelId, bookingMode: 'INSTANT', channel: 'VOYA_AGENT', serviceDate: fixtureSession.serviceDate, serviceTimezone: fixtureSession.scheduleTemplate.timezone, pax: 1, paxBreakdown: { ADULT: 1 }, capacityConsumption: 1, amount: 0, currency: fixturePlan.currency, status: 'NEW', idempotencyKey: key, requestFingerprint: fingerprint, customerName: 'Phase 6 race fixture' } });
      const raced = await Promise.allSettled([make(), make()]); const successes = raced.filter((item) => item.status === 'fulfilled'); const failures = raced.filter((item) => item.status === 'rejected'); const winners = successes.map((item: any) => item.value.id); if (successes.length !== 1 || failures.length !== 1) throw new Error(`Idempotency uniqueness race expected one winner and one conflict: ${JSON.stringify(raced.map((item: any) => item.status === 'rejected' ? { status: item.status, message: item.reason?.message, meta: item.reason?.meta } : { status: item.status, id: item.value.id }))}`); await prisma.booking.delete({ where: { id: winners[0] } }); concurrency = { status: 'PASS', attempted: 2, committed: successes.length, uniquenessConflicts: failures.length, inventoryConsumption: '0 (direct uniqueness fixture; BookingService inventory seam remains transaction-bound)' };
    }
    const result = { passing: !legacyViolations.length && legacyModernRelations === 0 && !duplicateKeys.length && pendingLinkedHolds === 0 && (!concurrency || concurrency.status !== 'FAIL'), counts: await counts(), legacyCount: legacy.length, legacy, legacyModernRelations, legacyViolations, canonicalCount: canonical.length, canonical, duplicateKeys: duplicateKeys.map((row) => ({ ...row, count: String(row.count) })), pendingLinkedHolds, concurrency };
    console.log(JSON.stringify(result, null, 2)); if (!result.passing) process.exitCode = 1;
  } finally { await prisma.$disconnect(); }
}
main().catch((error) => { console.error(error); process.exitCode = 1; });
