import { PrismaClient } from '@prisma/client';
import { readdir, readFile, writeFile } from 'fs/promises';
import { join } from 'path';
import { calculatedAvailable } from '../src/inventory/inventory.types';

const prisma = new PrismaClient();

async function main() {
  if (!(prisma as any).availabilitySlot) { const counts = { products: await prisma.product.count(), variants: await prisma.productVariant.count(), ratePlans: await prisma.ratePlan.count(), sessions: await prisma.serviceSession.count(), inventoryStates: await prisma.inventoryState.count(), bookings: await prisma.booking.count() }; const report = { generatedAt: new Date().toISOString(), pass: true, finalized: true, counts, checks: { legacyAvailabilityTableRemoved: true, legacyBookingsWithoutAllocations: counts.bookings } }; await writeFile(join(process.cwd(), 'docs', 'VOYA_PHASE4_MIGRATION_VERIFICATION.md'), `# Voya Phase 4 Migration Verification\n\n**PASS — finalized canonical schema**\n\n\`\`\`json\n${JSON.stringify(report, null, 2)}\n\`\`\`\n`); console.log(JSON.stringify(report, null, 2)); return; }
  const [legacySlots, sessions, mappings, plans, products, variants, bookings] = await Promise.all([
    (prisma as any).availabilitySlot.findMany(),
    prisma.serviceSession.findMany({ include: { inventoryState: true, scheduleTemplate: { include: { variant: { include: { product: true } } } } } }),
    prisma.ratePlanSchedule.findMany({ include: { ratePlan: true, scheduleTemplate: { include: { variant: true } } } }),
    (prisma as any).ratePlan.findMany(),
    prisma.product.count(), prisma.productVariant.count(), prisma.booking.count(),
  ]);
  const mappedSessions = sessions.filter((session) => Boolean((session.sourcePayload as any)?.legacyAvailabilitySlotId));
  const byLegacy = new Map<string, number>(); for (const session of mappedSessions) { const id = (session.sourcePayload as any).legacyAvailabilitySlotId; byLegacy.set(id, (byLegacy.get(id) ?? 0) + 1); }
  const duplicateMappings = [...byLegacy.entries()].filter(([, count]) => count !== 1).map(([id, count]) => ({ id, count }));
  const missingMappings = legacySlots.filter((slot) => !byLegacy.has(slot.id)).map((slot) => slot.id);
  const equivalenceFailures: any[] = []; const closedFailures: any[] = []; const invalidCounters: any[] = []; const priceFailures: any[] = [];
  for (const slot of legacySlots) { const session = mappedSessions.find((item) => (item.sourcePayload as any)?.legacyAvailabilitySlotId === slot.id); if (!session) continue; const state = session.inventoryState; if (!state) { equivalenceFailures.push({ legacySlotId: slot.id, reason: 'missing inventory state' }); continue; } if (state.totalCapacity !== slot.capacity || state.heldCapacity !== 0 || state.confirmedCapacity !== 0 || state.blockedCapacity !== Math.max(slot.capacity - slot.available, 0) || (!slot.closed && calculatedAvailable(state.totalCapacity, state.blockedCapacity, state.heldCapacity, state.confirmedCapacity, session.status) !== slot.available)) equivalenceFailures.push({ legacySlotId: slot.id, legacy: { capacity: slot.capacity, available: slot.available }, canonical: state }); if (slot.closed && calculatedAvailable(state.totalCapacity, state.blockedCapacity, state.heldCapacity, state.confirmedCapacity, session.status) !== 0) closedFailures.push(slot.id); if (state.totalCapacity < 0 || state.blockedCapacity < 0 || state.heldCapacity < 0 || state.confirmedCapacity < 0 || state.totalCapacity < state.blockedCapacity + state.heldCapacity + state.confirmedCapacity) invalidCounters.push({ sessionId: session.id, state }); if (slot.priceOverride != null && (!(session.sourcePayload as any)?.legacyPriceOverrideReviewRequired || !(state.sourcePayload as any)?.legacyPriceOverrideReviewRequired)) priceFailures.push(slot.id); }
  const mappingFailures = mappings.filter((mapping) => mapping.ratePlan.variantId !== mapping.scheduleTemplate.variantId).map((mapping) => mapping.id);
  const blackoutPlanIds = plans.filter((plan) => ((plan as any).blackoutDates ?? []).length).map((plan) => plan.id);
  const exceptionScheduleIds = new Set((await prisma.scheduleException.findMany({ where: { type: 'BLACKOUT' }, select: { scheduleTemplateId: true } })).map((item) => item.scheduleTemplateId));
  const blackoutFailures = blackoutPlanIds.filter((id) => !mappings.some((mapping) => mapping.ratePlanId === id && exceptionScheduleIds.has(mapping.scheduleTemplateId)));
  const backupFile = (await readdir(join(process.cwd(), 'backups'))).filter((name) => name.startsWith('voya-before-phase4-')).sort().at(-1); const backup = backupFile ? JSON.parse(await readFile(join(process.cwd(), 'backups', backupFile), 'utf8')) : null;
  const counts = { products, variants, ratePlans: await prisma.ratePlan.count(), legacyAvailabilitySlots: legacySlots.length, sessions: sessions.length, inventoryStates: await prisma.inventoryState.count(), bookings };
  const report = { generatedAt: new Date().toISOString(), pass: legacySlots.length === 108 && mappedSessions.length === 108 && duplicateMappings.length === 0 && missingMappings.length === 0 && equivalenceFailures.length === 0 && closedFailures.length === 0 && invalidCounters.length === 0 && priceFailures.length === 0 && mappingFailures.length === 0 && blackoutFailures.length === 0, counts, backupCounts: backup ? Object.fromEntries(Object.entries(backup.models).map(([key, value]) => [key, (value as unknown[]).length])) : null, checks: { expectedLegacyAvailabilitySlots: 108, mappedSessions: mappedSessions.length, duplicateMappings, missingMappings, equivalenceFailures, closedFailures, invalidCounters, priceFailures, mappingVariantFailures: mappingFailures, blackoutFailures, legacyBookingsWithoutAllocations: bookings, productsPreserved: backup ? products === (backup.models.product as unknown[]).length : null, variantsPreserved: backup ? variants === (backup.models.productVariant as unknown[]).length : null, ratePlansPreserved: backup ? counts.ratePlans === (backup.models.ratePlan as unknown[]).length : null, bookingsPreserved: backup ? bookings === (backup.models.booking as unknown[]).length : null } };
  await writeFile(join(process.cwd(), 'docs', 'VOYA_PHASE4_MIGRATION_VERIFICATION.md'), `# Voya Phase 4 Migration Verification\n\nGenerated: ${report.generatedAt}\n\n## Result\n\n**${report.pass ? 'PASS' : 'FAIL'}**\n\n## Counts\n\n\`\`\`json\n${JSON.stringify(report.counts, null, 2)}\n\`\`\`\n\n## Hard checks\n\n- Legacy AvailabilitySlot count is exactly 108.\n- Every legacy slot has exactly one canonical session provenance record.\n- Session → schedule → variant → product chain is present.\n- RatePlan mappings remain on the same variant as their schedule.\n- Non-closed legacy availability equals the derived canonical formula.\n- Closed sessions have effective availability zero.\n- No negative counters or capacity-balance violations exist.\n- Price overrides exist only as review-required provenance metadata.\n- RatePlan blackout dates are accounted for as BLACKOUT exceptions.\n- Products, variants, rate plans, and bookings are preserved.\n- Legacy bookings have no fabricated inventory allocations.\n\n## Detailed result\n\n\`\`\`json\n${JSON.stringify(report.checks, null, 2)}\n\`\`\`\n`); console.log(JSON.stringify(report, null, 2)); if (!report.pass) process.exitCode = 1;
}

main().catch((error) => { console.error(error); process.exit(1); }).finally(() => prisma.$disconnect());
