import { BookingStatus, CancellationFinancialState, CancellationInitiator, CancellationReasonCategory, PrismaClient, TenantKind, UserRole, VendorVerificationStatus } from '@prisma/client';
import { AuditService } from '../src/audit/audit.service';
import { RequestContextService } from '../src/common/request-context.service';
import { DemandAnalysisService } from '../src/demand/demand-analysis.service';
import { DemandObservationService } from '../src/demand/demand-observation.service';
import { DemandOpportunityService } from '../src/demand/demand-opportunity.service';
import { DemandPolicyService } from '../src/demand/demand-policy.service';
import { OutboxService } from '../src/outbox/outbox.service';

const prisma = new PrismaClient(); const fixture = `phase11-1-${Date.now()}`; const check = (value: unknown, message: string) => { if (!value) throw new Error(message); }; const day = (days: number) => new Date(Date.now() + days * 86400000).toISOString().slice(0, 10);

async function main() {
  const actorRow: any = await prisma.user.findFirst({ where: { role: { in: [UserRole.ADMIN, UserRole.SUB_ADMIN] } }, select: { id: true, email: true, fullName: true, role: true, tenantId: true } }); check(actorRow, 'Admin required');
  const agent: any = await prisma.tenant.findFirst({ where: { kind: TenantKind.TRAVEL_AGENT }, select: { id: true } }); const vendor: any = await prisma.tenant.findFirst({ where: { kind: TenantKind.VENDOR, vendorProfile: { verificationStatus: VendorVerificationStatus.VERIFIED } }, select: { id: true } }); check(agent && vendor, 'Agent and verified Vendor required');
  const vendorUser: any = await prisma.user.findFirst({ where: { tenantId: vendor.id, role: UserRole.VENDOR }, select: { id: true, email: true, fullName: true, role: true, tenantId: true } }); const source: any = await prisma.booking.findFirst({ where: { operationalSnapshot: { isNot: null } }, select: { productId: true, vendorTenantId: true, productRevisionId: true, variantId: true, ratePlanId: true, sessionId: true, bookingMode: true, serviceTimezone: true, agentUserId: true, operationalSnapshot: true } }); check(vendorUser && source, 'Vendor user and booking snapshot fixture required');
  const actor: any = { sub: actorRow.id, email: actorRow.email, fullName: actorRow.fullName, role: actorRow.role, tenantId: actorRow.tenantId }; const vendorActor: any = { sub: vendorUser.id, email: vendorUser.email, fullName: vendorUser.fullName, role: vendorUser.role, tenantId: vendorUser.tenantId }; const audit = new AuditService(new RequestContextService()); const outbox = new OutboxService(prisma as any); const observations = new DemandObservationService(prisma as any); const policies = new DemandPolicyService(prisma as any, audit, outbox); const analysis = new DemandAnalysisService(prisma as any, policies, audit, outbox); const opportunities = new DemandOpportunityService(prisma as any, audit, outbox, analysis);
  const before = await Promise.all([prisma.marketplaceSearchObservation.count(), prisma.demandOpportunity.count(), prisma.demandIntelligencePolicy.count({ where: { status: 'ACTIVE' } }), prisma.booking.count(), prisma.inventoryHold.count(), prisma.inventoryAllocation.count()]); check(before[2] === 0, 'Verifier will not alter an existing active policy');
  const observationIds: string[] = []; const bookingIds: string[] = []; const cancellationIds: string[] = []; const opportunityIds: string[] = []; const targetIds: string[] = []; const runIds: string[] = []; const policyIds: string[] = []; const checks: Record<string, unknown> = {};
  const record = async (scope: string, serviceDate: string, index: number, extra: any = {}) => { const id = `${fixture}-${scope}-${index}`; await observations.record({ tenantId: agent.id } as any, { serviceDate, destination: scope, category: 'ACTIVITY', subType: 'TREK', searchAttemptId: id, travellers: [{ travellerType: 'ADULT', quantity: 1 }], ...extra.dto } as any, { candidateRatePlanCount: extra.candidateRatePlanCount ?? 1, candidateSessionCount: extra.candidateSessionCount ?? 1, eligibleOfferCountBeforePrice: extra.eligibleOfferCountBeforePrice ?? 1, resultProductCount: extra.resultProductCount ?? 1, resultOfferCount: extra.resultOfferCount ?? 1, eligibilityFailureCounts: extra.eligibilityFailureCounts ?? {}, soldOutSessionIds: extra.soldOutSessionIds ?? [], priceDiagnostics: extra.priceDiagnostics ?? {} }); observationIds.push(id); };
  const addSnapshot = async (bookingId: string, destination: string) => {
    const s = source.operationalSnapshot;
    await prisma.bookingSnapshot.create({ data: { bookingId, productRevisionId: s.productRevisionId, scheduleTemplateId: s.scheduleTemplateId, sessionId: s.sessionId, productSnapshot: { ...(s.productSnapshot as any), destination: { city: destination }, type: 'ACTIVITY', subType: 'CANCELLATION' }, variantSnapshot: s.variantSnapshot, ratePlanSnapshot: s.ratePlanSnapshot, sessionSnapshot: s.sessionSnapshot, travellerSummary: { ADULT: 1 }, capacityUnit: s.capacityUnit, capacityConsumption: 1, bookingMode: s.bookingMode, cancellationPolicySnapshot: s.cancellationPolicySnapshot, cancellationPolicyFingerprint: `${fixture}-policy`, cancellationAcknowledgedAt: new Date(), pickupSnapshot: s.pickupSnapshot, questionsSnapshot: s.questionsSnapshot, bookingAnswers: s.bookingAnswers, agentSnapshot: s.agentSnapshot, channelSnapshot: s.channelSnapshot, confirmationPolicySnapshot: s.confirmationPolicySnapshot, fulfilmentPolicySnapshot: s.fulfilmentPolicySnapshot } });
  };
  try {
    for (let i = 0; i < 10; i += 1) {
      const booking: any = await prisma.booking.create({ data: { recordType: 'CANONICAL', bookingCode: `VY-${fixture.replace(/-/g, '').slice(-12)}-${i}`, vendorTenantId: source.vendorTenantId, agentTenantId: agent.id, agentUserId: source.agentUserId ?? actorRow.id, productId: source.productId, productRevisionId: source.productRevisionId, variantId: source.variantId, ratePlanId: source.ratePlanId, sessionId: source.sessionId, bookingMode: source.bookingMode ?? 'INSTANT', channel: 'PHASE11_1', serviceDate: new Date(Date.now() - 86400000), serviceTimezone: source.serviceTimezone ?? 'UTC', pax: 1, capacityConsumption: 1, amount: 100, currency: 'INR', status: i < 2 ? BookingStatus.CANCELLED : BookingStatus.COMPLETED, confirmedAt: new Date(Date.now() - 2 * 86400000), idempotencyKey: `${fixture}-confirmed-${i}`, requestFingerprint: `${fixture}-confirmed-${i}`, customerName: 'Phase 11.1 confirmed cohort' } }); bookingIds.push(booking.id); await addSnapshot(booking.id, 'Phase 11.1 Cancellation City'); if (i < 2) { const cancellation: any = await prisma.bookingCancellation.create({ data: { bookingId: booking.id, initiator: CancellationInitiator.VENDOR, reasonCategory: CancellationReasonCategory.VENDOR_OPERATIONAL, reason: 'Phase 11.1 controlled cancellation', cancelledAt: new Date(), serviceTimezone: source.serviceTimezone ?? 'UTC', serviceDateLocal: day(-1), cancellationDateLocal: day(0), daysBeforeService: 1, bookingAmount: 100, currency: 'INR', cancellationCharge: 0, refundEntitlement: 100, financialState: CancellationFinancialState.CANCELLED_NO_REFUND, calculationSnapshot: { fixture } } }); cancellationIds.push(cancellation.id); } }
    const pending: any = await prisma.booking.create({ data: { recordType: 'CANONICAL', bookingCode: `VY-${fixture.replace(/-/g, '').slice(-10)}-P`, vendorTenantId: source.vendorTenantId, agentTenantId: agent.id, agentUserId: source.agentUserId ?? actorRow.id, productId: source.productId, productRevisionId: source.productRevisionId, variantId: source.variantId, ratePlanId: source.ratePlanId, sessionId: source.sessionId, bookingMode: source.bookingMode ?? 'INSTANT', channel: 'PHASE11_1', serviceDate: new Date(Date.now() - 86400000), serviceTimezone: source.serviceTimezone ?? 'UTC', pax: 1, capacityConsumption: 1, amount: 100, currency: 'INR', status: BookingStatus.PENDING_VENDOR_CONFIRMATION, idempotencyKey: `${fixture}-pending`, requestFingerprint: `${fixture}-pending`, customerName: 'Phase 11.1 pending withdrawal' } }); bookingIds.push(pending.id);
    const legacy: any = await prisma.booking.create({ data: { recordType: 'LEGACY', bookingCode: `VY-${fixture.replace(/-/g, '').slice(-10)}-L`, vendorTenantId: source.vendorTenantId, agentTenantId: agent.id, productId: source.productId, channel: 'PHASE11_1', serviceDate: new Date(Date.now() - 86400000), pax: 1, amount: 100, currency: 'INR', status: BookingStatus.CANCELLED, customerName: 'Phase 11.1 legacy cancellation' } }); bookingIds.push(legacy.id);
    const rejected: any = await prisma.booking.create({ data: { recordType: 'CANONICAL', bookingCode: `VY-${fixture.replace(/-/g, '').slice(-10)}-R`, vendorTenantId: source.vendorTenantId, agentTenantId: agent.id, agentUserId: source.agentUserId ?? actorRow.id, productId: source.productId, productRevisionId: source.productRevisionId, variantId: source.variantId, ratePlanId: source.ratePlanId, sessionId: source.sessionId, bookingMode: source.bookingMode ?? 'INSTANT', channel: 'PHASE11_1', serviceDate: new Date(Date.now() - 86400000), serviceTimezone: source.serviceTimezone ?? 'UTC', pax: 1, capacityConsumption: 1, amount: 100, currency: 'INR', status: BookingStatus.VENDOR_REJECTED, idempotencyKey: `${fixture}-rejected`, requestFingerprint: `${fixture}-rejected`, customerName: 'Phase 11.1 vendor rejection' } }); bookingIds.push(rejected.id);
    const cancellationPolicy: any = await policies.create(actor, { name: `Phase 11.1 ${fixture}`, measurementWindowDays: 30, futureHorizonDays: 60, cooldownDays: 2, rules: [{ type: 'HIGH_DEMAND_LOW_SUPPLY', defaultPriority: 'HIGH', minSearchCount: 1, minUniqueAgentCount: 1, maxAverageResultProducts: 2 }, { type: 'FREQUENT_SOLD_OUT', defaultPriority: 'HIGH', minSearchCount: 1, minSoldOutSessionCount: 1, minSoldOutRate: 1 }, { type: 'HIGH_CANCELLATIONS', defaultPriority: 'HIGH', minConfirmedBookingCount: 10, minCancellationRate: 0.2 }, { type: 'PRICE_GAP', defaultPriority: 'MEDIUM', minSearchCount: 5, minPriceCeilingMissCount: 5, minPriceCeilingMissRate: 1 }, { type: 'COVERAGE_GAP', defaultPriority: 'MEDIUM', minSearchCount: 1, minUniqueAgentCount: 1, minZeroResultRate: 1 }] } as any); policyIds.push(cancellationPolicy.id); await policies.activate(actor, cancellationPolicy.id);
    for (let i = 0; i < 100; i += 1) await record('Price Denominator', day(30), i, i < 5 ? { dto: { currency: 'INR', priceMax: 1000 }, priceDiagnostics: { priceCeilingMiss: true, byCurrency: { INR: { minimum: 1200, median: 1400 } } } } : {});
    await record('Currency Group', day(30), 0, { dto: { currency: 'INR' } }); await record('Currency Group', day(30), 1, { dto: { currency: 'USD' } });
    await record('Horizon Included', day(30), 0); await record('Horizon Excluded', day(120), 0);
    await record('No Candidate', day(30), 0, { candidateRatePlanCount: 0, candidateSessionCount: 0, resultProductCount: 0, resultOfferCount: 0 }); await record('No Dated', day(30), 0, { candidateRatePlanCount: 1, candidateSessionCount: 0, resultProductCount: 0, resultOfferCount: 0 }); await record('Sold Out Classification', day(30), 0, { candidateRatePlanCount: 1, candidateSessionCount: 1, resultProductCount: 0, resultOfferCount: 0, eligibilityFailureCounts: { INSUFFICIENT_INVENTORY: 1 }, soldOutSessionIds: [`${fixture}-soldout`] }); await record('Cutoff Classification', day(30), 0, { candidateRatePlanCount: 1, candidateSessionCount: 1, resultProductCount: 0, resultOfferCount: 0, eligibilityFailureCounts: { CUTOFF_PASSED: 1 } });
    const active: any = await policies.active(); const candidates: any = await analysis.candidates(active); const cancellation = candidates.candidates.find((item: any) => item.type === 'HIGH_CANCELLATIONS'); const price = candidates.candidates.find((item: any) => item.type === 'PRICE_GAP'); const coverage = candidates.candidates.filter((item: any) => item.type === 'COVERAGE_GAP'); const horizonTypes = candidates.candidates.filter((item: any) => ['horizon included', 'horizon excluded'].includes(item.destinationNormalized));
    check(cancellation?.metrics.confirmedBookingCount === 10 && cancellation.metrics.cancellationCount === 2, 'Cancellation cohort denominator is incorrect'); checks.cancellationCohort = { denominator: cancellation?.metrics.confirmedBookingCount, cancellations: cancellation?.metrics.cancellationCount, rate: cancellation?.metrics.cancellationRate, pendingLegacyRejectedExcluded: true };
    check(price?.metrics.priceCeilingSearchCount === 5 && price.metrics.priceCeilingMissCount === 5 && price.metrics.priceCeilingMissRate === 1, 'Price denominator is incorrect'); checks.priceGap = { searchCount: price.metrics.searchCount, priceCeilingSearchCount: price.metrics.priceCeilingSearchCount, missCount: price.metrics.priceCeilingMissCount, rate: price.metrics.priceCeilingMissRate };
    check(coverage.every((item: any) => ['no candidate', 'no dated'].includes(item.destinationNormalized)), 'Coverage misclassified sold-out or eligibility gap'); checks.coverage = { generated: coverage.map((item: any) => item.destinationNormalized), soldOutAndCutoffExcluded: true };
    check(horizonTypes.length === 1 && horizonTypes[0].destinationNormalized === 'horizon included', 'Future horizon filter failed'); checks.futureHorizon = { included: 'horizon included', excluded: 'horizon excluded', excludedObservationStored: observationIds.includes(`${fixture}-Horizon Excluded-0`) };
    const nonPrice = candidates.candidates.find((item: any) => item.type === 'HIGH_DEMAND_LOW_SUPPLY' && item.destinationNormalized === 'currency group'); check(nonPrice?.metrics.searchCount === 2 && nonPrice.currency === null, 'Non-price grouping fragmented by currency'); checks.signalGrouping = { nonPriceSearchCount: nonPrice?.metrics.searchCount, currencyExcludedFromSupplyKey: true };
    const generated: any = await analysis.generate(actor); runIds.push(generated.analysis.id); for (const item of generated.created) if (item.id && !opportunityIds.includes(item.id)) opportunityIds.push(item.id); checks.generation = { created: generated.created.length, noBusinessMutation: true };
    const manualClosed: any = await opportunities.manual(actor, { type: 'COVERAGE_GAP', priority: 'LOW', title: `Closed ${fixture}`, destinationNormalized: 'closed', reason: 'Phase 11.1 closed-target proof' } as any); opportunityIds.push(manualClosed.id); const closed = await opportunities.resolve(actor, manualClosed.id, { expectedVersion: manualClosed.version, resolutionType: 'NO_ACTION', reason: 'Closed before targeting' }); check(closed.status === 'RESOLVED', 'Closed fixture did not resolve'); let closedTargetRejected = false; try { await opportunities.target(actor, manualClosed.id, { vendorTenantId: vendor.id }); } catch (error: any) { closedTargetRejected = error?.response?.message === 'DEMAND_OPPORTUNITY_CLOSED'; } check(closedTargetRejected, 'Closed opportunity accepted a new target'); checks.closedTarget = true;
    const raceOpp: any = await opportunities.manual(actor, { type: 'COVERAGE_GAP', priority: 'LOW', title: `Race ${fixture}`, destinationNormalized: 'race', reason: 'Phase 11.1 response race' } as any); opportunityIds.push(raceOpp.id); const raceTarget: any = await opportunities.target(actor, raceOpp.id, { vendorTenantId: vendor.id }); targetIds.push(raceTarget.id); const race = await Promise.allSettled([opportunities.vendorRespond(vendorActor, raceOpp.id, { status: 'INTERESTED', expectedVersion: raceTarget.version }), opportunities.vendorRespond(vendorActor, raceOpp.id, { status: 'DECLINED', expectedVersion: raceTarget.version })]); check(race.filter((item) => item.status === 'fulfilled').length === 1, 'Vendor response race did not produce one winner'); checks.vendorResponseRace = { winners: 1, losers: 1 };
    const historyOpp: any = await opportunities.manual(actor, { type: 'COVERAGE_GAP', priority: 'LOW', title: `History ${fixture}`, destinationNormalized: 'history', reason: 'Phase 11.1 target history' } as any); opportunityIds.push(historyOpp.id); const historyTarget: any = await opportunities.target(actor, historyOpp.id, { vendorTenantId: vendor.id }); targetIds.push(historyTarget.id); const removed: any = await opportunities.untarget(actor, historyOpp.id, vendor.id, { reason: 'No longer relevant' }); check(removed.status === 'REMOVED' && (await prisma.demandOpportunityEvent.findFirst({ where: { opportunityId: historyOpp.id, eventType: 'VENDOR_UNTARGETED' } })), 'Target history was not preserved'); checks.targetHistory = { preserved: true, status: 'REMOVED', event: 'VENDOR_UNTARGETED' };
    const during = await Promise.all([prisma.booking.count(), prisma.inventoryHold.count(), prisma.inventoryAllocation.count()]); check(during[0] === before[3] + 13 && during[1] === before[4] && during[2] === before[5], 'Demand flow mutated business state');
    console.log(JSON.stringify({ phase: '11.1', fixture, checks }, null, 2));
  } finally {
    if (opportunityIds.length) { await prisma.demandOpportunityEvent.deleteMany({ where: { opportunityId: { in: opportunityIds } } }); await prisma.demandOpportunityVendorTarget.deleteMany({ where: { opportunityId: { in: opportunityIds } } }); await prisma.demandOpportunityAssessment.deleteMany({ where: { opportunityId: { in: opportunityIds } } }); await prisma.demandOpportunity.deleteMany({ where: { id: { in: opportunityIds } } }); }
    if (runIds.length) await prisma.demandAnalysisRun.deleteMany({ where: { id: { in: runIds } } }); if (policyIds.length) await prisma.demandIntelligencePolicy.deleteMany({ where: { id: { in: policyIds } } }); if (cancellationIds.length) await prisma.bookingCancellation.deleteMany({ where: { id: { in: cancellationIds } } }); if (bookingIds.length) await prisma.bookingSnapshot.deleteMany({ where: { bookingId: { in: bookingIds } } }); if (bookingIds.length) await prisma.booking.deleteMany({ where: { id: { in: bookingIds } } }); if (observationIds.length) await prisma.marketplaceSearchObservation.deleteMany({ where: { searchAttemptId: { in: observationIds } } }); const ids = [...policyIds, ...runIds, ...opportunityIds, ...targetIds, ...cancellationIds]; if (ids.length) await prisma.auditLog.deleteMany({ where: { entityId: { in: ids } } }); const aggregates = [...policyIds, ...opportunityIds]; if (aggregates.length) await prisma.outboxEvent.deleteMany({ where: { aggregateId: { in: aggregates } } });
    const after = await Promise.all([prisma.marketplaceSearchObservation.count(), prisma.demandOpportunity.count(), prisma.demandIntelligencePolicy.count({ where: { status: 'ACTIVE' } }), prisma.booking.count(), prisma.inventoryHold.count(), prisma.inventoryAllocation.count()]); check(after.every((value, index) => value === before[index]), 'Controlled Phase 11.1 cleanup changed genuine records');
  }
}
main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
