import { AuditService } from '../src/audit/audit.service';
import { RequestContextService } from '../src/common/request-context.service';
import { OutboxService } from '../src/outbox/outbox.service';
import { PrismaClient, BookingMode, BookingRecordType, BookingStatus, CancellationFinancialState, CancellationInitiator, CancellationReasonCategory, CapacityUnit, FilePurpose, FileVisibility, FulfilmentMode, MediaKind, ProductRevisionStatus, ProductStatus, ScheduleExceptionType, ScheduleStatus, SessionStatus, SupplierMetricDirection, SupplierMetricMissingDataTreatment, SupplierMetricStatus, SupplierQualityDimension, SupplierQualityIssueStatus, SupplierQualityMetricCode, SupplierQualityPolicyStatus, SupplierTier, TenantKind, UserRole, VoucherVersionStatus } from '@prisma/client';
import { SupplierPerformanceService } from '../src/quality/supplier-performance.service';
import { SupplierQualityEvaluator } from '../src/quality/supplier-quality-evaluator';
import { SupplierQualityIssueService, SupplierQualityPolicyService, SupplierQualitySnapshotService, SupplierTierService } from '../src/quality/supplier-quality.service';

const prisma = new PrismaClient();
const now = new Date('2026-10-11T00:00:00.000Z');
const windowStart = new Date('2026-09-11T00:00:00.000Z');
const serviceDate = new Date('2026-10-10T00:00:00.000Z');
const serviceStartsAt = new Date('2026-10-10T03:30:00.000Z'); // 09:00 Asia/Kolkata
const results: Record<string, unknown> = {};
const check = (condition: unknown, message: string) => { if (!condition) throw new Error(message); };
const id = (prefix: string) => `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

async function main() {
  const actorRow = await prisma.user.findFirst({ where: { role: { in: [UserRole.ADMIN, UserRole.SUB_ADMIN] } }, select: { id: true, email: true, fullName: true, role: true, tenantId: true } });
  check(actorRow, 'An ADMIN or SUB_ADMIN user is required for the controlled verifier');
  const actor = { sub: actorRow!.id, email: actorRow!.email, fullName: actorRow!.fullName, role: actorRow!.role, tenantId: actorRow!.tenantId } as any;
  const vendor = await prisma.tenant.create({ data: { name: `Phase 10.2 Runtime Vendor ${id('v')}`, slug: id('phase-10-2-vendor').toLowerCase(), kind: TenantKind.VENDOR } });
  const otherVendor = await prisma.tenant.create({ data: { name: `Phase 10.2 Other Vendor ${id('v')}`, slug: id('phase-10-2-other').toLowerCase(), kind: TenantKind.VENDOR } });
  const agentTenant = await prisma.tenant.create({ data: { name: `Phase 10.2 Runtime Agent ${id('a')}`, slug: id('phase-10-2-agent').toLowerCase(), kind: TenantKind.TRAVEL_AGENT } });
  const agentUser = await prisma.user.create({ data: { tenantId: agentTenant.id, email: `${id('agent')}@phase10-2.test`, passwordHash: 'controlled', fullName: 'Controlled agent', role: UserRole.TRAVEL_AGENT } });
  const createdBookings: string[] = []; const createdSnapshots: string[] = []; const createdFiles: string[] = []; const createdProducts: string[] = []; const createdRevisions: string[] = []; const createdPolicies: string[] = [];
  let variantId = ''; let ratePlanId = ''; let scheduleId = ''; let sessionIds: string[] = []; let slotId = '';
  const evaluator = new SupplierQualityEvaluator(); const performance = new SupplierPerformanceService(prisma as any, evaluator); const audit = new AuditService(new RequestContextService()); const outbox = new OutboxService(prisma as any); const snapshotService = new SupplierQualitySnapshotService(prisma as any, performance, evaluator, audit, outbox); const tierService = new SupplierTierService(prisma as any, audit, outbox); const issueService = new SupplierQualityIssueService(prisma as any, audit); const policyService = new SupplierQualityPolicyService(prisma as any, audit, outbox);
  try {
    const coreProduct = await prisma.product.create({ data: { tenantId: vendor.id, productCode: id('CORE').toUpperCase(), status: ProductStatus.DRAFT } }); createdProducts.push(coreProduct.id);
    const coreRevision = await prisma.productRevision.create({ data: { productId: coreProduct.id, versionNumber: 1, status: ProductRevisionStatus.PUBLISHED, productName: 'Phase 10.2 Runtime Activity', type: 'ACTIVITY', subType: 'CONTROLLED', description: 'controlled', cityName: 'Bengaluru', stateName: 'Karnataka', countryName: 'India', createdById: actor.sub } }); createdRevisions.push(coreRevision.id);
    await prisma.product.update({ where: { id: coreProduct.id }, data: { currentRevisionId: coreRevision.id } });
    const variant = await prisma.productVariant.create({ data: { productId: coreProduct.id, variantCode: id('VAR').toUpperCase(), name: 'Controlled variant' } }); variantId = variant.id;
    const ratePlan = await prisma.ratePlan.create({ data: { variantId, ratePlanCode: id('RATE').toUpperCase(), name: 'Controlled rate', validFrom: new Date('2026-01-01'), validTo: new Date('2027-01-01'), currency: 'INR', basePrice: 100 } }); ratePlanId = ratePlan.id;
    const schedule = await prisma.scheduleTemplate.create({ data: { variantId, scheduleCode: id('SCH').toUpperCase(), name: 'Controlled schedule', status: ScheduleStatus.ACTIVE, timezone: 'Asia/Kolkata', effectiveFrom: serviceDate, operatingDays: ['SATURDAY'], capacityUnit: CapacityUnit.PERSON } }); scheduleId = schedule.id;
    const slot = await prisma.scheduleSlotTemplate.create({ data: { scheduleTemplateId: scheduleId, slotCode: id('SLOT').toUpperCase(), startTime: '09:00', active: true } }); slotId = slot.id;
    for (let index = 0; index < 3; index += 1) { const session = await prisma.serviceSession.create({ data: { scheduleTemplateId: scheduleId, slotTemplateId: index === 0 ? null : slotId, serviceDate, sessionKey: `CONTROL-${index}`, localStartTime: '09:00', startsAt: serviceStartsAt, status: SessionStatus.OPEN } }); sessionIds.push(session.id); }
    await prisma.scheduleException.create({ data: { scheduleTemplateId: scheduleId, serviceDate, type: ScheduleExceptionType.BLACKOUT, reason: 'runtime global blackout', exceptionKey: id('GLOBAL'), createdAt: new Date('2026-10-09T06:00:00.000Z') } });
    await prisma.scheduleException.create({ data: { scheduleTemplateId: scheduleId, serviceDate, type: ScheduleExceptionType.BLACKOUT, reason: 'runtime duplicate blackout', exceptionKey: id('DUPLICATE'), createdAt: new Date('2026-10-09T07:00:00.000Z') } });
    await prisma.scheduleException.create({ data: { scheduleTemplateId: scheduleId, serviceDate, type: ScheduleExceptionType.CLOSED, reason: 'outside threshold', exceptionKey: id('OLD'), createdAt: new Date('2026-09-30T06:00:00.000Z') } });
    const createBooking = async (label: string, data: Record<string, unknown>) => { const booking = await prisma.booking.create({ data: { recordType: BookingRecordType.CANONICAL, bookingCode: id(label).toUpperCase(), vendorTenantId: vendor.id, agentTenantId: agentTenant.id, agentUserId: agentUser.id, productId: coreProduct.id, productRevisionId: coreRevision.id, variantId, ratePlanId, sessionId: sessionIds[0], channel: 'CONTROLLED', serviceDate: new Date('2026-12-31T00:00:00.000Z'), serviceTimezone: 'Asia/Kolkata', pax: 1, capacityConsumption: 1, idempotencyKey: id(`idem-${label}`), requestFingerprint: id(`fingerprint-${label}`), amount: 100, currency: 'INR', status: BookingStatus.CONFIRMED, customerName: 'Controlled traveller', ...data } as any }); createdBookings.push(booking.id); return booking; };
    const addSnapshot = async (bookingId: string, startsAt = serviceStartsAt) => { const snapshot = await prisma.bookingSnapshot.create({ data: { bookingId, productRevisionId: coreRevision.id, scheduleTemplateId: scheduleId, sessionId: sessionIds[0], productSnapshot: {}, variantSnapshot: {}, ratePlanSnapshot: {}, sessionSnapshot: { startsAt: startsAt.toISOString(), timezone: 'Asia/Kolkata' }, travellerSummary: {}, capacityUnit: CapacityUnit.PERSON, capacityConsumption: 1, bookingMode: BookingMode.INSTANT, cancellationPolicySnapshot: [], cancellationPolicyFingerprint: 'controlled', cancellationAcknowledgedAt: new Date('2026-09-01T00:00:00.000Z'), questionsSnapshot: [], bookingAnswers: {}, agentSnapshot: {}, channelSnapshot: {}, confirmationPolicySnapshot: {}, fulfilmentPolicySnapshot: {} } }); createdSnapshots.push(snapshot.id); return snapshot; };
    const cancel = async (bookingId: string, initiator: CancellationInitiator, cancelledAt: Date, daysBeforeService: number) => prisma.bookingCancellation.create({ data: { bookingId, initiator, reasonCategory: initiator === CancellationInitiator.VENDOR ? CancellationReasonCategory.VENDOR_OPERATIONAL : CancellationReasonCategory.OTHER, reason: 'controlled runtime cancellation', cancelledAt, serviceTimezone: 'Asia/Kolkata', serviceDateLocal: '2026-10-10', cancellationDateLocal: cancelledAt.toISOString().slice(0, 10), daysBeforeService, bookingAmount: 100, currency: 'INR', cancellationCharge: 0, refundEntitlement: 100, financialState: CancellationFinancialState.CANCELLED_NO_REFUND, calculationSnapshot: {} } });
    const slaA = await createBooking('SLA-A', { bookingMode: BookingMode.VENDOR_CONFIRMATION, serviceDate: new Date('2026-12-31'), createdAt: new Date('2026-10-09T08:00:00Z'), confirmationDueAt: new Date('2026-10-09T10:00:00Z'), confirmedAt: new Date('2026-10-09T09:00:00Z') });
    const slaB = await createBooking('SLA-B', { bookingMode: BookingMode.VENDOR_CONFIRMATION, serviceDate: new Date('2026-12-31'), createdAt: new Date('2026-10-09T08:00:00Z'), confirmationDueAt: new Date('2026-10-09T11:00:00Z'), rejectedAt: new Date('2026-10-09T08:30:00Z'), status: BookingStatus.VENDOR_REJECTED });
    await createBooking('SLA-C', { bookingMode: BookingMode.VENDOR_CONFIRMATION, serviceDate: new Date('2026-12-31'), createdAt: new Date('2026-10-09T08:00:00Z'), confirmationDueAt: new Date('2026-10-09T12:00:00Z'), expiredAt: new Date('2026-10-09T12:00:00Z'), status: BookingStatus.CONFIRMATION_EXPIRED });
    await createBooking('SLA-D', { bookingMode: BookingMode.INSTANT, serviceDate: new Date('2026-12-31'), createdAt: new Date('2026-10-09T08:00:00Z'), confirmedAt: new Date('2026-10-09T08:01:00Z') });
    await createBooking('SLA-E', { bookingMode: BookingMode.MANUAL_ON_REQUEST, serviceDate: new Date('2026-12-31'), createdAt: new Date('2026-10-09T08:00:00Z'), confirmedAt: new Date('2026-10-09T08:02:00Z') });
    const serviceBookings: any[] = [];
    for (let index = 0; index < 10; index += 1) { const booking = await createBooking(`SERVICE-${index}`, { bookingMode: index % 2 ? BookingMode.MANUAL_ON_REQUEST : BookingMode.INSTANT, serviceDate, createdAt: index === 0 ? new Date('2026-08-12T08:00:00Z') : new Date('2026-10-01T08:00:00Z'), confirmedAt: new Date('2026-10-01T09:00:00Z') }); serviceBookings.push(booking); }
    await cancel(serviceBookings[0].id, CancellationInitiator.VENDOR, new Date('2026-10-09T12:00:00Z'), 1);
    await cancel(serviceBookings[1].id, CancellationInitiator.VENDOR, new Date('2026-10-05T12:00:00Z'), 5);
    await cancel(serviceBookings[2].id, CancellationInitiator.AGENT, new Date('2026-10-09T12:00:00Z'), 1); await addSnapshot(serviceBookings[2].id);
    await cancel(serviceBookings[3].id, CancellationInitiator.ADMIN, new Date('2026-10-10T04:00:00Z'), 0); await addSnapshot(serviceBookings[3].id);
    const readyBooking = serviceBookings[4]; await addSnapshot(readyBooking.id); const fulfilmentReady = await prisma.bookingFulfilment.create({ data: { bookingId: readyBooking.id, mode: FulfilmentMode.AUTO, status: 'VOUCHER_READY', generationStatus: 'SUCCEEDED' } }); const readyFile = await prisma.fileAsset.create({ data: { tenantId: vendor.id, storageKey: id('ready-file'), originalName: 'ready.pdf', mimeType: 'application/pdf', sizeBytes: 1, visibility: FileVisibility.PRIVATE, purpose: FilePurpose.BOOKING_VOUCHER } }); createdFiles.push(readyFile.id); await prisma.voucherVersion.create({ data: { bookingId: readyBooking.id, fulfilmentId: fulfilmentReady.id, versionNumber: 1, voucherCode: id('READY-CODE'), fileAssetId: readyFile.id, sourceEvidenceFingerprint: 'ready', contentFingerprint: 'ready', generatedAt: new Date('2026-10-10T03:29:00Z'), status: VoucherVersionStatus.CURRENT } });
    const lateBooking = serviceBookings[3]; const lateFulfilment = await prisma.bookingFulfilment.create({ data: { bookingId: lateBooking.id, mode: FulfilmentMode.AUTO, status: 'VOUCHER_READY', generationStatus: 'SUCCEEDED' } }); const lateFile = await prisma.fileAsset.create({ data: { tenantId: vendor.id, storageKey: id('late-file'), originalName: 'late.pdf', mimeType: 'application/pdf', sizeBytes: 1, visibility: FileVisibility.PRIVATE, purpose: FilePurpose.BOOKING_VOUCHER } }); createdFiles.push(lateFile.id); await prisma.voucherVersion.create({ data: { bookingId: lateBooking.id, fulfilmentId: lateFulfilment.id, versionNumber: 1, voucherCode: id('LATE-CODE'), fileAssetId: lateFile.id, sourceEvidenceFingerprint: 'late', contentFingerprint: 'late', generatedAt: new Date('2026-10-10T03:31:00Z'), status: VoucherVersionStatus.CURRENT } });
    await createBooking('SERVICE-FUTURE', { bookingMode: BookingMode.INSTANT, serviceDate: new Date('2026-12-10'), createdAt: now, confirmedAt: now });
    for (let index = 0; index < 4; index += 1) { const product = await prisma.product.create({ data: { tenantId: vendor.id, productCode: id(`IMG${index}`).toUpperCase(), status: ProductStatus.LIVE } }); createdProducts.push(product.id); const revision = await prisma.productRevision.create({ data: { productId: product.id, versionNumber: 1, status: ProductRevisionStatus.PUBLISHED, productName: `Image fixture ${index}`, type: 'ACTIVITY', subType: 'CONTROLLED', description: 'controlled', cityName: 'Bengaluru', stateName: 'Karnataka', countryName: 'India', createdById: actor.sub } }); createdRevisions.push(revision.id); await prisma.product.update({ where: { id: product.id }, data: { currentRevisionId: revision.id } }); await prisma.productMedia.create({ data: { revisionId: revision.id, kind: index < 3 ? MediaKind.IMAGE : MediaKind.VIDEO, externalUrl: `https://example.test/${index}.jpg` } }); }
    await prisma.booking.updateMany({ where: { id: { in: [serviceBookings[3].id, serviceBookings[4].id] } }, data: { confirmedAt: new Date('2026-10-10T03:00:00Z') } });
    const raw = await (performance as any).rawMetrics(vendor.id, windowStart, now, 2, 2) as any[]; const metric = (code: SupplierQualityMetricCode) => raw.find((row) => row.metricCode === code);
    check(metric(SupplierQualityMetricCode.CONFIRMATION_WITHIN_SLA_RATE).denominator === 3 && metric(SupplierQualityMetricCode.CONFIRMATION_WITHIN_SLA_RATE).numerator === 1, 'SLA cohort did not isolate A/B/C'); check(metric(SupplierQualityMetricCode.VENDOR_RESPONSE_WITHIN_SLA_RATE).denominator === 2 && metric(SupplierQualityMetricCode.VENDOR_RESPONSE_WITHIN_SLA_RATE).numerator === 2, 'Vendor response SLA is incorrect'); check(metric(SupplierQualityMetricCode.AVG_VENDOR_RESPONSE_MINUTES).rawValue === 45, 'Average response minutes is incorrect'); check(metric(SupplierQualityMetricCode.CONFIRMATION_OVERDUE_RATE).rawValue === 33.33, 'Overdue rate is incorrect'); results.sla = { confirmationWithin: metric(SupplierQualityMetricCode.CONFIRMATION_WITHIN_SLA_RATE).rawValue, vendorResponseWithin: metric(SupplierQualityMetricCode.VENDOR_RESPONSE_WITHIN_SLA_RATE).rawValue, averageResponseMinutes: metric(SupplierQualityMetricCode.AVG_VENDOR_RESPONSE_MINUTES).rawValue, overdueRate: metric(SupplierQualityMetricCode.CONFIRMATION_OVERDUE_RATE).rawValue };
    check(metric(SupplierQualityMetricCode.VENDOR_CANCELLATION_RATE).numerator === 2 && metric(SupplierQualityMetricCode.VENDOR_CANCELLATION_RATE).denominator === 10 && metric(SupplierQualityMetricCode.VENDOR_CANCELLATION_RATE).rawValue === 20, 'Vendor cancellation cohort is incorrect'); check(metric(SupplierQualityMetricCode.SHORT_NOTICE_VENDOR_CANCELLATION_RATE).numerator === 1 && metric(SupplierQualityMetricCode.SHORT_NOTICE_VENDOR_CANCELLATION_RATE).denominator === 2 && metric(SupplierQualityMetricCode.SHORT_NOTICE_VENDOR_CANCELLATION_RATE).rawValue === 50, 'Short-notice cancellation is incorrect'); results.cancellation = { vendorNumerator: 2, denominator: 10, rate: metric(SupplierQualityMetricCode.VENDOR_CANCELLATION_RATE).rawValue, shortNotice: metric(SupplierQualityMetricCode.SHORT_NOTICE_VENDOR_CANCELLATION_RATE).rawValue, oldCreatedBookingIncluded: true, futureServiceBookingExcluded: true };
    check(metric(SupplierQualityMetricCode.VOUCHER_READY_BEFORE_SERVICE_RATE).denominator === 7 && metric(SupplierQualityMetricCode.VOUCHER_READY_BEFORE_SERVICE_RATE).numerator === 1 && metric(SupplierQualityMetricCode.VOUCHER_READY_BEFORE_SERVICE_RATE).rawValue === 14.29, `Fulfilment cancellation boundary or readiness is incorrect: ${JSON.stringify(metric(SupplierQualityMetricCode.VOUCHER_READY_BEFORE_SERVICE_RATE))}`); check(metric(SupplierQualityMetricCode.AVG_FULFILMENT_TURNAROUND_MINUTES).sampleSize === 2 && metric(SupplierQualityMetricCode.AVG_FULFILMENT_TURNAROUND_MINUTES).rawValue === 30, 'Fulfilment turnaround is incorrect'); results.voucherBoundary = { readyAt: '08:59 Asia/Kolkata', lateAt: '09:01 Asia/Kolkata', readyRate: metric(SupplierQualityMetricCode.VOUCHER_READY_BEFORE_SERVICE_RATE).rawValue, expectedDenominator: 7, cancelledBeforeBoundaryExcluded: true, cancelledAfterBoundaryCounted: true };
    check(metric(SupplierQualityMetricCode.LAST_MINUTE_STOP_SELL_RATE).numerator === 3 && metric(SupplierQualityMetricCode.LAST_MINUTE_STOP_SELL_RATE).denominator === 3, 'Stop-sell session counting/timing is incorrect'); check(metric(SupplierQualityMetricCode.LIVE_PRODUCT_IMAGE_COVERAGE_RATE).rawValue === 75, 'Image coverage is incorrect'); results.stopSell = { affectedSessionIds: 3, denominator: 3, duplicateCountedOnce: true, tenDayExceptionExcluded: true }; results.imageCoverage = '3 of 4 LIVE published products with active IMAGE media = 75%';
    for (const code of [SupplierQualityMetricCode.CUSTOMER_RATING, SupplierQualityMetricCode.NPS, SupplierQualityMetricCode.COMPLAINT_RATE]) { const row = metric(code); check(row.status === SupplierMetricStatus.UNAVAILABLE && row.rawValue === null && row.sampleSize === 0 && row.score === null, `${code} is not unavailable-first`); } results.travellerUnavailable = true;
    const scorePolicy = await prisma.supplierQualityPolicy.create({
      data: { versionNumber: 900000 + Math.floor(Math.random() * 5000), name: 'Phase 10.2 isolated scoring fixture', measurementWindowDays: 30, shortNoticeDays: 2, lastMinuteStopSellDays: 2, createdById: actor.sub,
        metricRules: { create: [
          { metricCode: SupplierQualityMetricCode.CONFIRMATION_WITHIN_SLA_RATE, dimension: SupplierQualityDimension.CONFIRMATION_SLA, direction: SupplierMetricDirection.HIGHER_BETTER, weight: 2, targetValue: 80, warningValue: 60, minimumSampleSize: 1, missingDataTreatment: SupplierMetricMissingDataTreatment.EXCLUDE, passScore: 100, warnScore: 50, failScore: 0 },
          { metricCode: SupplierQualityMetricCode.VENDOR_CANCELLATION_RATE, dimension: SupplierQualityDimension.CANCELLATION_RELIABILITY, direction: SupplierMetricDirection.LOWER_BETTER, weight: 1, targetValue: 10, warningValue: 20, minimumSampleSize: 1, missingDataTreatment: SupplierMetricMissingDataTreatment.EXCLUDE, passScore: 100, warnScore: 50, failScore: 0 },
        ] },
        tierRules: { create: [{ tier: SupplierTier.ELITE, minimumScore: 90 }, { tier: SupplierTier.PREFERRED, minimumScore: 75 }, { tier: SupplierTier.STANDARD, minimumScore: 50 }, { tier: SupplierTier.WATCHLIST, minimumScore: 25 }, { tier: SupplierTier.RESTRICTED, minimumScore: 0 }] },
      },
      include: { metricRules: { orderBy: { rank: 'asc' } }, tierRules: true },
    });
    createdPolicies.push(scorePolicy.id); const assessedPass = evaluator.assess({ ...metric(SupplierQualityMetricCode.CONFIRMATION_WITHIN_SLA_RATE), rawValue: 80, sampleSize: 1 } as any, scorePolicy.metricRules[0] as any); const assessedFail = evaluator.assess({ ...metric(SupplierQualityMetricCode.VENDOR_CANCELLATION_RATE), rawValue: 30, sampleSize: 10 } as any, scorePolicy.metricRules[1] as any); const score = evaluator.score([assessedPass, assessedFail], scorePolicy.metricRules as any); check(assessedPass.status === SupplierMetricStatus.PASS && assessedFail.status === SupplierMetricStatus.FAIL && Math.abs((score ?? 0) - 66.6666667) < 0.001, 'Controlled scoring result is incorrect'); check(evaluator.recommendedTier(score, scorePolicy as any) === SupplierTier.STANDARD, 'Controlled recommended tier is incorrect'); results.scoring = { statuses: ['PASS', 'FAIL'], weightedScore: score, recommendedTier: SupplierTier.STANDARD };
    const raceAllowed = await prisma.supplierQualityPolicy.count({ where: { status: SupplierQualityPolicyStatus.ACTIVE } }) === 0; check(raceAllowed, 'Cannot run isolated activation race while a shared ACTIVE policy exists'); const racePolicies = await Promise.all([900100, 900101].map((versionNumber) => prisma.supplierQualityPolicy.create({ data: { versionNumber, name: `Phase 10.2 race ${versionNumber}`, measurementWindowDays: 30, shortNoticeDays: 2, lastMinuteStopSellDays: 2, createdById: actor.sub } }))); createdPolicies.push(...racePolicies.map((p) => p.id)); const raceResults = await Promise.allSettled(racePolicies.map((p) => policyService.activate(actor, p.id))); const activeRaceCount = await prisma.supplierQualityPolicy.count({ where: { id: { in: racePolicies.map((p) => p.id) }, status: SupplierQualityPolicyStatus.ACTIVE } }); check(activeRaceCount === 1 && raceResults.some((r) => r.status === 'rejected' && JSON.stringify(r.reason).includes('QUALITY_POLICY_ACTIVE_CONFLICT')), 'Policy activation race did not produce one active and one controlled conflict'); results.policyActivationRace = { activePolicies: activeRaceCount, controlledConflict: true };
    await prisma.supplierQualityPolicy.deleteMany({ where: { id: { in: racePolicies.map((p) => p.id) } } });
    const concurrentCaptures = await Promise.all([snapshotService.capture(actor, vendor.id, { windowStart: windowStart.toISOString(), windowEnd: now.toISOString() }), snapshotService.capture(actor, vendor.id, { windowStart: windowStart.toISOString(), windowEnd: now.toISOString() })]); const captureIds = new Set(concurrentCaptures.map((s) => s.id)); check(captureIds.size === 1, 'Concurrent captures did not return one logical snapshot'); const captureSnapshot = concurrentCaptures[0]; createdSnapshots.push(captureSnapshot.id); results.snapshotRace = { returnedIds: [...captureIds], oneLogicalSnapshot: true };
    const issueSnapshot = await prisma.supplierQualitySnapshot.create({ data: { vendorTenantId: vendor.id, windowStart, windowEnd: now, metrics: {}, snapshotKey: id('issue-snapshot') } }); createdSnapshots.push(issueSnapshot.id); const failMetric: any = { metricCode: SupplierQualityMetricCode.VENDOR_CANCELLATION_RATE, dimension: SupplierQualityDimension.CANCELLATION_RELIABILITY, rawValue: 30, numerator: 3, denominator: 10, sampleSize: 10, unit: 'percent', status: SupplierMetricStatus.FAIL, score: 0, sourceTrace: { cohort: 'controlled' } }; const firstIssue = await prisma.$transaction((tx) => (snapshotService as any).openOrUpdateIssue(tx, vendor.id, issueSnapshot.id, failMetric)); const secondIssue = await prisma.$transaction((tx) => (snapshotService as any).openOrUpdateIssue(tx, vendor.id, issueSnapshot.id, failMetric)); check(firstIssue.id === secondIssue.id, 'Repeated failures duplicated the quality issue'); await issueService.transition(actor, firstIssue.id, 'acknowledge'); await issueService.transition(actor, firstIssue.id, 'resolve', { reason: 'controlled resolution' }); let invalidTransition = false; try { await issueService.transition(actor, firstIssue.id, 'acknowledge'); } catch (error) { invalidTransition = JSON.stringify(error).includes('QUALITY_ISSUE_INVALID_TRANSITION'); } check(invalidTransition, 'Terminal issue transition was not controlled'); results.issueLifecycle = { repeatedFailureSameIssue: true, acknowledged: true, resolved: true, terminalTransitionControlled: true };
    const autoPolicy = await prisma.supplierQualityPolicy.create({ data: { versionNumber: 910000 + Math.floor(Math.random() * 5000), name: 'Phase 10.2 isolated auto-resolution fixture', status: SupplierQualityPolicyStatus.ACTIVE, measurementWindowDays: 30, shortNoticeDays: 2, lastMinuteStopSellDays: 2, createdById: actor.sub, metricRules: { create: [{ metricCode: SupplierQualityMetricCode.LIVE_PRODUCT_IMAGE_COVERAGE_RATE, dimension: SupplierQualityDimension.CATALOGUE_QUALITY, direction: SupplierMetricDirection.HIGHER_BETTER, weight: 1, targetValue: 50, warningValue: 25, minimumSampleSize: 1, missingDataTreatment: SupplierMetricMissingDataTreatment.EXCLUDE, passScore: 100, warnScore: 50, failScore: 0 }] } } }); createdPolicies.push(autoPolicy.id); const autoIssue = await prisma.supplierQualityIssue.create({ data: { vendorTenantId: vendor.id, snapshotId: captureSnapshot.id, metricCode: SupplierQualityMetricCode.LIVE_PRODUCT_IMAGE_COVERAGE_RATE, dimension: SupplierQualityDimension.CATALOGUE_QUALITY, severity: 'CRITICAL', status: SupplierQualityIssueStatus.OPEN, title: 'controlled auto resolution', details: { rawValue: 0 } } }); const resolvingSnapshot = await snapshotService.capture(actor, vendor.id, { windowStart: windowStart.toISOString(), windowEnd: now.toISOString() }); createdSnapshots.push(resolvingSnapshot.id); const resolvedIssue = await prisma.supplierQualityIssue.findUnique({ where: { id: autoIssue.id } }); const autoAudit = await prisma.auditLog.findFirst({ where: { tenantId: vendor.id, action: 'SUPPLIER_QUALITY_ISSUE_AUTO_RESOLVED', entityId: autoIssue.id } }); check(resolvedIssue?.status === SupplierQualityIssueStatus.RESOLVED && autoAudit, 'Automatic issue resolution was not audited'); results.autoResolutionAudit = true;
    const downstreamBefore = JSON.stringify(await prisma.product.findMany({ where: { tenantId: vendor.id }, select: { id: true, status: true, currentRevisionId: true } })); await tierService.assign(actor, vendor.id, { tier: SupplierTier.STANDARD, reason: 'controlled standard', sourceSnapshotId: captureSnapshot.id }); await tierService.assign(actor, vendor.id, { tier: SupplierTier.PREFERRED, reason: 'controlled preferred', sourceSnapshotId: captureSnapshot.id }); const tierRows = await prisma.supplierTierAssignment.findMany({ where: { vendorTenantId: vendor.id }, orderBy: { effectiveFrom: 'asc' } }); check(tierRows.length === 2 && tierRows[0].effectiveTo && tierRows[1].effectiveTo === null, 'Tier history is not effective-dated'); let mismatch = false; try { await tierService.assign(actor, otherVendor.id, { tier: SupplierTier.STANDARD, reason: 'wrong evidence', sourceSnapshotId: captureSnapshot.id }); } catch (error) { mismatch = JSON.stringify(error).includes('QUALITY_TIER_SNAPSHOT_VENDOR_MISMATCH'); } check(mismatch, 'Cross-vendor tier evidence was not rejected'); const downstreamAfter = JSON.stringify(await prisma.product.findMany({ where: { tenantId: vendor.id }, select: { id: true, status: true, currentRevisionId: true } })); check(downstreamBefore === downstreamAfter, 'Quality tier changed catalogue/downstream state'); results.tierGovernance = { standardClosed: true, preferredCurrent: true, sourceOwnershipControlled: true, downstreamUnchanged: true };
    const resolveAudit = await prisma.auditLog.findFirst({ where: { tenantId: vendor.id, action: 'SUPPLIER_QUALITY_ISSUE_RESOLVE' } }); check(resolveAudit, 'Issue transition audit was not persisted atomically'); results.audit = { issueTransitionAuditPresent: true };
    console.log(JSON.stringify({ phase: '10.2', fixtureVendor: vendor.id, checks: results }, null, 2));
  } finally {
    await prisma.supplierQualityIssue.deleteMany({ where: { vendorTenantId: { in: [vendor.id, otherVendor.id] } } }); await prisma.supplierTierAssignment.deleteMany({ where: { vendorTenantId: { in: [vendor.id, otherVendor.id] } } });
    const snapshotIds = (await prisma.supplierQualitySnapshot.findMany({ where: { vendorTenantId: { in: [vendor.id, otherVendor.id] } }, select: { id: true } })).map((s) => s.id);
    if (snapshotIds.length) await prisma.supplierQualityMetricSnapshot.deleteMany({ where: { snapshotId: { in: snapshotIds } } }); await prisma.supplierQualitySnapshot.deleteMany({ where: { vendorTenantId: { in: [vendor.id, otherVendor.id] } } });
    if (createdBookings.length) { await prisma.voucherVersion.deleteMany({ where: { bookingId: { in: createdBookings } } }); await prisma.bookingFulfilment.deleteMany({ where: { bookingId: { in: createdBookings } } }); await prisma.bookingCancellation.deleteMany({ where: { bookingId: { in: createdBookings } } }); await prisma.bookingSnapshot.deleteMany({ where: { bookingId: { in: createdBookings } } }); await prisma.booking.deleteMany({ where: { id: { in: createdBookings } } }); }
    if (scheduleId) { await prisma.scheduleException.deleteMany({ where: { scheduleTemplateId: scheduleId } }); await prisma.serviceSession.deleteMany({ where: { scheduleTemplateId: scheduleId } }); await prisma.scheduleSlotTemplate.deleteMany({ where: { scheduleTemplateId: scheduleId } }); await prisma.scheduleTemplate.delete({ where: { id: scheduleId } }); }
    if (createdRevisions.length) await prisma.productMedia.deleteMany({ where: { revisionId: { in: createdRevisions } } }); for (const productId of createdProducts) await prisma.product.update({ where: { id: productId }, data: { currentRevisionId: null } }).catch(() => undefined); if (createdRevisions.length) await prisma.productRevision.deleteMany({ where: { id: { in: createdRevisions } } }); if (ratePlanId) await prisma.ratePlan.delete({ where: { id: ratePlanId } }).catch(() => undefined); if (variantId) await prisma.productVariant.delete({ where: { id: variantId } }).catch(() => undefined); if (createdProducts.length) await prisma.product.deleteMany({ where: { id: { in: createdProducts } } }); if (createdFiles.length) await prisma.fileAsset.deleteMany({ where: { id: { in: createdFiles } } }); if (createdPolicies.length) await prisma.supplierQualityPolicy.deleteMany({ where: { id: { in: createdPolicies } } }); await prisma.auditLog.deleteMany({ where: { tenantId: { in: [vendor.id, otherVendor.id] } } }); await prisma.outboxEvent.deleteMany({ where: { tenantId: { in: [vendor.id, otherVendor.id] } } }); await prisma.user.delete({ where: { id: agentUser.id } }).catch(() => undefined); await prisma.tenant.deleteMany({ where: { id: { in: [vendor.id, otherVendor.id, agentTenant.id] } } }); await prisma.$disconnect();
  }
}
main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
