import { ChannelContractStatus, ChannelInventoryExposureMode, ChannelMappingStatus, CommercialRuleKind, CommercialRuleVersionStatus, CommercialScopeType, PrismaClient, UserRole } from '@prisma/client';
import { AuditService } from '../src/audit/audit.service';
import { CommercialCalculatorService } from '../src/commercial/commercial-calculator.service';
import { CommercialService } from '../src/commercial/commercial.service';
import { CutoffService } from '../src/eligibility/cutoff.service';
import { EligibilityService } from '../src/eligibility/eligibility.service';
import { OutboxService } from '../src/outbox/outbox.service';
import { RequestContextService } from '../src/common/request-context.service';
import { ResourcesService } from '../src/resources/resources.service';
import { ChannelContractService } from '../src/distribution/channel-contract.service';
import { ChannelEligibilityService } from '../src/distribution/channel-eligibility.service';
import { ChannelMappingService } from '../src/distribution/channel-mapping.service';
import { DistributionAuthGuard } from '../src/distribution/distribution-auth.guard';
import { DistributionCatalogService } from '../src/distribution/distribution-catalog.service';
import { DistributionAvailabilityService } from '../src/distribution/distribution-availability.service';
import { DistributionEventProjectorService, DistributionEventService } from '../src/distribution/distribution-event.service';
import { DistributionPricingService } from '../src/distribution/distribution-pricing.service';
import { DistributionService } from '../src/distribution/distribution.service';
import { AuthUser } from '../src/common/auth.types';

const prisma = new PrismaClient();
const admin: AuthUser = { sub: '', email: 'phase12-verifier@voya.demo', fullName: 'Phase 12 Verifier', role: UserRole.ADMIN, tenantId: null, organizationRole: null, active: true };
const startedAt = new Date();
const assert = (condition: unknown, message: string) => { if (!condition) throw new Error(`Phase 12 assertion failed: ${message}`); };

async function authenticate(guard: DistributionAuthGuard, apiKey: string) {
  const request: any = { headers: { 'x-api-key': apiKey } };
  await guard.canActivate({ switchToHttp: () => ({ getRequest: () => request }) } as any);
  return request.distributionContext;
}

async function main() {
  const audit = new AuditService(new RequestContextService()); const outbox = new OutboxService(prisma as any); const commercial = new CommercialService(prisma as any, audit, outbox, new CommercialCalculatorService()); const resources = new ResourcesService(prisma as any, audit, outbox); const coreEligibility = new EligibilityService(prisma as any, commercial, resources, new CutoffService()); const contracts = new ChannelContractService(prisma as any, audit, outbox); const mappings = new ChannelMappingService(prisma as any, audit, outbox); const channelEligibility = new ChannelEligibilityService(prisma as any); const distribution = new DistributionService(prisma as any, audit, outbox, contracts, mappings, channelEligibility); const catalog = new DistributionCatalogService(prisma as any); const availability = new DistributionAvailabilityService(prisma as any, channelEligibility); const pricing = new DistributionPricingService(prisma as any, commercial, channelEligibility, coreEligibility); const events = new DistributionEventService(prisma as any); const projector = new DistributionEventProjectorService(prisma as any); const authGuard = new DistributionAuthGuard(prisma as any);
  const suffix = Math.random().toString(36).slice(2, 10).toUpperCase(); const channelCode = `PHASE12_PARTNER_${suffix}`; const ids: string[] = []; const outboxIds: string[] = []; let channelId = ''; let credentialId = ''; let apiKey = '';
  const baseline = { channels: await prisma.distributionChannel.count(), contracts: await prisma.channelContract.count(), productMappings: await prisma.productChannelMapping.count(), variantMappings: await prisma.variantChannelMapping.count(), rateMappings: await prisma.ratePlanChannelMapping.count(), bookings: await prisma.booking.count(), holds: await prisma.inventoryHold.count(), allocations: await prisma.inventoryAllocation.count(), snapshots: await prisma.bookingSnapshot.count() };
  const agentChannel = await prisma.distributionChannel.findUniqueOrThrow({ where: { code: 'VOYA_AGENT' } }); const agentMapping = await prisma.ratePlanChannelMapping.findFirstOrThrow({ where: { channelId: agentChannel.id, status: ChannelMappingStatus.ACTIVE }, include: { ratePlan: { include: { variant: true } } } });
  const product = await prisma.product.findFirstOrThrow({ where: { id: agentMapping.ratePlan.variant.productId }, include: { variants: { where: { status: 'ACTIVE', archivedAt: null }, include: { ratePlans: { where: { status: 'ACTIVE' } } } } } }); const variant = product.variants.find((item) => item.id === agentMapping.ratePlan.variantId) || product.variants[0]; const ratePlan = variant.ratePlans[0] || agentMapping.ratePlan;
  const session = await prisma.serviceSession.findFirstOrThrow({ where: { serviceDate: { gt: new Date() }, scheduleTemplate: { variantId: variant.id, capacityUnitReviewRequired: false, ratePlanMappings: { some: { ratePlanId: ratePlan.id, active: true } } }, archivedAt: null }, include: { inventoryState: true, scheduleTemplate: true }, orderBy: { serviceDate: 'asc' } });
  admin.sub = (await prisma.user.findFirstOrThrow({ where: { role: UserRole.ADMIN, active: true }, select: { id: true } })).id;
  try {
    const channel = await distribution.createChannel(admin, { code: channelCode, name: `Phase 12 Partner ${suffix}`, type: 'PARTNER_API', description: 'Isolated Phase 12 verifier channel', active: true }); channelId = channel.id; ids.push(channel.id);
    const draftA = await contracts.create(admin, channelId, { name: 'Contract A', effectiveFrom: '2020-01-01T00:00:00.000Z', capabilities: ['CATALOG_READ', 'AVAILABILITY_READ', 'PRICING_READ', 'EVENT_READ'], allowedCurrencies: ['INR'], availabilityHorizonDays: 365 }); ids.push(draftA.id);
    const draftB = await contracts.create(admin, channelId, { name: 'Contract B', effectiveFrom: '2020-01-01T00:00:00.000Z', capabilities: ['CATALOG_READ', 'AVAILABILITY_READ', 'PRICING_READ', 'EVENT_READ'], allowedCurrencies: ['INR'], availabilityHorizonDays: 365 }); ids.push(draftB.id);
    const activations = await Promise.allSettled([contracts.activate(admin, draftA.id), contracts.activate(admin, draftB.id)]); assert(activations.filter((item) => item.status === 'fulfilled').length === 1, 'exactly one competing contract activation wins'); assert(activations.filter((item) => item.status === 'rejected').length === 1, 'losing contract activation is rejected');
    const activeContract = await contracts.active(channelId); assert(activeContract?.status === ChannelContractStatus.ACTIVE, 'external contract is active');
    const productMapping = await distribution.productMapping(admin, { channelId, productId: product.id, externalProductCode: `P12-P-${suffix}`, status: ChannelMappingStatus.ACTIVE }); ids.push(productMapping.id);
    const variantMapping = await distribution.variantMapping(admin, { channelId, variantId: variant.id, externalVariantCode: `P12-V-${suffix}`, status: ChannelMappingStatus.ACTIVE }); ids.push(variantMapping.id);
    const rateMapping = await distribution.rateMapping(admin, { channelId, ratePlanId: ratePlan.id, externalRatePlanCode: `P12-R-${suffix}`, status: ChannelMappingStatus.ACTIVE }); ids.push(rateMapping.id);
    const rule = await distribution.inventoryRule(admin, { ratePlanChannelMappingId: rateMapping.id, exposureMode: ChannelInventoryExposureMode.EXACT_REMAINING, capacityBuffer: 2, maxPublishedCapacity: 5 }); ids.push(rule.id);
    const credential = await distribution.createCredential(admin, { channelId, name: 'Phase 12 verifier key', scopes: ['CATALOG_READ', 'AVAILABILITY_READ', 'PRICING_READ', 'EVENT_READ'] }); credentialId = credential.id; apiKey = credential.apiKey;
    const auth = await authenticate(authGuard, apiKey); assert(auth.channelId === channelId && auth.channelCode === channelCode, 'credential resolves only its own channel');
    assert(credential.apiKey && credential.secretShownOnce === true, 'secret returned once at creation'); const stored = await prisma.channelApiCredential.findUniqueOrThrow({ where: { id: credentialId } }); assert(stored.keyHash !== apiKey && !stored.keyHash.includes(apiKey) && stored.keyPrefix !== apiKey, 'raw secret is not stored'); const listed: any = (await distribution.credentials(channelId))[0]; assert(!('keyHash' in listed) && !('apiKey' in listed), 'subsequent credential reads omit secret');
    const catalogItems = await catalog.products(auth, productMapping.externalProductCode); assert(catalogItems.length === 1 && catalogItems[0].variants[0].ratePlans.length >= 1, 'normalized catalog returns mapped safe projection'); const safeText = JSON.stringify(catalogItems); assert(!/supplier|payable|margin|sourcePayload|settlement|quality|demand/i.test(safeText), 'catalog projection excludes confidential fields');
    const beforeInventory = await prisma.inventoryState.findUniqueOrThrow({ where: { sessionId: session.id } }); const available = await availability.availability(auth, { externalProductCode: productMapping.externalProductCode, externalVariantCode: variantMapping.externalVariantCode, externalRatePlanCode: rateMapping.externalRatePlanCode!, dateFrom: new Date(session.serviceDate).toISOString().slice(0, 10), dateTo: new Date(session.serviceDate).toISOString().slice(0, 10) }); const row: any = available.items.find((item: any) => item.sessionId === session.id); const canonical = Math.max(0, beforeInventory.totalCapacity - beforeInventory.blockedCapacity - beforeInventory.heldCapacity - beforeInventory.confirmedCapacity); assert(row?.remainingCapacity === Math.min(5, Math.max(0, canonical - 2)), 'inventory buffer and publication cap are applied'); const afterInventory = await prisma.inventoryState.findUniqueOrThrow({ where: { sessionId: session.id } }); assert(JSON.stringify(beforeInventory) === JSON.stringify(afterInventory), 'distribution availability does not mutate InventoryState');
    const quote = await pricing.quote(auth, { externalRatePlanCode: rateMapping.externalRatePlanCode!, sessionId: session.id, travellers: [{ type: 'ADULT', quantity: 1 }], units: 1, currency: 'INR' }); assert(quote.provisional === true && quote.quoteFingerprint && !('supplier' in quote) && !('voya' in quote), 'normalized quote is safe and provisional'); const quoteAgain = await pricing.quote(auth, { externalRatePlanCode: rateMapping.externalRatePlanCode!, sessionId: session.id, travellers: [{ type: 'ADULT', quantity: 1 }], units: 1, currency: 'INR' }); assert(quote.quoteFingerprint === quoteAgain.quoteFingerprint, 'same semantic quote has stable fingerprint');
    const channelRule = await prisma.commercialRule.create({ data: { code: `P12-RULE-${suffix}`, name: 'Phase 12 channel markup', kind: CommercialRuleKind.VOYA_REVENUE, scopeType: CommercialScopeType.GLOBAL, distributionChannelId: channelId, createdById: admin.sub } }); ids.push(channelRule.id); const channelVersion = await prisma.commercialRuleVersion.create({ data: { ruleId: channelRule.id, versionNumber: 1, status: CommercialRuleVersionStatus.ACTIVE, effectiveFrom: new Date('2020-01-01T00:00:00.000Z'), priority: 99, config: { model: 'MARKUP_FIXED', fixedAmount: '7' }, createdById: admin.sub, activatedById: admin.sub } }); ids.push(channelVersion.id); const externalCommercial = await commercial.evaluateInternal({ ratePlanId: ratePlan.id, serviceDate: session.serviceDate, units: 1, travellers: [{ travellerType: 'ADULT', quantity: 1 }], channel: channelCode }); const agentCommercial = await commercial.evaluateInternal({ ratePlanId: ratePlan.id, serviceDate: session.serviceDate, units: 1, travellers: [{ travellerType: 'ADULT', quantity: 1 }], channel: 'VOYA_AGENT' }); assert(externalCommercial.appliedRules?.some((item: any) => item.ruleId === channelRule.id) && !agentCommercial.appliedRules?.some((item: any) => item.ruleId === channelRule.id), 'channel-qualified commercial rule applies only to its channel');
    const mappedProductCode = (await prisma.productChannelMapping.findFirstOrThrow({ where: { channelId: agentChannel.id, productId: product.id } })).externalProductCode; let crossChannelDenied = false; try { await catalog.product(auth, mappedProductCode); } catch { crossChannelDenied = true; } assert(crossChannelDenied, 'Channel A cannot read Channel B product');
    let duplicateRejected = false; try { await distribution.productMapping(admin, { channelId, productId: product.id, externalProductCode: `P12-OTHER-${suffix}`, status: ChannelMappingStatus.ACTIVE }); } catch { duplicateRejected = true; } assert(duplicateRejected, 'duplicate product mapping rejected');
    const source = await prisma.outboxEvent.create({ data: { eventType: 'PRODUCT_PUBLISHED', aggregateType: 'Product', aggregateId: product.id, payload: { channelId, externalProductCode: productMapping.externalProductCode } } }); outboxIds.push(source.id); const projectedOne = await projector.project(1000); const eventCountOne = await prisma.distributionEvent.count({ where: { channelId } }); const projectedTwo = await projector.project(1000); const eventCountTwo = await prisma.distributionEvent.count({ where: { channelId } }); assert(eventCountOne === eventCountTwo && eventCountOne >= 1, `projector is idempotent and independent of Outbox status: ${JSON.stringify({ projectedOne, eventCountOne, projectedTwo, eventCountTwo, sourceCreatedAt: source.createdAt })}`); const eventFeed = await events.list(auth, { limit: 50 }); assert(eventFeed.items.length >= 1 && eventFeed.items.every((item) => item.type), 'event feed is channel-scoped');
    const afterBusiness = { bookings: await prisma.booking.count(), holds: await prisma.inventoryHold.count(), allocations: await prisma.inventoryAllocation.count(), snapshots: await prisma.bookingSnapshot.count() }; assert(JSON.stringify(baseline) === JSON.stringify({ ...baseline, ...afterBusiness }), 'distribution reads do not mutate booking, hold, allocation, or snapshot state');
    const removed = await distribution.revokeCredential(admin, credentialId); assert(removed.status === 'REVOKED', 'credential revocation recorded'); let revokedDenied = false; try { await authenticate(authGuard, apiKey); } catch { revokedDenied = true; } assert(revokedDenied, 'revoked credential is denied');
    console.log(JSON.stringify({ phase: '12', checks: { contractConcurrency: 'one winner / one loser', channelType: channel.type, voyaAgentIdPreserved: agentChannel.id, mappingBackfill: { product: true, variant: true, ratePlan: true }, catalog: true, availability: { buffer: 2, maxPublishedCapacity: 5, inventoryUnchanged: true }, quote: { readOnly: true, stableFingerprint: true, channelRule: true }, crossChannelDenied, secretHashOnly: true, eventProjection: { firstRun: projectedOne, secondRun: projectedTwo, eventCount: eventCountTwo }, revokedDenied }, baseline }, null, 2));
  } finally {
    if (channelId) await prisma.distributionChannel.delete({ where: { id: channelId } }).catch(() => undefined);
    const phaseOutbox = await prisma.outboxEvent.findMany({ where: { createdAt: { gte: startedAt } }, select: { id: true, aggregateId: true, payload: true } }); const toDelete = phaseOutbox.filter((row: any) => row.id === sourceId(outboxIds) || ids.includes(row.aggregateId) || JSON.stringify(row.payload).includes(channelId)).map((row) => row.id); if (toDelete.length) await prisma.outboxEvent.deleteMany({ where: { id: { in: toDelete } } });
    if (ids.length) await prisma.auditLog.deleteMany({ where: { entityId: { in: ids } } }).catch(() => undefined);
    // Prisma is disconnected by the outer finally.
  }
}

function sourceId(ids: string[]) { return ids[0]; }
main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
