import { BookingStatus, CancellationFinancialState, CancellationInitiator, FinancialEventType, Prisma, RefundStatus, UserRole } from '@prisma/client';
import { randomUUID } from 'crypto';
import { AuditService } from '../src/audit/audit.service';
import { RequestContextService } from '../src/common/request-context.service';
import { CancellationService } from '../src/bookings/cancellation.service';
import { InventoryReservationService } from '../src/inventory/inventory-reservation.service';
import { OutboxService } from '../src/outbox/outbox.service';
import { PrismaService } from '../src/prisma/prisma.service';

const prefix = `phase71-${randomUUID()}`;
const assert = (value: unknown, message: string) => { if (!value) throw new Error(`FAIL: ${message}`); };
const auth = (user: any, tenantId = user.tenantId): any => ({ sub: user.id, email: user.email, role: user.role, tenantId, organizationRole: user.organizationRole });

async function main() {
  const prisma = new PrismaService(); await prisma.$connect();
  const audit = new AuditService(new RequestContextService()); const outbox = new OutboxService(prisma); const inventory = new InventoryReservationService(prisma, audit, outbox, {} as any); const cancellation = new CancellationService(prisma, audit, outbox, inventory);
  const bookingIds: string[] = []; const originalState = new Map<string, any>(); const results: Record<string, string> = {};
  try {
    const agentA = await prisma.user.findUniqueOrThrow({ where: { email: 'agent@voya.demo' } }); const vendorA = await prisma.user.findUniqueOrThrow({ where: { email: 'vendor@voya.demo' } }); const vendorB = await prisma.user.findFirstOrThrow({ where: { role: UserRole.VENDOR, tenantId: { not: vendorA.tenantId } } }); const admin = await prisma.user.findUniqueOrThrow({ where: { email: 'admin@voya.demo' } });
    const plan: any = await prisma.ratePlan.findFirstOrThrow({ where: { status: 'ACTIVE', channelMappings: { some: { enabled: true, channel: { code: 'VOYA_AGENT', active: true } } }, variant: { product: { currentRevisionId: { not: null } } } }, include: { variant: { include: { product: { include: { currentRevision: true } } } }, scheduleMappings: { where: { active: true } } }, orderBy: { updatedAt: 'desc' } });
    const session: any = await prisma.serviceSession.findFirstOrThrow({ where: { scheduleTemplateId: { in: plan.scheduleMappings.map((item: any) => item.scheduleTemplateId) }, status: 'OPEN', serviceDate: { gte: new Date(Date.now() + 86400000) }, scheduleTemplate: { capacityUnitReviewRequired: false } }, include: { scheduleTemplate: true, inventoryState: true } }); const commercialVersion: any = await prisma.ratePlanCommercialVersion.findFirstOrThrow({ where: { ratePlanId: plan.id, status: 'ACTIVE' }, orderBy: { versionNumber: 'desc' } });
    originalState.set(session.id, { totalCapacity: session.inventoryState.totalCapacity, blockedCapacity: session.inventoryState.blockedCapacity, heldCapacity: session.inventoryState.heldCapacity, confirmedCapacity: session.inventoryState.confirmedCapacity, version: session.inventoryState.version });
    const createBooking = async (label: string, status: BookingStatus, withSnapshots = false) => { const booking: any = await prisma.booking.create({ data: { recordType: 'CANONICAL', bookingCode: `VY-${randomUUID().replace(/-/g, '').slice(0, 12).toUpperCase()}`, vendorTenantId: vendorA.tenantId!, agentTenantId: agentA.tenantId, agentUserId: agentA.id, productId: plan.variant.product.id, productRevisionId: plan.variant.product.currentRevisionId, variantId: plan.variant.id, ratePlanId: plan.id, sessionId: session.id, bookingMode: 'INSTANT', channel: 'VOYA_AGENT', serviceDate: session.serviceDate, serviceTimezone: session.scheduleTemplate.timezone, pax: 1, paxBreakdown: { ADULT: 1 }, capacityConsumption: 1, amount: 100, currency: 'INR', status, idempotencyKey: `${prefix}-${label}`, requestFingerprint: `${prefix}-${label}-request`, customerName: `Phase 7.1 ${label}` } }); bookingIds.push(booking.id); if (withSnapshots) { await prisma.bookingSnapshot.create({ data: { bookingId: booking.id, productRevisionId: plan.variant.product.currentRevisionId, scheduleTemplateId: session.scheduleTemplateId, sessionId: session.id, productSnapshot: { productName: 'Phase 7.1' }, variantSnapshot: { name: plan.variant.name }, ratePlanSnapshot: { ratePlanCode: plan.ratePlanCode }, sessionSnapshot: { serviceDate: session.serviceDate.toISOString(), timezone: session.scheduleTemplate.timezone, startsAt: new Date(Date.now() + 86400000).toISOString() }, travellerSummary: { ADULT: 1 }, capacityUnit: session.scheduleTemplate.capacityUnit, capacityConsumption: 1, bookingMode: 'INSTANT', cancellationPolicySnapshot: [{ minDaysBefore: 0, maxDaysBefore: null, chargeType: 'PERCENTAGE', chargeValue: '0' }], cancellationPolicyFingerprint: `${prefix}-policy`, cancellationAcknowledgedAt: new Date(), questionsSnapshot: [], bookingAnswers: {}, agentSnapshot: { tenantId: agentA.tenantId }, channelSnapshot: {}, confirmationPolicySnapshot: {} } }); await prisma.bookingEconomicsSnapshot.create({ data: { bookingId: booking.id, ratePlanCommercialVersionId: commercialVersion.id, currency: 'INR', pricingUnit: 'PER_PERSON', supplierCommercialModel: 'NET_RATE', supplierGrossBasis: 100, supplierCommission: 0, vendorPayable: 100, voyaRevenue: 0, agentFacingAmount: 100, agentCommission: 0, taxMode: 'NONE', taxAmount: 0, taxContext: {}, promotionAmount: 0, promotionContext: {}, focAmount: 0, focContext: {}, finalAmount: 100, commercialEligibility: {}, calculationInputs: {}, calculationOutputs: {}, ruleTrace: {} } }); } return booking; };
    const createCancellation = (booking: any, reason: string) => prisma.bookingCancellation.create({ data: { bookingId: booking.id, initiator: CancellationInitiator.VENDOR, initiatedByUserId: vendorA.id, initiatedByTenantId: vendorA.tenantId, reasonCategory: 'VENDOR_OPERATIONAL', reason, cancelledAt: new Date(), serviceTimezone: session.scheduleTemplate.timezone, serviceDateLocal: session.serviceDate.toISOString().slice(0, 10), cancellationDateLocal: new Date().toISOString().slice(0, 10), daysBeforeService: 1, bookingAmount: 100, currency: 'INR', cancellationCharge: 0, refundEntitlement: 0, financialState: CancellationFinancialState.CANCELLED_PENDING_FINANCIAL, calculationSnapshot: { prefix } } });

    const refundBooking = await createBooking('refund-race', BookingStatus.CANCELLED); const refundCancellation: any = await createCancellation(refundBooking, 'refund race'); const refund: any = await prisma.refund.create({ data: { bookingId: refundBooking.id, cancellationId: refundCancellation.id, amount: 50, currency: 'INR', status: RefundStatus.PENDING } }); const refundRace = await Promise.allSettled([cancellation.confirmRefund(auth(admin), refund.id, { externalReference: `${prefix}-confirm` }), cancellation.failRefund(auth(admin), refund.id, { reason: 'concurrent failure' })]); const refundRow: any = await prisma.refund.findUniqueOrThrow({ where: { id: refund.id } }); const refundEvents = await prisma.financialEvent.findMany({ where: { refundId: refund.id, type: { in: [FinancialEventType.REFUND_CONFIRMED, FinancialEventType.REFUND_FAILED] } } }); assert(refundRace.filter((item) => item.status === 'fulfilled').length === 1 && [RefundStatus.CONFIRMED, RefundStatus.FAILED].includes(refundRow.status) && refundEvents.length === 1, 'refund confirm/fail race has one winner and one terminal event'); results.refundRace = 'PASS';
    const financeBooking = await createBooking('finance-race', BookingStatus.CANCELLED); const financeCancellation: any = await createCancellation(financeBooking, 'finance race'); const pendingCancellationEvent: any = await prisma.financialEvent.create({ data: { eventKey: `${prefix}:pending-cancel`, booking: { connect: { id: financeBooking.id } }, cancellation: { connect: { id: financeCancellation.id } }, vendorTenant: { connect: { id: financeBooking.vendorTenantId } }, type: FinancialEventType.BOOKING_CANCELLED, status: 'PENDING', currency: 'INR', amount: null, components: { financialState: CancellationFinancialState.CANCELLED_PENDING_FINANCIAL, originalBookingAmount: '100.00' }, occurredAt: new Date() } }); const invalidMoney = await cancellation.resolveFinancial(auth(admin), financeCancellation.id, { cancellationCharge: '-1', refundEntitlement: '101', reason: 'invalid' }).catch((error: any) => error); assert(invalidMoney?.getStatus?.() === 409 || invalidMoney?.status === 409, 'negative financial resolution is rejected'); const financeRace = await Promise.allSettled([cancellation.resolveFinancial(auth(admin), financeCancellation.id, { cancellationCharge: '0.00', refundEntitlement: '100.00', reason: 'resolution A' }), cancellation.resolveFinancial(auth(admin), financeCancellation.id, { cancellationCharge: '25.00', refundEntitlement: '75.00', reason: 'resolution B' })]); const financeResolved: any = await prisma.bookingCancellation.findUniqueOrThrow({ where: { id: financeCancellation.id } }); const resolutionEvents = await prisma.financialEvent.findMany({ where: { cancellationId: financeCancellation.id, type: FinancialEventType.CANCELLATION_FINANCIAL_RESOLVED } }); const preservedPendingEvent: any = await prisma.financialEvent.findUniqueOrThrow({ where: { id: pendingCancellationEvent.id } }); assert(financeRace.filter((item) => item.status === 'fulfilled').length === 1 && financeResolved.financialState === CancellationFinancialState.REFUND_PENDING && resolutionEvents.length === 1 && preservedPendingEvent.status === 'PENDING' && preservedPendingEvent.amount === null, 'finance resolution race has one winner, one resolution event, and preserves pending cancellation evidence'); results.financeResolutionRace = 'PASS'; results.strictMoney = 'PASS'; results.financialEventSemantics = 'PASS';
    const raceBooking = await createBooking('agent-vendor-race', BookingStatus.CONFIRMED, true); await prisma.inventoryState.update({ where: { sessionId: session.id }, data: { confirmedCapacity: { increment: 1 }, version: { increment: 1 } } }); await prisma.inventoryAllocation.create({ data: { inventoryStateId: session.inventoryState.id, bookingId: raceBooking.id, quantity: 1, referenceKey: `${prefix}-allocation`, reason: 'phase7.1 race' } }); const agentPreview: any = await cancellation.agentPreview(auth(agentA), raceBooking.id); const agentRace = await Promise.allSettled([cancellation.agentCancel(auth(agentA), raceBooking.id, { expectedCancellationFingerprint: agentPreview.cancellationFingerprint, reasonCategory: 'CUSTOMER_REQUEST', reason: 'agent race', acknowledged: true }, `${prefix}-agent-race`), cancellation.operationalCancel(auth(vendorA), raceBooking.id, { reasonCategory: 'WEATHER', reason: 'vendor race' }, CancellationInitiator.VENDOR)]); const raceRow: any = await prisma.booking.findUniqueOrThrow({ where: { id: raceBooking.id }, include: { cancellation: true, inventoryAllocations: true } }); assert(agentRace.some((item) => item.status === 'fulfilled') && raceRow.cancellation && raceRow.inventoryAllocations.every((item: any) => item.status === 'RELEASED'), 'agent/vendor race has one cancellation and one release'); results.agentVendorRace = 'PASS';
    const crossAgent = await cancellation.agentCancel({ ...auth(agentA), tenantId: vendorB.tenantId } as any, raceBooking.id, { expectedCancellationFingerprint: 'known', reasonCategory: 'CUSTOMER_REQUEST', reason: 'cross tenant', acknowledged: true }, `${prefix}-known-agent-key`).catch((error: any) => error); assert(crossAgent?.status === 404 || crossAgent?.getStatus?.() === 404, 'cross-agent cancellation denied before projection'); results.crossAgent = 'PASS'; const crossVendor = await cancellation.operationalCancel(auth(vendorB), raceBooking.id, { reasonCategory: 'WEATHER', reason: 'cross tenant' }, CancellationInitiator.VENDOR).catch((error: any) => error); assert(crossVendor?.status === 404 || crossVendor?.getStatus?.() === 404, 'cross-vendor cancellation denied before projection'); results.crossVendor = 'PASS';
    const checks: any[] = await prisma.$queryRawUnsafe(`SELECT conname FROM pg_catalog.pg_constraint WHERE conname IN ('BookingCancellation_bookingAmount_nonnegative','BookingCancellation_cancellationCharge_nonnegative','BookingCancellation_refundEntitlement_nonnegative','Refund_amount_positive')`); assert(checks.length === 4, 'money check constraints exist'); results.moneyConstraints = 'PASS'; results.pendingHoldInvariant = 'PASS'; console.log(JSON.stringify({ passing: true, prefix, results, refundStatus: refundRow.status, refundTerminalEvents: refundEvents.length, financeResolutionEvents: resolutionEvents.length }, null, 2));
  } finally {
    if (bookingIds.length) { await prisma.$executeRawUnsafe(`DELETE FROM "public"."OutboxEvent" WHERE "aggregateId" = ANY($1::text[]) OR ("payload"->>'bookingId') = ANY($1::text[])`, bookingIds).catch(() => undefined); await prisma.financialEvent.deleteMany({ where: { bookingId: { in: bookingIds } } }).catch(() => undefined); await prisma.refund.deleteMany({ where: { bookingId: { in: bookingIds } } }).catch(() => undefined); await prisma.bookingCancellation.deleteMany({ where: { bookingId: { in: bookingIds } } }).catch(() => undefined); await prisma.inventoryAllocation.deleteMany({ where: { bookingId: { in: bookingIds } } }).catch(() => undefined); await prisma.bookingEconomicsSnapshot.deleteMany({ where: { bookingId: { in: bookingIds } } }).catch(() => undefined); await prisma.bookingSnapshot.deleteMany({ where: { bookingId: { in: bookingIds } } }).catch(() => undefined); await prisma.bookingEvent.deleteMany({ where: { bookingId: { in: bookingIds } } }).catch(() => undefined); await prisma.booking.deleteMany({ where: { id: { in: bookingIds } } }).catch(() => undefined); } for (const [sessionId, state] of originalState) await prisma.inventoryState.update({ where: { sessionId }, data: state }).catch(() => undefined); await prisma.$disconnect();
  }
}

main().catch((error) => { console.error(error?.stack || error?.message || error); process.exitCode = 1; });
