import { ChannelContractStatus, ChannelInventoryExposureMode, ChannelMappingStatus, DistributionCapability, PrismaClient, UserRole, VendorVerificationStatus } from '@prisma/client';
import { AuditService } from '../src/audit/audit.service';
import { AuthUser } from '../src/common/auth.types';
import { RequestContextService } from '../src/common/request-context.service';
import { CommercialCalculatorService } from '../src/commercial/commercial-calculator.service';
import { CommercialService } from '../src/commercial/commercial.service';
import { CutoffService } from '../src/eligibility/cutoff.service';
import { EligibilityService } from '../src/eligibility/eligibility.service';
import { ResourcesService } from '../src/resources/resources.service';
import { OutboxService } from '../src/outbox/outbox.service';
import { ChannelContractService } from '../src/distribution/channel-contract.service';
import { ChannelEligibilityService } from '../src/distribution/channel-eligibility.service';
import { ChannelMappingService } from '../src/distribution/channel-mapping.service';
import { DistributionAuthGuard } from '../src/distribution/distribution-auth.guard';
import { DistributionCatalogService } from '../src/distribution/distribution-catalog.service';
import { DistributionAvailabilityService } from '../src/distribution/distribution-availability.service';
import { DistributionEventProjectorService, DistributionEventService } from '../src/distribution/distribution-event.service';
import { DistributionPricingService } from '../src/distribution/distribution-pricing.service';
import { DistributionService } from '../src/distribution/distribution.service';
import { AdminService } from '../src/admin/admin.service';

const prisma = new PrismaClient();
const assert = (value: unknown, message: string) => { if (!value) throw new Error(`Phase 12.1 assertion failed: ${message}`); };
const codeOf = (error: any) => error?.response?.code || error?.response?.reasonCodes?.[0] || error?.response?.gates?.find((gate: any) => gate.code)?.code || error?.response?.message || error?.message || String(error);
async function rejected(task: () => Promise<unknown>, expected?: string) { try { await task(); throw new Error(`Expected rejection${expected ? ` (${expected})` : ''}`); } catch (error: any) { if (error.message?.startsWith('Expected rejection')) throw error; if (expected) assert(String(codeOf(error)).includes(expected), `expected ${expected}, got ${codeOf(error)}`); return error; } }
async function authenticate(guard: DistributionAuthGuard, apiKey: string) { const request: any = { headers: { 'x-api-key': apiKey } }; await guard.canActivate({ switchToHttp: () => ({ getRequest: () => request }) } as any); return request.distributionContext; }

async function main() {
  const audit = new AuditService(new RequestContextService()); const outbox = new OutboxService(prisma as any); const commercial = new CommercialService(prisma as any, audit, outbox, new CommercialCalculatorService()); const resources = new ResourcesService(prisma as any, audit, outbox); const core = new EligibilityService(prisma as any, commercial, resources, new CutoffService()); const contracts = new ChannelContractService(prisma as any, audit, outbox); const mappings = new ChannelMappingService(prisma as any, audit, outbox); const channelEligibility = new ChannelEligibilityService(prisma as any); const distribution = new DistributionService(prisma as any, audit, outbox, contracts, mappings, channelEligibility); const catalog = new DistributionCatalogService(prisma as any); const availability = new DistributionAvailabilityService(prisma as any, channelEligibility); const pricing = new DistributionPricingService(prisma as any, commercial, channelEligibility, core); const events = new DistributionEventService(prisma as any); const projector = new DistributionEventProjectorService(prisma as any); const authGuard = new DistributionAuthGuard(prisma as any); const adminService = new AdminService(prisma as any, audit, outbox, mappings);
  const actor: AuthUser = { sub: (await prisma.user.findFirstOrThrow({ where: { role: UserRole.ADMIN, active: true }, select: { id: true } })).id, email: 'phase12-1@voya.demo', fullName: 'Phase 12.1 Verifier', role: UserRole.ADMIN, tenantId: null, organizationRole: null, active: true };
  const suffix = Math.random().toString(36).slice(2, 10).toUpperCase(); const channelCode = `PARTNER_API_${suffix}`; const startedAt = new Date(); let channelId = ''; let resourceRequirementId = ''; const createdIds: string[] = [];
  const baseline = { bookings: await prisma.booking.count(), holds: await prisma.inventoryHold.count(), allocations: await prisma.inventoryAllocation.count(), snapshots: await prisma.bookingSnapshot.count() };
  const agent = await prisma.distributionChannel.findUniqueOrThrow({ where: { code: 'VOYA_AGENT' } }); const agentMapping = await prisma.ratePlanChannelMapping.findFirstOrThrow({ where: { channelId: agent.id, status: ChannelMappingStatus.ACTIVE }, include: { ratePlan: { include: { variant: true } } } });
  const product = await prisma.product.findUniqueOrThrow({ where: { id: agentMapping.ratePlan.variant.productId } }); const variant = await prisma.productVariant.findUniqueOrThrow({ where: { id: agentMapping.ratePlan.variantId } }); const ratePlan = await prisma.ratePlan.findUniqueOrThrow({ where: { id: agentMapping.ratePlanId } });
  const session = await prisma.serviceSession.findFirstOrThrow({ where: { serviceDate: { gt: new Date() }, archivedAt: null, scheduleTemplate: { variantId: variant.id, capacityUnitReviewRequired: false, ratePlanMappings: { some: { ratePlanId: ratePlan.id, active: true } } } }, include: { inventoryState: true, scheduleTemplate: true }, orderBy: { serviceDate: 'asc' } });
  const serviceDate = new Date(session.serviceDate).toISOString().slice(0, 10); const checks: Record<string, unknown> = {};
  try {
    const channel = await distribution.createChannel(actor, { code: channelCode, name: `Partner API ${suffix}`, type: 'PARTNER_API', active: true }); channelId = channel.id; createdIds.push(channel.id); assert(channel.version === 1, 'channel starts at version one');
    const full = await contracts.create(actor, channelId, { name: 'Full contract', effectiveFrom: '2020-01-01T00:00:00.000Z', capabilities: Object.values(DistributionCapability), allowedCurrencies: [' inr ', 'INR'], availabilityHorizonDays: 30 }); createdIds.push(full.id); assert(full.allowedCurrencies.length === 1 && full.allowedCurrencies[0] === 'INR', 'contract currencies are normalized and deduplicated');
    await rejected(() => contracts.create(actor, channelId, { name: 'Invalid currency', effectiveFrom: '2020-01-01T00:00:00.000Z', capabilities: [DistributionCapability.CATALOG_READ], allowedCurrencies: ['US'], availabilityHorizonDays: 30 }), 'CHANNEL_CONTRACT_CURRENCY_INVALID');
    const active = await contracts.activate(actor, full.id); assert(active.status === ChannelContractStatus.ACTIVE, 'full contract activates');
    const pm = await distribution.productMapping(actor, { channelId, productId: product.id, externalProductCode: `P121-P-${suffix}`, status: ChannelMappingStatus.ACTIVE }); const vm = await distribution.variantMapping(actor, { channelId, variantId: variant.id, externalVariantCode: `P121-V-${suffix}`, status: ChannelMappingStatus.ACTIVE }); const rm = await distribution.rateMapping(actor, { channelId, ratePlanId: ratePlan.id, externalRatePlanCode: `P121-R-${suffix}`, status: ChannelMappingStatus.ACTIVE }); createdIds.push(pm.id, vm.id, rm.id);
    const rule = await distribution.inventoryRule(actor, { ratePlanChannelMappingId: rm.id, exposureMode: ChannelInventoryExposureMode.EXACT_REMAINING, capacityBuffer: 1, maxPublishedCapacity: 5, maxUnitsPerQuote: 2 }); createdIds.push(rule.id);
    const credential = await distribution.createCredential(actor, { channelId, name: '  phase12.1 key  ', scopes: Object.values(DistributionCapability), expiresAt: new Date(Date.now() + 86400000).toISOString() }); createdIds.push(credential.id); assert(credential.name === 'phase12.1 key' && credential.secretShownOnce && credential.apiKey, 'credential secret is one-time and name is trimmed'); const stored = await prisma.channelApiCredential.findUniqueOrThrow({ where: { id: credential.id } }); assert(stored.keyHash !== credential.apiKey && !stored.keyHash.includes(credential.apiKey), 'credential stores only a hash');
    const auth: any = await authenticate(authGuard, credential.apiKey); assert(auth.channelId === channelId && auth.capabilities.length === 4, 'credential resolves active contract intersection');
    const catalogResult: any = await catalog.product(auth, pm.externalProductCode); const catalogText = JSON.stringify(catalogResult); assert(catalogResult.variants.some((item: any) => item.ratePlans.length) && !('instantConfirmation' in catalogResult) && !/'fileAsset|sourcePayload|supplier|payable|margin|settlement|quality|demand/i.test(catalogText), 'catalog uses canonical commercial and public-safe media projection'); checks.catalog = true;
    const available: any = await availability.availability(auth, { externalProductCode: pm.externalProductCode, externalVariantCode: vm.externalVariantCode, externalRatePlanCode: rm.externalRatePlanCode, dateFrom: serviceDate, dateTo: serviceDate }); assert(available.dateFrom === serviceDate && available.items.every((item: any) => typeof item.serviceDate === 'string' && /^\d{4}-\d{2}-\d{2}$/.test(item.serviceDate)), 'availability is date-only');
    await rejected(() => availability.availability(auth, { externalProductCode: pm.externalProductCode, externalRatePlanCode: rm.externalRatePlanCode, dateFrom: `${serviceDate}T00:00:00.000Z`, dateTo: serviceDate }), 'CHANNEL_DATE_ONLY_REQUIRED');
    const quote: any = await pricing.quote(auth, { externalRatePlanCode: rm.externalRatePlanCode, sessionId: session.id, travellers: [{ type: 'ADULT', quantity: 1 }], units: 1 }); assert(quote.provisional && quote.currency === 'INR' && quote.quoteFingerprint && !('supplier' in quote) && !('voya' in quote), 'quote is authoritative, provisional and confidential-safe'); await rejected(() => pricing.quote(auth, { externalRatePlanCode: rm.externalRatePlanCode, sessionId: session.id, travellers: [{ type: 'ADULT', quantity: 1 }], units: 1, currency: 'USD' }), 'CHANNEL_CURRENCY_NOT_ALLOWED'); await rejected(() => pricing.quote(auth, { externalRatePlanCode: rm.externalRatePlanCode, sessionId: session.id, travellers: [{ type: 'ADULT', quantity: 1 }], units: 3 }), 'CHANNEL_MAX_UNITS_EXCEEDED'); checks.quote = true;
    const cutoffResult: any = await core.evaluate({ ratePlanId: ratePlan.id, sessionId: session.id, travellers: [{ travellerType: 'ADULT', quantity: 1 }], units: 1, skipAgentGovernance: true, skipChannelGovernance: true, now: new Date(session.startsAt!.getTime() + 1000) }); assert(cutoffResult.reasonCodes?.includes('CUTOFF_PASSED') || cutoffResult.gates.some((gate: any) => gate.code === 'CUTOFF_PASSED'), 'cutoff failure is enforced without a price'); checks.cutoff = true; const requirement = await prisma.scheduleResourceRequirement.create({ data: { scheduleTemplateId: session.scheduleTemplateId, resourceType: 'GUIDE', quantity: 1, required: true, active: true, requirementKey: `P121-REQ-${suffix}` } }); resourceRequirementId = requirement.id; const resourceResult: any = await core.evaluate({ ratePlanId: ratePlan.id, sessionId: session.id, travellers: [{ travellerType: 'ADULT', quantity: 1 }], units: 1, skipAgentGovernance: true, skipChannelGovernance: true }); assert(resourceResult.gates.some((gate: any) => gate.gate === 'RESOURCES' && gate.code === 'RESOURCE_NOT_READY'), 'resource readiness failure is enforced'); await prisma.scheduleResourceRequirement.delete({ where: { id: resourceRequirementId } }); resourceRequirementId = ''; checks.resource = true;
    await prisma.channelInventoryRule.delete({ where: { id: rule.id } }); const noRule = await rejected(() => availability.availability(auth, { externalProductCode: pm.externalProductCode, externalRatePlanCode: rm.externalRatePlanCode, dateFrom: serviceDate, dateTo: serviceDate }), 'CHANNEL_INVENTORY_NOT_EXPOSED'); assert(!JSON.stringify((noRule as any).response).includes('amount'), 'inventory failure does not leak price'); await distribution.inventoryRule(actor, { ratePlanChannelMappingId: rm.id, exposureMode: ChannelInventoryExposureMode.EXACT_REMAINING, capacityBuffer: 1, maxPublishedCapacity: 5, maxUnitsPerQuote: 2 });
    const far = new Date(); far.setUTCDate(far.getUTCDate() + 31); await rejected(() => availability.availability(auth, { externalProductCode: pm.externalProductCode, externalRatePlanCode: rm.externalRatePlanCode, dateFrom: serviceDate, dateTo: far.toISOString().slice(0, 10) }), 'CHANNEL_AVAILABILITY_RANGE_EXCEEDED');
    const productRace = await Promise.allSettled([mappings.product(actor, { channelId, productId: product.id, externalProductCode: pm.externalProductCode, status: ChannelMappingStatus.ACTIVE, expectedVersion: pm.version }), mappings.product(actor, { channelId, productId: product.id, externalProductCode: pm.externalProductCode, status: ChannelMappingStatus.ACTIVE, expectedVersion: pm.version })]); assert(productRace.filter((r) => r.status === 'fulfilled').length === 1 && productRace.filter((r) => r.status === 'rejected').length === 1, 'mapping optimistic race has one winner'); const pmAfter: any = await prisma.productChannelMapping.findUniqueOrThrow({ where: { id: pm.id } }); await rejected(() => mappings.product(actor, { channelId, productId: product.id, externalProductCode: `CHANGED-${suffix}`, status: ChannelMappingStatus.ACTIVE, expectedVersion: pmAfter.version }), 'CHANNEL_EXTERNAL_IDENTIFIER_IMMUTABLE');
    const channelRace = await Promise.allSettled([distribution.updateChannel(actor, channelId, { name: `winner-${suffix}`, expectedVersion: 1 }), distribution.updateChannel(actor, channelId, { name: `loser-${suffix}`, expectedVersion: 1 })]); assert(channelRace.filter((r) => r.status === 'fulfilled').length === 1 && channelRace.filter((r) => r.status === 'rejected').length === 1, 'channel optimistic race has one winner'); const channelNow: any = await prisma.distributionChannel.findUniqueOrThrow({ where: { id: channelId } }); await rejected(() => distribution.updateChannel(actor, channelId, { active: false, expectedVersion: channelNow.version }), 'CHANNEL_DISABLE_CONFIRMATION_REQUIRED'); const disabled: any = await distribution.updateChannel(actor, channelId, { active: false, confirmDisable: true, expectedVersion: channelNow.version }); await distribution.updateChannel(actor, channelId, { active: true, expectedVersion: disabled.version });
    const mismatch = await channelEligibility.evaluate({ channelId, productId: product.id, variantId: '00000000-0000-0000-0000-000000000000', ratePlanId: ratePlan.id }); assert(mismatch.reasonCodes.includes('CHANNEL_MAPPING_HIERARCHY_MISMATCH'), 'hierarchy mismatch fails closed');
    const vendorTenantId = (await prisma.product.findUniqueOrThrow({ where: { id: product.id }, select: { tenantId: true } })).tenantId; await prisma.vendorProfile.update({ where: { tenantId: vendorTenantId }, data: { verificationStatus: VendorVerificationStatus.SUSPENDED } }); try { assert((await catalog.products(auth, pm.externalProductCode)).length === 0, 'suspended vendor is absent from catalog'); const suspended = await channelEligibility.evaluate({ channelId, productId: product.id, variantId: variant.id, ratePlanId: ratePlan.id }); assert(suspended.reasonCodes.includes('VENDOR_SUSPENDED'), 'suspended vendor is denied'); } finally { await prisma.vendorProfile.update({ where: { tenantId: vendorTenantId }, data: { verificationStatus: VendorVerificationStatus.VERIFIED } }); }
    const policy = await prisma.productFulfilmentPolicy.findUniqueOrThrow({ where: { productRevisionId: (await prisma.productRevision.findUniqueOrThrow({ where: { id: (await prisma.product.findUniqueOrThrow({ where: { id: product.id }, select: { currentRevisionId: true } })).currentRevisionId! }, select: { id: true } })).id } }); await prisma.productFulfilmentPolicy.update({ where: { id: policy.id }, data: { reviewRequired: true } }); try { const review = await channelEligibility.evaluate({ channelId, productId: product.id, variantId: variant.id, ratePlanId: ratePlan.id }); assert(review.reasonCodes.includes('FULFILMENT_POLICY_REVIEW_REQUIRED'), 'fulfilment review gate denies distribution'); } finally { await prisma.productFulfilmentPolicy.update({ where: { id: policy.id }, data: { reviewRequired: false } }); }
    await prisma.ratePlan.update({ where: { id: ratePlan.id }, data: { status: 'INACTIVE' } }); try { const inactive = await channelEligibility.evaluate({ channelId, productId: product.id, variantId: variant.id, ratePlanId: ratePlan.id }); assert(inactive.reasonCodes.includes('CHANNEL_RATE_PLAN_STATE_NOT_DISTRIBUTABLE'), 'inactive rate plan is denied'); } finally { await prisma.ratePlan.update({ where: { id: ratePlan.id }, data: { status: 'ACTIVE' } }); }
    const contract2 = await contracts.create(actor, channelId, { name: 'Catalog-only contract', effectiveFrom: '2020-01-01T00:00:00.000Z', capabilities: [DistributionCapability.CATALOG_READ], allowedCurrencies: ['INR'], availabilityHorizonDays: 30 }); createdIds.push(contract2.id); await contracts.retire(actor, full.id); await contracts.activate(actor, contract2.id); const reducedAuth: any = await authenticate(authGuard, credential.apiKey); assert(reducedAuth.capabilities.length === 1 && reducedAuth.capabilities[0] === DistributionCapability.CATALOG_READ, 'effective capabilities are credential scopes intersected with active contract'); await rejected(() => distribution.createCredential(actor, { channelId, name: 'not allowed', scopes: [DistributionCapability.EVENT_READ] }), 'CHANNEL_CREDENTIAL_SCOPE_NOT_ALLOWED');
    const limited = await distribution.createCredential(actor, { channelId, name: 'revoke race', scopes: [DistributionCapability.CATALOG_READ] }); createdIds.push(limited.id); const revokes = await Promise.all([distribution.revokeCredential(actor, limited.id), distribution.revokeCredential(actor, limited.id)]); assert(revokes.filter((item: any) => !item.idempotent).length === 1 && revokes.filter((item: any) => item.idempotent).length === 1, 'credential revoke race produces one state transition');
    const legacyOff = await adminService.setRatePlanChannel(actor, ratePlan.id, false); assert(legacyOff.enabled === false && legacyOff.status === ChannelMappingStatus.DISABLED, 'legacy VOYA_AGENT disable delegates to canonical mapping'); const legacy = await adminService.setRatePlanChannel(actor, ratePlan.id, true); assert(legacy.enabled === true && legacy.status === ChannelMappingStatus.ACTIVE, 'legacy VOYA_AGENT enable delegates to canonical mapping'); checks.legacyEndpoint = true;
    const sources = await Promise.all([
      prisma.outboxEvent.create({ data: { eventType: 'PRODUCT_PUBLISHED', aggregateType: 'Product', aggregateId: product.id, tenantId: vendorTenantId, payload: { productId: product.id } } }),
      prisma.outboxEvent.create({ data: { eventType: 'REVISION_PUBLISHED', aggregateType: 'ProductRevision', aggregateId: (await prisma.product.findUniqueOrThrow({ where: { id: product.id }, select: { currentRevisionId: true } })).currentRevisionId, tenantId: vendorTenantId, payload: {} } }),
      prisma.outboxEvent.create({ data: { eventType: 'VARIANT_UPDATED', aggregateType: 'ProductVariant', aggregateId: variant.id, tenantId: vendorTenantId, payload: {} } }),
      prisma.outboxEvent.create({ data: { eventType: 'COMMERCIAL_VERSION_ACTIVATED', aggregateType: 'RatePlanCommercialVersion', aggregateId: (await prisma.ratePlanCommercialVersion.findFirstOrThrow({ where: { ratePlanId: ratePlan.id, status: 'ACTIVE' }, select: { id: true } })).id, tenantId: vendorTenantId, payload: {} } }),
      prisma.outboxEvent.create({ data: { eventType: 'INVENTORY_HOLD_CREATED', aggregateType: 'InventoryState', aggregateId: session.inventoryState!.id, tenantId: vendorTenantId, payload: {} } }),
    ]); const projected = await projector.project(1000); const projectedAgain = await projector.project(1000); const eventRows = await prisma.distributionEvent.findMany({ where: { channelId }, select: { resourceType: true, externalResourceCode: true } }); assert(projected.projected >= 4 && projectedAgain.projected === 0 && eventRows.some((r) => r.resourceType === 'Product' && r.externalResourceCode === pm.externalProductCode) && eventRows.some((r) => r.resourceType === 'ProductVariant' && r.externalResourceCode === vm.externalVariantCode) && eventRows.some((r) => r.resourceType === 'RatePlanCommercialVersion' && r.externalResourceCode === rm.externalRatePlanCode), 'projector routes real resource events and is idempotent'); assert((await events.list(reducedAuth, { limit: 100 })).items.length >= 1, 'structured channel event feed is available'); checks.projector = { projected: projected.projected, secondRun: projectedAgain.projected, resources: eventRows.length };
    const final = { bookings: await prisma.booking.count(), holds: await prisma.inventoryHold.count(), allocations: await prisma.inventoryAllocation.count(), snapshots: await prisma.bookingSnapshot.count() }; assert(JSON.stringify(baseline) === JSON.stringify(final), 'distribution proof does not mutate booking or inventory business state'); checks.noBookingMutation = true;
    await mappings.product(actor, { channelId, productId: product.id, externalProductCode: pm.externalProductCode, status: ChannelMappingStatus.RETIRED, expectedVersion: (await prisma.productChannelMapping.findUniqueOrThrow({ where: { id: pm.id }, select: { version: true } })).version }); await rejected(() => mappings.product(actor, { channelId, productId: product.id, externalProductCode: pm.externalProductCode, status: ChannelMappingStatus.ACTIVE, expectedVersion: 99 }), 'CHANNEL_MAPPING_RETIRED'); checks.stateMachine = true;
    console.log(JSON.stringify({ phase: '12.1', fixture: { channelCode, isolated: true }, checks, baseline }, null, 2));
  } finally {
    if (resourceRequirementId) await prisma.scheduleResourceRequirement.delete({ where: { id: resourceRequirementId } }).catch(() => undefined);
    if (channelId) await prisma.distributionChannel.delete({ where: { id: channelId } }).catch(() => undefined);
    const recent = await prisma.outboxEvent.findMany({ where: { createdAt: { gte: startedAt } }, select: { id: true, aggregateId: true, payload: true } }); const ids = recent.filter((row: any) => createdIds.includes(row.aggregateId) || JSON.stringify(row.payload).includes(channelCode) || (channelId && JSON.stringify(row.payload).includes(channelId))).map((row) => row.id); if (ids.length) await prisma.outboxEvent.deleteMany({ where: { id: { in: ids } } });
    if (createdIds.length) await prisma.auditLog.deleteMany({ where: { entityId: { in: createdIds } } }).catch(() => undefined);
  }
}
main().catch((error) => { console.error(error); process.exitCode = 1; }).finally(() => prisma.$disconnect());
