import { apiRequest } from "./apiClient";
import type { PaginatedResponse } from "@/types/api";
export type BookingRecord = { id: string; reference: string; status: string; source?: string; customerName: string; customerEmail: string; customerPhone?: string | null; totalMinor: number; subtotalMinor?: number; taxMinor?: number; discountMinor?: number; commissionMinor?: number; refundMinor?: number; currency: string; notes?: string | null; voucherCode?: string | null; holdExpiresAt?: string | null; activity: { id: string; name: string }; schedule: { id: string; startsAt: string; capacity: number; bookedSeats: number }; agent?: { id: string; company: string } | null; supplier?: { id: string; company: string } | null; passengers: Array<{ id: string; firstName: string; lastName: string; type: string }>; payments?: Array<{ id: string; amountMinor: number; currency: string; status: string; method: string; providerReference?: string | null; refunds?: Array<{ id: string; requestedAmountMinor: number; approvedAmountMinor?: number | null; status: string }> }>; invoices?: Array<{ id: string; invoiceNumber: string; totalMinor: number; status: string }>; auditHistory?: Array<{ id: string; action: string; createdAt: string }> };
export function listBookings(query = "page=1&pageSize=25") { return apiRequest<PaginatedResponse<BookingRecord>>(`/bookings?${query}`); }
export function getBooking(id: string) { return apiRequest<BookingRecord>(`/bookings/${id}`); }
export function createBooking(payload: Record<string, unknown>) { return apiRequest<BookingRecord>("/bookings", { method: "POST", body: JSON.stringify(payload) }); }
export function updateBooking(id: string, payload: Record<string, unknown>) { return apiRequest<BookingRecord>(`/bookings/${id}`, { method: "PATCH", body: JSON.stringify(payload) }); }
export function bookingAction(id: string, action: "confirm" | "cancel" | "complete" | "no-show") { return apiRequest<BookingRecord>(`/bookings/${id}/${action}`, { method: "POST" }); }
export function createPayment(payload: { bookingId: string; amountMinor: number; currency: string; method: "CARD" | "BANK_TRANSFER" | "CASH" | "MOCK"; idempotencyKey: string }) { return apiRequest(`/payments`, { method: "POST", body: JSON.stringify(payload) }); }
export function createInvoice(payload: { bookingId: string; invoiceNumber: string; subtotalMinor: number; taxMinor: number; totalMinor: number; currency: string }) { return apiRequest(`/invoices`, { method: "POST", body: JSON.stringify(payload) }); }
