"use client";

import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { listUsers, type UserMembership } from "@/services/userService";
import { DataTable } from "@/components/table/DataTable";
import { PaginationControls } from "@/components/table/PaginationControls";
import { EmptyState, ErrorPanel, LoadingTable } from "@/components/feedback/Feedback";
import type { PaginationMeta } from "@/types/api";

const initialMeta: PaginationMeta = { page: 1, pageSize: 25, totalItems: 0, totalPages: 1, hasNextPage: false, hasPreviousPage: false };

export function UserList() {
  const [rows, setRows] = useState<UserMembership[]>([]); const [search, setSearch] = useState(""); const [status, setStatus] = useState(""); const [sortOrder, setSortOrder] = useState<"asc" | "desc">("desc"); const [meta, setMeta] = useState(initialMeta); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const params = new URLSearchParams(window.location.search); setSearch(params.get("search") ?? ""); setStatus(params.get("status") ?? ""); setSortOrder(params.get("sortOrder") === "asc" ? "asc" : "desc"); setPage(Math.max(1, Number(params.get("page") ?? "1"))); const size = Number(params.get("pageSize") ?? "25"); if ([10, 25, 50, 100].includes(size)) setMeta((current) => ({ ...current, pageSize: size })); }, []);
  const syncUrl = useCallback((next: Partial<{ page: number; pageSize: number; search: string; status: string; sortOrder: "asc" | "desc" }>) => { const value = { page, pageSize: meta.pageSize, search, status, sortOrder, ...next }; const params = new URLSearchParams({ page: String(value.page), pageSize: String(value.pageSize), sortBy: "createdAt", sortOrder: value.sortOrder }); if (value.search) params.set("search", value.search); if (value.status) params.set("status", value.status); window.history.replaceState(null, "", `${window.location.pathname}?${params}`); }, [meta.pageSize, page, search, sortOrder, status]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const params = new URLSearchParams({ page: String(page), pageSize: String(meta.pageSize), sortBy: "createdAt", sortOrder }); if (search) params.set("search", search); if (status) params.set("status", status); const result = await listUsers(params.toString()); setRows(result.data); setMeta(result.meta); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load users"); } finally { setLoading(false); } }, [meta.pageSize, page, search, sortOrder, status]);
  useEffect(() => { void load(); }, [load]);
  const clear = () => { setSearch(""); setStatus(""); setSortOrder("desc"); setPage(1); syncUrl({ page: 1, search: "", status: "", sortOrder: "desc" }); };
  return <div><div className="page-heading"><div><p className="eyebrow">ADMINISTRATION</p><h2>Users</h2><p className="subtext">Manage tenant membership, roles and active status.</p></div><Link className="primary button-link" href="/settings/users/new">Create user</Link></div><section className="panel"><div className="toolbar"><input aria-label="Search users" placeholder="Search name or email..." value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); syncUrl({ page: 1, search: event.target.value }); }} /><select aria-label="Filter users status" value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); syncUrl({ page: 1, status: event.target.value }); }}><option value="">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Disabled</option></select><select aria-label="Sort direction users" value={sortOrder} onChange={(event) => { const value = event.target.value as "asc" | "desc"; setSortOrder(value); setPage(1); syncUrl({ page: 1, sortOrder: value }); }}><option value="desc">Newest first</option><option value="asc">Oldest first</option></select><button type="button" onClick={clear}>Clear filters</button></div>{loading ? <LoadingTable /> : error ? <ErrorPanel message={error} onRetry={() => void load()} /> : rows.length === 0 ? <EmptyState title="No users found" /> : <DataTable rows={rows.map((row) => ({ ...row, id: row.user.id }))} columns={[{ key: "name", label: "User", render: (row) => <><strong>{row.user.displayName}</strong><small>{row.user.email}</small></> }, { key: "memberships", label: "Memberships", render: (row) => row.user._count?.memberships ?? 0 }, { key: "role", label: "Role", render: (row) => <>{row.customRole?.name ?? row.role}</> }, { key: "status", label: "Status", render: (row) => <span className={`status ${row.user.isActive ? "confirmed" : "cancelled"}`}>{row.user.isActive ? "ACTIVE" : "DISABLED"}</span> }, { key: "lastLogin", label: "Last login", render: (row) => row.user.lastLoginAt ? new Date(row.user.lastLoginAt).toLocaleString() : "Never" }, { key: "created", label: "Created", render: (row) => new Date(row.user.createdAt).toLocaleDateString() }]} actions={(row) => <Link href={`/settings/users/${row.user.id}/edit`}>Edit</Link>} />}{!loading && !error && <PaginationControls meta={meta} onPageChange={(nextPage) => { setPage(nextPage); syncUrl({ page: nextPage }); }} onPageSizeChange={(size) => { setPage(1); setMeta((current) => ({ ...current, pageSize: size })); syncUrl({ page: 1, pageSize: size }); }} />}</section></div>;
}
