"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { apiRequest } from "@/services/apiClient";
import type { PaginatedResponse, PaginationMeta } from "@/types/api";
import { DataTable } from "@/components/table/DataTable";
import { PaginationControls } from "@/components/table/PaginationControls";
import { EmptyState, ErrorPanel, LoadingTable } from "@/components/feedback/Feedback";
type Passenger = { id: string; firstName: string; lastName: string; type: string; booking?: { reference?: string; customerName?: string } };
const initialMeta: PaginationMeta = { page: 1, pageSize: 25, totalItems: 0, totalPages: 1, hasNextPage: false, hasPreviousPage: false };
export function PassengerList() { const [rows, setRows] = useState<Passenger[]>([]); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [meta, setMeta] = useState(initialMeta); const [sortBy, setSortBy] = useState("lastName"); const [sortOrder, setSortOrder] = useState<"asc" | "desc">("asc"); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  useEffect(() => { const params = new URLSearchParams(window.location.search); setSearch(params.get("search") ?? ""); setPage(Math.max(1, Number(params.get("page") ?? "1"))); setSortBy(params.get("sortBy") ?? "lastName"); setSortOrder(params.get("sortOrder") === "desc" ? "desc" : "asc"); const size = Number(params.get("pageSize") ?? "25"); if ([10, 25, 50, 100].includes(size)) setMeta((current) => ({ ...current, pageSize: size })); }, []);
  const syncUrl = useCallback((nextPage: number, nextSearch: string, size: number, nextSortBy = sortBy, nextSortOrder = sortOrder) => { const params = new URLSearchParams({ page: String(nextPage), pageSize: String(size), sortBy: nextSortBy, sortOrder: nextSortOrder }); if (nextSearch) params.set("search", nextSearch); window.history.replaceState(null, "", `${window.location.pathname}?${params}`); }, [sortBy, sortOrder]);
  const load = useCallback(async () => { setLoading(true); setError(""); try { const query = new URLSearchParams({ page: String(page), pageSize: String(meta.pageSize), sortBy, sortOrder }); if (search) query.set("search", search); const result = await apiRequest<PaginatedResponse<Passenger>>(`/passengers?${query}`); setRows(result.data); setMeta(result.meta); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load passengers"); } finally { setLoading(false); } }, [meta.pageSize, page, search, sortBy, sortOrder]);
  useEffect(() => { void load(); }, [load]);
  async function remove(row: Passenger) { if (!window.confirm(`Remove ${row.firstName} ${row.lastName} from this active hold?`)) return; setError(""); try { await apiRequest(`/passengers/${row.id}`, { method: "DELETE" }); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to remove passenger"); } }
  return <div><div className="page-heading"><div><p className="eyebrow">BOOKINGS</p><h2>Passengers</h2><p className="subtext">Passenger records scoped through their tenant booking.</p></div><Link className="primary button-link" href="/passengers/new">Create passenger</Link></div><section className="panel"><div className="toolbar"><input aria-label="Search passengers" placeholder="Search passengers…" value={search} onChange={(event) => { setSearch(event.target.value); setPage(1); syncUrl(1, event.target.value, meta.pageSize); }} /><select aria-label="Sort passengers" value={sortBy} onChange={(event) => { setSortBy(event.target.value); setPage(1); syncUrl(1, search, meta.pageSize, event.target.value, sortOrder); }}><option value="lastName">Last name</option><option value="firstName">First name</option><option value="createdAt">Created date</option></select><select aria-label="Sort direction passengers" value={sortOrder} onChange={(event) => { const value = event.target.value as "asc" | "desc"; setSortOrder(value); setPage(1); syncUrl(1, search, meta.pageSize, sortBy, value); }}><option value="asc">Ascending</option><option value="desc">Descending</option></select><button type="button" onClick={() => { setSearch(""); setPage(1); syncUrl(1, "", meta.pageSize); }}>Clear filters</button></div>{loading ? <LoadingTable /> : error ? <ErrorPanel message={error} onRetry={() => void load()} /> : rows.length === 0 ? <EmptyState title="No passengers found" /> : <DataTable rows={rows} columns={[{ key: "name", label: "Passenger", render: (row) => <strong>{row.firstName} {row.lastName}</strong> }, { key: "type", label: "Type", render: (row) => row.type }, { key: "booking", label: "Booking", render: (row) => row.booking?.reference ?? "—" }, { key: "customer", label: "Customer", render: (row) => row.booking?.customerName ?? "—" }]} actions={(row) => <><Link href={`/passengers/${row.id}`}>View</Link><Link href={`/passengers/${row.id}/edit`}>Edit</Link><button type="button" onClick={() => void remove(row)}>Remove</button></>} />}{!loading && !error && <PaginationControls meta={meta} onPageChange={(nextPage) => { setPage(nextPage); syncUrl(nextPage, search, meta.pageSize); }} onPageSizeChange={(size) => { setPage(1); setMeta((current) => ({ ...current, pageSize: size })); syncUrl(1, search, size); }} />}</section></div>;
}
