import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { InventoryHoldStatus, Prisma, SessionStatus } from '@prisma/client';
import { AuditService } from '../audit/audit.service';
import { AuthUser } from '../common/auth.types';
import { OutboxService } from '../outbox/outbox.service';
import { PrismaService } from '../prisma/prisma.service';
import { ResourcesService } from '../resources/resources.service';
import { calculatedAvailable, capacityQuantity } from './inventory.types';

export type ReservationInput = { sessionId: string; quantity: number; expiresAt?: Date; referenceKey?: string; bookingId?: string; reason?: string; actor?: AuthUser | null };
export type ReservationTx = Prisma.TransactionClient;

@Injectable()
export class InventoryReservationService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService, private readonly outbox: OutboxService, private readonly resources: ResourcesService) {}

  async getAvailability(sessionId: string) {
    const session = await this.prisma.serviceSession.findUnique({ where: { id: sessionId }, include: { inventoryState: true, scheduleTemplate: true } });
    if (!session) throw new NotFoundException('Session not found');
    const state = session.inventoryState;
    return { sessionId, totalCapacity: state?.totalCapacity ?? 0, blockedCapacity: state?.blockedCapacity ?? 0, heldCapacity: state?.heldCapacity ?? 0, confirmedCapacity: state?.confirmedCapacity ?? 0, availableCapacity: calculatedAvailable(state?.totalCapacity ?? 0, state?.blockedCapacity ?? 0, state?.heldCapacity ?? 0, state?.confirmedCapacity ?? 0, session.status), sessionStatus: session.status, version: state?.version ?? 0, capacityUnit: session.scheduleTemplate.capacityUnit, capacityUnitReviewRequired: session.scheduleTemplate.capacityUnitReviewRequired, inventoryReady: !session.scheduleTemplate.capacityUnitReviewRequired };
  }

  async createHold(input: ReservationInput) {
    if (input.bookingId) throw new ConflictException('BOOKING_HOLD_TRANSITION_REQUIRED');
    return this.prisma.$transaction((tx) => this.createHoldInTransaction(tx, input));
  }

  async createHoldInTransaction(tx: ReservationTx, input: ReservationInput) {
    const expiresAt = input.expiresAt ?? new Date(Date.now() + 15 * 60_000);
    if (expiresAt <= new Date()) throw new ConflictException('Hold expiry must be in the future');
    const state = await this.lockStateForBooking(tx, input.sessionId); if (!state) throw new NotFoundException('Inventory state not found');
    const session = await tx.serviceSession.findUniqueOrThrow({ where: { id: input.sessionId }, include: { scheduleTemplate: true } }); this.assertCapacityReview(session.scheduleTemplate.capacityUnitReviewRequired);
    const quantity = capacityQuantity(session.scheduleTemplate.capacityUnit, input.quantity);
    if (input.referenceKey) { const existing = await tx.inventoryHold.findFirst({ where: { inventoryStateId: state.id, referenceKey: input.referenceKey } }); if (existing) { if (existing.quantity !== quantity) throw new ConflictException('Reference key already exists with a different quantity'); return existing; } }
    this.assertOpen(session.status); await this.assertResources(input.sessionId, tx); this.assertAvailable(state, session.status, quantity);
    const hold = await tx.inventoryHold.create({ data: { inventoryStateId: state.id, quantity, expiresAt, referenceKey: input.referenceKey, bookingId: input.bookingId, reason: input.reason } }); await tx.inventoryState.update({ where: { id: state.id }, data: { heldCapacity: { increment: quantity }, version: { increment: 1 } } });
    await this.audit.write(tx, { actor: input.actor, action: 'INVENTORY_HOLD_CREATED', entityType: 'InventoryHold', entityId: hold.id, metadata: { sessionId: input.sessionId, quantity, bookingId: input.bookingId ?? null } }); await this.outbox.enqueue(tx, { eventType: 'INVENTORY_HOLD_CREATED', aggregateType: 'InventoryState', aggregateId: state.id, payload: { holdId: hold.id, quantity, bookingId: input.bookingId ?? null } }); return hold;
  }

  releaseHold(holdId: string, reason = 'released', actor?: AuthUser | null) { return this.genericHoldTransition(holdId, InventoryHoldStatus.RELEASED, reason, actor); }
  expireHold(holdId: string, actor?: AuthUser | null) { return this.genericHoldTransition(holdId, InventoryHoldStatus.EXPIRED, 'expired', actor); }
  private async genericHoldTransition(holdId: string, status: InventoryHoldStatus, reason: string, actor?: AuthUser | null) { return this.prisma.$transaction(async (tx) => { const found = await tx.inventoryHold.findUnique({ where: { id: holdId } }); if (!found) throw new NotFoundException('Inventory hold not found'); if (found.bookingId) throw new ConflictException('BOOKING_HOLD_TRANSITION_REQUIRED'); return this.transitionHoldInTransaction(tx, holdId, status, reason, actor); }); }
  async releaseHoldInTransaction(tx: ReservationTx, holdId: string, reason = 'released', actor?: AuthUser | null) { return this.transitionHoldInTransaction(tx, holdId, InventoryHoldStatus.RELEASED, reason, actor); }
  async expireHoldInTransaction(tx: ReservationTx, holdId: string, actor?: AuthUser | null) { return this.transitionHoldInTransaction(tx, holdId, InventoryHoldStatus.EXPIRED, 'expired', actor); }
  private async transitionHoldInTransaction(tx: ReservationTx, holdId: string, status: InventoryHoldStatus, reason: string, actor?: AuthUser | null) { const found = await tx.inventoryHold.findUnique({ where: { id: holdId } }); if (!found) throw new NotFoundException('Inventory hold not found'); const state = await this.lockStateById(tx, found.inventoryStateId); const hold = await tx.inventoryHold.findUniqueOrThrow({ where: { id: holdId } }); if (hold.status !== InventoryHoldStatus.ACTIVE) return hold; const saved = await tx.inventoryHold.update({ where: { id: holdId }, data: { status, releasedAt: new Date(), reason, version: { increment: 1 } } }); await tx.inventoryState.update({ where: { id: state.id }, data: { heldCapacity: { decrement: hold.quantity }, version: { increment: 1 } } }); const action = status === InventoryHoldStatus.EXPIRED ? 'INVENTORY_HOLD_EXPIRED' : 'INVENTORY_HOLD_RELEASED'; await this.audit.write(tx, { actor, action, entityType: 'InventoryHold', entityId: hold.id, reason, metadata: { quantity: hold.quantity, bookingId: hold.bookingId ?? null } }); await this.outbox.enqueue(tx, { eventType: action, aggregateType: 'InventoryHold', aggregateId: hold.id, payload: { quantity: hold.quantity, bookingId: hold.bookingId ?? null } }); return saved; }

  async convertHoldToConfirmed(holdId: string, input: { bookingId?: string; referenceKey?: string; actor?: AuthUser | null } = {}) { return this.prisma.$transaction(async (tx) => { const found = await tx.inventoryHold.findUnique({ where: { id: holdId } }); if (!found) throw new NotFoundException('Inventory hold not found'); if (found.bookingId) throw new ConflictException('BOOKING_HOLD_TRANSITION_REQUIRED'); return this.convertHoldToConfirmedInTransaction(tx, holdId, input); }); }
  async convertHoldToConfirmedInTransaction(tx: ReservationTx, holdId: string, input: { bookingId?: string; referenceKey?: string; actor?: AuthUser | null } = {}) {
    const found = await tx.inventoryHold.findUnique({ where: { id: holdId } }); if (!found) throw new NotFoundException('Inventory hold not found'); const state = await this.lockStateById(tx, found.inventoryStateId); const hold = await tx.inventoryHold.findUniqueOrThrow({ where: { id: holdId } });
    if (hold.status !== InventoryHoldStatus.ACTIVE) { if (hold.status === InventoryHoldStatus.CONVERTED) return tx.inventoryAllocation.findUniqueOrThrow({ where: { sourceHoldId: hold.id } }); throw new ConflictException(`Hold is ${hold.status}`); }
    if (hold.expiresAt <= new Date()) throw new ConflictException('BOOKING_CONFIRMATION_EXPIRED'); const session = await tx.serviceSession.findUniqueOrThrow({ where: { id: state.sessionId }, include: { scheduleTemplate: true } }); this.assertCapacityReview(session.scheduleTemplate.capacityUnitReviewRequired); this.assertOpen(session.status); const readiness = await this.resources.resourceReadiness(session.id, tx); if (!readiness.ready) throw new ConflictException('RESOURCE_NOT_READY');
    const saved = await tx.inventoryHold.update({ where: { id: hold.id }, data: { status: InventoryHoldStatus.CONVERTED, convertedAt: new Date(), version: { increment: 1 } } }); await tx.inventoryState.update({ where: { id: state.id }, data: { heldCapacity: { decrement: hold.quantity }, confirmedCapacity: { increment: hold.quantity }, version: { increment: 1 } } }); const allocation = await tx.inventoryAllocation.create({ data: { inventoryStateId: state.id, quantity: hold.quantity, bookingId: input.bookingId, referenceKey: input.referenceKey ?? hold.referenceKey, sourceHoldId: hold.id, reason: 'converted from hold' } }); await this.audit.write(tx, { actor: input.actor, action: 'INVENTORY_HOLD_CONVERTED', entityType: 'InventoryHold', entityId: saved.id, metadata: { allocationId: allocation.id, quantity: hold.quantity, bookingId: input.bookingId ?? null } }); await this.outbox.enqueue(tx, { eventType: 'INVENTORY_HOLD_CONVERTED', aggregateType: 'InventoryHold', aggregateId: hold.id, payload: { allocationId: allocation.id, quantity: hold.quantity, bookingId: input.bookingId ?? null } }); return allocation;
  }

  async confirmDirect(input: ReservationInput) { if (input.bookingId) throw new ConflictException('BOOKING_HOLD_TRANSITION_REQUIRED'); return this.prisma.$transaction((tx) => this.confirmDirectInTransaction(tx, input)); }
  async confirmDirectInTransaction(tx: ReservationTx, input: ReservationInput) { const state = await this.lockStateForBooking(tx, input.sessionId); if (!state) throw new NotFoundException('Inventory state not found'); const session = await tx.serviceSession.findUniqueOrThrow({ where: { id: input.sessionId }, include: { scheduleTemplate: true } }); this.assertCapacityReview(session.scheduleTemplate.capacityUnitReviewRequired); const quantity = capacityQuantity(session.scheduleTemplate.capacityUnit, input.quantity); if (input.referenceKey) { const existing = await tx.inventoryAllocation.findFirst({ where: { inventoryStateId: state.id, referenceKey: input.referenceKey } }); if (existing) return existing; } this.assertOpen(session.status); await this.assertResources(input.sessionId, tx); this.assertAvailable(state, session.status, quantity); const allocation = await tx.inventoryAllocation.create({ data: { inventoryStateId: state.id, quantity, bookingId: input.bookingId, referenceKey: input.referenceKey, reason: input.reason } }); await tx.inventoryState.update({ where: { id: state.id }, data: { confirmedCapacity: { increment: quantity }, version: { increment: 1 } } }); await this.audit.write(tx, { actor: input.actor, action: 'INVENTORY_DIRECT_CONFIRMED', entityType: 'InventoryAllocation', entityId: allocation.id, metadata: { sessionId: input.sessionId, quantity, bookingId: input.bookingId ?? null } }); await this.outbox.enqueue(tx, { eventType: 'INVENTORY_DIRECT_CONFIRMED', aggregateType: 'InventoryAllocation', aggregateId: allocation.id, payload: { sessionId: input.sessionId, quantity, bookingId: input.bookingId ?? null } }); return allocation; }

  async releaseAllocation(allocationId: string, actor?: AuthUser | null) { return this.prisma.$transaction(async (tx) => { const allocation = await tx.inventoryAllocation.findUnique({ where: { id: allocationId } }); if (!allocation) throw new NotFoundException('Inventory allocation not found'); if (allocation.bookingId) throw new ConflictException('BOOKING_HOLD_TRANSITION_REQUIRED'); const state = await this.lockStateById(tx, allocation.inventoryStateId); const current = await tx.inventoryAllocation.findUniqueOrThrow({ where: { id: allocationId } }); if (current.status === 'RELEASED') return current; const released = await tx.inventoryAllocation.update({ where: { id: allocationId }, data: { status: 'RELEASED', releasedAt: new Date() } }); await tx.inventoryState.update({ where: { id: state.id }, data: { confirmedCapacity: { decrement: current.quantity }, version: { increment: 1 } } }); await this.audit.write(tx, { actor, action: 'INVENTORY_ALLOCATION_RELEASED', entityType: 'InventoryAllocation', entityId: allocationId, metadata: { quantity: current.quantity } }); await this.outbox.enqueue(tx, { eventType: 'INVENTORY_ALLOCATION_RELEASED', aggregateType: 'InventoryAllocation', aggregateId: allocationId, payload: { quantity: current.quantity } }); return released; }); }
  async expireDueHolds(now = new Date()) { const due = await this.prisma.inventoryHold.findMany({ where: { bookingId: null, status: 'ACTIVE', expiresAt: { lte: now } }, select: { id: true } }); const expired = []; for (const hold of due) expired.push(await this.expireHold(hold.id)); return { expired: expired.length, holds: expired }; }
  async lockStateForBooking(tx: ReservationTx, sessionId: string) { return this.lockState(tx, sessionId); }
  private async lockState(tx: ReservationTx, sessionId: string) { if ((tx as any).$executeRawUnsafe) await (tx as any).$executeRawUnsafe('SET LOCAL search_path TO public'); const rows = await tx.$queryRawUnsafe<any[]>(`SELECT * FROM "public"."InventoryState" WHERE "sessionId" = $1 FOR UPDATE`, sessionId); return rows[0] ?? null; }
  private async lockStateById(tx: ReservationTx, id: string) { if ((tx as any).$executeRawUnsafe) await (tx as any).$executeRawUnsafe('SET LOCAL search_path TO public'); const rows = await tx.$queryRawUnsafe<any[]>(`SELECT * FROM "public"."InventoryState" WHERE "id" = $1 FOR UPDATE`, id); if (!rows[0]) throw new NotFoundException('Inventory state not found'); return rows[0]; }
  private assertCapacityReview(reviewRequired: boolean) { if (reviewRequired) throw new ConflictException('CAPACITY_UNIT_REVIEW_REQUIRED'); }
  private assertOpen(status: SessionStatus) { if (status !== SessionStatus.OPEN) throw new ConflictException(`SESSION_${status}`); }
  private assertAvailable(state: any, status: SessionStatus, quantity: number) { if (quantity <= 0) throw new ConflictException('INVENTORY_QUANTITY_INVALID'); const available = calculatedAvailable(Number(state.totalCapacity), Number(state.blockedCapacity), Number(state.heldCapacity), Number(state.confirmedCapacity), status); if (quantity > available) throw new ConflictException('INVENTORY_INSUFFICIENT'); }
  private async assertResources(sessionId: string, tx: ReservationTx) { const readiness = await this.resources.resourceReadiness(sessionId, tx); if (!readiness.ready) throw new ConflictException(readiness.reasonCodes.join(',')); }
}
