import { ConflictException, Injectable, NotFoundException } from '@nestjs/common';
import { SessionStatus } from '@prisma/client';
import { AuthUser } from '../common/auth.types';
import { requireTenant } from '../common/tenant';
import { AuditService } from '../audit/audit.service';
import { OutboxService } from '../outbox/outbox.service';
import { PrismaService } from '../prisma/prisma.service';
import { ResourcesService } from '../resources/resources.service';
import { ScheduleOperationalStateService } from '../schedules/schedule-operational-state.service';
import { calculatedAvailable } from './inventory.types';
import { InventoryBulkApplyDto, InventoryBulkPreviewDto, InventoryQueryDto } from './inventory.dto';

@Injectable()
export class InventoryService {
  constructor(private readonly prisma: PrismaService, private readonly audit: AuditService, private readonly outbox: OutboxService, private readonly resources: ResourcesService, private readonly operational: ScheduleOperationalStateService) {}

  async list(user: AuthUser, query: InventoryQueryDto) {
    const tenantId = requireTenant(user);
    const rows = await this.prisma.serviceSession.findMany({ where: { scheduleTemplate: { variant: { product: { tenantId, ...(query.productId ? { id: query.productId } : {}) } }, ...(query.variantId ? { variantId: query.variantId } : {}), ...(query.scheduleId ? { id: query.scheduleId } : {}), ...(query.ratePlanId ? { ratePlanMappings: { some: { ratePlanId: query.ratePlanId, active: true } } } : {}) }, ...(query.from || query.to ? { serviceDate: { ...(query.from ? { gte: new Date(query.from) } : {}), ...(query.to ? { lte: new Date(query.to) } : {}) } } : {}) }, include: { inventoryState: true, slotTemplate: true, scheduleTemplate: { include: { variant: { include: { product: { select: { id: true, productCode: true, currentRevision: { select: { productName: true } } } } } }, ratePlanMappings: { where: { active: true }, include: { ratePlan: { select: { id: true, ratePlanCode: true, name: true } } } } } } }, orderBy: [{ serviceDate: 'asc' }, { startsAt: 'asc' }], take: 500 });
    return Promise.all(rows.map(async (row) => { const state = row.inventoryState; const readiness = await this.resources.resourceReadiness(row.id); const review = row.scheduleTemplate.capacityUnitReviewRequired; return { id: row.id, productId: row.scheduleTemplate.variant.product.id, productCode: row.scheduleTemplate.variant.product.productCode, productName: row.scheduleTemplate.variant.product.currentRevision?.productName, variantId: row.scheduleTemplate.variantId, scheduleId: row.scheduleTemplateId, scheduleName: row.scheduleTemplate.name, sessionDate: row.serviceDate, sessionKey: row.sessionKey, slotCode: row.slotTemplate?.slotCode ?? null, localStartTime: row.localStartTime, localEndTime: row.localEndTime, sessionStatus: row.status, totalCapacity: state?.totalCapacity ?? 0, blockedCapacity: state?.blockedCapacity ?? 0, heldCapacity: state?.heldCapacity ?? 0, confirmedCapacity: state?.confirmedCapacity ?? 0, availableCapacity: calculatedAvailable(state?.totalCapacity ?? 0, state?.blockedCapacity ?? 0, state?.heldCapacity ?? 0, state?.confirmedCapacity ?? 0, row.status), version: state?.version ?? 0, inventoryVersion: state?.version ?? 0, sessionVersion: row.version, capacityUnitReviewRequired: review, inventoryReady: !review && readiness.ready, sharedRatePlans: row.scheduleTemplate.ratePlanMappings.map((mapping) => ({ id: mapping.ratePlan.id, code: mapping.ratePlan.ratePlanCode, name: mapping.ratePlan.name })), resourceReady: readiness.ready, resourceReasonCodes: review ? [...readiness.reasonCodes, 'CAPACITY_UNIT_REVIEW_REQUIRED'] : readiness.reasonCodes, operationalReasonCodes: review ? ['CAPACITY_UNIT_REVIEW_REQUIRED'] : [] }; }));
  }

  async bulkPreview(user: AuthUser, dto: InventoryBulkPreviewDto) {
    const tenantId = requireTenant(user); this.validateStatusProposal(dto.proposal.sessionStatus, dto.proposal.statusReason); const sessions = await this.selectedSessions(tenantId, dto); const conflicts: Array<Record<string, unknown>> = [];
    const affected = sessions.map((session) => { const state = session.inventoryState; const total = dto.proposal.newTotalCapacity ?? state?.totalCapacity ?? 0; const blocked = dto.proposal.newBlockedCapacity ?? state?.blockedCapacity ?? 0; const held = state?.heldCapacity ?? 0; const confirmed = state?.confirmedCapacity ?? 0; if (total < blocked + held + confirmed) conflicts.push({ sessionId: session.id, code: 'CAPACITY_BELOW_COMMITTED', totalCapacity: total, blockedCapacity: blocked, heldCapacity: held, confirmedCapacity: confirmed }); return { sessionId: session.id, serviceDate: session.serviceDate, sessionKey: session.sessionKey, inventoryVersion: state?.version ?? 0, sessionVersion: session.version, current: this.counters(session), proposed: { totalCapacity: total, blockedCapacity: blocked, heldCapacity: held, confirmedCapacity: confirmed, sessionStatus: dto.proposal.sessionStatus ?? session.status, statusReason: dto.proposal.statusReason ?? null, availableCapacity: calculatedAvailable(total, blocked, held, confirmed, dto.proposal.sessionStatus ?? session.status) }, sharedRatePlans: session.scheduleTemplate.ratePlanMappings.map((mapping) => mapping.ratePlan.ratePlanCode) }; });
    return { scheduleVersion: sessions[0]?.scheduleTemplate.version ?? null, affected, conflicts, impactedRatePlans: [...new Set(affected.flatMap((row) => row.sharedRatePlans))], mutates: false };
  }

  async bulkApply(user: AuthUser, dto: InventoryBulkApplyDto) {
    const tenantId = requireTenant(user); if (!dto.rows.length) throw new ConflictException('At least one inventory row is required'); const statusMutation = dto.rows.some((row) => row.sessionStatus !== undefined); if (statusMutation && dto.expectedScheduleVersion == null) throw new ConflictException('expectedScheduleVersion is required for status mutation');
    return this.prisma.$transaction(async (tx) => { if ((tx as any).$executeRawUnsafe) await (tx as any).$executeRawUnsafe('SET LOCAL search_path TO public');
      let schedule: any = null;
      if (statusMutation) { const scheduleRows = await tx.$queryRawUnsafe(`SELECT * FROM "ScheduleTemplate" WHERE "id" = $1 FOR UPDATE`, dto.scheduleTemplateId) as any[]; if (!scheduleRows[0]) throw new NotFoundException('Schedule not found'); if (Number(scheduleRows[0].version) !== dto.expectedScheduleVersion) throw new ConflictException('Schedule changed; reload and retry.'); schedule = scheduleRows[0]; }
      const rows = [...dto.rows].sort((a, b) => a.sessionId.localeCompare(b.sessionId)); const locked: any[] = [];
      for (const row of rows) { const session = await tx.serviceSession.findFirst({ where: { id: row.sessionId, scheduleTemplateId: dto.scheduleTemplateId, scheduleTemplate: { variant: { product: { tenantId } } } } }); if (!session) throw new NotFoundException(`Session ${row.sessionId} not found`); const sessionRows = await tx.$queryRawUnsafe(`SELECT * FROM "ServiceSession" WHERE "id" = $1 FOR UPDATE`, row.sessionId) as any[]; const lockedSession = sessionRows[0]; const stateRows = await tx.$queryRawUnsafe(`SELECT * FROM "InventoryState" WHERE "sessionId" = $1 FOR UPDATE`, row.sessionId) as any[]; const state = stateRows[0] ?? null; const expectedInventoryVersion = row.expectedInventoryVersion ?? row.expectedVersion; if (expectedInventoryVersion == null || Number(state?.version ?? 0) !== expectedInventoryVersion) throw new ConflictException(`Inventory version conflict for session ${row.sessionId}`); if (row.sessionStatus !== undefined && row.expectedSessionVersion == null) throw new ConflictException(`Session version is required for ${row.sessionId}`); if (row.sessionStatus !== undefined && Number(lockedSession.version) !== row.expectedSessionVersion) throw new ConflictException(`Session version conflict for ${row.sessionId}`); if (row.sessionStatus === SessionStatus.ARCHIVED) throw new ConflictException('ARCHIVED sessions require an explicit archive operation'); this.validateStatusProposal(row.sessionStatus, row.statusReason); const total = row.newTotalCapacity ?? Number(state?.totalCapacity ?? 0); const blocked = row.newBlockedCapacity ?? Number(state?.blockedCapacity ?? 0); const held = Number(state?.heldCapacity ?? 0); const confirmed = Number(state?.confirmedCapacity ?? 0); if (total < 0 || blocked < 0 || total < blocked + held + confirmed) throw new ConflictException(`Invalid proposed counters for session ${row.sessionId}`); locked.push({ row, session: lockedSession, state, total, blocked }); }
      const selectedByDate = new Map<string, Set<string>>(); const allByDate = new Map<string, number>(); if (statusMutation) for (const item of locked) { const key = new Date(item.session.serviceDate).toISOString().slice(0, 10); if (!selectedByDate.has(key)) selectedByDate.set(key, new Set()); selectedByDate.get(key)!.add(item.session.id); } if (statusMutation) for (const key of selectedByDate.keys()) allByDate.set(key, await tx.serviceSession.count({ where: { scheduleTemplateId: dto.scheduleTemplateId, serviceDate: new Date(`${key}T00:00:00.000Z`), archivedAt: null } }));
      for (const item of locked) { const { row, session, state, total, blocked } = item; if (state) await tx.inventoryState.update({ where: { id: state.id }, data: { ...(row.newTotalCapacity !== undefined ? { totalCapacity: total } : {}), ...(row.newBlockedCapacity !== undefined ? { blockedCapacity: blocked } : {}), version: { increment: 1 } } }); else if (row.newTotalCapacity !== undefined) await tx.inventoryState.create({ data: { sessionId: session.id, totalCapacity: total, blockedCapacity: blocked } }); if (row.sessionStatus !== undefined) { const date = new Date(session.serviceDate).toISOString().slice(0, 10); const fullScope = selectedByDate.get(date)?.size === allByDate.get(date); if (row.sessionStatus === SessionStatus.OPEN) await this.operational.clearException(tx, { scheduleTemplateId: dto.scheduleTemplateId, serviceDate: session.serviceDate, slotTemplateId: session.slotTemplateId, fullScope: !!fullScope }); else await this.operational.setException(tx, { scheduleTemplateId: dto.scheduleTemplateId, serviceDate: session.serviceDate, slotTemplateId: session.slotTemplateId, type: row.sessionStatus, reason: row.statusReason ?? 'bulk status change' }); } }
      if (statusMutation) { const result = await tx.scheduleTemplate.updateMany({ where: { id: dto.scheduleTemplateId, version: dto.expectedScheduleVersion }, data: { version: { increment: 1 } } }); if (result.count !== 1) throw new ConflictException('Schedule changed; reload and retry.'); }
      await this.audit.write(tx, { actor: user, tenantId, action: 'INVENTORY_BULK_APPLIED', entityType: 'InventoryState', metadata: { sessionCount: rows.length, sessionIds: rows.map((row) => row.sessionId), scheduleVersion: statusMutation ? Number(schedule.version) + 1 : undefined } }); await this.outbox.enqueue(tx, { tenantId, eventType: 'INVENTORY_BULK_APPLIED', aggregateType: 'ScheduleTemplate', aggregateId: dto.scheduleTemplateId, payload: { sessionCount: rows.length, statusMutation } }); return { applied: rows.length, sessionIds: rows.map((row) => row.sessionId), scheduleVersion: statusMutation ? Number(schedule.version) + 1 : undefined };
    });
  }

  private async selectedSessions(tenantId: string, dto: InventoryBulkPreviewDto) { return this.prisma.serviceSession.findMany({ where: { scheduleTemplateId: dto.scheduleTemplateId, serviceDate: { gte: new Date(dto.dateFrom), lte: new Date(dto.dateTo) }, ...(dto.slotTemplateIds?.length ? { slotTemplateId: { in: dto.slotTemplateIds } } : {}), scheduleTemplate: { variant: { product: { tenantId } } } }, include: { inventoryState: true, scheduleTemplate: { include: { ratePlanMappings: { where: { active: true }, include: { ratePlan: { select: { ratePlanCode: true } } } } } } }, orderBy: [{ serviceDate: 'asc' }, { sessionKey: 'asc' }] }); }
  private counters(session: any) { const state = session.inventoryState; return { totalCapacity: state?.totalCapacity ?? 0, blockedCapacity: state?.blockedCapacity ?? 0, heldCapacity: state?.heldCapacity ?? 0, confirmedCapacity: state?.confirmedCapacity ?? 0, availableCapacity: calculatedAvailable(state?.totalCapacity ?? 0, state?.blockedCapacity ?? 0, state?.heldCapacity ?? 0, state?.confirmedCapacity ?? 0, session.status), sessionStatus: session.status, version: state?.version ?? 0 }; }
  private validateStatusProposal(status?: SessionStatus, reason?: string) { if ((status === SessionStatus.CLOSED || status === SessionStatus.BLACKOUT) && !reason?.trim()) throw new ConflictException('statusReason is required for CLOSED and BLACKOUT'); }
}
