import { Injectable, NotFoundException } from '@nestjs/common';
import { BookingMode, BookingStatus, CancellationInitiator, MediaKind, ProductRevisionStatus, ProductStatus, ScheduleExceptionType, SessionStatus, SupplierMetricStatus, SupplierQualityDimension, SupplierQualityMetricCode, SupplierQualityPolicyStatus } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
import { MetricResult, SupplierQualityEvaluator } from './supplier-quality-evaluator';

const DAY = 86400000;
const rate = (numerator: number, denominator: number) => denominator ? Number(((numerator / denominator) * 100).toFixed(2)) : null;
const empty = (metricCode: SupplierQualityMetricCode, dimension: SupplierQualityDimension, unit: string): MetricResult => ({ metricCode, dimension, rawValue: null, numerator: null, denominator: null, sampleSize: 0, unit, status: SupplierMetricStatus.UNAVAILABLE, score: null, sourceTrace: { unavailable: 'first-class traveller feedback source not configured' } });
const dateKey = (date: Date, timezone: string) => new Intl.DateTimeFormat('en-CA', { timeZone: timezone, year: 'numeric', month: '2-digit', day: '2-digit' }).format(date);
const calendarDaysBetween = (serviceDate: Date, createdAt: Date, timezone: string) => Math.round((Date.parse(`${dateKey(serviceDate, timezone)}T00:00:00Z`) - Date.parse(`${dateKey(createdAt, timezone)}T00:00:00Z`)) / DAY);
function localEndOfDay(date: Date, timezone: string) { const key = dateKey(date, timezone); const naive = new Date(`${key}T23:59:59.999Z`); const parts = new Intl.DateTimeFormat('en-US', { timeZone: timezone, hour12: false, year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', second: '2-digit' }).formatToParts(naive).reduce<Record<string, string>>((out, part) => { out[part.type] = part.value; return out; }, {}); const renderedAsUtc = Date.parse(`${parts.year}-${parts.month}-${parts.day}T${parts.hour === '24' ? '00' : parts.hour}:${parts.minute}:${parts.second}.${String(naive.getMilliseconds()).padStart(3, '0')}Z`); return new Date(naive.getTime() - (renderedAsUtc - naive.getTime())); }

@Injectable()
export class SupplierPerformanceService {
  constructor(private readonly prisma: PrismaService, private readonly evaluator: SupplierQualityEvaluator) {}

  async computeCurrent(vendorTenantId: string, now = new Date(), windowStartOverride?: Date) {
    const vendor = this.prisma.tenant?.findUnique ? await this.prisma.tenant.findUnique({ where: { id: vendorTenantId }, select: { kind: true } }) : { kind: 'VENDOR' as const };
    if (!vendor || vendor.kind !== 'VENDOR') throw new NotFoundException('Vendor tenant not found');
    const policy = await this.prisma.supplierQualityPolicy.findFirst({ where: { status: SupplierQualityPolicyStatus.ACTIVE }, include: { metricRules: { where: { enabled: true }, orderBy: { rank: 'asc' } }, tierRules: true } });
    const windowEnd = now;
    const windowStart = windowStartOverride ?? new Date(now.getTime() - (policy?.measurementWindowDays ?? 30) * DAY);
    const raw = await this.rawMetrics(vendorTenantId, windowStart, windowEnd, policy?.shortNoticeDays ?? 0, policy?.lastMinuteStopSellDays ?? 0);
    const metrics = raw.map((m) => this.evaluator.assess(m, policy?.metricRules.find((r) => r.metricCode === m.metricCode)));
    const overallScore = policy ? this.evaluator.score(metrics, policy.metricRules) : null;
    const [currentAssignment, latestSnapshotOverall, latestSnapshotForCurrentPolicy, openIssues] = await Promise.all([
      this.prisma.supplierTierAssignment.findFirst({ where: { vendorTenantId, effectiveTo: null }, orderBy: { effectiveFrom: 'desc' } }),
      this.prisma.supplierQualitySnapshot.findFirst({ where: { vendorTenantId }, orderBy: { generatedAt: 'desc' }, include: { metricSnapshots: true } }),
      policy ? this.prisma.supplierQualitySnapshot.findFirst({ where: { vendorTenantId, policyId: policy.id }, orderBy: { generatedAt: 'desc' }, include: { metricSnapshots: true } }) : null,
      this.prisma.supplierQualityIssue.findMany({ where: { vendorTenantId, status: { in: ['OPEN', 'ACKNOWLEDGED'] } }, orderBy: { openedAt: 'desc' } }),
    ]);
    return { vendorTenantId, windowStart, windowEnd, policy: policy ? { id: policy.id, versionNumber: policy.versionNumber, name: policy.name, measurementWindowDays: policy.measurementWindowDays, shortNoticeDays: policy.shortNoticeDays, lastMinuteStopSellDays: policy.lastMinuteStopSellDays, metricRules: policy.metricRules, tierRules: policy.tierRules } : null, metrics, overallScore, recommendedTier: policy ? this.evaluator.recommendedTier(overallScore, policy) : null, currentTier: currentAssignment?.tier ?? null, latestSnapshot: latestSnapshotOverall, latestSnapshotOverall, latestSnapshotForCurrentPolicy, openIssues };
  }

  private async rawMetrics(vendorTenantId: string, start: Date, end: Date, shortNoticeDays: number, lastMinuteStopSellDays: number): Promise<MetricResult[]> {
    const slaBookings = await this.prisma.booking.findMany({ where: { recordType: 'CANONICAL', vendorTenantId, bookingMode: BookingMode.VENDOR_CONFIRMATION, createdAt: { gte: start, lt: end } }, select: { createdAt: true, confirmationDueAt: true, confirmedAt: true, rejectedAt: true, expiredAt: true, status: true } });
    const serviceStart = new Date(`${start.toISOString().slice(0, 10)}T00:00:00.000Z`);
    const serviceEnd = new Date(`${end.toISOString().slice(0, 10)}T23:59:59.999Z`);
    const serviceBookings = await this.prisma.booking.findMany({ where: { recordType: 'CANONICAL', vendorTenantId, bookingMode: { in: [BookingMode.INSTANT, BookingMode.VENDOR_CONFIRMATION, BookingMode.MANUAL_ON_REQUEST] }, confirmedAt: { not: null }, serviceDate: { gte: serviceStart, lte: serviceEnd } }, select: { id: true, status: true, createdAt: true, confirmedAt: true, serviceDate: true, serviceTimezone: true, operationalSnapshot: { select: { sessionSnapshot: true } }, fulfilment: { select: { vouchers: { select: { generatedAt: true, status: true, voidedAt: true } } } }, cancellation: { select: { initiator: true, daysBeforeService: true, cancelledAt: true } } } });
    const observable = slaBookings.filter((b) => Boolean(b.confirmationDueAt && (b.confirmationDueAt <= end || b.confirmedAt || b.rejectedAt || b.expiredAt)));
    const responded = observable.filter((b) => Boolean(b.confirmedAt || b.rejectedAt));
    const responseTimes = responded.map((b) => ((b.confirmedAt || b.rejectedAt)!.getTime() - b.createdAt.getTime()) / 60000).filter((n) => n >= 0);
    const withinSlaResponses = responded.filter((b) => { const responseAt = b.confirmedAt || b.rejectedAt; return Boolean(responseAt && b.confirmationDueAt && responseAt <= b.confirmationDueAt); });
    const confirmedWithin = observable.filter((b) => Boolean(b.confirmedAt && b.confirmationDueAt && b.confirmedAt <= b.confirmationDueAt)).length;
    const overdue = observable.filter((b) => b.status === BookingStatus.CONFIRMATION_EXPIRED || Boolean(b.expiredAt)).length;
    const vendorCancelled = serviceBookings.filter((b) => b.cancellation?.initiator === CancellationInitiator.VENDOR);
    const shortCancelled = vendorCancelled.filter((b) => (b.cancellation?.daysBeforeService ?? Number.MAX_SAFE_INTEGER) <= shortNoticeDays);
    type ServiceBooking = typeof serviceBookings[number];
    const serviceBoundary = (booking: ServiceBooking) => {
      const snapshot = booking.operationalSnapshot?.sessionSnapshot as Record<string, unknown> | null;
      if (snapshot?.startsAt) return new Date(String(snapshot.startsAt));
      const timezone = String(snapshot?.timezone || booking.serviceTimezone || 'UTC');
      return localEndOfDay(booking.serviceDate, timezone);
    };
    const fulfilmentExpectedBookings = serviceBookings.filter((b) => !b.cancellation || b.cancellation.cancelledAt >= serviceBoundary(b));
    const validVoucherAt = (booking: ServiceBooking) => { const versions = booking.fulfilment?.vouchers.filter((v) => v.status !== 'VOID' && !v.voidedAt).map((v) => v.generatedAt).sort((a, b) => a.getTime() - b.getTime()) ?? []; return versions[0] ?? null; };
    const voucherReady = fulfilmentExpectedBookings.filter((b) => { const readyAt = validVoucherAt(b); return Boolean(readyAt && readyAt <= serviceBoundary(b)); });
    const turnarounds = fulfilmentExpectedBookings.map((b) => { const readyAt = validVoucherAt(b); return readyAt && b.confirmedAt ? (readyAt.getTime() - b.confirmedAt.getTime()) / 60000 : null; }).filter((n): n is number => n !== null && n >= 0);
    const productRows = await this.prisma.product.findMany({ where: { tenantId: vendorTenantId, status: ProductStatus.LIVE }, select: { currentRevision: { select: { status: true, media: { where: { kind: MediaKind.IMAGE, archivedAt: null }, select: { id: true } } } } } });
    const imageDenominator = productRows.filter((p) => p.currentRevision?.status === ProductRevisionStatus.PUBLISHED).length;
    const imageNumerator = productRows.filter((p) => p.currentRevision?.status === ProductRevisionStatus.PUBLISHED && Boolean(p.currentRevision.media.length)).length;
    const sessions = this.prisma.serviceSession?.findMany ? await this.prisma.serviceSession.findMany({ where: { serviceDate: { gte: serviceStart, lte: serviceEnd }, status: { not: SessionStatus.ARCHIVED }, scheduleTemplate: { variant: { product: { tenantId: vendorTenantId } } } }, select: { id: true, scheduleTemplateId: true, slotTemplateId: true, serviceDate: true } }) : [];
    const exceptions = this.prisma.scheduleException?.findMany ? await this.prisma.scheduleException.findMany({ where: { type: { in: [ScheduleExceptionType.BLACKOUT, ScheduleExceptionType.CLOSED] }, archivedAt: null, serviceDate: { gte: serviceStart, lte: serviceEnd }, scheduleTemplate: { variant: { product: { tenantId: vendorTenantId } } } }, select: { scheduleTemplateId: true, slotTemplateId: true, serviceDate: true, createdAt: true, scheduleTemplate: { select: { timezone: true } } } }) : [];
    const affectedSessions = new Set<string>();
    for (const exception of exceptions) { const days = calendarDaysBetween(exception.serviceDate, exception.createdAt, exception.scheduleTemplate.timezone); if (days < 0 || days > lastMinuteStopSellDays) continue; for (const session of sessions) if (session.scheduleTemplateId === exception.scheduleTemplateId && session.serviceDate.getTime() === exception.serviceDate.getTime() && (!exception.slotTemplateId || session.slotTemplateId === exception.slotTemplateId)) affectedSessions.add(session.id); }
    return [
      { metricCode: SupplierQualityMetricCode.CONFIRMATION_WITHIN_SLA_RATE, dimension: SupplierQualityDimension.CONFIRMATION_SLA, rawValue: rate(confirmedWithin, observable.length), numerator: confirmedWithin, denominator: observable.length, sampleSize: observable.length, unit: 'percent', status: SupplierMetricStatus.UNASSESSED, score: null, sourceTrace: { cohort: 'recordType CANONICAL, bookingMode VENDOR_CONFIRMATION, createdAt >= windowStart and < windowEnd', observable: 'confirmationDueAt <= evaluationEnd OR confirmedAt OR rejectedAt OR expiredAt' } },
      { metricCode: SupplierQualityMetricCode.VENDOR_RESPONSE_WITHIN_SLA_RATE, dimension: SupplierQualityDimension.CONFIRMATION_SLA, rawValue: rate(withinSlaResponses.length, responded.length), numerator: withinSlaResponses.length, denominator: responded.length, sampleSize: responded.length, unit: 'percent', status: SupplierMetricStatus.UNASSESSED, score: null, sourceTrace: { cohort: 'same vendor-confirmation SLA cohort', response: 'confirmedAt OR rejectedAt <= confirmationDueAt', noResponseExpiry: 'not a response' } },
      { metricCode: SupplierQualityMetricCode.AVG_VENDOR_RESPONSE_MINUTES, dimension: SupplierQualityDimension.CONFIRMATION_SLA, rawValue: responseTimes.length ? Number((responseTimes.reduce((a, b) => a + b, 0) / responseTimes.length).toFixed(2)) : null, numerator: null, denominator: responseTimes.length, sampleSize: responseTimes.length, unit: 'minutes', status: SupplierMetricStatus.UNASSESSED, score: null, sourceTrace: { response: 'confirmedAt or rejectedAt minus Booking.createdAt' } },
      { metricCode: SupplierQualityMetricCode.CONFIRMATION_OVERDUE_RATE, dimension: SupplierQualityDimension.CONFIRMATION_SLA, rawValue: rate(overdue, observable.length), numerator: overdue, denominator: observable.length, sampleSize: observable.length, unit: 'percent', status: SupplierMetricStatus.UNASSESSED, score: null, sourceTrace: { cohort: 'same observable vendor-confirmation requests', numerator: 'CONFIRMATION_EXPIRED or expiredAt' } },
      { metricCode: SupplierQualityMetricCode.VENDOR_CANCELLATION_RATE, dimension: SupplierQualityDimension.CANCELLATION_RELIABILITY, rawValue: rate(vendorCancelled.length, serviceBookings.length), numerator: vendorCancelled.length, denominator: serviceBookings.length, sampleSize: serviceBookings.length, unit: 'percent', status: SupplierMetricStatus.UNASSESSED, score: null, sourceTrace: { cohort: 'recordType CANONICAL, confirmedAt != null, serviceDate within window, all booking modes', numerator: 'BookingCancellation initiator VENDOR; AGENT and ADMIN excluded' } },
      { metricCode: SupplierQualityMetricCode.SHORT_NOTICE_VENDOR_CANCELLATION_RATE, dimension: SupplierQualityDimension.CANCELLATION_RELIABILITY, rawValue: rate(shortCancelled.length, vendorCancelled.length), numerator: shortCancelled.length, denominator: vendorCancelled.length, sampleSize: vendorCancelled.length, unit: 'percent', status: SupplierMetricStatus.UNASSESSED, score: null, sourceTrace: { cohort: 'Vendor cancellations in service-date cohort', thresholdDays: shortNoticeDays, denominator: 'vendor cancellations' } },
      { metricCode: SupplierQualityMetricCode.VOUCHER_READY_BEFORE_SERVICE_RATE, dimension: SupplierQualityDimension.FULFILMENT_QUALITY, rawValue: rate(voucherReady.length, fulfilmentExpectedBookings.length), numerator: voucherReady.length, denominator: fulfilmentExpectedBookings.length, sampleSize: fulfilmentExpectedBookings.length, unit: 'percent', status: SupplierMetricStatus.UNASSESSED, score: null, sourceTrace: { cohort: 'confirmed service-date bookings, all booking modes; cancellation before immutable service boundary excluded', boundary: 'BookingSnapshot.sessionSnapshot.startsAt, otherwise local end-of-day using snapshot timezone/Booking.serviceTimezone', voucher: 'earliest non-VOID, non-voided VoucherVersion.generatedAt' } },
      { metricCode: SupplierQualityMetricCode.AVG_FULFILMENT_TURNAROUND_MINUTES, dimension: SupplierQualityDimension.FULFILMENT_QUALITY, rawValue: turnarounds.length ? Number((turnarounds.reduce((a, b) => a + b, 0) / turnarounds.length).toFixed(2)) : null, numerator: null, denominator: turnarounds.length, sampleSize: turnarounds.length, unit: 'minutes', status: SupplierMetricStatus.UNASSESSED, score: null, sourceTrace: { definition: 'first valid VoucherVersion.generatedAt minus Booking.confirmedAt', laterRegenerationExcluded: true } },
      { metricCode: SupplierQualityMetricCode.LAST_MINUTE_STOP_SELL_RATE, dimension: SupplierQualityDimension.INVENTORY_RELIABILITY, rawValue: rate(affectedSessions.size, sessions.length), numerator: affectedSessions.size, denominator: sessions.length, sampleSize: sessions.length, unit: 'percent', status: SupplierMetricStatus.UNASSESSED, score: null, sourceTrace: { source: 'BLACKOUT/CLOSED ScheduleException', timing: 'service-calendar days from exception.createdAt to serviceDate', thresholdDays: lastMinuteStopSellDays, counting: 'unique affected ServiceSession IDs; slot exception matches slot, global exception matches all sessions' } },
      { metricCode: SupplierQualityMetricCode.LIVE_PRODUCT_IMAGE_COVERAGE_RATE, dimension: SupplierQualityDimension.CATALOGUE_QUALITY, rawValue: rate(imageNumerator, imageDenominator), numerator: imageNumerator, denominator: imageDenominator, sampleSize: imageDenominator, unit: 'percent', status: SupplierMetricStatus.UNASSESSED, score: null, sourceTrace: { source: 'LIVE Product current PUBLISHED Revision with active IMAGE ProductMedia', videoOnlyExcluded: true } },
      empty(SupplierQualityMetricCode.CUSTOMER_RATING, SupplierQualityDimension.TRAVELLER_OUTCOME, 'rating'), empty(SupplierQualityMetricCode.NPS, SupplierQualityDimension.TRAVELLER_OUTCOME, 'score'), empty(SupplierQualityMetricCode.COMPLAINT_RATE, SupplierQualityDimension.TRAVELLER_OUTCOME, 'percent'),
    ];
  }
}
