import { Injectable } from '@nestjs/common';

@Injectable()
export class BookingProjectionService {
  private timeline(booking: any) { return (booking.events ?? []).map((event: any) => ({ eventType: event.eventType, fromStatus: event.fromStatus, toStatus: event.toStatus, reason: event.reason, metadata: event.metadata, createdAt: event.createdAt, actorRole: event.actorRole })); }
  private base(booking: any) { const snapshot = booking.operationalSnapshot; const cancellation = booking.cancellation; return { id: booking.id, bookingCode: booking.bookingCode, recordType: booking.recordType, status: booking.status, bookingMode: booking.bookingMode, serviceDate: booking.serviceDate, serviceTimezone: booking.serviceTimezone, confirmationDueAt: booking.confirmationDueAt, confirmedAt: booking.confirmedAt, rejectedAt: booking.rejectedAt, expiredAt: booking.expiredAt, customerName: booking.customerName, customerEmail: booking.customerEmail, snapshot, travellers: booking.travellers, cancellation: cancellation ? { id: cancellation.id, initiator: cancellation.initiator, reasonCategory: cancellation.reasonCategory, reason: cancellation.reason, financialState: cancellation.financialState, cancellationCharge: cancellation.cancellationCharge, refundEntitlement: cancellation.refundEntitlement, refund: cancellation.refund ? { id: cancellation.refund.id, amount: cancellation.refund.amount, currency: cancellation.refund.currency, status: cancellation.refund.status } : null } : null, timeline: this.timeline(booking) }; }
  forAgent(booking: any) { const result = this.base(booking); const economics = booking.economicsSnapshot; return { ...result, amount: Number(booking.amount), currency: booking.currency, economics: economics ? { currency: economics.currency, pricingUnit: economics.pricingUnit, agentFacingAmount: economics.agentFacingAmount, taxMode: economics.taxMode, taxAmount: economics.taxAmount, promotionAmount: economics.promotionAmount, finalAmount: economics.finalAmount, commercialEligibility: economics.commercialEligibility } : null }; }
  forVendor(booking: any) { const result = this.base(booking); const economics = booking.economicsSnapshot; return { ...result, vendor: { id: booking.vendorTenant?.id, name: booking.vendorTenant?.name }, agent: booking.agentTenant ? { id: booking.agentTenant.id, name: booking.agentTenant.name } : null, economics: economics ? { currency: economics.currency, pricingUnit: economics.pricingUnit, supplierGrossBasis: economics.supplierGrossBasis, supplierCommission: economics.supplierCommission, vendorPayable: economics.vendorPayable, finalAmount: economics.finalAmount } : null }; }
  forAdmin(booking: any) { return { ...this.base(booking), vendorTenant: booking.vendorTenant, agentTenant: booking.agentTenant, agentUser: booking.agentUser, product: booking.product, ratePlan: booking.ratePlan, economicsSnapshot: booking.economicsSnapshot, inventoryHolds: booking.inventoryHolds, inventoryAllocations: booking.inventoryAllocations }; }
}
