-- Phase 9 finalize: backfill must run before this migration is deployed.
ALTER TABLE "FinancialEvent" ALTER COLUMN "vendorTenantId" SET NOT NULL;
ALTER TABLE "Payout" ADD CONSTRAINT "Payout_settlementBatchId_key" UNIQUE ("settlementBatchId");
ALTER TABLE "FinancialEvent" ADD CONSTRAINT "FinancialEvent_vendorTenantId_fkey" FOREIGN KEY ("vendorTenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FinancialEvent" ADD CONSTRAINT "FinancialEvent_settlementBatchId_fkey" FOREIGN KEY ("settlementBatchId") REFERENCES "SettlementBatch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "FinancialEvent" ADD CONSTRAINT "FinancialEvent_payoutId_fkey" FOREIGN KEY ("payoutId") REFERENCES "Payout"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "Payout" ADD CONSTRAINT "Payout_settlementBatchId_fkey" FOREIGN KEY ("settlementBatchId") REFERENCES "SettlementBatch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "VendorSettlementPolicy" ADD CONSTRAINT "VendorSettlementPolicy_vendorTenantId_fkey" FOREIGN KEY ("vendorTenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CancellationVendorSettlementResolution" ADD CONSTRAINT "CancellationVendorSettlementResolution_cancellationId_fkey" FOREIGN KEY ("cancellationId") REFERENCES "BookingCancellation"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CancellationVendorSettlementResolution" ADD CONSTRAINT "CancellationVendorSettlementResolution_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CancellationVendorSettlementResolution" ADD CONSTRAINT "CancellationVendorSettlementResolution_vendorTenantId_fkey" FOREIGN KEY ("vendorTenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "CancellationVendorSettlementResolution" ADD CONSTRAINT "CancellationVendorSettlementResolution_financialEventId_fkey" FOREIGN KEY ("financialEventId") REFERENCES "FinancialEvent"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SettlementHold" ADD CONSTRAINT "SettlementHold_vendorTenantId_fkey" FOREIGN KEY ("vendorTenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SettlementHold" ADD CONSTRAINT "SettlementHold_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SettlementHold" ADD CONSTRAINT "SettlementHold_financialEventId_fkey" FOREIGN KEY ("financialEventId") REFERENCES "FinancialEvent"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SettlementBatch" ADD CONSTRAINT "SettlementBatch_vendorTenantId_fkey" FOREIGN KEY ("vendorTenantId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SettlementLine" ADD CONSTRAINT "SettlementLine_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "SettlementBatch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SettlementLine" ADD CONSTRAINT "SettlementLine_bookingId_fkey" FOREIGN KEY ("bookingId") REFERENCES "Booking"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SettlementEventAllocation" ADD CONSTRAINT "SettlementEventAllocation_batchId_fkey" FOREIGN KEY ("batchId") REFERENCES "SettlementBatch"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SettlementEventAllocation" ADD CONSTRAINT "SettlementEventAllocation_lineId_fkey" FOREIGN KEY ("lineId") REFERENCES "SettlementLine"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "SettlementEventAllocation" ADD CONSTRAINT "SettlementEventAllocation_financialEventId_fkey" FOREIGN KEY ("financialEventId") REFERENCES "FinancialEvent"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
ALTER TABLE "PayoutAttempt" ADD CONSTRAINT "PayoutAttempt_payoutId_fkey" FOREIGN KEY ("payoutId") REFERENCES "Payout"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "FinanceConfiguration" ADD CONSTRAINT "FinanceConfiguration_singleton_check" CHECK ("id" = 'default');
ALTER TABLE "SettlementHold" ADD CONSTRAINT "SettlementHold_scope_shape_check" CHECK (("scope" = 'VENDOR' AND "bookingId" IS NULL AND "financialEventId" IS NULL) OR ("scope" = 'BOOKING' AND "bookingId" IS NOT NULL AND "financialEventId" IS NULL) OR ("scope" = 'FINANCIAL_EVENT' AND "bookingId" IS NULL AND "financialEventId" IS NOT NULL));
ALTER TABLE "SettlementBatch" ADD CONSTRAINT "SettlementBatch_money_nonnegative_check" CHECK ("grossBookingValue" >= 0 AND "vendorBasePayable" >= 0 AND "adjustmentTotal" >= -"vendorBasePayable" AND "netPayable" >= 0);
ALTER TABLE "SettlementLine" ADD CONSTRAINT "SettlementLine_money_nonnegative_check" CHECK ("grossBookingValue" >= 0 AND "vendorPayableBase" >= 0 AND "netVendorPayable" >= 0);
ALTER TABLE "Payout" ADD CONSTRAINT "Payout_canonical_amount_positive_check" CHECK ("recordType" = 'LEGACY' OR "amount" > 0);
ALTER TABLE "PayoutAttempt" ADD CONSTRAINT "PayoutAttempt_amount_positive_check" CHECK ("amount" > 0);
CREATE UNIQUE INDEX "VendorSettlementPolicy_vendorTenantId_key" ON "VendorSettlementPolicy"("vendorTenantId");
CREATE UNIQUE INDEX "CancellationVendorSettlementResolution_cancellationId_key" ON "CancellationVendorSettlementResolution"("cancellationId");
CREATE UNIQUE INDEX "CancellationVendorSettlementResolution_financialEventId_key" ON "CancellationVendorSettlementResolution"("financialEventId");
CREATE UNIQUE INDEX "SettlementBatch_batchCode_key" ON "SettlementBatch"("batchCode");
CREATE UNIQUE INDEX "PayoutAttempt_payoutId_attemptNumber_key" ON "PayoutAttempt"("payoutId", "attemptNumber");
CREATE UNIQUE INDEX "SettlementEventAllocation_active_financialEvent_key" ON "SettlementEventAllocation"("financialEventId") WHERE "status" IN ('ALLOCATED', 'SETTLED');
CREATE INDEX "FinancialEvent_vendorTenantId_occurredAt_idx" ON "FinancialEvent"("vendorTenantId", "occurredAt");
CREATE INDEX "VendorSettlementPolicy_vendorTenantId_active_idx" ON "VendorSettlementPolicy"("vendorTenantId", "active");
CREATE INDEX "SettlementHold_vendorTenantId_status_idx" ON "SettlementHold"("vendorTenantId", "status");
CREATE INDEX "SettlementHold_bookingId_status_idx" ON "SettlementHold"("bookingId", "status");
CREATE INDEX "SettlementHold_financialEventId_status_idx" ON "SettlementHold"("financialEventId", "status");
CREATE INDEX "SettlementBatch_vendorTenantId_status_createdAt_idx" ON "SettlementBatch"("vendorTenantId", "status", "createdAt");
CREATE INDEX "SettlementLine_batchId_idx" ON "SettlementLine"("batchId");
CREATE INDEX "SettlementLine_bookingId_idx" ON "SettlementLine"("bookingId");
CREATE INDEX "SettlementEventAllocation_financialEventId_status_idx" ON "SettlementEventAllocation"("financialEventId", "status");
