import { useEffect, useState } from 'react';
import { api, type AgentBooking } from '../api';
import { Badge, ErrorBox, Loading, Panel, shortDate, money } from '../components/Ui';

export default function AgentBookings() {
  const [rows, setRows] = useState<AgentBooking[]>([]); const [selected, setSelected] = useState<AgentBooking | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); try { setRows(await api.request<AgentBooking[]>('/agent/bookings')); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  if (loading) return <Loading />;
  return <>{error && <ErrorBox error={error} />}<Panel title="My bookings"><div className="table-wrap"><table><thead><tr><th>Booking</th><th>Product</th><th>Service date</th><th>Amount</th><th>Mode</th><th>Status</th><th /></tr></thead><tbody>{rows.map((row) => <tr key={row.id}><td className="mono">{row.bookingCode}</td><td>{row.snapshot?.productSnapshot?.productName || '—'}</td><td>{shortDate(row.serviceDate)}</td><td>{money(row.amount || 0)}</td><td>{row.bookingMode?.replaceAll('_', ' ') || 'Legacy'}</td><td><Badge value={row.status} /></td><td><button className="btn small" onClick={() => api.request<AgentBooking>(`/agent/bookings/${row.id}`).then(setSelected).catch((e) => setError(e.message))}>Details</button></td></tr>)}</tbody></table></div>{!rows.length && <div className="empty">No bookings created by this agent yet.</div>}</Panel>{selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><div className="voucher-modal booking-detail" onClick={(e) => e.stopPropagation()}><div className="modal-head"><h3>{selected.bookingCode}</h3><button className="btn small" onClick={() => setSelected(null)}>Close</button></div><p><Badge value={selected.status} /> · {selected.bookingMode?.replaceAll('_', ' ') || 'Legacy'} · {shortDate(selected.serviceDate)}</p><h4>{selected.snapshot?.productSnapshot?.productName} · {selected.snapshot?.variantSnapshot?.name}</h4><p className="muted">{selected.status === 'PENDING_VENDOR_CONFIRMATION' ? `Waiting for vendor confirmation${selected.confirmationDueAt ? ` by ${new Date(selected.confirmationDueAt).toLocaleString()}` : ''}.` : selected.status === 'PENDING_MANUAL_REVIEW' ? 'Waiting for platform manual review.' : 'Server-authoritative booking status.'}</p><p><b>Price:</b> {money(selected.amount || 0)} {selected.currency}</p><h4>Travellers</h4>{selected.travellers.map((traveller, index) => <div key={index}>{traveller.fullName || `Traveller ${index + 1}`} · {traveller.travellerType}</div>)}<h4>Timeline</h4>{selected.timeline.map((event, index) => <div key={index} className="timeline-row"><b>{event.eventType}</b><span>{new Date(event.createdAt).toLocaleString()}</span>{event.reason && <small>{event.reason}</small>}</div>)}</div></div>}</>;
}
