import { useEffect, useState } from 'react';
import { api } from '../api';
import { Badge, ErrorBox, Loading, money, Panel, shortDate } from '../components/Ui';
import type { AgentSearchContext } from './AgentMarketplace';
import BookingWizard from './BookingWizard';

export default function AgentProductView({ productId, context, onBack }: { productId: string; context: AgentSearchContext; onBack: () => void }) {
  const [product, setProduct] = useState<any>(null); const [error, setError] = useState(''); const [selected, setSelected] = useState<any>(null);
  useEffect(() => { setProduct(null); setSelected(null); setError(''); api.request<any>(`/marketplace/products/${productId}/view`, { method: 'POST', body: JSON.stringify(context) }).then(setProduct).catch((e) => setError(e.message)); }, [productId, context]);
  if (error) return <><button className="link-button" onClick={onBack}>Back to marketplace</button><ErrorBox error={error} /></>;
  if (!product) return <Loading text="Loading published customer view..." />;
  if (selected) return <BookingWizard product={product} offer={selected} context={context} onDone={() => setSelected(null)} />;
  return <><button className="link-button" onClick={onBack}>Back to marketplace</button><div className="admin-hero"><div><h2>{product.name}</h2><p className="muted">{product.destination.city}, {product.destination.state}, {product.destination.country} · {context.serviceDate} · {context.travellers.map((item) => `${item.quantity} ${item.travellerType.toLowerCase()}`).join(', ')}</p></div></div><Panel><p>{product.description}</p><div className="chips">{product.highlights?.map((item: string) => <span className="chip" key={item}>{item}</span>)}</div></Panel><Panel title="What travellers should know"><div className="form-grid three"><div><b>Inclusions</b><ul>{product.inclusions?.map((item: string) => <li key={item}>{item}</li>)}</ul></div><div><b>Exclusions</b><ul>{product.exclusions?.map((item: string) => <li key={item}>{item}</li>)}</ul></div><div><b>Important information</b><ul>{product.importantInfo?.map((item: string) => <li key={item}>{item}</li>)}</ul></div></div></Panel>{product.media?.length > 0 && <Panel title="Gallery"><div className="listing-list">{product.media.map((media: any) => <img key={media.id} src={media.url} alt={media.description || product.name} style={{ maxWidth: 220, maxHeight: 140, objectFit: 'cover' }} />)}</div></Panel>}<Panel title="Eligible offers"><div className="listing-list">{product.variants?.map((variant: any) => <div className="listing-card" key={variant.id}><div className="listing-info"><b>{variant.name}</b><small>{variant.description || ''} · {variant.durationMinutes ? `${variant.durationMinutes} min` : 'Flexible'} · {variant.privateShared || 'Standard'}</small><small>{variant.pickupIncluded ? `Pickup: ${variant.pickupType || 'included'} ${variant.pickupInput || ''} ${variant.pickupTimings || ''}` : 'Pickup not included'}{variant.dropoffIncluded ? ` · Drop-off ${variant.dropoffTimings || ''}` : ''}</small>{variant.offers?.map((offer: any) => <div className="rate-meta" key={`${offer.ratePlanId}-${offer.sessionId}`}><span>{shortDate(offer.serviceDate)} {offer.localStartTime || 'date'} · <Badge value={offer.bookingMode || 'ON_REQUEST'} /></span><strong>{money(offer.price?.finalAmount || 0)}</strong><button className="btn small primary" onClick={() => setSelected(offer)}>Book this offer</button></div>)}</div></div>)}</div></Panel></>;
}
