import { useEffect, useState } from 'react';
import { api, type VendorBooking } from '../api';
import { Badge, ErrorBox, Loading, Panel, shortDate, money } from '../components/Ui';

const tabs = [['ALL', 'All'], ['NEEDS_ACTION', 'Needs Action'], ['PENDING', 'Pending'], ['CONFIRMED', 'Confirmed'], ['REJECTED', 'Rejected / Expired'], ['LEGACY', 'Legacy']] as const;
export default function Bookings() {
  const [rows, setRows] = useState<VendorBooking[]>([]); const [filter, setFilter] = useState('ALL'); const [selected, setSelected] = useState<VendorBooking | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true);
  async function load() { setLoading(true); try { setRows(await api.request<VendorBooking[]>('/vendor/bookings')); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function decide(id: string, action: 'confirm' | 'reject') { const reason = action === 'reject' ? window.prompt('Rejection reason') : ''; if (action === 'reject' && !reason?.trim()) return; try { await api.request(`/vendor/bookings/${id}/${action}`, { method: action === 'reject' ? 'POST' : 'POST', body: action === 'reject' ? JSON.stringify({ reason }) : undefined }); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  async function cancelService(id: string) { try { const preview = await api.request<any>(`/vendor/bookings/${id}/cancellation/preview`, { method: 'POST' }); if (!preview.eligible) { setError((preview.reasonCodes || ['Booking cannot be cancelled']).join(', ')); return; } const reason = window.prompt('Supplier cancellation reason'); const reasonCategory = window.prompt('Reason category (WEATHER, SAFETY, VENDOR_OPERATIONAL, OTHER)') || 'OTHER'; if (!reason?.trim()) return; await api.request(`/vendor/bookings/${id}/cancellation`, { method: 'POST', body: JSON.stringify({ reason, reasonCategory }) }); await load(); } catch (e) { setError(e instanceof Error ? e.message : String(e)); } }
  if (loading) return <Loading />;
  const visible = rows.filter((row) => filter === 'ALL' || (filter === 'NEEDS_ACTION' && row.status === 'PENDING_VENDOR_CONFIRMATION') || (filter === 'PENDING' && ['PENDING_VENDOR_CONFIRMATION', 'PENDING_MANUAL_REVIEW'].includes(row.status)) || (filter === 'CONFIRMED' && row.status === 'CONFIRMED') || (filter === 'REJECTED' && ['VENDOR_REJECTED', 'MANUAL_REJECTED', 'CONFIRMATION_EXPIRED'].includes(row.status)) || (filter === 'LEGACY' && row.recordType === 'LEGACY'));
  return <>{error && <ErrorBox error={error} />}<div className="toolbar"><div className="chips">{tabs.map(([value, label]) => <button key={value} onClick={() => setFilter(value)} className={`chip ${filter === value ? 'active' : ''}`}>{label}</button>)}</div></div><Panel title="Incoming bookings"><div className="table-wrap"><table><thead><tr><th>Booking</th><th>Product / Variant</th><th>Service</th><th>Agent</th><th>Deadline</th><th>Status</th><th>Actions</th></tr></thead><tbody>{visible.map((row) => <tr key={row.id}><td className="mono">{row.bookingCode}</td><td>{row.snapshot?.productSnapshot?.productName || 'Legacy'}<br /><small>{row.snapshot?.variantSnapshot?.name || ''}</small></td><td>{shortDate(row.serviceDate)}</td><td>{row.agent?.name || '—'}</td><td>{row.confirmationDueAt ? new Date(row.confirmationDueAt).toLocaleString() : '—'}</td><td><Badge value={row.status} /></td><td><div className="row-actions"><button className="btn small" onClick={() => api.request<VendorBooking>(`/vendor/bookings/${row.id}`).then(setSelected).catch((e) => setError(e.message))}>View</button>{row.recordType === 'CANONICAL' && row.status === 'PENDING_VENDOR_CONFIRMATION' && <><button className="btn accent small" onClick={() => void decide(row.id, 'confirm')}>Confirm</button><button className="btn small" onClick={() => void decide(row.id, 'reject')}>Reject</button></>}{row.recordType === 'CANONICAL' && ['CONFIRMED', 'PENDING_VENDOR_CONFIRMATION'].includes(row.status) && <button className="btn small" onClick={() => void cancelService(row.id)}>Cancel service</button>}{row.status === 'PENDING_MANUAL_REVIEW' && <small className="muted">Platform manual review</small>}</div></td></tr>)}</tbody></table></div>{!visible.length && <div className="empty">No bookings in this queue.</div>}</Panel>{selected && <div className="modal-backdrop" onClick={() => setSelected(null)}><div className="voucher-modal booking-detail" onClick={(e) => e.stopPropagation()}><div className="modal-head"><h3>{selected.bookingCode}</h3><button className="btn small" onClick={() => setSelected(null)}>Close</button></div><p><Badge value={selected.status} /> · {selected.bookingMode?.replaceAll('_', ' ') || 'Legacy'}</p><h4>{selected.snapshot?.productSnapshot?.productName} · {selected.snapshot?.variantSnapshot?.name}</h4><p>{shortDate(selected.serviceDate)} · {selected.snapshot?.sessionSnapshot?.localStartTime || ''}</p><p><b>Agent:</b> {selected.agent?.name || '—'} · <b>Vendor amount:</b> {money(selected.economics?.vendorPayable || 0)}</p><h4>Travellers</h4>{selected.travellers.map((t, i) => <div key={i}>{t.fullName || `Traveller ${i + 1}`} · {t.travellerType}</div>)}<h4>Timeline</h4>{selected.timeline.map((e, i) => <div key={i} className="timeline-row"><b>{e.eventType}</b><span>{new Date(e.createdAt).toLocaleString()}</span></div>)}</div></div>}</>;
}
