import { useEffect, useMemo, useState } from 'react';
import { api } from '../api';
import { ErrorBox, Field, Loading, Panel } from '../components/Ui';

type Profile = { id: string; legalBusinessName: string; operatingCity: string; operatingRegion: string; gstin?: string; category?: string; verificationStatus: string; readinessScore: number; payoutAccountMasked?: string; payoutAccountHolder?: string; payoutBankName?: string; payoutBranch?: string; payoutIfsc?: string; payoutSwift?: string; payoutAccountType?: string; payoutCurrency?: string; documentStatus: Record<string, { status: string; fileName?: string }> };
type Activity = { id: string; productName: string; status: string; ratePlans?: Array<{ id: string }> };
type Props = { onNavigate?: (page: 'listings' | 'dashboard') => void };
const steps = ['Business Details', 'Documents', 'Bank & Payout', 'Catalogue Setup', 'Go Live Review'];
const documentItems = [['GSTIN Certificate', 'gstin'], ['PAN Card', 'pan'], ['Cancelled Cheque / Bank Proof', 'bankProof'], ['Trade License / Activity Permit', 'tradeLicense']] as const;

export default function Onboarding({ onNavigate }: Props) {
  const [profile, setProfile] = useState<Profile | null>(null); const [activities, setActivities] = useState<Activity[]>([]); const [activeStep, setActiveStep] = useState(0); const [error, setError] = useState(''); const [saved, setSaved] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { try { const [p, a] = await Promise.all([api.request<Profile>('/vendor/profile'), api.request<Activity[]>('/activities')]); setProfile(p); setActivities(a); } catch (e) { setError((e as Error).message); } }
  useEffect(() => { void load(); }, []);
  const summary = useMemo(() => ({ live: activities.filter((a) => a.status === 'LIVE').length, total: activities.length, plans: activities.reduce((n, a) => n + (a.ratePlans?.length || 0), 0) }), [activities]);
  if (error && !profile) return <ErrorBox error={error} />; if (!profile) return <Loading />;
  const docs = profile.documentStatus || {};
  const businessComplete = Boolean(profile.legalBusinessName && profile.operatingCity && profile.operatingRegion && profile.category);
  const documentsComplete = documentItems.every(([, key]) => docs[key]?.status === 'VERIFIED');
  const bankComplete = Boolean(profile.payoutAccountMasked && profile.payoutAccountHolder && profile.payoutBankName && profile.payoutBranch && profile.payoutIfsc);
  const catalogueComplete = activities.some((a) => (a.ratePlans?.length || 0) > 0);
  const reviewComplete = activities.some((a) => a.status === 'LIVE');
  const complete = [businessComplete, documentsComplete, bankComplete, catalogueComplete, reviewComplete];
  const current = Math.max(0, complete.findIndex((v) => !v));
async function save() { const currentProfile = profile!; setBusy(true); setError(''); try { const updated = await api.request<Profile>('/vendor/profile', { method: 'PATCH', body: JSON.stringify({ legalBusinessName: currentProfile.legalBusinessName.trim(), operatingCity: currentProfile.operatingCity.trim(), operatingRegion: currentProfile.operatingRegion.trim(), gstin: currentProfile.gstin?.trim() || undefined, category: currentProfile.category?.trim() || undefined, payoutAccountMasked: currentProfile.payoutAccountMasked?.trim() || undefined, payoutAccountHolder: currentProfile.payoutAccountHolder?.trim() || undefined, payoutBankName: currentProfile.payoutBankName?.trim() || undefined, payoutBranch: currentProfile.payoutBranch?.trim() || undefined, payoutIfsc: currentProfile.payoutIfsc?.trim().toUpperCase() || undefined, payoutSwift: currentProfile.payoutSwift?.trim().toUpperCase() || undefined, payoutAccountType: currentProfile.payoutAccountType || 'CURRENT', payoutCurrency: currentProfile.payoutCurrency?.trim().toUpperCase() || 'INR' }) }); setProfile(updated); setSaved('Details saved successfully.'); setTimeout(() => setSaved(''), 2500); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  async function upload(key: string, file: File | undefined) { if (!file) return; if (file.size > 8 * 1024 * 1024) { setError('Document is too large. Please choose a file smaller than 8 MB.'); return; } setBusy(true); setError(''); try { const dataUrl = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = () => reject(new Error('Unable to read document')); reader.readAsDataURL(file); }); const updated = await api.request<Profile>(`/vendor/documents/${key}`, { method: 'POST', body: JSON.stringify({ fileName: file.name, dataUrl }) }); setProfile(updated); setSaved(`${file.name} uploaded and submitted for admin review.`); setTimeout(() => setSaved(''), 2500); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  function open(page: 'listings' | 'dashboard') { onNavigate?.(page); }
  return <>
    <div className="onboarding-intro"><div><h2>Complete your vendor onboarding</h2><p className="muted">Finish each step to make your activities available for booking and settlement.</p></div><span className="badge">Step {activeStep + 1} of 5</span></div>
    <div className="stepper">{steps.map((label, index) => <button type="button" className={`step ${complete[index] ? 'done' : ''} ${activeStep === index ? 'now' : ''}`} key={label} onClick={() => setActiveStep(index)}><i>{complete[index] ? '✓' : index + 1}</i><b>{label}</b><small>{complete[index] ? 'Complete' : index === current ? 'In progress' : 'Pending'}</small></button>)}</div>
    {error && <ErrorBox error={error} />}{saved && <div className="alert success">{saved}</div>}
    {activeStep === 0 && <Panel title="Step 1 · Business Details"><p className="muted">Tell Voya who the vendor is and where it operates. These fields identify the business attached to the logged-in tenant.</p><div className="form-grid two"><Field label="Legal Business Name" hint="Required"><input value={profile.legalBusinessName} onChange={(e) => setProfile({ ...profile, legalBusinessName: e.target.value })} /></Field><Field label="Operating City" hint="Required"><input value={profile.operatingCity} onChange={(e) => setProfile({ ...profile, operatingCity: e.target.value })} /></Field><Field label="Operating Region" hint="Required"><input value={profile.operatingRegion} onChange={(e) => setProfile({ ...profile, operatingRegion: e.target.value })} /></Field><Field label="GSTIN"><input value={profile.gstin || ''} onChange={(e) => setProfile({ ...profile, gstin: e.target.value })} /></Field><Field label="Category" hint="Required"><input value={profile.category || ''} onChange={(e) => setProfile({ ...profile, category: e.target.value })} /></Field></div><div className="actions"><button className="btn primary" disabled={busy || !businessComplete} onClick={async () => { await save(); setActiveStep(1); }}>Save and Continue</button></div></Panel>}
    {activeStep === 1 && <Panel title="Step 2 · Documents"><p className="muted">Upload the documents required to verify the vendor. The demo records the filename, status, and upload time for each document.</p><div className="doc-grid">{documentItems.map(([label, key]) => { const status = docs[key]?.status || 'PENDING'; return <div className={`doc-card ${status === 'VERIFIED' ? 'done' : ''}`} key={key}><span className="doc-icon">{status === 'VERIFIED' ? '✓' : '+'}</span><div><b>{label}</b><small>{status === 'VERIFIED' ? `Uploaded · Verified${docs[key]?.fileName ? ` · ${docs[key].fileName}` : ''}` : 'Required / pending'}</small></div><label className="btn small file-button">{status === 'VERIFIED' ? 'Replace' : 'Upload'}<input type="file" accept=".pdf,.jpg,.jpeg,.png" disabled={busy} onChange={(e) => upload(key, e.target.files?.[0])} /></label></div>; })}</div><div className="actions"><button className="btn" onClick={() => setActiveStep(0)}>Back</button><button className="btn primary" disabled={!documentsComplete} onClick={() => setActiveStep(2)}>Continue to Bank & Payout</button></div></Panel>}
    {activeStep === 2 && <Panel title="Step 3 · Bank & Payout"><p className="muted">Enter the payout details required for settlement. Account numbers remain masked; banking verification can be connected later.</p><div className="form-grid two"><Field label="Payout Account" hint="Example: HDFC •••• 4821"><input value={profile.payoutAccountMasked || ''} onChange={(e) => setProfile({ ...profile, payoutAccountMasked: e.target.value })} /></Field><Field label="Account Holder Name"><input value={profile.payoutAccountHolder || ''} onChange={(e) => setProfile({ ...profile, payoutAccountHolder: e.target.value })} /></Field><Field label="Bank Name"><input value={profile.payoutBankName || ''} onChange={(e) => setProfile({ ...profile, payoutBankName: e.target.value })} /></Field><Field label="Branch"><input value={profile.payoutBranch || ''} onChange={(e) => setProfile({ ...profile, payoutBranch: e.target.value })} /></Field><Field label="IFSC Code" hint="Required for Indian bank settlement"><input value={profile.payoutIfsc || ''} onChange={(e) => setProfile({ ...profile, payoutIfsc: e.target.value.toUpperCase() })} /></Field><Field label="SWIFT / BIC Code" hint="Required for international settlement"><input value={profile.payoutSwift || ''} onChange={(e) => setProfile({ ...profile, payoutSwift: e.target.value.toUpperCase() })} /></Field><Field label="Account Type"><select value={profile.payoutAccountType || 'CURRENT'} onChange={(e) => setProfile({ ...profile, payoutAccountType: e.target.value })}><option value="CURRENT">Current</option><option value="SAVINGS">Savings</option></select></Field><Field label="Payout Currency"><select value={profile.payoutCurrency || 'INR'} onChange={(e) => setProfile({ ...profile, payoutCurrency: e.target.value })}><option value="INR">INR — Indian Rupee</option><option value="USD">USD — US Dollar</option><option value="EUR">EUR — Euro</option></select></Field></div><div className="form-grid two"><Field label="Settlement readiness"><input value={bankComplete ? 'Details provided' : 'Required'} disabled /></Field></div><div className="actions"><button className="btn" onClick={() => setActiveStep(1)}>Back</button><button className="btn primary" disabled={busy || !bankComplete} onClick={async () => { await save(); setActiveStep(3); }}>Save and Continue</button></div></Panel>}
    {activeStep === 3 && <Panel title="Step 4 · Catalogue Setup"><p className="muted">Create at least one activity and attach at least one rate plan. Activities are products; rate plans are their bookable prices and operating rules.</p><div className="kpi-row three"><div className="kpi-card"><span>Activities</span><strong>{summary.total}</strong><small>Product masters</small></div><div className="kpi-card"><span>Rate plans</span><strong>{summary.plans}</strong><small>Commercial offers</small></div><div className="kpi-card"><span>Live listings</span><strong>{summary.live}</strong><small>Ready for review</small></div></div><div className="actions"><button className="btn" onClick={() => setActiveStep(2)}>Back</button><button className="btn accent" onClick={() => open('listings')}>Open Listings</button><button className="btn primary" disabled={!catalogueComplete} onClick={() => setActiveStep(4)}>Continue to Go Live Review</button></div></Panel>}
    {activeStep === 4 && <Panel title="Step 5 · Go Live Review"><p className="muted">Review the items below before presenting the vendor as ready. Use the linked screens to correct anything incomplete.</p><div className="readiness-list onboarding-checks"><div><span>Business details</span><b className={businessComplete ? 'good' : 'warn'}>{businessComplete ? 'Complete' : 'Incomplete'}</b></div><div><span>Required documents</span><b className={documentsComplete ? 'good' : 'warn'}>{documentsComplete ? 'Complete' : 'Incomplete'}</b></div><div><span>Bank and payout details</span><b className={bankComplete ? 'good' : 'warn'}>{bankComplete ? 'Complete' : 'Incomplete'}</b></div><div><span>Catalogue and rate plans</span><b className={catalogueComplete ? 'good' : 'warn'}>{catalogueComplete ? 'Complete' : 'Incomplete'}</b></div><div><span>At least one live listing</span><b className={reviewComplete ? 'good' : 'warn'}>{reviewComplete ? 'Ready' : 'Pending'}</b></div></div><div className="actions"><button className="btn" onClick={() => setActiveStep(3)}>Back</button><button className="btn" onClick={() => open('listings')}>Review Listings</button><button className="btn primary" onClick={() => open('dashboard')}>{reviewComplete ? 'Go to Dashboard' : 'Go to Dashboard'}</button></div></Panel>}
  </>;
}
