import { useEffect, useState } from 'react';
import { api } from '../api';
import { Badge, ErrorBox, Loading, Panel } from '../components/Ui';

export default function Opportunities() {
  const [items, setItems] = useState<any[] | null>(null); const [selected, setSelected] = useState<any>(null); const [error, setError] = useState(''); const [note, setNote] = useState(''); const [history, setHistory] = useState(false);
  const load = () => api.request<any[]>(`/vendor/opportunities${history ? '?history=true' : ''}`).then(setItems).catch((e) => setError((e as Error).message));
  useEffect(() => { void load(); }, [history]);
  const open = async (id: string) => { try { await api.request(`/vendor/opportunities/${id}/view`, { method: 'POST' }); setSelected(await api.request(`/vendor/opportunities/${id}`)); await load(); } catch (e) { setError((e as Error).message); } };
  const respond = async (status: string) => { if (!selected) return; try { await api.request(`/vendor/opportunities/${selected.id}/respond`, { method: 'POST', body: JSON.stringify({ status, expectedVersion: selected.version, responseNote: note || undefined }) }); setNote(''); await open(selected.id); } catch (e) { setError((e as Error).message); } };
  if (error) return <ErrorBox error={error} />; if (!items) return <Loading text="Loading targeted opportunities..." />;
  return <><div className="admin-hero"><div><h2>Opportunities</h2><p className="muted">Only opportunities explicitly targeted to this Vendor are shown.</p></div></div><div className="actions"><button className={!history ? 'btn primary' : 'btn'} onClick={() => setHistory(false)}>Active</button><button className={history ? 'btn primary' : 'btn'} onClick={() => setHistory(true)}>Responded / History</button></div><Panel title={history ? 'Opportunity history' : 'Active supply opportunities'}>{items.map((item) => <div className="listing-card" key={item.id} onClick={() => open(item.id)} style={{ cursor: 'pointer' }}><div className="listing-info"><b>{item.title}</b><small>{item.destination || 'Any destination'} · {item.category || 'Any category'} · {item.type} · {item.source}</small><p>{Object.entries(item.metrics || {}).map(([key, value]) => <span key={key} className="badge" style={{ marginRight: 6 }}>{key}: {String(value)}</span>)}</p><Badge value={item.status} /> <Badge value={item.priority} /></div></div>)}{!items.length && <div className="empty">No opportunities in this view.</div>}</Panel>{selected && <Panel title={selected.title} action={<button onClick={() => setSelected(null)}>Close</button>}><p><b>Requested action:</b> {selected.recommendedAction || 'Review and respond with a supply plan.'}</p><p className="muted">This view contains aggregate demand evidence only. It does not expose Agent identities, raw queries, competitors, or confidential rates.</p><div className="score-table">{Object.entries(selected.metrics || {}).map(([key, value]) => <p key={key}><b>{key}:</b> {String(value)}</p>)}</div>{['TARGETED', 'VIEWED'].includes(selected.status) && <><label className="field"><span>Response note</span><textarea value={note} onChange={(e) => setNote(e.target.value)} rows={3} placeholder="Optional context for the Supply Team" /></label><button onClick={() => respond('INTERESTED')}>Interested</button> <button onClick={() => respond('DECLINED')}>Decline</button></>}</Panel>}</>;
}
