import { useEffect, useMemo, useState } from 'react';
import { api } from '../api';
import { Badge, ErrorBox, Loading, Panel } from '../components/Ui';

type Metric = { metricCode: string; dimension: string; rawValue: number | null; numerator: number | null; denominator: number | null; sampleSize: number; unit: string; status: string; score: number | null; sourceTrace?: unknown };
type PerformanceData = { policy: { name: string; measurementWindowDays: number; metricRules: Array<{ metricCode: string; targetValue: number; warningValue: number; direction: string }> } | null; metrics: Metric[]; overallScore: number | null; recommendedTier: string | null; currentTier: string | null; windowStart: string; windowEnd: string; openIssues: Array<{ id: string; title: string; severity: string; status: string }> };
type HistoryRow = { id: string; generatedAt: string; overallScore: number | null; recommendedTier: string | null; currentTierAtCalculation: string | null; policy?: { name: string; versionNumber: number } | null };
const labels: Record<string, string> = { CONFIRMATION_WITHIN_SLA_RATE: 'Confirmation within SLA', AVG_VENDOR_RESPONSE_MINUTES: 'Avg Vendor response time', VENDOR_CANCELLATION_RATE: 'Vendor cancellation rate', VOUCHER_READY_BEFORE_SERVICE_RATE: 'Voucher ready before service', LAST_MINUTE_STOP_SELL_RATE: 'Last-minute stop-sell rate', LIVE_PRODUCT_IMAGE_COVERAGE_RATE: 'Live Product image coverage', CUSTOMER_RATING: 'Customer rating', NPS: 'NPS', COMPLAINT_RATE: 'Complaint rate' };
const dimensions = ['CONFIRMATION_SLA', 'CANCELLATION_RELIABILITY', 'FULFILMENT_QUALITY', 'INVENTORY_RELIABILITY', 'TRAVELLER_OUTCOME', 'CATALOGUE_QUALITY'];
const displayValue = (m: Metric) => m.rawValue === null ? 'Not available' : `${m.rawValue}${m.unit === 'percent' ? '%' : m.unit === 'minutes' ? ' min' : ''}`;

export default function Performance() {
  const [data, setData] = useState<PerformanceData | null>(null); const [history, setHistory] = useState<HistoryRow[]>([]); const [error, setError] = useState('');
  useEffect(() => { Promise.all([api.request<PerformanceData>('/vendor/performance'), api.request<HistoryRow[]>('/vendor/performance/history')]).then(([current, previous]) => { setData(current); setHistory(previous); }).catch((e) => setError((e as Error).message)); }, []);
  const ruleMap = useMemo(() => new Map((data?.policy?.metricRules || []).map((r) => [r.metricCode, r])), [data]);
  if (error) return <ErrorBox error={error} />; if (!data) return <Loading />;
  const cards = data.metrics.filter((m) => ['CONFIRMATION_WITHIN_SLA_RATE', 'AVG_VENDOR_RESPONSE_MINUTES', 'VENDOR_CANCELLATION_RATE', 'VOUCHER_READY_BEFORE_SERVICE_RATE', 'LAST_MINUTE_STOP_SELL_RATE', 'LIVE_PRODUCT_IMAGE_COVERAGE_RATE'].includes(m.metricCode));
  return <>
    <div className="admin-hero"><div><h2>Performance &amp; Quality</h2><p className="muted">Operational quality measured from canonical bookings, fulfilment, inventory, and catalogue records.</p></div><span className="badge">{data.policy ? `Window: ${data.policy.measurementWindowDays} days` : 'Quality scoring policy not active'}</span></div>
    <div className="kpi-row three"><div className="kpi-card"><span>Current Supplier Tier</span><strong>{data.currentTier || 'Not assigned'}</strong><small>Governed by Voya</small></div><div className="kpi-card"><span>Quality Score / 100</span><strong>{data.overallScore === null ? 'Not available' : data.overallScore.toFixed(1)}</strong><small>{data.policy ? 'Policy assessed' : 'Scoring policy not active'}</small></div><div className="kpi-card"><span>Recommended Tier</span><strong>{data.recommendedTier || 'Not available'}</strong><small>Does not automatically change tier</small></div></div>
    {!data.policy && <div className="alert info">Quality scoring policy not active. Raw operational metrics remain available; score and recommendation are not fabricated.</div>}
    <Panel title="Operational metrics"><div className="score-table">{cards.map((m) => { const rule = ruleMap.get(m.metricCode); return <div key={m.metricCode}><b>{labels[m.metricCode] || m.metricCode}</b><span>{displayValue(m)}</span><span>{rule ? `${rule.direction === 'HIGHER_BETTER' ? '≥' : '≤'} ${rule.targetValue}${m.unit === 'percent' ? '%' : m.unit === 'minutes' ? ' min' : ''}` : 'Not configured'}</span><span><Badge value={m.status === 'UNAVAILABLE' ? 'Not available' : m.status} /><small>Sample: {m.sampleSize}</small></span></div>; })}</div></Panel>
    <Panel title="Quality scorecard"><div className="score-table">{dimensions.map((dimension) => { const rows = data.metrics.filter((m) => m.dimension === dimension); return <div key={dimension}><b>{dimension.replaceAll('_', ' ')}</b><span>{rows.length ? rows.map((m) => labels[m.metricCode] || m.metricCode).join(', ') : 'Not available'}</span><span>{rows.some((m) => m.status === 'FAIL') ? 'Needs attention' : rows.some((m) => m.status === 'UNAVAILABLE') ? 'Not available' : rows.some((m) => m.status === 'WARN') ? 'Monitor' : 'Measured'}</span><em>{dimension === 'TRAVELLER_OUTCOME' ? 'Not available — traveller feedback source not configured' : ''}</em></div>; })}</div></Panel>
    <Panel title="Traveller outcomes"><div className="score-table">{['CUSTOMER_RATING', 'NPS', 'COMPLAINT_RATE'].map((code) => <div key={code}><b>{labels[code]}</b><span>Not available</span><span>Source not configured</span><small>Excluded from scoring and issue creation</small></div>)}</div></Panel>
    <Panel title="Assessment history"><div className="table-wrap"><table><thead><tr><th>Generated</th><th>Policy</th><th>Score</th><th>Recommended tier</th><th>Tier at calculation</th></tr></thead><tbody>{history.map((row) => <tr key={row.id}><td>{new Date(row.generatedAt).toLocaleString()}</td><td>{row.policy ? `${row.policy.name} · v${row.policy.versionNumber}` : 'No policy'}</td><td>{row.overallScore ?? 'Not available'}</td><td>{row.recommendedTier || 'Not available'}</td><td>{row.currentTierAtCalculation || 'Not assigned'}</td></tr>)}</tbody></table></div>{!history.length && <div className="empty">No captured assessment history yet.</div>}</Panel>
    <Panel title="Improvement queue"><div className="task-list">{data.openIssues.length ? data.openIssues.map((issue) => <div className="task medium" key={issue.id}><b>{issue.title}</b><span>{issue.severity} · {issue.status}</span></div>) : <div className="empty">No open quality issues.</div>}</div></Panel>
    <p className="muted">Tier status is governed by Voya. Quality score does not automatically change your tier.</p>
  </>;
}
