import { useEffect, useRef, useState } from 'react';
import { api, type Product, type ProductListingItem, type ProductListingResponse } from '../api';
import { ErrorBox, Loading } from '../components/Ui';
import ProductBuilder from './ProductBuilder';

export function formatRelativeTime(value: string) {
  const seconds = Math.max(0, Math.round((Date.now() - new Date(value).getTime()) / 1000));
  if (seconds < 60) return 'just now';
  const minutes = Math.round(seconds / 60); if (minutes < 60) return `${minutes}m ago`;
  const hours = Math.round(minutes / 60); if (hours < 24) return `${hours}h ago`;
  return `${Math.round(hours / 24)}d ago`;
}

const statusLabel: Record<ProductListingItem['displayStatus'], string> = { PUBLISHED: 'Live', UNDER_REVIEW: 'Under review', DRAFT: 'Draft', NEEDS_CHANGES: 'Needs changes', SUSPENDED: 'Suspended', ARCHIVED: 'Archived' };
const bookabilityLabel: Record<ProductListingItem['bookability']['status'], string> = { BOOKABLE: 'Bookable', NOT_BOOKABLE: 'Not bookable', LOW_INVENTORY: 'Low inventory', NOT_EVALUATED: 'Not evaluated' };

export default function Products() {
  const [data, setData] = useState<ProductListingResponse | null>(null); const [search, setSearch] = useState(''); const [status, setStatus] = useState<'' | 'LIVE' | 'REVIEW' | 'DRAFT'>(''); const [page, setPage] = useState(1); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [selected, setSelected] = useState<Product | null>(null); const [wizardOpen, setWizardOpen] = useState(false);
  const createButtonRef = useRef<HTMLButtonElement>(null); const triggerRef = useRef<HTMLButtonElement | null>(null); const rowTriggers = useRef<Record<string, HTMLButtonElement | null>>({});
  useEffect(() => { const timer = window.setTimeout(() => { setLoading(true); setError(''); const params = new URLSearchParams({ search, page: String(page), limit: '25' }); if (status) params.set('status', status); api.request<ProductListingResponse>(`/products/listing?${params}`).then(setData).catch((e) => setError(e instanceof Error ? e.message : String(e))).finally(() => setLoading(false)); }, 300); return () => window.clearTimeout(timer); }, [search, status, page]);
  function openCreate() { triggerRef.current = createButtonRef.current; setSelected(null); setWizardOpen(true); }
  function openEdit(item: ProductListingItem) { triggerRef.current = rowTriggers.current[item.id]; setSelected({ id: item.id } as Product); setWizardOpen(true); }
  function closeWizard() { setWizardOpen(false); setSelected(null); window.setTimeout(() => triggerRef.current?.focus(), 0); }
  const summary = data?.summary || { live: 0, review: 0, draft: 0 };
  return <div className="products-page"><div className="products-heading"><div><h2>Products</h2><p>Build one canonical experience, then manage options, rates and inventory underneath it.</p></div><button ref={createButtonRef} className="btn accent" onClick={openCreate}>+ Create experience</button></div>
    <div className="products-toolbar"><label className="search-field"><span className="sr-only">Search products</span><input placeholder="Search products…" value={search} onChange={(e) => { setSearch(e.target.value); setPage(1); }} /></label><div className="summary-filters"><button className={status === 'LIVE' ? 'summary-filter active success' : 'summary-filter success'} title="Published products currently live" onClick={() => { setStatus(status === 'LIVE' ? '' : 'LIVE'); setPage(1); }}><b>{summary.live}</b> Live</button><button className={status === 'REVIEW' ? 'summary-filter active warning' : 'summary-filter warning'} title="Products with a working revision under review" onClick={() => { setStatus(status === 'REVIEW' ? '' : 'REVIEW'); setPage(1); }}><b>{summary.review}</b> Review</button><button className={status === 'DRAFT' ? 'summary-filter active' : 'summary-filter'} title="Products with a working draft revision" onClick={() => { setStatus(status === 'DRAFT' ? '' : 'DRAFT'); setPage(1); }}><b>{summary.draft}</b> Draft</button></div></div>
    <section className="products-table-card" aria-live="polite">{error ? <ErrorBox error={error} /> : loading && !data ? <Loading text="Loading products…" /> : data?.items.length ? <div className="products-table-scroll"><table className="products-table"><thead><tr><th>Experience</th><th>Destination</th><th>Options</th><th>Bookability</th><th>Quality</th><th>Status</th><th><span className="sr-only">Action</span></th></tr></thead><tbody>{data.items.map((item) => <tr key={item.id}><td><div className="product-name-cell"><b>{item.experienceName}</b><small>{item.productCode} · Updated {formatRelativeTime(item.updatedAt)}</small></div></td><td>{item.destination || '—'}</td><td>{item.optionCount}</td><td><span className={`table-status ${item.bookability.status.toLowerCase()}`}>{bookabilityLabel[item.bookability.status]}</span></td><td>{item.quality.score === null ? <span className="muted">Not scored</span> : item.quality.score}</td><td><span className={`table-status ${item.displayStatus.toLowerCase()}`}>{statusLabel[item.displayStatus]}</span></td><td><button ref={(node) => { rowTriggers.current[item.id] = node; }} className="table-action" onClick={() => openEdit(item)}>{item.action === 'FIX' ? 'Fix' : 'Open'}</button></td></tr>)}</tbody></table></div> : <div className="products-empty"><h3>{search || status ? 'No products match these filters' : 'No products yet'}</h3><p>{search || status ? 'Try clearing the search or status filter.' : 'Create your first experience to start building the catalogue.'}</p></div>}{data && data.pagination.totalPages > 1 && <div className="products-pagination"><span>Page {data.pagination.page} of {data.pagination.totalPages}</span><div><button className="btn small" disabled={page <= 1 || loading} onClick={() => setPage((value) => value - 1)}>Previous</button><button className="btn small" disabled={page >= data.pagination.totalPages || loading} onClick={() => setPage((value) => value + 1)}>Next</button></div></div>}</section>
    {wizardOpen && <ProductBuilder product={selected} onDone={closeWizard} onChanged={() => setPage(1)} />}
  </div>;
}
